### PR TITLE
[202205] Advance sonic-dbsyncd submodule

### PR DESCRIPTION
**Pull request by vivekrnv**
```
4dcfb61 Handled the error case of negative age (https://github.com/sonic-net/sonic-buildimage/pull/57)
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca should we create a branch for this repo in 202205 instead of taking master into it?
from my POV the major fix is in one commit: Handled the error case of negative age.

**Comment by yxieca** [comment]
> @yxieca should we create a branch for this repo in 202205 instead of taking master into it? from my POV the major fix is in one commit: Handled the error case of negative age.

Sounds like we are deviating from the master branch? If so, we should create 202205 branch. Please confirm.

**Comment by vivekrnv** [comment]
> > @yxieca should we create a branch for this repo in 202205 instead of taking master into it? from my POV the major fix is in one commit: Handled the error case of negative age.
> 
> Sounds like we are deviating from the master branch? If so, we should create 202205 branch. Please confirm.

Yeah i think so.

**Comment by yxieca** [comment]
> > > @yxieca should we create a branch for this repo in 202205 instead of taking master into it? from my POV the major fix is in one commit: Handled the error case of negative age.
> > 
> > 
> > Sounds like we are deviating from the master branch? If so, we should create 202205 branch. Please confirm.
> 
> Yeah i think so.

https://github.com/sonic-net/sonic-buildimage/pull/14307

**Pull request merged**
