### PR TITLE
[202012] Upgrade SAI xgs to 4.3.12.2

### PR DESCRIPTION
**Pull request by Gfrom2016**
#### Why I did it
Upgrade the SAI version to 4.3.12.2 to include the following changes:
- 4.3.10.2: [JIRA SONIC-68535][CSP CS00012273299] sai_query_attribute_capability for obj type SAI_OBJECT_TYPE_SWITCH
- 4.3.11.2: [JIRA SONIC-76883][CSP CS00012303308] SDK-367579: Skip flex port check when in iBodSync context
- 4.3.12.2: [JIRA SONIC-76472][CSP CS00012299690] Source suppressed broadcast packets count on interface TX discard statistics

##### Work item tracking
- Microsoft ADO **(number only)**: 24962692

#### How I did it
Upgrade the SAI version in sai.mk file.

#### How to verify it
Run SONiC basic test in SAI release pipeline: https://dev.azure.com/mssonic/internal/_build/results?buildId=361078&view=results

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### A picture of a cute animal (not mandatory but encouraged)

Signed-off-by: zitingguo-ms <zitingguo@microsoft.com>

### CODE REVIEW

**Comment by neethajohn** [comment]
@Gfrom2016, after approving I realized that there are test failures for fdb and vlan. Can you take a look at those? Please hold off merge

**Comment by Gfrom2016** [comment]
@neethajohn Sure, I will check the failure

**Comment by Gfrom2016** [comment]
The latest SAI release pipeline result: https://dev.azure.com/mssonic/internal/_build/results?buildId=361078&view=results

**Comment by neethajohn** [comment]
The latest sai release pipelines has all testcases passing. We are good to merge

**Comment by yxieca** [comment]
@qiluo-msft please merge this PR. Thanks.

**Review by yxieca — APPROVED** [review]

**Pull request merged**
