### PR TITLE
[containercfgd] Add multi ASIC support for syslog rate limit feature

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

For multi asic platform, the container name is not the same as service name. For example, service name swss, the container in namespace asic0 will have container name swss0. This PR is to support multi ASIC platform.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Add a global variable service_name and use it to match DB key.

#### How to verify it

Manual test
Unit test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by saiarcot895 — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox is there any dependency between this one and the PR in utilities?

**Comment by Junchao-Mellanox** [comment]
Hi Liat, there is no dependency. We can merge this one first.

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca , could you please help cherry-pick?

**Comment by yxieca** [comment]
@Junchao-Mellanox can this feature wait for 202405 branch?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox can this feature wait for 202405 branch?

I am ok with it. @saiarcot895 , what do you think?

**Pull request merged**
