### PR TITLE
[Mellanox] Fix retry logic on discovery of MST device

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### Why I did it
Fixing retry logic when MST device is discovered. The current implementation only fetches the name of the device but doesn't verify if the device is accessible which can be confirmed by querying the device and ensuring the command passes.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added a query command with device as parameter and ensured it passes.

#### How to verify it
Running upgrade tests.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by vivekrnv — APPROVED** [review]

**Review by volodymyrsamotiy — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by dgsudharsan** [comment]
202405 PR created here due to manual conflicts: https://github.com/sonic-net/sonic-buildimage/pull/20390

**Pull request merged**
