### PR TITLE
[Master] [DNX SAI] Update DNX SAI to 9.2.X and SDK on master branch

### PR DESCRIPTION
**Pull request by wenyiz2021**
#### Why I did it
SAI 9.2.x was sanitized and posted on 202305 branch: https://github.com/sonic-net/sonic-buildimage/pull/17432/files

Posting SAI 9.2.x to master branch also.

##### Work item tracking
- Microsoft ADO **(number only)**:
26607678

#### How to verify it
No Sanitization done

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by arlakshm** [comment]
@wenyiz2021, the build is failing can please check

**Review by arlakshm — DISMISSED** [review]

**Comment by wenyiz2021** [comment]
> @wenyiz2021, the build is failing can please check

@arlakshm fixed, please check again, thanks!

**Review by arlakshm — APPROVED** [review]
Lgtm

**Comment by wenyiz2021** [comment]
@lguohan kindly ask your help to merge this PR

**Comment by wenyiz2021** [comment]
@rlhui for viz

**Review by lguohan — APPROVED** [review]

**Pull request merged**
