### PR TITLE
[submodule] Update sonic-swss pointer

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
a2a483d [acl] Add new ACL key BTH_OPCODE and AETH_SYNDROME  (sonic-net/sonic-swss#2617)
9d1f66b [bfdorch] add local discriminator to state DB (sonic-net/sonic-swss#2629)
c54b3d1 Vxlan tunnel endpoint custom monitoring APPL DB table. (sonic-net/sonic-swss#2589)
7f03db2 Fix potential risks (sonic-net/sonic-swss#2516)
383ee68 [refactor]Refactoring sai handle status (sonic-net/sonic-swss#2621)
cd95972 Fix issue #13341 ARP entry can be out of sync between kernel and APPL_DB if multiple updates are received from RTNL (sonic-net/sonic-swss#2619)
a01470f Remove TODO comments that are no longer relevant (sonic-net/sonic-swss#2622)
d058390 Changed the BFD default detect multiplier to 10x (sonic-net/sonic-swss#2614)
d78b528 [MuxOrch] Enabling neighbor when adding in active state (sonic-net/sonic-swss#2601)
4ebdad1 [routesync] Fix for stale dynamic neighbor (sonic-net/sonic-swss#2553)
8857f92 Added new attributes for Vnet and Vxlan ecmp configurations. (sonic-net/sonic-swss#2584)
b6bbc3e Revert "[voq][chassis]Add show fabric counters port/queue commands (sonic-net/sonic-swss#2522)" (sonic-net/sonic-swss#2611)
52406e2 Add missing parameter to on_switch_shutdown_request method. (sonic-net/sonic-swss#2567)
4ac9ad9 Increase diff coverage to 80% (sonic-net/sonic-swss#2599)
8a0bb36 Handle Mac address 'none' (sonic-net/sonic-swss#2593)
f496ab3 [vstest] Only collect stdout of orchagent_restart_check in vstest (sonic-net/sonic-swss#2597)
1dab495 Avoid aborting orchagent when setting TUNNEL attributes (sonic-net/sonic-swss#2591)
4395cea Fix neighbor doesn't update all attribute (sonic-net/sonic-swss#2577)

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prsunny  looks like swss is not constantly updated and once a PR is needed for master many others comes in. we need a more frequest update of this repo to master.
@Junchao-Mellanox  can you please identify the issues which cause the failure and ask the PR owner to take further look?

**Comment by prsunny** [comment]
> @prsunny looks like swss is not constantly updated and once a PR is needed for master many others comes in. we need a more frequest update of this repo to master. @Junchao-Mellanox can you please identify the issues which cause the failure and ask the PR owner to take further look?

agree with you @liat-grozovik. need to check with build folks if this can be automated

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik ， I see this issue on other PR, e.g. https://github.com/sonic-net/sonic-buildimage/pull/13557. So, I suppose this issue is not introduced by this PR. I will try to reproduce the issue locally.

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik  , the test failed at sonic-mgmt test case test_disable_rsyslog_rate_limit. I tried run it >30 times locally, and I cannot reproduce it. After checking the test log https://www.testbed-tools.org/scheduler/testplan/63d783ff5fd40eb56f582159, I found the case failed on a multiASIC platform. So, I suspect that this is an issue only on multiASIC. I can't do further check as there is no multiASIC platform available from my side. 

Hi @prsunny , could you please ask someone to debug this issue on multiASIC platform?

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox  I can see it is on many other PRs.
should we consider disabling the test for multi-asic and create a github issue for someone to debug it and then add the test back?

**Comment by Junchao-Mellanox** [comment]
I will send email to sonic admin

**Comment by prsunny** [comment]
> Hi @liat-grozovik , the test failed at sonic-mgmt test case test_disable_rsyslog_rate_limit. I tried run it >30 times locally, and I cannot reproduce it. After checking the test log https://www.testbed-tools.org/scheduler/testplan/63d783ff5fd40eb56f582159, I found the case failed on a multiASIC platform. So, I suspect that this is an issue only on multiASIC. I can't do further check as there is no multiASIC platform available from my side.
> 
> Hi @prsunny , could you please ask someone to debug this issue on multiASIC platform?

Requested internally.

**Comment by liat-grozovik** [comment]
Not needed. Newer PR was already created and merged

**Pull request closed without merging**
