### PR TITLE
[master][sonic-utilities] Update sonic-utilities submodule

### PR DESCRIPTION
**Pull request by yozhao101**
Signed-off-by: Yong Zhao <yozhao@microsoft.com>

#### Why I did it
This PR aims to update the `sonic-utilities` submodule.

- src/sonic-utilities
> [87fc0a4 ](https://github.com/Azure/sonic-utilities/commit/87fc0a4909928320325b2afcad2562a6db9d3c40)- 2022-05-12 | [scripts/fast-reboot] Add option to include ssd-upgrader-part boot option with SONiC partition (# [2150] https://github.com/Azure/sonic-utilities/pull/2150) [Arun Saravanan Balachandran]
> [90abc07 ](https://github.com/Azure/sonic-utilities/commit/90abc0716e5369624655c228496805d0e849f351)- 2022-05-12 |  [config reload] Fix invalid rstrip. (# [2157] https://github.com/Azure/sonic-utilities/pull/2157) [Gang Lv]
> [fac1769 ](https://github.com/Azure/sonic-utilities/commit/fac1769624c476a81750cdb3c87a9ce4f157f939)- 2022-05-12 | Accept 0 for queue and dscp (# [2162] https://github.com/Azure/sonic-utilities/pull/2162) [Bing Wang]

### CODE REVIEW

**Review by qiluo-msft — DISMISSED** [review]

**Comment by yozhao101** [comment]
I updated this PR since another PR (https://github.com/Azure/sonic-buildimage/pull/10670) was already merged.

**Comment by liat-grozovik** [comment]
closing this one as it is old and not relevant any more.
at this point submodule updates are done automatically and not needed user PR

**Pull request closed without merging**
