### PR TITLE
[chassis/multi-asic]  Enable Sending BGP Community over internal neighbors over iBGP Session

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Enable Sending BGP Community over internal neighbors over iBGP Session

Microsoft ADO: 25268695

Why I did:
Without this change BGP community send by e-BGP Peers are not carry-forward to other e-BGP peers.

How I Verify:

1. UT updated
2. Manual Verification (See Below)

Without this Change

```
str2-xxxx-lc1-2# show bgp ipv6  20c0:a801::/64
BGP routing table entry for 20c0:a801::/64, version 52141
Paths: (1 available, best #1, table default)
  Not advertised to any peer
  65000 65500
    2603:10e2:400::6 from 2603:10e2:400::6 (3.3.3.6)
      Origin IGP, localpref 100, valid, internal, best (First path received)
      Last update: Tue Sep 26 16:08:26 2023
str2-xxxx-lc1-2# show ip bgp 192.168.35.128/25
BGP routing table entry for 192.168.35.128/25, version 52688
Paths: (1 available, best #1, table default)
  Not advertised to any peer
  65000 65502
    3.3.3.6 from 3.3.3.6 (3.3.3.6)
      Origin IGP, localpref 100, valid, internal, best (First path received)
      Last update: Tue Sep 26 15:45:51 2023
```
After the change

```
str2-xxxx-lc2-2(config)# router bgp 65100
str2-xxxx-lc2-2(config-router)# address-family ipv4
str2-xxxx-lc2-2(config-router-af)# neighbor INTERNAL_PEER_V4 send-community
str2-xxxx-lc2-2(config-router-af)# exit
str2-xxxx-lc2-2(config-router)# address-family ipv6
str2-xxxx-lc2-2(config-router-af)# neighbor INTERNAL_PEER_V6 send-community
```

```
str2-xxxx-lc1-2# show bgp ipv6  20c0:a801::/64
BGP routing table entry for 20c0:a801::/64, version 52400
Paths: (1 available, best #1, table default)
  Not advertised to any peer
  65000 65500
    2603:10e2:400::6 from 2603:10e2:400::6 (3.3.3.6)
      Origin IGP, localpref 100, valid, internal, best (First path received)
      **Community: 1111:1111**
      Last update: Tue Sep 26 16:10:19 2023
str2-xxxx-lc1-2# show ip bgp 192.168.35.128/25
BGP routing table entry for 192.168.35.128/25, version 52947
Paths: (1 available, best #1, table default)
  Not advertised to any peer
  65000 65502
    3.3.3.6 from 3.3.3.6 (3.3.3.6)
      Origin IGP, localpref 100, valid, internal, best (First path received)
      **Community: 1111:1111**
      Last update: Tue Sep 26 16:10:09 2023
```

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Review by judyjoseph — APPROVED** [review]

**Comment by gechiang** [comment]
@yxieca , @StormLiangMS , Can you help review/approve for the corresponding branches (202205, 202211,a nd 202305)
Thanks!

**Comment by yxieca** [comment]
@abdosi I have a couple questions for this change:

- What if the send-community was configured asymmetrically? Will it cause harm?
- If a peer doesn't support receiving/handling the community, what will it do when received community? Any harmful situation that you are aware of?

**Comment by abdosi** [comment]
> @abdosi I have a couple questions for this change:
> 
> * What if the send-community was configured asymmetrically? Will it cause harm?
 
> * If a peer doesn't support receiving/handling the community, what will it do when received community? Any harmful situation that you are aware of?

It should not. community goes in BGP frame and other side will just parse it and use it accordingly. There is no requirement for it to be enable on both side of BGP session.
It just point to network config not being correct.

**Comment by StormLiangMS** [comment]
@abdosi have you tested with 202305?

**Comment by StormLiangMS** [comment]
@abdosi @gechiang to support cherry pick, could you pls also provide test result with 202305 image?

**Comment by abdosi** [comment]
> @abdosi @gechiang to support cherry pick, could you pls also provide test result with 202305 image?

@StormLiangMS  this is generic FRR change so should work with 202305. We don't have chassis image available as of now for 202305 to test end to end.  Change only applies to Chassis/mulit-asic system only

**Pull request merged**
