### PR TITLE
[201911][Mellanox] Update FW to version 2008_3388

### PR DESCRIPTION
**Pull request by moshemos**
#### Why I did it
FW Fix
* Spectrum-3 | PCI calibration changes from a static to a dynamic mechanism

#### How I did it
* Update FW.mk file to point to FW  version 2008_3388

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by moshemos** [comment]
/azpw run sonic-buildimage_merge_20220905.19,kvmtest-t0-sonic,kvmtest-t1-lag

**Comment by moshemos** [comment]
move the PR to new PR 

https://github.com/sonic-net/sonic-buildimage/pull/11978

**Pull request closed without merging**
