### PR TITLE
[Alphanetworks] Add new platform BES2348T

### PR DESCRIPTION
**Pull request by juntseng62**
#### Why I did it
Add the support for Alphanetworks BES2348T

#### How I did it
Implemented the support for platform BES2348T

Switch Vendor: Alphanetworks
HwSKU: Alphanetworks-BES2348T
ASIC Vendor: Broadcom

#### How to verify it
Verified the show platform commands
Attached file:
[bes2348t_test_log.txt](https://github.com/Azure/sonic-buildimage/files/8938548/bes2348t_test_log.txt)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by geans-pin** [comment]
Please provided UT

**Comment by geans-pin** [comment]
> Please provided UT



> #### Why I did it
> Add the support for Alphanetworks BES2348T
> 
> #### How I did it
> Implemented the support for platform BES2348T
> 
> Switch Vendor: Alphanetworks HwSKU: Alphanetworks-BES2348T ASIC Vendor: Broadcom
> 
> #### How to verify it
> Verified the show platform commands Attached file: [bes2348t_test_log.txt](https://github.com/Azure/sonic-buildimage/files/8938548/bes2348t_test_log.txt)
> 
> #### Which release branch to backport (provide reason below if selected)
> * [ ]  201811
> * [ ]  201911
> * [ ]  202006
> * [ ]  202012
> * [ ]  202106
> * [ ]  202111
> * [ ]  202205
> 
> #### Description for the changelog
> #### Link to config_db schema for YANG module changes
> #### A picture of a cute animal (not mandatory but encouraged)

**Comment by juntseng62** [comment]
Verify with PDE PYTEST UT PRs
1. [https://github.com/Azure/sonic-buildimage/pull/10836](https://github.com/Azure/sonic-buildimage/pull/10836)
2. [https://github.com/Azure/sonic-platform-pdk-pde/pull/30](https://github.com/Azure/sonic-platform-pdk-pde/pull/30)

Test log:
[bes2348t_pde_pytest_ut_log.txt](https://github.com/Azure/sonic-buildimage/files/8953928/bes2348t_pde_pytest_ut_log.txt)

**Comment by geans-pin** [comment]
Approved~ looks good to me

**Review by geans-pin — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by adyeung** [comment]
@prgeor pls help merge

**Comment by kannankvs** [comment]
@juntseng62  : We need to update the "Switch ASIC" column and "Port Configuration" column in the page [Supported Platform page](https://sonic-net.github.io/SONiC/Supported-Devices-and-Platforms.html). Kindly share the "Switch ASIC" (ex : Trident,Tomahawk etc) details and "Port Configuration" for the newly added platform.

**Comment by xinliu-seattle** [comment]
@juntseng62 can you please provide which ASIC SKU it is, so that we can update the supported platform with the right information.

**Comment by juntseng62** [comment]
@kannankvs  @xinliu-seattle: Platform Information show as below, Thanks.

Vendor: Alphanetworks
Platform: BES2348T
ASIC Vender: Broadcom
Switch ASIC: Trident 3.X2
Port Configuration: 48x1G+4x25G

**Comment by juntseng62** [comment]
@xinliu-seattle Please help to add Alphanetworks BES2348T to the supported platform list. Please help review it and let me know if anything is missing. Thanks.

**Pull request merged**
