### PR TITLE
Frr bookworm upgrade

### PR DESCRIPTION
**Pull request by hasan-brcm**
#### Why I did it
Migrate FRR To bookworm.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Makefile and docker config changes to refer to bookworm instead of bullseye.

#### How to verify it
Build bookworm frr docker.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog
Migrate FRR to bookworm.

### CODE REVIEW

**Comment by saiarcot895** [comment]
Might be blocked on #18150.

**Comment by saiarcot895** [comment]
@hasan-brcm Can you trigger a rerun of the PR checks?

**Comment by hasan-brcm** [comment]
> Azure Pipelines successfully started running 1 pipeline(s).

Apr 16 run failed due to libsnmp:
dh: error: unable to load addon python2: Can't locate Debian/Debhelper/Sequence/python2.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python2 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at (eval 13) line 1.
BEGIN failed--compilation aborted at (eval 13) line 1.

make[2]: *** [debian/rules:43: clean] Error 25
make[2]: Leaving directory '/sonic/src/snmpd/net-snmp-5.7.3+dfsg'
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
make[1]: *** [Makefile:35: /sonic/target/debs/bookworm/libsnmp-base_5.7.3+dfsg-5_all.deb] Error 2
make[1]: Leaving directory '/sonic/src/snmpd'
[  FAIL LOG END  ] [ target/debs/bookworm/libsnmp-base_5.7.3+dfsg-5_all.deb ]
make: *** [slave.mk:733: target/debs/bookworm/libsnmp-base_5.7.3+dfsg-5_all.deb] Error 1

**Comment by saiarcot895** [comment]
Could you remove the if-check and TODO comment in `rules/libyang.mk`? I added this during the Bookworm base image upgrade so that it wouldn't try to build unnecessary packages for Bookworm, but it is needed now.

**Comment by hasan-brcm** [comment]
> Could you remove the if-check and TODO comment in `rules/libyang.mk`? I added this during the Bookworm base image upgrade so that it wouldn't try to build unnecessary packages for Bookworm, but it is needed now.

Done. Thx!

**Comment by saiarcot895** [comment]
@hasan-brcm Looks like there are build failures in building FRR for Bookworm, can you resolve those?

Also, were you able to successfully build FRR for Bookworm locally?

**Comment by saiarcot895** [comment]
Hi @hasan-brcm any update here?

**Comment by hasan-brcm** [comment]
The below command in sonic-frr/Makefile needs EMAIL or DEBEMAIL env variable set.
```
gbp dch --ignore-branch --new-version=8.5.4-sonic-0 --dch-opt="--force-bad-version" --commit --git-author
```

Error:
```
...
Switched to a new branch 'frr/8.5'
branch 'frr/8.5' set up to track 'origin/frr/8.5'.
gbp:error: Either 'EMAIL' or 'DEBEMAIL' must be set in the environment for 'dch' to work
make[1]: *** [Makefile:11: /sonic/target/debs/bookworm/frr_8.5.4-sonic-0_amd64.deb] Error 1
```

**Comment by saiarcot895** [comment]
In `sonic-slave-bookworm/Dockerfile.user.j2`, can you add a environment variable there that sets `DEBEMAIL` to `$user@contoso.com`? (similar to how the username and email are set for git.

**Comment by saiarcot895** [comment]
That works too

**Comment by saiarcot895** [comment]
Current failures:

```
FAILED tests/test_bbr.py::test_set_handler_not_enabled_not_valid - AssertionError: expected call not found.
Expected: log_info('BBRMgr::BBR is disabled. Drop the request')
Actual: not called.
FAILED tests/test_bbr.py::test_del_handler - AssertionError: expected call not found.
Expected: log_err("The 'BGP_BBR' table shouldn't be removed from the db")
Actual: not called.
FAILED tests/test_bbr.py::test___init_1 - AssertionError: expected call not found.
Expected: log_err("BBRMgr::Disabled: 'bgp' key is not found in constants")
Actual: not called.
FAILED tests/test_bbr.py::test___init_2 - AssertionError: expected call not found.
Expected: log_info('BBRMgr::Disabled: no bgp.bbr.enabled in the constants')
Actual: not called.
FAILED tests/test_bbr.py::test___init_3 - AssertionError: expected call not found.
Expected: log_info('BBRMgr::Disabled: no bgp.bbr.enabled in the constants')
Actual: not called.
FAILED tests/test_bbr.py::test___init_4 - AssertionError: expected call not found.
Expected: log_info('BBRMgr::Disabled: no bgp.bbr.enabled in the constants')
Actual: not called.
FAILED tests/test_bbr.py::test___init_5 - AssertionError: expected call not found.
Expected: log_info('BBRMgr::Disabled: no BBR enabled peers')
Actual: not called.
FAILED tests/test_bbr.py::test___init_6 - AssertionError: expected call not found.
Expected: log_info("BBRMgr::Initialized and enabled. Default state: 'disabled'")
Actual: not called.
FAILED tests/test_bbr.py::test___init_7 - AssertionError: expected call not found.
Expected: log_info("BBRMgr::Initialized and enabled. Default state: 'disabled'")
Actual: not called.
FAILED tests/test_bbr.py::test___init_8 - AssertionError: expected call not found.
Expected: log_info("BBRMgr::Initialized and enabled. Default state: 'enabled'")
Actual: not called.
FAILED tests/test_bbr.py::test___read_pgs_no_configuration - AssertionError: expected call not found.
Expected: log_info("BBRMgr::no 'peers' was found in constants")
```

**Comment by saiarcot895** [comment]
Seeing as all of these are in `tests/test_bbr.py`, and they're all failing in the same way (there's a mock for `bgpcfgd.managers_setsrc.log_info` (and variants), and pytest isn't seeing the call to that function happening), there's probably a common problem here. Please check to see if the function passed into the `@patch` function decorator needs to change.

**Comment by zhangyanzhao** [comment]
let's complete the merge of this PR before 5/30 to catch up 202405 release fork date.

**Comment by zhangyanzhao** [comment]
still target 202405 release

**Review by StormLiangMS — DISMISSED** [review]
LGTM

**Review by saiarcot895 — APPROVED** [review]

**Comment by StormLiangMS** [comment]
hi @hasan-brcm @saiarcot895 this change LGTM, but I got one question for the support of bookworm. 

For BRCM SDK, I remember the current version we planed for 202405 release (11?) supports only bullseye. So for 202405, there would be only one container stay in bullseye, it is the syncd. All other containers would go to bookworm. And for later release, start from 202411, the syncd and others would be landed on bookworm, is this correct?

**Comment by adyeung** [comment]
@StormLiangMS BRCM SDK will remain on bookworm until 202411, eg, platform/broadcom/docker-syncd-brcm

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
