### PR TITLE
[Mellanox] Fix uninitialized variable on module plug event

### PR DESCRIPTION
**Pull request by fastiuk**
#### Why I did it
To fix uninitialized variable

#### How I did it
Add initial value

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### A picture of a cute animal (it is my cat Finn)
PXL_20230413_140941610 PORTRAIT

### CODE REVIEW

**Comment by fastiuk** [comment]
@lguohan could you please review?

**Comment by liat-grozovik** [comment]
@fastiuk to which branches this fix should go in? just master?

**Comment by fastiuk** [comment]
That bug with us since day 0.
starting from v201911, when that file was created.
Since that, I assume master is enough

**Comment by fastiuk** [comment]
> @fastiuk to which branches this fix should go in? just master?

That bug with us since day 0.
starting from v201911, when that file was created.
Since that, I assume master is enough

**Comment by fastiuk** [comment]
@prgeor could you please review this fix? Thanks

**Review by prgeor — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
