### PR TITLE
Fix arista_7800r3a_36d2_lc fabric link down issue

### PR DESCRIPTION
**Pull request by jfeng-arista**
arista_7800r3a_36d2_lc several fabric links on Arista 7800r3a_36d2_lc chip1 are down due to some mis-configuration. Fixing the configutation here  so those links on chip 1 can come up. 
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@arlakshm for awareness

**Comment by kenneth-arista** [comment]
Requesting backport to 202205 and 202305 as well.

**Review by arlakshm — APPROVED** [review]

**Comment by jfeng-arista** [comment]
> Hi @jfeng-arista, can put that data from `show fabric...` commands to see which links are affected before and after this change?

Yes . 

"show fabric counters port -n **asic1**"  you can see those about 50 links are down now on that type of card .( links on asic 0 are fine ) . 

With this change , all those link expected to be up should up now while I was testing ( except if there is any flaky ones ).

**Comment by jfeng-arista** [comment]
> > Hi @jfeng-arista, can put that data from `show fabric...` commands to see which links are affected before and after this change?
> 
> Yes .
> 
> "show fabric counters port -n **asic1**" you can see those about 50 links are down now on that type of card .( links on asic 0 are fine ) .
> 
> With this change , all those link expected to be up should up now while I was testing ( except if there is any flaky ones ).

Discussed this change with Arvind. For expected links status we can find out at "sonic-mgmt/tests/voq/fabric_data", and that should cover all cards that we supported. 
For example, for this 7800r3a_36d2_lc, the expected down fabric links are: 
  ASIC    PORT    STATE   
------  ------  ------- 
     0      25     down       
     0      31     down       
     0      64     down       
     0      67     down       
     0     104     down       
     0     111     down       
     0     121     down       
     0     126     down       
     0     140     down       
     0     143     down       
     0     160     down       
     0     163     down 
     
     1       2     down       
     1       7     down       
     1      25     down       
     1      31     down       
     1      56     down       
     1      58     down       
     1      88     down       
     1      92     down       
     1     107     down       
     1     110     down       
     1     126     down       
     1     160     down       
     1     163     down

**Review by vmittal-msft — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@yxieca @wangxin please help merge.

**Comment by StormLiangMS** [comment]
hi @vmittal-msft  approved, pls update the ADO.

**Pull request merged**
