### PR TITLE
[frr] fix default zebra config not inserted into empty zebra.conf

### PR DESCRIPTION
**Pull request by stepanblyschak**
#### Why I did it

If zebra.conf is cleared:

```
for f in /etc/sonic/frr/*.conf; do cp /dev/null $f; done
```

The following line:

```
sed -i '1i no fpm use-next-hop-groups\nfpm address 127.0.0.1' $FILE_NAME
```

will not insert default zebra configuration as there is no first line.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Replace ```sed``` with simple ```echo``` commands

#### How to verify it

Configure ```split``` mode. Clear FRR configuration files. Reboot the switch and verify default zebra configuration is applied.
Write some configuration into zebra.conf and reboot. Verify that default and user zebra configuration is present in /etc/frr/zebra.conf.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [x] master.510-fbe75ee85_Internal

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by stepanblyschak** [comment]
marvell build failed on sonic-ycabled target:
```

  File "/sonic/src/sonic-platform-daemons/sonic-ycabled/setup.py", line 28, in <module>
    setup(
  File "/usr/local/lib/python3.9/dist-packages/setuptools/__init__.py", line 162, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.9/dist-packages/setuptools/__init__.py", line 157, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.9/dist-packages/setuptools/dist.py", line 699, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 779, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.9/dist-packages/setuptools/dist.py", line 758, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.9/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpkfux992o', '--quiet', 'grpcio>=1.59.0']' returned non-zero exit status 1.
[  FAIL LOG END  ] [ target/python-wheels/bullseye/sonic_ycabled-1.0-py3-none-any.whl ]
make: *** [slave.mk:882: target/python-wheels/bullseye/sonic_ycabled-1.0-py3-none-any.whl] Error 1
make: *** Waiting for unfinished jobs....
```
Since the same package was built successfully for other platform and not related to the change I'll guess it is some environment issue.

The dual-tor test fails on test_features_state when running "show mux status" and is not related to this PR:

```
E               Failed: Processes "['_verify_show_mux_status--<MultiAsicSonicHost vlab-06>', '_verify_show_mux_status--<MultiAsicSonicHost vlab-05>']" failed with exit code "1"
E               Exception:
E               run module shell failed, Ansible Results =>
E               {"changed": true, "cmd": "show mux status", "delta": "0:00:02.461083", "end": "2023-10-02 09:08:12.665198", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-10-02 09:08:10.204115", "stderr": "", "stderr_lines": [], "stdout": "could not retrieve key state value for port Ethernet4 inside table MUX_CABLE_TABLE", "stdout_lines": ["could not retrieve key state value for port Ethernet4 inside table MUX_CABLE_TABLE"]}
E               Traceback:
E               Traceback (most recent call last):
E                 File "/var/src/sonic-mgmt/tests/common/helpers/parallel.py", line 35, in run
E                   Process.run(self)
E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/var/src/sonic-mgmt/tests/common/plugins/sanity_check/checks.py", line 479, in _verify_show_mux_status
E                   dut_mux_status = dut.show_and_parse("show mux status")
E                 File "/var/src/sonic-mgmt/tests/common/devices/sonic.py", line 1609, in show_and_parse
E                   output = self.shell(show_cmd, **kwargs)["stdout_lines"]
E                 File "/var/src/sonic-mgmt/tests/common/devices/base.py", line 127, in _run
E                   raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E               tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E               {"changed": true, "cmd": "show mux status", "delta": "0:00:02.461083", "end": "2023-10-02 09:08:12.665198", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-10-02 09:08:10.204115", "stderr": "", "stderr_lines": [], "stdout": "could not retrieve key state value for port Ethernet4 inside table MUX_CABLE_TABLE", "stdout_lines": ["could not retrieve key state value for port Ethernet4 inside table MUX_CABLE_TABLE"]}
```

I consider to restart the test suite.

**Comment by stepanblyschak** [comment]
PR checkers pass now, so I assume it is unstable and not related to the change due to the analysis above and have to be investigated separately.

**Comment by StormLiangMS** [comment]
ADO: 25530585

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
