### PR TITLE
Increase LAG Ids to 1024

### PR DESCRIPTION
**Pull request by ysmanman**
#### Why I did it
Today at most 128 LAGs are supported. This is not sufficient if there are many LAGs with just few ports.

#### How I did it
Increase LAG Ids to 1024 for DNX device.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Review by arlakshm — APPROVED** [review]

**Comment by rlhui** [comment]
@ysmanman - could you check why test is failing and resolve?

**Comment by ysmanman** [comment]
Hi @arlakshm , I think we need to cherry-pick this PR into 202205.

**Comment by kenneth-arista** [comment]
@arlakshm gentle ping as this is required to address https://github.com/sonic-net/sonic-buildimage/issues/14271

**Comment by rlhui** [comment]
@arlakshm please add a MSFT ADO for the cherry-pick request

**Comment by arlakshm** [comment]
MSFT ADO 25260643

**Comment by gechiang** [comment]
Adding a note here that the reason this change was not requested for 202305 branch is because this change is already present in 202305.

**Pull request merged**
