### PR TITLE
[Mellanox] get LED capability from capability file

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Currently, LED sysfs path is hardcoded. We will need change LED code if new LED color is supported for new platforms. This PR is aimed to improve this. By this PR, LED sysfs path is deduced from LED capability file.

#### How I did it

Improve LED management on Nvidia platform:

- get LED capability from capability file and deduce sysfs name according to the capability

#### How to verify it

Unit test
Manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor , could you please help review it?

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor , could you please kindly review this?

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@liat-grozovik to merge

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik , could you please help merge this?

**Review by liat-grozovik — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @StormLiangMS , could you please help cherry-pick to 202211?

**Pull request merged**
