### PR TITLE
Add yang model definition for CHASSIS_MODULE table

### PR DESCRIPTION
**Pull request by tjchadaga**
#### Why I did it
Add yang model definition for CHASSIS_MODULE define and implemented for sonic chassis. HLD for this configuration is included in https://github.com/sonic-net/SONiC/blob/master/doc/pmon/pmon-chassis-design.md#configuration

Fixes https://github.com/sonic-net/sonic-buildimage/issues/12640

#### How I did it
Added yang model definition, unit tests, sample config and documentation for the table
#### How to verify it

1.  Validated config tree generation using "pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/sonic-voq-inband-interface.yang"

2. Built the below python-wheels to validate unit tests and other changes
    target/python-wheels/bullseye/sonic_yang_mgmt-1.0-py3-none-any.whl
    target/python-wheels/bullseye/sonic_yang_models-1.0-py3-none-any.whl
    target/python-wheels/bullseye/sonic_config_engine-1.0-py3-none-any.whl

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211

#### Link to config_db schema for YANG module changes

https://github.com/sonic-net/sonic-buildimage/blob/bf705140d01ad4d7d8e9b39777d96689de3e1ffb/src/sonic-yang-models/doc/Configuration.md#chassis-module

### CODE REVIEW

**Review by ganglyu — APPROVED** [review]

**Review by arlakshm — APPROVED** [review]

**Comment by xumia** [comment]
image
There are two checks with the same name Azure.sonic-buildimage, one of them does not have chance to pass the check. It might be caused by Azure pipelines issue. Need to merge the PR by force.

**Comment by yxieca** [comment]
@tjchadaga can you create separate PR for 202205 branch?

**Comment by StormLiangMS** [comment]
@tjchadaga can you create separate PR for 202211 branch?

**Comment by tjchadaga** [comment]
> @tjchadaga can you create separate PR for 202211 branch?

@StormLiangMS -   PR https://github.com/sonic-net/sonic-buildimage/pull/14358 was created for 202211 branch

**Pull request merged**
