### PR TITLE
[Mellanox] CMIS host management script

### PR DESCRIPTION
**Pull request by skr31**
#### Why I did it
Added a script for CMIS Host Management enabling and disabling on a running switch.
This intend to prevent issues caused by wrong configuration of the feature.
The idea is to provide a more convenient way for users to configure the feature.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add the script to /usr/bin/ that supports two options:
--enable - receives paths to config files for Port SI parameters and Module SI parameters:
media_settings.json, optics_si_settings.json, and enables the feature
--disable - disables the feature
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [ ] 202311
- [X] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by noaOrMlnx — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@prgeor FYI

**Comment by dprital** [comment]
@prgeor  / @bingwang-ms  - Can it be cherry picked to 202405 please ?

**Comment by bingwang-ms** [comment]
I'm good to cherry-pick to 202405. But we don't need it for 202311 as we don't have CMIS in 202311.

**Comment by dprital** [comment]
> I'm good to cherry-pick to 202405. But we don't need it for 202311 as we don't have CMIS in 202311.

CMIS was added to 202311. having this script will assist with Enable\ Disable of CMIS Host management. 
It was already merged to 202311: https://github.com/sonic-net/sonic-buildimage/pull/19526

**Comment by bingwang-ms** [comment]
> > I'm good to cherry-pick to 202405. But we don't need it for 202311 as we don't have CMIS in 202311.
> 
> CMIS was added to 202311. having this script will assist with Enable\ Disable of CMIS Host management. It was already merged to 202311: #19526

Yes, you are right.

**Pull request merged**
