### PR TITLE
Updated MMU settings for Nokia 400g and 100g HWSKUs

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
Updated MMU settings to enhance performance for RDMA traffic in production.  

##### Work item tracking
- Microsoft ADO **(28551006)**:

#### How I did it
Updated device files for buffer pool/profile settings.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by judyjoseph** [comment]
@saksarav-nokia please review

**Comment by vmittal-msft** [comment]
for arista hwsku - https://github.com/sonic-net/sonic-buildimage/pull/18500
for qos tests - https://github.com/sonic-net/sonic-mgmt/pull/11907

**Comment by gechiang** [comment]
@vmittal-msft , wondering how these numbers were chosen? Were there any performance tests done?  Or these were recommended by Nokia team which did run rigorous performance testing and resulted to this numbers for the community to consume? If you can add some support info in the description that would be helpful.

**Comment by vmittal-msft** [comment]
> @vmittal-msft , wondering how these numbers were chosen? Were there any performance tests done? Or these were recommended by Nokia team which did run rigorous performance testing and resulted to this numbers for the community to consume? If you can add some support info in the description that would be helpful.

@gechiang These numbers are chosen based on internal discussion with RDMA team and field experience. We will have sai release matching with these changes as well (It helps with expanded buffers for PG).

**Comment by vmittal-msft** [comment]
Adding dump from HW tables to facilitate code review - 
[MMU settings.txt](https://github.com/sonic-net/sonic-buildimage/files/15422809/MMU.settings.txt)

**Comment by vmittal-msft** [comment]
@saksarav-nokia please review.

**Comment by vmittal-msft** [comment]
'/azpw ms_conflict

**Review by mlok-nokia — APPROVED** [review]
Checked it with Sakthi . It looks good.

**Comment by saksarav-nokia** [comment]
Anshu already ran  the sonic-mgmt Qos and verified this PR and adjusted the Qos.yml.. Looks good.

**Comment by mlok-nokia** [comment]
@vmittal-msft This change requires to modify the expected result to pass the UT in image build.

**Comment by vmittal-msft** [comment]
[nokia_logs.txt](https://github.com/user-attachments/files/15844712/nokia_logs.txt)

**Comment by vmittal-msft** [comment]
@saksarav-nokia  please review latest settings.

**Comment by gechiang** [comment]
@vmittal-msft please share MSFT ADO number for this PR

**Comment by vmittal-msft** [comment]
> @vmittal-msft please share MSFT ADO number for this PR



> @vmittal-msft please share MSFT ADO number for this PR

Done

**Comment by vmittal-msft** [comment]
@yxieca @lguohan @rlhui Can you please help merge this ?

**Pull request merged**
