### PR TITLE
Added blkinfo module to host for use by ssdutil

### PR DESCRIPTION
**Pull request by assrinivasan**
#### Why I did it
Part of fix for issue #9407 

##### Work item tracking
- Microsoft ADO: 25484875

#### How I did it
Added blkinfo module to the host

#### How to verify it
Install image with this change, then run: `pip list | grep blkinfo` and verify the following output:
```
$ pip list | grep blkinfo
blkinfo                    0.2.0
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305
- [x] 202311
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Review by saiarcot895 — APPROVED** [review]

**Comment by assrinivasan** [comment]
@prgeor @lguohan please help merge. TIA.

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@assrinivasan fyi.

**Comment by assrinivasan** [comment]
> @assrinivasan fyi. 
Yes @prgeor I have an ADO to manually fix the cherry pick conflicts. Will update.

**Pull request merged**
