### PR TITLE
[armhf][Nokia-7215]Add HWSKU files for new SAI

### PR DESCRIPTION
**Pull request by Pavan-Nokia**
Add new easy bringup (EZB) files for new SAI 1.12.0

#### Why I did it
Add supporting HWSKU files for new Marvell SAI

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
Build marvell-armhf sonic image and test on 7215-IXS-T1
Ran full OC test to verify no regressions.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Pavan-Nokia** [comment]
/azpw run Azure.sonic-buildimage (Test kvmtest-t1-lag by Elastictest)

**Comment by Pavan-Nokia** [comment]
@Blueve This PR along with #16299 updates SAI for Nokia-7215

The PR check failures are not related to my changes can we rerun the checks

**Comment by Blueve** [comment]
ADO: 24866493

**Comment by Blueve** [comment]
@StormLiangMS could you help cherry-pick this to 202305?

**Pull request merged**
