### PR TITLE
[Chassis] Update lossy profile to restrict buffer usage in congestion state

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
This change is to restrict lossy queue buffer usage in case of congestion state.

##### Work item tracking
- Microsoft ADO **(29315559)**:

#### How I did it
Updated alpha from 0 to -4 (400g) & -5 (100g) port speed. This configuration is applied on system port and will be using HWSKU port speed settings.

#### How to verify it
It is verified using sonic-mgmt tests and running ok.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by vmittal-msft** [comment]
@saksarav-nokia @kenneth-arista please help review.

**Comment by gechiang** [comment]
@vmittal-msft , Is this also applicable for 202205 chassis? if so, please add the label "chassis for 202205 branch"

**Comment by vmittal-msft** [comment]
@BYGX-wcr

**Comment by BYGX-wcr** [comment]
Hi @judyjoseph , Can you please review this? I have no experience in RDMA buffer tuning.

**Review by arlakshm — COMMENTED** [review]
Why the alpha value is different for 400g/100g Lcs. If a 400g port is configured at 100g speed, will it still use the 400g port alpha?

**Comment by vmittal-msft** [comment]
It is different to give different q limits for different port speeds. 100g port will get lesser limit then 400g.

**Review by arlakshm — APPROVED** [review]

**Comment by judyjoseph** [comment]
@vmittal-msft, do add reference to the qos tests run with these new configs, or any PR sonic-mgmt test change needed to support this.

**Comment by vmittal-msft** [comment]
Yes. I have requested Nokia team to refer this while opening sonic-mgmt PR.

**Review by arlakshm — APPROVED** [review]

**Review by kenneth-arista — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@yxieca @rlhui @wangxin Can you please help merge ?

**Pull request merged**
