### PR TITLE
[BGP]Increasing maximum-paths to 514

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### Why I did it
This PR follows https://github.com/sonic-net/sonic-buildimage/pull/20744
Increasing the maximum-paths to 514. Currently value of 64 restricts the maximum paths that can created by BGP.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Updated constants file.

#### How to verify it
Modified UT to verify.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by r12f — APPROVED** [review]

**Comment by r12f** [comment]
although not a expert, but looks like a very straight forward change. signed off!

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
