### PR TITLE
Upgrade Ansible to 6.7.0 and make Python3 as the default interpreter in sonic-mgmt-docker

### PR DESCRIPTION
**Pull request by wsycqyz**
#### Why I did it
This PR is part of sonic-mgmt-docker Python3 migration project.

##### Work item tracking
- Microsoft ADO **(number only)**: 24397943

#### How I did it
1. Upgrade Ansible to 6.7.0
2. Make Python3 as the default interpreter. python is a soft link to python3. If you want to use python2, use the command python2 explicitly.
3. Upgrade some pip packages to higher version in order to meet security requirement.

#### How to verify it
1. Build a private sonic-mgmt-docker successfully.
2. Verify python is python3.
4. Verify python2 is working with 202012 and 202205 branch.
5. Verify python3 is working with master branch.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by wangxin — DISMISSED** [review]

**Comment by wsycqyz** [comment]
Will wait for a few days. After PR test and nightly test verified and then merge.

**Review by wangxin — APPROVED** [review]

**Pull request merged**
