### PR TITLE
[Mellanox] Fix 4600c sensors.conf inverted psu number designation 

### PR DESCRIPTION
**Pull request by yuazhe**
#### Why I did it
This PR is used to standardize several sensors.conf psu section
I. Fix 4600/4600c inverted psu number designation
II. Fix 5600 second psu miss set_power_cap label
III. Standardized comments

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
check `sensors` command output

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] 202311
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yuazhe please check if this also needed for 202305

**Comment by yuazhe** [comment]
@yxieca please help to approve this pr for 202305

**Pull request merged**
