### PR TITLE
Update Broadcom SAI to 7.1.0.0-9

### PR DESCRIPTION
**Pull request by saiarcot895**
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

#### Why I did it

This brings in a SAI library that is compiled on Bullseye.

#### How to verify it

XGS SAI library has been tested with fib, fdb, and VxLAN decap test cases.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Comment by yxieca** [comment]
@saiarcot895 can this change be cherry-picked to 20205? Is there other dependencies needs to go first?

**Comment by saiarcot895** [comment]
Looks like d30d84b4c6e12583ec9a322a3a4054358d364478 is a dependency.

Also, is there a reason DNX SAI library is still at 7.1.0.0-1?

**Comment by judyjoseph** [comment]
@saiarcot895 there is a change made with version 7.1.0.0-8 which increases the MAX_ACL_TABLES -- I am checking with @richardyu-ms if this is applicable to both XGS and DNX 

```
 -#define _BRCM_SAI_MAX_ACL_TABLES                 47
 +/* Max GID Value returned by "data dump field.group.nof_fgs" */
 +#define _BRCM_SAI_MAX_ACL_TABLES                 128
```

**Review by gechiang — APPROVED** [review]

**Review by judyjoseph — APPROVED** [review]

**Comment by saiarcot895** [comment]
For backporting to 202205, #10864 is a dependency.

**Pull request merged**
