### PR TITLE
Update the iSMART_64 tool

### PR DESCRIPTION
**Pull request by santhosh-kt**
#### Why I did it
- Updating the iSMART_64 tool for supporting latest debian releases.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
On branch new_ismart
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   platform/broadcom/sonic-platform-modules-dell/s6100/scripts/iSMART_64

#### How to verify it
- In s6100, run the `iSMART_64` tool.

md5sum - 24725730d7649769c7ba50971c1f2955

#### Which release branch to backport (provide reason below if selected)

- [x] 201811
- [x] 201911
- [x] 202006
- [x] 202012
- [x] 202106
- [x] 202111
- [x] 202205
- [x] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by santhosh-kt** [comment]
Please cherry-pick the change across the requested versions.

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@lguohan please help merge.

**Comment by prgeor** [comment]
@yxieca @StormLiangMS pleae cherry pick

**Comment by yxieca** [comment]
> @yxieca @StormLiangMS pleae cherry pick

This doesn't look like a bug fix?

**Comment by prgeor** [comment]
> > @yxieca @StormLiangMS pleae cherry pick
> 
> This doesn't look like a bug fix?

@santhosh-kt please update the description with GPIO issue fixed by this updated tool?

**Comment by santhosh-kt** [comment]
@prgeor  = Updated the description.

**Comment by StormLiangMS** [comment]
@prgeor ADO?

**Pull request merged**
