### PR TITLE
Implementation of S3IP SYSFS framework and two platforms supporting S3IP SYSFS

### PR DESCRIPTION
**Pull request by tianshangfei**
#### Why I did it
Implementation of S3IP SYSFS framework
#### How I did it
Add S3IP SYSFS framework Implementation and two platforms supporting S3IP SYSFS (TCS8400, TCS9400)
#### How to verify it
Manual test
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog

Add S3IP SYSFS framework Implementation and two platforms supporting S3IP SYSFS (TCS8400, TCS9400)

### CODE REVIEW

**Comment by lihuay** [comment]
@tianshangfei : there a few issues with this PR. 
1. can you please authorize the EasyCLA, This is standard LF practice. 
2. This PR is almost 120K lines. This makes it difficult for people to offer a meaningful code review. Can you please break this PR into smaller piece, e.g. separate the platform dependent part from the platform independent part
3. This PR is failing the pre-checkin tests. can you please fix.

**Comment by tianshangfei** [comment]
> @tianshangfei : there a few issues with this PR.
> 
> 1. can you please authorize the EasyCLA, This is standard LF practice.
> 2. This PR is almost 120K lines. This makes it difficult for people to offer a meaningful code review. Can you please break this PR into smaller piece, e.g. separate the platform dependent part from the platform independent part
> 3. This PR is failing the pre-checkin tests. can you please fix.

I will update code PR later

**Comment by tianshangfei** [comment]
> @tianshangfei : there a few issues with this PR.
> 
> 1. can you please authorize the EasyCLA, This is standard LF practice.
> 2. This PR is almost 120K lines. This makes it difficult for people to offer a meaningful code review. Can you please break this PR into smaller piece, e.g. separate the platform dependent part from the platform independent part
> 3. This PR is failing the pre-checkin tests. can you please fix.

This PR has been divided into two parts and added to the S3IP sysfs HLD PR. Please see the update
https://github.com/sonic-net/SONiC/pull/1068

**Comment by tianshangfei** [comment]
这个pr过时了，请看更新https://github.com/sonic-net/SONiC/pull/1068

**Pull request closed without merging**
