### PR TITLE
[Submodule] Updating sonic-swss to latest commits

### PR DESCRIPTION
**Pull request by tapashdas**
…dated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID (#2538)

#### Why I did it
 Updating sonic-swss to latest to include following fixes - 
  a443945 : Updated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID (#2538)

#### How I did it
Updating sonic-swss pointer to latest

#### How to verify it
Verified these changes on real hardware

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by tapashdas** [comment]
@dgsudharsan , @prsunny  Please review

**Comment by tapashdas** [comment]
@srj102 Please review

**Comment by tapashdas** [comment]
https://github.com/sonic-net/sonic-swss/pull/2538

**Review by dgsudharsan — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by lguohan** [comment]
there is conflict needs to be resolved.

**Comment by dgsudharsan** [comment]
Hi @tapashdas . I am closing this PR since a newer PR is already merged https://github.com/sonic-net/sonic-buildimage/pull/13223

**Pull request closed without merging**
