### PR TITLE
[submodule] Advance sonic-swss-common pointer

### PR DESCRIPTION
**Pull request by dprital**
Signed-off-by: dprital <drorp@nvidia.com>

#### Why I did it

Update sonic-swss-common submodule pointer to include the following:
* Add docker-mux related table names  ([#627](https://github.com/sonic-net/sonic-swss-common/pull/627))
* Transfer organization from Azure to sonic-net ([#656](https://github.com/sonic-net/sonic-swss-common/pull/656))

#### How I did it

Update submodule pointer 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by msosyak** [comment]
@dprital Could you update your PR to include the latest commits from sonic-swss  
[\[fdborch\] Fix FDB flush issues ](https://github.com/sonic-net/sonic-swss/commit/8dae35645962b0ce8b9b4ddc80d64162b51b5f65)


[\[muxorch\] return true if the nbr IP is in the skip_neighbors list ](https://github.com/sonic-net/sonic-swss/commit/2cb70a320173a44a4b1e2006cc45ee658f03d83e)

Thank you in advance

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
