### PR TITLE
[master] Update XGS SAI version to 10.1.35.0

### PR DESCRIPTION
**Pull request by r12f**
#### Why I did it

Upgrade the xgs SAI version to 10.1.35.0 to include the following changes:

- 10.1.21.0: Update the ACL impelementation to enable the ACL switch bind to support PFCWD on MACSEC devices
- 10.1.23.0: Handle the FDR stats get not supported more properly.
- 10.1.24.0: (CSP CS00012316286) Fix LPM Miss ACL with counters fails
- 10.1.25.0: Improve ECMP performance
- 10.1.28.0: Fix SAI is not honoring the bcm_linkscan_interval set in .bcm config file for Ramon and error with setting SAI_NEIGHBOR_ENTRY_ATTR_IS_LOCAL attribute for neighbor
- 10.1.29.0: Fix fabric switch initialization delayed if SW linkscan enabled during platform init
- 10.1.30.0: (CSP CS00012356911) Fix traffic drops on all priorities when PFC asserted on two priorities.
- 10.1.31.0: NHG performance fix
- 10.1.33.0: (CSP CS00012345242) High CPU due to SAI code calls bcm_port_resource_get for every fabric error counter
- 10.1.35.0: Support MMU configuration updates for TH5.

##### Work item tracking
- Microsoft ADO **(number only)**: 28724885

#### How I did it

Upgrade the SAI version in the sai.mk file.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [X] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Gfrom2016** [comment]
@r12f Could you also list in the description what changes were included between version 10.1.21.0 and 10.1.35.0, in addition to the 10.1.35.0 version that exists now?

**Comment by r12f** [comment]
> @r12f Could you also list in the description what changes were included between version 10.1.21.0 and 10.1.35.0, in addition to the 10.1.35.0 version that exists now?

Yep! Ze is working on it with Ziting to provide more details on the previous releases.

**Comment by r12f** [comment]
Hi @Gfrom2016 , I have got the release log updated.

**Comment by Gfrom2016** [comment]
Basic SONiC test on 202311 with 10.1.35.0 results: https://dev.azure.com/mssonic/internal/_build/results?buildId=596255&view=results, fyi

**Review by Gfrom2016 — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
@r12f Please file another PR to 202405 branch to address cherry-pick conflict if it's required.

**Comment by r12f** [comment]
@Pterosaur , do you mind to help with this? Thanks!

**Comment by Gfrom2016** [comment]
@bingwang-ms @r12f @Pterosaur 202405 branch already upgraded in this PR #19635

**Pull request merged**
