### PR TITLE
[Nokia][chassis] modify Nokia-IXR7250E-36x400G platform specified reboot to allow SUP to log expected/unexpected midplane/module connectivity msg

### PR DESCRIPTION
**Pull request by mlok-nokia**
#### Why I did it
For Linecard expected and unexpected reboot, Supervisor needs to log a expected and unexpected lost connectivity message.  After the new mechanism has been introduced by PRs.   For Nokia-IXR7250E-36x600G linecard,  it requires to handle missing heartbeat reboot is unexpected reboot for SUP.   Issue https://github.com/sonic-net/sonic-buildimage/issues/18540

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
On Nokia-IXR7250E-36x400G platform, missing heartbeat reboot also call the "sudo reboot" which creates a CHASSIS_MODULE_REBOOT_INFO_TABLE entry expected reboot on SUP.  Since heartbeat reboot is unexpected reboot, it requires to modify the platform_reboot check if it is missing heart reboot, then remove the CHASSIS_MODULE_REBOOT_INFO_TABLE entry on the SUP. So that, SUP can log the unexpected log.

#### How to verify it
1) Simulated the missing heartbeat reboot on the linecard, then, verify the log message on SUP as below
```
Apr 25 19:50:19.286081 ixre-cpm-chassis7 WARNING pmon#chassisd: Module LINE-CARD0 went off-line!
Apr 25 19:50:22.549416 ixre-cpm-chassis7 WARNING pmon#chassisd: Unexpected: Module LINE-CARD0 lost midplane connectivity.
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@deepak-singhal0408  @judyjoseph  This PR is for an issue of logging lost midplane connectivity log.  Total 3 PRs. Please review them.  Thanks

**Review by deepak-singhal0408 — APPROVED** [review]
LGTM

**Comment by gechiang** [comment]
@mlok-nokia ,
What is the dependency of this PR with "https://github.com/sonic-net/sonic-platform-daemons/pull/480"?
If let's say we backport this to .msft repo 202205 branch but not the platorm-daemons PR (480), will there be any build issue or functionality issue?  Reason I am asking this is because I don't think "https://github.com/sonic-net/sonic-platform-daemons/pull/480" will be allowed to 202205 branch and since we don't have a .msft 202205 repo for this platform-deamons submodule, the  complete bug fix will be incomplete for the community building with 202205...  But we should be able tomake internal build with patch.  Just want to make sure there are no negative impact to the rest of the community.
please confirm.
Thanks!

**Comment by mlok-nokia** [comment]
> @mlok-nokia , What is the dependency of this PR with "[sonic-net/sonic-platform-daemons#480](https://github.com/sonic-net/sonic-platform-daemons/pull/480)"? If let's say we backport this to .msft repo 202205 branch but not the platorm-daemons PR (480), will there be any build issue or functionality issue? Reason I am asking this is because I don't think "[sonic-net/sonic-platform-daemons#480](https://github.com/sonic-net/sonic-platform-daemons/pull/480)" will be allowed to 202205 branch and since we don't have a .msft 202205 repo for this platform-deamons submodule, the complete bug fix will be incomplete for the community building with 202205... But we should be able tomake internal build with patch. Just want to make sure there are no negative impact to the rest of the community. please confirm. Thanks!

It should be fine without any other related PRs in the same build image.

**Comment by deepak-singhal0408** [comment]
MSFT ADO: 28164943

**Comment by gechiang** [comment]
@StormLiangMS , @yxieca , Please help review/approve for backport this bug fix to 202305 and 202311.
Thanks!

**Comment by gechiang** [comment]
Discussed this with @yxieca , Going forward, we will no longer be backporting any fixes to 202305 and 202311 any more including Chassis.  So I will be removing the labels requesting for backport.  We plan to pick up 202405 next as the next branch for full chassis support.

**Pull request merged**
