### PR TITLE
[Mellanox] Support DSCP remapping in Dual-ToR topo for SN4700-O8V48, update buffers for t0

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
#### Why I did it
Need to provide support for SN4700-O8V48 for Dual-ToR.
DSCP remapping is a part of Dual-ToR feature, so need to update HWSKU files to align with requirements

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Use QoS config the same as used in 4600C platform that is already supports Dual-ToR
update buffers for T0

#### How to verify it
Run DSCP remapping test for Dual-ToR

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@bingwang-ms to check

**Comment by bingwang-ms** [comment]
For this specific HWSKU, the change looks good to me. For the Dual-ToR topo, the current plan is to use HWSKU Mellanox-SN4700-V64. Are you going to define the topo and buffer template as well?

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@yxieca Can you please help merge this PR? Another PR will be raised for HWSKU SN4700-V64

**Comment by ayurkiv-nvda** [comment]
Reminder regarding cherry-pick this PR to 202305

**Comment by dgsudharsan** [comment]
@StormLiangMS  Can you please cherry-pick for 202305?

**Pull request merged**
