### PR TITLE
add 200G values to pg profile lookup

### PR DESCRIPTION
**Pull request by ccroy-arista**
This change adds 200G settings for Tomahawk 5 to the pg_profile_lookup.

Fixes: https://github.com/aristanetworks/sonic-qual.msft/issues/159

#### Why I did it

This change is needed in order for some qos tests to run against TH5.

#### How I did it

Added the values then manually ran qos tests identified in the issue above to verify fix.

#### How to verify it

Run qos/test_qos_sai.py::TestQosSai::testParameter and confirm that the IndexError in the issue above does not occur.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311
- [x] 202405

### CODE REVIEW

**Review by r12f — APPROVED** [review]
lgtm!

**Comment by ccroy-arista** [comment]
202405 merge conflict is due to needing the following PR to be cherry-picked into 202405 first: https://github.com/sonic-net/sonic-buildimage/pull/19161

**Comment by ccroy-arista** [comment]
Awaiting cherry-pick to 202405.

**Comment by ccroy-arista** [comment]
Awaiting cherry-pick to 202405.

**Pull request merged**
