### PR TITLE
[Marvell] platform renaming for innovium

### PR DESCRIPTION
**Pull request by krismarvell**
#### Why I did it
Renaming of platforms and asic types for marvell
This PR has dependencies on the below submodule PRs

<html><body>

Repo | PR title | State
-- | -- | --
sonic-swss |[ [Marvell] platform renaming for innovium](https://github.com/sonic-net/sonic-swss/pull/3252) | Open
sonic-utilities |[ platform renaming for innovium](https://github.com/sonic-net/sonic-utilities/pull/3474) | Open
sonic-sairedis |[ [Marvell] platform renaming for innovium](https://github.com/sonic-net/sonic-sairedis/pull/1408) | Open
sonic-mgmt |[Changes to support chip name change from innovium to marvell-teralynx](https://github.com/sonic-net/sonic-mgmt/pull/14330) | Open

</body>
</html>

#### How I did it
renamed platform folder names and asic types as below
platform/innovium renamed to platform/marvell-teralynx

#### How to verify
Verify marvell-teralynx  builds going through, and verify the images in teralynx switches and verified linkup of interfaces

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)
master

#### Description for the changelog
NA

#### Link to config_db schema for YANG module changes
NA

### CODE REVIEW

**Comment by saiarcot895** [comment]
@Blueve please help with the review for this

@liushilongbuaa @xumia please help with the changes to the pipeline yml files. Specifically, are there any other changes needed for the nightly official builds?

**Comment by krismarvell** [comment]
@liushilongbuaa @xumia Can you pls checking if there are additional changes needed for the nightly pipeline builds with these changes ? @Blueve Can you pls help review ?

**Comment by liushilongbuaa** [comment]
checking.

**Review by liushilongbuaa — APPROVED** [review]

**Comment by saiarcot895** [comment]
Would it be possible to keep the image name for marvell_prestera_arm64 and marvell_prestera_armhf the same as it is now? The platform string can be renamed, but if the image name is kept the same, that would be good for scripts/automation that use the existing name.

**Comment by krismarvell** [comment]
@saiarcot895 it wont be possible to make the image name same as before due to two below reasons.
1. the image names are closely tied with ONE_IMAGE definition in marvell platform and hence keeping the old image names vs platform string renames in code may end up in image build errors and may require unclean fix for the same. 
2. Also, for the platform users, we would like to add prestera as reference marker for this asic for clarity.
The scripts/automation using the above platform image names, is that something i can make appropriate changes so as to work with this change ? Pls let me know

**Review by saiarcot895 — APPROVED** [review]

**Comment by krismarvell** [comment]
@saiarcot895 have done a latest rebase with a conflict resolved. Request help with the merge.

**Comment by krismarvell** [comment]
@lguohan Can you pls help merge this changeset

**Pull request merged**
