### PR TITLE
Fixing #12634

### LINKED ISSUE #12634: [PDDF] sfputil show lpmode will get error message
#### Description

When cmd "sfputil show lpmode", console will dump error message. 
#### Steps to reproduce the issue:
1. Insert QSFP transceiver to port. 
2. Cmd "sfputil show lpmode" will get error message. 

3.

#### Describe the results you received:
Get below fail message,
File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 1064, in lpmode
    lpmode = platform_chassis.get_sfp(physical_port).get_lpmode()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform_pddf_base/pddf_sfp.py", line 207, in get_lpmode
    power_set = self.get_power_set()
AttributeError: 'Sfp' object has no attribute 'get_power_set'

#### Describe the results you expected:
Cmd "sfputil show lpmode should get all port lpmode status (on or off). It can't get error message"

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

### PR DESCRIPTION
**Pull request by FuzailBrcm**
#### Why I did it
Fixes #12634 

Observing the following error while running 'sfputil show lpmode' command.
AttributeError: 'Sfp' object has no attribute 'get_power_set'

Root Cause: get_power_set() is defined for QSFP28 and QSFP+ i.e. Sff8636 and Sff8634. However, the function is not defined in the optoe_base class.
 
#### How I did it
To use get_power_set(), we need to initialise the 'api' via get_xcvr_api() and then use it to run get_power_set().
  

```
 

root@sonic:/home/admin# sfputil show lpmode

Port         Low-power Mode

-----------  ----------------

Ethernet88   Off

Ethernet96   Off

Ethernet248  Off

Ethernet240  Off

Ethernet32   Off

 

root@sonic:/home/admin# sfputil lpmode on Ethernet240

Enabling low-power mode for port Ethernet240 ... OK

root@sonic:/home/admin#

root@sonic:/home/admin# sfputil show lpmode

Port         Low-power Mode

-----------  ----------------

Ethernet240  On

Ethernet80   Off

..........

 

root@sonic:~# sfputil lpmode off Ethernet240

Disabling low-power mode for port Ethernet240 ... OK

root@sonic:~#

root@sonic:~#

root@sonic:~#

root@sonic:~# sfputil show lpmode

Port         Low-power Mode

-----------  ----------------

...............

Ethernet248  Off

........

Ethernet240  Off

``` 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by FuzailBrcm** [comment]
@prgeor , @ds952811 
Please review

**Review by ds952811 — APPROVED** [review]

**Review by jostar-yang — APPROVED** [review]
it is fine to me.

**Comment by adyeung** [comment]
@prgeor @lguohan pls help review and merge

**Pull request merged**
