### PR TITLE
[submodule] Advance sonic-linux-kernel pointer

### PR DESCRIPTION
**Pull request by dprital**
Signed-off-by: dprital <drorp@nvidia.com>

#### Why I did it

Update sonic-linux-kernel submodule pointer to include the following:
* [Mellanox] Add new kernel patches from HW-MGMT package V.7.0020.3005 ([#287](https://github.com/sonic-net/sonic-linux-kernel/pull/287))
* [patch] mlxsw: i2c: Prevent transaction execution for special chip ([#279](https://github.com/sonic-net/sonic-linux-kernel/pull/279))
* [sflow + dropmon] added missing patch for the sFlow + dropmon feature. ([#281](https://github.com/sonic-net/sonic-linux-kernel/pull/281))
* [sflow + dropmon] added patches for the sFlow + dropmon feature. ([#276](https://github.com/sonic-net/sonic-linux-kernel/pull/276))

#### How I did it

update submodule pointer

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by dprital** [comment]
.azpw run

**Comment by saiarcot895** [comment]
Closing in favor of #11709.

**Pull request closed without merging**
