### PR TITLE
[platform-common] submodule update

### PR DESCRIPTION
**Pull request by dmytroxIntel**
sonic-platform-common:
9df998bbec12083dd88104657d2fd8f67e217bc3 (HEAD -> master, origin/master, origin/HEAD) Don't read AUX_MON_TYPE if memory model is flat ([#339](https://github.com/sonic-net/sonic-platform-common/pull/339))
676b329efd1b8cbe30b6e874308cd1ccf69466f8 Removing null characters while decoding from syseeprom ([#338](https://github.com/sonic-net/sonic-platform-common/pull/338))

#### Why I did it
Need to merge xcvr fix in cmis implementation from sonic-platform-common submodule
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by dmytroxIntel** [comment]
@lguohan , @prgeor , @StormLiangMS please merge this submodule update

**Comment by dmytroxIntel** [comment]
@kperumalbfn , please merge this submodule update

**Review by kperumalbfn — APPROVED** [review]

**Comment by kperumalbfn** [comment]
@dmytroxIntel Is this change required in 202211 branch?

**Comment by prgeor** [comment]
@dmytroxIntel this commit is already available in the master. please remove:

`
676b329efd1b8cbe30b6e874308cd1ccf69466f8 Removing null characters while decoding from syseeprom (https://github.com/sonic-net/sonic-platform-common/pull/338)
`

**Comment by lguohan** [comment]
@prgeor , if it is already included, then the actuall commit does not include the commit. the pr is fine, just description is confusing.

**Pull request merged**
