### PR TITLE
Update HWSKU files for EZBv1.08 for SONiC 202311 branch

### PR DESCRIPTION
**Pull request by krismarvell**
#### Why I did it
EZB V1.08 supports below new features
serdes params support
PHY LED support

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added 1.08 xml files with new features

#### How to verify it
Build sonic 202311 image and verify interface link up in marvell hwsku

Build 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

### CODE REVIEW

**Comment by saiarcot895** [comment]
This looks like it can just be a cherry-pick of #19403? If so, can this be closed, and that PR be marked for cherry-pick back to 202405 and 202311?

**Comment by krismarvell** [comment]
@saiarcot895 #19403 in 202311 branch has different hwsku content (e.g. board hwsku file contains TWSI params in 202311 vs master which does not have). And these files in #19330 vs #19403 are being used in different releases by different end users. Hence there is a need to maintain different hwsku files both in 202311 and master. But from 202405 onwards, we can make sure this converge  vs master snapshot.

**Review by saiarcot895 — APPROVED** [review]

**Comment by saiarcot895** [comment]
@krismarvell Can you update the title to add `[202311] ` at the beginning, to make it clear that this is going into the 202311 branch?

**Comment by krismarvell** [comment]
@saiarcot895 I have updated the Heading as per your comment. Pls let me know if you see any ambiguity. Thanks for reviewing and approving,

**Comment by Blueve** [comment]
ADO 29332201

**Pull request merged**
