### PR TITLE
[Chassis] add startup_tsa_tsb_service_files

### PR DESCRIPTION
**Pull request by arlakshm**
#### Why I did it
Add startup_tsa_tsb service file for Arista Linecards.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
add the `startup_tsa_tsb` service files for Arista Linecards platform

#### How to verify it
Test on T2 tests

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by YatishSVC** [comment]
lgtm

**Review by kenneth-arista — APPROVED** [review]
LGTM

**Review by arista-nwolfe — APPROVED** [review]
Thanks for adding these files Arvind

**Review by Javier-Tan — APPROVED** [review]
LGTM

**Comment by Javier-Tan** [comment]
Fixes sonic-net/sonic-mgmt#15629

**Review by rlhui — APPROVED** [review]

**Pull request merged**
