### PR TITLE
[202205][Arista] Mark thermals as not controllable for 7050CX3-32S platform

### PR DESCRIPTION
**Pull request by andywongarista**
#### Why I did it
The platform_tests.api.test_thermal::test_set_low_threshold testcase fails because by default the thermals on this platform are not controllable via the API.

#### How I did it
Mark thermals as not controllable in platform.json

#### How to verify it
Verified that testcase is skipped instead of failing

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by assrinivasan — APPROVED** [review]

**Comment by prgeor** [comment]
@andywongarista can you review?

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@lguohan could you merge. failure is not related to this pr

**Comment by yxieca** [comment]
@andywongarista Generally, we only cherry-pick changes from master to feature branches. Cherry-picking from feature branch to feature branch is easier to get into merge conflicts etc. Do you have master branch PR that can be cherry-picked into 202211 and/or 202012 branch? If not, please raise separate PRs for these 2 branches.

**Comment by andywongarista** [comment]
@yxieca This PR on master can be cherry-picked: https://github.com/sonic-net/sonic-buildimage/pull/12082

**Pull request merged**
