### PR TITLE
[TACACS] Ignore TACACS accounting trace log when debug disabled.

### PR DESCRIPTION
**Pull request by liuh-80**
Ignore TACACS accounting trace log when debug disabled.

#### Why I did it
TACACS accounting trace log is only for debug, improve code to not generate trace log when debug disabled.

##### Work item tracking
- Microsoft ADO: 25270078

#### How I did it
Ignore TACACS accounting trace log when debug disabled.

#### How to verify it
Pass all UT.
Manually verified the auditd-tacplus not generate trace log when debug disabled. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

will updated with this PR image later.
- [x] SONiC.master-16482.360728-2c8b4066f
- [x] SONiC.202205-16653.368721-c45a92ff2

#### Description for the changelog
Ignore TACACS accounting trace log when debug disabled.

### CODE REVIEW

**Comment by liuh-80** [comment]
re-trigger build by close and re-open

**Review by qiluo-msft — APPROVED** [review]

**Comment by liuh-80** [comment]
Close by mistake, re-open

**Comment by liuh-80** [comment]
There is a bug in this PR, when backport, the fix PR also need backport: https://github.com/sonic-net/sonic-buildimage/pull/18357

**Comment by liuh-80** [comment]
During validation, I found this PR can't auto cherry-pick because this PR has a code bug which fixed by https://github.com/sonic-net/sonic-buildimage/pull/18357

So manually create 2 cherry-pick PR:
202305: https://github.com/sonic-net/sonic-buildimage/pull/19061
202311: https://github.com/sonic-net/sonic-buildimage/pull/19060

**Pull request merged**
