### PR TITLE
[FRR]Upgrade FRR to 8.5.4

### PR DESCRIPTION
**Pull request by dgsudharsan**
Addresses https://github.com/sonic-net/SONiC/issues/1537
#### Why I did it
Upgrading FRR 8.5.4 to include latest fixes.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

**New patches that were added:**

| Patch | FRR Pull request| Issue fixed |
| ------  |--------- | ------------ |
| 0024-lib-use-snmp-s-large-fd-sets-for-agentx.patch  | https://github.com/FRRouting/frr/pull/13396 | https://github.com/FRRouting/frr/issues/14143|
| 0025-bgp-community-memory-leak-fix.patch  |https://github.com/FRRouting/frr/pull/15466 | https://github.com/FRRouting/frr/issues/15459 |
| 0026-bgp-fib-suppress-announce-fix.patch  | https://github.com/FRRouting/frr/pull/15634 | https://github.com/FRRouting/frr/issues/15626|
| 0027-lib-Do-not-convert-EVPN-prefixes-into-IPv4-IPv6-if-n.patch | https://github.com/FRRouting/frr/pull/15418 | https://github.com/FRRouting/frr/issues/14419 |

**Removed patches:**
| Patch | Upstream FRR commit that is present in 8.5.4 | 
| ------  |--------- | 
| 0019-zebra-Abstract-dplane_ctx_route_init-to-init-route-w.patch | https://github.com/FRRouting/frr/commit/3f01977b990641f43c0916cd5db6b2ffe20d3ba0  |
|0020-zebra-Fix-crash-when-dplane_fpm_nl-fails-to-process-.patch | https://github.com/FRRouting/frr/commit/fe5f62441558bd657a8444072a2b12d84f626fdc |
|0022-bgpd-Don-t-read-the-first-byte-of-ORF-header-if-we-a.patch | https://github.com/FRRouting/frr/commit/3515178de4a56d66ed948a774efcbe4a854e1ca7 |
|0023-bgpd-Make-sure-we-have-enough-data-to-read-two-bytes.patch | https://github.com/FRRouting/frr/commit/460ee930d6dbce6e96ecbfcd568a291f31bae24e |
|0024-bgpd-Do-not-process-NLRIs-if-the-attribute-length-is.patch | https://github.com/FRRouting/frr/commit/f291f1ee9434f56d4b185db0652794a92e313b00 |
|0025-bgpd-Use-treat-as-withdraw-for-tunnel-encapsulation-.patch| https://github.com/FRRouting/frr/commit/8a4a88c46d15004b1a584cd47f9f6b8278f8da66 |
|0026-zebra-Add-encap-type-when-building-packet-for-FPM.patch | https://github.com/FRRouting/frr/commit/f0f7b285b99dbd971400d33feea007232c0bd4a9 | 
|0028-bgpd-Check-mandatory-attributes-more-carefully-for-U.patch| https://github.com/FRRouting/frr/commit/21418d64af11553c402f932b0311c812d98ac3e4 |
|0029-bgpd-Handle-MP_REACH_NLRI-malformed-packets-with-ses.patch |https://github.com/FRRouting/frr/commit/30b5c2a434d25981e16792f6f50162beb517ae4d | 
|0030-bgpd-Treat-EOR-as-withdrawn-to-avoid-unwanted-handli.patch |https://github.com/FRRouting/frr/commit/01f232c227e566fec924472eb61cd6489a6e1d2b| 
|0031-bgpd-Ignore-handling-NLRIs-if-we-received-MP_UNREACH.patch | https://github.com/FRRouting/frr/commit/a0c4ec2f52b299d45a77b0fcb29452329d22dce1 |
|0032-zebra-Fix-fpm-multipath-encap-addition.patch | https://github.com/FRRouting/frr/commit/10a9a5f400586450d52d7acfdd05c2cff27b7f80| 

**Realigned patches:**
| Old Patch | New patch |
| ------  |--------- | 
|0005-Add-support-of-bgp-l3vni-evpn.patch | 0005-Add-support-of-bgp-l3vni-evpn.patch | 
|0021-zebra-remove-duplicated-nexthops-when-sending-fpm-msg.patch| 0019-zebra-remove-duplicated-nexthops-when-sending-fpm-msg.patch|
| 0027-zebra-Fix-non-notification-of-better-admin-won.patch| 0020-zebra-Fix-non-notification-of-better-admin-won.patch |
| Disable-ipv6-src-address-test-in-pceplib.patch| 0021-Disable-ipv6-src-address-test-in-pceplib.patch|
| cross-compile-changes.patch |0022-cross-compile-changes.patch|
| 0033-zebra-The-dplane_fpm_nl-return-path-leaks-memory.patch | 0023-zebra-The-dplane_fpm_nl-return-path-leaks-memory.patch|

#### How to verify it
Running sonic-mgmt test suite.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@StormLiangMS please review and approve. final tests expected in few days. once completed i wish to merge it.

**Comment by robertvolkmann** [comment]
@dgsudharsan FRR 8.5 has an urgent bug that prevents of using e.g. `match evpn vni` in a route-map. The fix was already merged into 9.0, 9.1 and 10.0, but for 8.5 it is still ongoing.

PR for 8.5: https://github.com/FRRouting/frr/pull/15418
Bug description: https://github.com/FRRouting/frr/issues/14419#issuecomment-1836456246

**Comment by dgsudharsan** [comment]
> @dgsudharsan FRR 8.5 has an urgent bug that prevents of using e.g. `match evpn vni` in a route-map. The fix was already merged into 9.0, 9.1 and 10.0, but it is still ongoing for 8.5.
> 
> PR for 8.5: [FRRouting/frr#15418](https://github.com/FRRouting/frr/pull/15418) Bug description: [FRRouting/frr#14419 (comment)](https://github.com/FRRouting/frr/issues/14419#issuecomment-1836456246)

Thanks for pointing out. I have taken this fix in the latest commit.

**Comment by robertvolkmann** [comment]
@donaldsharp Yeah, the branches 202305 and 202311 with FRR 8.5.1 are also affected.

**Comment by dgsudharsan** [comment]
> @donaldsharp Yeah, the branches 202305 and 202311 with FRR 8.5.1 are also affected.

Here is PR for 202311 https://github.com/sonic-net/sonic-buildimage/pull/18732

@StormLiangMS  please review

**Review by donaldsharp — APPROVED** [review]
LGTM

**Comment by liat-grozovik** [comment]
@StormLiangMS kindly help to review and merge.

**Comment by StormLiangMS** [comment]
hi @dgsudharsan as we discussed in the email, beside the bgp fib suppress issue, others LGTM. Could you pls help to priority the separate PR to disable it from both SONiC and FRR level by default?

**Pull request merged**
