### PR TITLE
[minigraph] Added support to parse "AssociatedSliceStr" attribute of minigraph

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Added support to parse "AssociatedSliceStr" attribute of minigraph and save as `slice_type` as part of DEVICE_METADATA for Chassis Device Type.
Yang model are done as part of : https://github.com/sonic-net/sonic-buildimage/pull/19094

Also as part of this change fixed issue of current device not selected correctly as asic_hostname not being correct.

Why I did:
In BGP Templates we need to take different action based on this attribute.

How I verify:
UT updated.

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by lguohan** [comment]
@qiluo-msft , here is another minigraph parse change. can you check if you can accomodate this one?

**Comment by abdosi** [comment]
@lguohan / @qiluo-msft  :  please help merge of this.

**Review by qiluo-msft — APPROVED** [review]

**Comment by abdosi** [comment]
@bingwang-ms : can you please pick for 202405.Needed for chassis

**Pull request merged**
