### PR TITLE
Update BRCM KNET modules to support new psample definitions from sflow…

### PR DESCRIPTION
**Pull request by michaelli10**
#### What I did
Update BRCM KNET modules to support new psample definitions from sflow dropmon feature
#### Why I did it
BRCM KNET build was failing after changes in [sflow dropmon feature PR284](https://github.com/sonic-net/sonic-linux-kernel/pull/284)).   References to psample were updated in the sflow dropmon feature and needs to be updated in BRCM KNET modules.
#### How I did it
- Remove KNET module psample (use Linux kernel psample instead)
- Make changes in KNET sflow psample code to reflect new psample function definition
- Advance sonic-linux-kernel submodule to get sflow dropmon feature in [PR284](https://github.com/sonic-net/sonic-linux-kernel/pull/284).
- Advance saibcm-modules-dnx to pickup changes in [PR10](https://github.com/sonic-net/saibcm-modules/pull/10).

#### Commits included in #11709
f015a8b [sflow_dropmon_knet] Update BRCM KNET modules to support new psample definitions from sflow + dropmon feature (#11709)
0298b4a [sflow_dropmon_knet] Advance saibcm-modules-dnx (#11709)
12f5c81 [sflow_dropmon_knet] Advance sonic-linux-kernel (#11709)

### CODE REVIEW

**Comment by saiarcot895** [comment]
The changes in this PR should go in with a sonic-linux-kernel submodule update.

**Review by saiarcot895 — APPROVED** [review]

**Comment by saiarcot895** [comment]
Could you update the PR description to include the individual commits in the `sonic-linux-kernel` submodule update?

**Comment by michaelli10** [comment]
> Could you update the PR description to include the individual commits in the `sonic-linux-kernel` submodule update?

I updated the commit ID for the 2 items describing the advancement of sonic-linux-kernel and saibcm-module submodules in the PR description.
> Advance sonic-linux-kernel submodule to get sflow dropmon feature in https://github.com/sonic-net/sonic-linux-kernel/pull/284. Commit https://github.com/sonic-net/sonic-buildimage/commit/12f5c81ff7ff78ec75aa899eccd3cdbfeba66ae5
> Advance saibcm-modules-dnx to pickup changes in https://github.com/sonic-net/saibcm-modules/pull/10. Commit https://github.com/sonic-net/sonic-buildimage/commit/0298b4aafc712d1fd1fafa80d225104acb7c52e5

**Comment by saiarcot895** [comment]
I meant something like this:

```
fdd9bac [Mellanox] Add new kernel patches from HW-MGMT package V.7.0020.3005 (#287)
50e2bff [patch] mlxsw: i2c: Prevent transaction execution for special chip (#279)
fa9411d [sflow + dropmon] added missing patch for the sFlow + dropmon feature. (#281)
1f83896 [sflow + dropmon] added patches for the sFlow + dropmon feature. (#276)
```

**Comment by michaelli10** [comment]
@saiarcot895 added references to the 3 commits in the PR description.  Let me know if any other info is needed.

**Pull request merged**
