### PR TITLE
[202205][Arista] Update arista platform submodules

### PR DESCRIPTION
**Pull request by pjavanarista**
#### Why I did it
* Fixed race condition during fabric initialization
* Better handle transceiver insertion

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Description for the changelog
Update Arista platform submodules

### CODE REVIEW

**Comment by lguohan** [comment]
which platform does this affect?

**Comment by lguohan** [comment]
@arlakshm , can you check if this is needed?

**Comment by kenneth-arista** [comment]
> which platform does this affect?

Sorry I missed this question earlier. These changes specifically target the Arista 7800r3a* linecards; e.g.,
* x86_64-arista_7800r3a_36d2_lc
* x86_64-arista_7800r3a_36d_lc
* x86_64-arista_7800r3a_36dm2_lc
* x86_64-arista_7800r3a_36p_lc
* x86_64-arista_7800r3ak_36d2_lc
* x86_64-arista_7800r3ak_36dm2_lc

**Comment by kenneth-arista** [comment]
> @arlakshm , can you check if this is needed?

@lguohan and @arlakshm these changes are necessary for the Wolverine line cards to address some race conditions with fabric initialization as well corner cases during transceiver insertions. Let us know if you have any additional questions.

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@lguohan @yxieca, can you help merge this PR. This is needed for chassis

**Comment by yxieca** [comment]
@kenneth-arista does this change affect any platform other than 7800? @arlakshm  can you assess if we can take this change to chassis branch only?

**Comment by kenneth-arista** [comment]
We can close this PR in favor of merging https://github.com/sonic-net/sonic-buildimage/pull/19338 instead

**Comment by arlakshm** [comment]
closing this PR

**Pull request closed without merging**
