### PR TITLE
[202311][cherry-pick][NTP] Add NTP extended configuration

### PR DESCRIPTION
**Pull request by fastiuk**
hld [#1296](https://github.com/sonic-net/SONiC/pull/1296)
closes [#1254](https://github.com/sonic-net/SONiC/issues/1254)
cherry-picks [#15058](https://github.com/sonic-net/sonic-buildimage/pull/15058)

#### Why I did it
To cover the next AIs:
* Configure NTP global parameters
* Add/remove new NTP servers
* Change the configuration for NTP servers
* Show NTP status
* Show NTP configuration

#### How I did it
* Add YANG model for a new configuration
* Extend configuration templates to support new knobs

#### Description for the changelog

* Add ability to configure NTP global parameters such as authentication, dhcp, admin state
* Change the configuration for NTP servers
* Add an ability to show NTP configuration

#### Link to config_db schema for YANG module changes

[NTP configuration](https://github.com/sonic-net/sonic-buildimage/blob/202311/src/sonic-yang-models/doc/Configuration.md#ntp-servers)

#### A picture of a cute animal (it is my cat Finn)
PXL_20230413_140941610 PORTRAIT

### CODE REVIEW

**Comment by yxieca** [comment]
@fastiuk this seems to be a feature PR. I don't think we should cherry-pick feature PR(s) into a release branch.

**Comment by fastiuk** [comment]
> @fastiuk this seems to be a feature PR. I don't think we should cherry-pick feature PR(s) into a release branch.

It is. But 4 out of 5 PRs for this feature were merged, and are part of 202311. So I think it is mandatory to cherry-pick the last one

**Comment by yxieca** [comment]
@fastiuk test_ntp is consistently failure. Can you make the test compatible with before and after this change?

**Comment by fastiuk** [comment]
> @fastiuk test_ntp is consistently failure. Can you make the test compatible with before and after this change?

Tests passed. Please merge it

**Comment by fastiuk** [comment]
@yxieca Any updates?

**Pull request merged**
