### PR TITLE
Upgrade broadcom platform containers(syncd) to Bookworm

### PR DESCRIPTION
**Pull request by sg893052**
#### Why I did it
Migration of platform broadcom docker syncd from bullseye to bookworm

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Update container makefiles with correct dependencies
Update container Dockerfile with correct base image

#### How to verify it
Compilation of the following images:
[docker-syncd-brcm.gz]
[docker-syncd-brcm-dnx.gz]
[sonic-broadcom-dnx.bin]
[sonic-broadcom.bin]

Loaded sonic-broadcom.bin on a x86_64-accton_as7816_64x-r0
root@sonic:/home/admin# docker ps | grep syncd
1bc2b3bbe11c   docker-syncd-brcm:latest             "/usr/local/bin/supe…"   13 minutes ago   Up 13 minutes             syncd
root@sonic:/home/admin#
root@sonic:/home/admin# docker exec -it syncd bash
root@sonic:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@sonic:/#

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by sg893052** [comment]
@adyeung FYI

**Comment by adyeung** [comment]
@saiarcot895 pls help review

**Review by saiarcot895 — APPROVED** [review]

**Comment by adyeung** [comment]
@saiarcot895 thanks for the review, I assume you want to hold off the merge until SAI release 12.x is out? Otherwise, pls share the merge plan

**Comment by adyeung** [comment]
Last call, if there is no objection, we will proceed to merge for 202411

**Comment by saiarcot895** [comment]
No objections from me

**Review by Praveen-Brcm — APPROVED** [review]

**Pull request merged**
