### PR TITLE
DellEMC: Initial commit for S5224F platform support

### PR DESCRIPTION
**Pull request by arunlk-dell**
#### Why I did it
Added support for the device S5224F

#### How I did it
Implemented the support for the platform S5224F

Switch Vendor: DellEMC
* Switch SKU: S5224F-ON
* ASIC Vendor: Broadcom
* SONiC Image: sonic-broadcom.bin

#### How to verify it
Verified the show platform/interface commands

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### A picture of a cute animal (not mandatory but encouraged)

[s5212_logs.txt](https://github.com/Azure/sonic-buildimage/files/7137639/s5212_logs.txt)

### CODE REVIEW

**Comment by arunlk-dell** [comment]
@sujinmkang @prgeor - Can you review and approve the changes ?

**Review by sujinmkang — DISMISSED** [review]

**Comment by sujinmkang** [comment]
@arunlk-dell Can you please check those LGTM alerts?

**Comment by arunlk-dell** [comment]
@sujinmkang.....Have addressed the LGTM alerts, the wrong name/number of the argument alerts are due to different platform definitions.

**Review by sujinmkang — DISMISSED** [review]

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
