### PR TITLE
[services] kill container on stop in warm/fast mode

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

Depends on https://github.com/Azure/sonic-utilities/pull/2184.
#### Why I did it

To optimize stop on warm boot.

#### How I did it

Added kill for containers

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Comment by stepanblyschak** [comment]
@vaibhavhd looks like this PR won't pass tests without sonic-utilities update as well as sonic-utilities update PR won't pass tests without this PR. Updated sonic-utilities here and checking results.

**Comment by vaibhavhd** [comment]
The tests failed with:
`        "FAILED:dut:Longest downtime period must be less then 200 seconds. It was 0:03:43.843506", `

**Comment by vaibhavhd** [comment]
I am curious now why the same PR on 202012 (https://github.com/Azure/sonic-buildimage/pull/10511) consistently passed and this one on master consistently failed.
Particularly when this PR is meant to improve the warmboot flow.

**Comment by stepanblyschak** [comment]
On VS switch there is an issue with few services that are not observed on the DUT:

```
admin@localhost:~$ sudo systemctl --failed
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION
● hostname-config.service  loaded failed failed Update hostname based on config>
● system-health.service    loaded failed failed SONiC system health monitor
● watchdog-control.service loaded failed failed watchdog control service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
3 loaded units listed.
```

This is causing hostcgd to wait forever in ```wait_till_system_init_done```. In this state hostcfgd does not reach to SIGTERM sent by systemd during shutdown and as a result is killed with a SIGKILL after 90 sec. This should be fixed in hostcfgd regardless to above issue in order to make test passed on VS.

**Comment by stepanblyschak** [comment]
There is a problem that hostcfgd blocks forever and does not react to SIGTERM causing a delay in warm boot

**Comment by yxieca** [comment]
@stepanblyschak  you are also updating sonic-utilities submodule head with this PR? Please update PR comments accordingly and list the changes included in this PR by submodule change.

**Comment by liat-grozovik** [comment]
I would suggest to differentiate and have submodule PR on a separate PR

**Comment by stepanblyschak** [comment]
@liat-grozovik @yxieca It is for test, currently this PR is blocked due to https://github.com/Azure/sonic-swss-common/issues/603

**Comment by vaibhavhd** [comment]
> Please note, that this PR only works togather with [Azure/sonic-utilities#2184](https://github.com/Azure/sonic-utilities/pull/2184) thus we will need to merge [Azure/sonic-utilities#2184](https://github.com/Azure/sonic-utilities/pull/2184) first and I will need to updated utilities submodule in this PR to make tests pass

@stepanblyschak utilities PR is merged now.  Please update the submodule here and let's trigger the new PR tests on this PR.

**Comment by stepanblyschak** [comment]
kvmtest-t1-lag tests fail because they exceed the timeout of 300m. Looks like the timeout needs to be increased

**Review by vaibhavhd — APPROVED** [review]

**Pull request merged**
