### PR TITLE
[202311][zebra] remove dplane_fpm_nl config from zebra.conf

### PR DESCRIPTION
**Pull request by stepanblyschak**
#### Why I did it

Remove dplane_fpm_nl configuration from zebra.conf to fix the following errors in /var/log/frr/zebra.log:

```
Jun 27 10:59:26.839855 qa-eth-vt04-6-3700c ERR bgp#zebra[49]: [SHWNK-NWT5S][EC 100663304] No such command on config line 10: no fpm use-next-hop-groups
Jun 27 10:59:26.839855 qa-eth-vt04-6-3700c ERR bgp#zebra[49]: [SHWNK-NWT5S][EC 100663304] No such command on config line 12: fpm address 127.0.0.1
```

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Remove these configs.

#### How to verify it

Build and run - no errors in the log.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by StormLiangMS** [comment]
this seems an enhancement, not necessary for 202305.

**Comment by stepanblyschak** [comment]
@StormLiangMS Could you please clarify, any reason for not taking it for 202305? What about this PR which targets 202311?

**Comment by StormLiangMS** [comment]
hi @stepanblyschak besides these two error logs, it is annoying, but could I suppose there is no functional breakage? If so, I think we can live with it. 

For 202311, I'm ok, but it would be Ying's call to cherry pick or not. @yxieca

**Comment by stepanblyschak** [comment]
@StormLiangMS No functional impact

**Comment by yxieca** [comment]
> @StormLiangMS No functional impact

Thanks for confirming. It looks like ineffective command generating noise error log. I am okay with taking it into 202311 but I agree with Storm, it is too late and too trivial for 202305 to take at this stage.

**Pull request merged**
