### PR TITLE
[submodule] Advance sonic-swss pointer

### PR DESCRIPTION
**Pull request by dprital**
Signed-off-by: dprital <drorp@nvidia.com>

#### Why I did it

Update sonic-swss submodule pointer to include the following:
* *Flexcounter - Fix issue: ip prefix of a route flow pattern shall be initialized even if VRF/VNET is not ready ([#2461](https://github.com/sonic-net/sonic-swss/pull/2461))
* Revert "[counters] Improve performance by polling only configured ports buffer queue/pg counters (2360) ([#2458](https://github.com/sonic-net/sonic-swss/pull/2458))
* [ci][asan] add DVS tests run with ASAN ([#2441](https://github.com/sonic-net/sonic-swss/pull/2441))
* [ci] Only when test stage succeeded or succeededwithissues, PR run Gcov ([#2460](https://github.com/sonic-net/sonic-swss/pull/2460))
* [orchagent]: Publish identified events via structured-events channel ([#2446](https://github.com/sonic-net/sonic-swss/pull/2446))
* [QoS] Enforce drop probability only for colors whose WRED are enabled ([#2422](https://github.com/sonic-net/sonic-swss/pull/2422))
* [swss] Replace memset functions ([#2423](https://github.com/sonic-net/sonic-swss/pull/2423))
* Modified the test file to remove click commands and do the REDIS-DB u… ([#2264](https://github.com/sonic-net/sonic-swss/pull/2264))
* Install libyang in azure pipeline ([#2445](https://github.com/sonic-net/sonic-swss/pull/2445))
* check state_db for po before sending ARP/ND pkts ([#2444](https://github.com/sonic-net/sonic-swss/pull/2444))
* [portmgr] Fixed the orchagent crash due to late arrival of notif ([#2431](https://github.com/sonic-net/sonic-swss/pull/2431))
* Revert "[VS Test] Skip failing subport tests (2370)" ([#2421](https://github.com/sonic-net/sonic-swss/pull/2421))
* [UT] [Portsyncd] Added Unit Tests for portsyncd ([#2297](https://github.com/sonic-net/sonic-swss/pull/2297))
* Change the log messages in addKernelNeigh/Route from ERROR to INFO ([#2437](https://github.com/sonic-net/sonic-swss/pull/2437))
* [BFD]Clean up state_db BFD entries on swss restart ([#2434](https://github.com/sonic-net/sonic-swss/pull/2434))
* EntityBulker SIGSEGV when create_entry attr_count 0 ([#2224](https://github.com/sonic-net/sonic-swss/pull/2224))
* Fix the Fec Mode Setting of gbsyncd ([#2430](https://github.com/sonic-net/sonic-swss/pull/2430))
* [neighsyncd] Enabling ipv4 link local entries for non-dualtor ([#2427](https://github.com/sonic-net/sonic-swss/pull/2427))
* Revert "[ci][asan] add DVS tests run with ASAN (2363)" ([#2433](https://github.com/sonic-net/sonic-swss/pull/2433))
* Dynamic port configuration - add port buffer cfg to the port ref counter ([#2194](https://github.com/sonic-net/sonic-swss/pull/2194))
* tlm_teamd: Filter portchannel subinterface events from STATE_DB LAG_TABLE ([#2408](https://github.com/sonic-net/sonic-swss/pull/2408))
* [counters] Improve performance by polling only configured ports buffer queue/pg counters ([#2360](https://github.com/sonic-net/sonic-swss/pull/2360))
* added support for Xsight platform ([#2426](https://github.com/sonic-net/sonic-swss/pull/2426))
* [ci][asan] add DVS tests run with ASAN ([#2363](https://github.com/sonic-net/sonic-swss/pull/2363))
* Handle dual ToR neighbor miss scenario ([#2151](https://github.com/sonic-net/sonic-swss/pull/2151))
* Upstream new development on p4orch ([#2237](https://github.com/sonic-net/sonic-swss/pull/2237))
* [lgtm] Fix dependency ([#2419](https://github.com/sonic-net/sonic-swss/pull/2419))
* [muxorch] Returning true if nbr in skip_neighbor_ in isNeighborActive() ([#2415](https://github.com/sonic-net/sonic-swss/pull/2415))
* [macsec]: Set MTU for MACsec ([#2398](https://github.com/sonic-net/sonic-swss/pull/2398))
* Delete Invalid if condition in intfsorch.cpp ([#2411](https://github.com/sonic-net/sonic-swss/pull/2411))

#### How I did it

Advance sonic-swss pointer

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by Pterosaur** [comment]
This PR needs waiting for https://github.com/sonic-net/sonic-sairedis/pull/1107 to be merge.

**Comment by prsunny** [comment]
@dprital , can you please rebase and resubmit this PR, I had to change the swss commit for PR 2297 to fix the commit message.

**Comment by liat-grozovik** [comment]
@prsunny looks like swss is not frequently updated. i suggest that at least in master we have it more frequently to avoid failures on the pr update.
@dprital  thanks for the PR. as there are failures, need to check what is the root cause and communicate with Prince or the pr owner

**Comment by dprital** [comment]
> @dprital , can you please rebase and resubmit this PR, I had to change the swss commit for PR 2297 to fix the commit message.

Done

**Comment by liat-grozovik** [comment]
@dprital please work with @prsunny  to get this PR in master. we have too many PRs missing in master from this repo.

**Comment by prsunny** [comment]
@dprital, merged the revert PR.. could you please rebase?

**Comment by dprital** [comment]
> @dprital, merged the revert PR.. could you please rebase?

Done

**Pull request closed without merging**
