### PR TITLE
[Nokia-7220 IXR] Add support for NOKIA 7220 IXR-H4

### PR DESCRIPTION
**Pull request by fzhou-nokia**
#### Why I did it
Add support for NOKIA 7220 IXR-H4

> NOKIA 7220-IXR-H4:
> Platform: x86_64-nokia_ixr7220_h4-r0
> HwSKU: Nokia-IXR7220-H4
> ASIC: Broadcom
> Port Config: 64x400G + 2x10G

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

1. Added module under ../device/nokia directory.
2. Modified the platform/broadcom/one-image.mk and platform/broadcom/ platform-modules-nokia.mk 
3. Update PMON submodule link

#### How to verify it

1.	Make sure the sonic-buildimage is successful 
2.	Run this image on x86_64-nokia_ixr7220_h4-r0 and verify all dockers are up and test basic commands like:
                  o	show version
                  o	show platform summary
                  o	show platform syseeprom
                  o	show platform fan
                  o	show platform psustatus
                  o	show platform firmware status
                  o	show platform temperature
                  o	sudo show system-health detail
                  o	show interface status
3.	Run OC test with T1 topology and have 100% pass on platform.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by fzhou-nokia** [comment]
@jon-nokia @mlok-nokia @Pavan-Nokia, please help to review, Thanks!

**Review by jon-nokia — APPROVED** [review]

**Comment by Pavan-Nokia** [comment]
@prgeor Could you please help review and merge.
Thank you

**Comment by Pavan-Nokia** [comment]
@yxieca @bingwang-ms @Blueve Please help Review and merge this PR

**Comment by bingwang-ms** [comment]
@fzhou-nokia , @Pavan-Nokia Please file a PR to 202405 to address conflict.

**Pull request merged**
