### PR TITLE
Update cisco-8000.ini to 202405.0.3 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: anamehra anamehra@cisco.com

Cisco platform 202405.0.3 release

#### Why I did it
Cisco platform 202405.0.3 release

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405
- [ ] 
#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by anamehra** [comment]
@abdosi @rlhui , For your viz! Thanks

**Comment by yejianquan** [comment]
Hi @anamehra , could you share the release notes?

https://github.com/Cisco-8000-sonic/platform-cisco-8000/releases/tag/202405.0.3 is showing 404,
I can visit it 10 mins ago

**Comment by anamehra** [comment]
@yejianquan , please check again and let me know if you still see the issue.

**Comment by yejianquan** [comment]
> @yejianquan , please check again and let me know if you still see the issue.

@anamehra Can see it now, one qq, with 0.3 code drop, we don't need to disable BFD during the nightly running, right?

**Review by yejianquan — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
https://github.com/Cisco-8000-sonic/platform-cisco-8000/releases/tag/202405.0.3

**Pull request merged**
