### PR TITLE
add support for save-on-set to gnmi

### PR DESCRIPTION
**Pull request by rlucus**
Design:
https://github.com/sonic-net/SONiC/pull/1297

Paired PR:
https://github.com/sonic-net/sonic-gnmi/pull/108

#### Why I did it
This enables the ability to turn on save-on-set for sonic-gnmi with a configDB entry. 

#### How I did it
Adds to the telemetry binary command line flags if the db value is present.

### CODE REVIEW

**Comment by rlucus** [comment]
I'm pretty sure this test won't pass until https://github.com/sonic-net/sonic-gnmi/pull/108/ is merged.

**Review by baxia-lan — APPROVED** [review]

**Comment by baxia-lan** [comment]
Hi @lguohan, ms_conflict check is failing, is this check for ms internal repo? Could you please help to resolve this?

cc. @StormLiangMS,@liushilongbuaa as mentioned in the conflict msg.

**Pull request merged**
