### PR TITLE
[Broadcom] Upgrade xgs SAI version to 10.1.42.0

### PR DESCRIPTION
**Pull request by Gfrom2016**
#### Why I did it
Upgrade xgs SAI version to 10.1.42.0 with the following fixes.
- 10.1.39.0: [CSP CS00012349283] back-porting SONIC-88703 to SAI10.1
- 10.1.40.0: [CSP CS00012352844] port SONIC-92490 to rel_ocp_sai_10_1
- 10.1.41.0: [CS00012358054] Port SONIC-93029 to 10.1GA. Description: [TH2/TH] Warm reboot from SAI 4.3.5 to SAI 8.4 SONiC image fails
- 10.1.42.0: [CS00012361544] Backport SONIC-93974 to 10.1. Description: MSFT Prod Issue - TD2 device is sending massive PFC

##### Work item tracking
- Microsoft ADO **(number only)**: 29305413

#### How I did it
Update xgs SAI version to 10.1.42.0 in sai.mk file.

#### How to verify it
Run SAI release validation pipeline: https://dev.azure.com/mssonic/internal/_build/results?buildId=632622&view=results

#### Which release branch to backport (provide reason below if selected)

- [x] 202311
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by kperumalbfn — APPROVED** [review]

**Comment by Gfrom2016** [comment]
Cherry-pick to 202311 #20123 has been merged, add Include label

**Pull request merged**
