### PR TITLE
[TestbedV2]Migrate t0 and t1-lag to TestbedV2

### PR DESCRIPTION
**Pull request by yejianquan**
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.

#### Why I did it
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
#### How I did it
Migrate the t0 and t1-lag test jobs in buildimage repo to TestbedV2.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by yejianquan** [comment]
> @qiluo-msft Create #12454 for the conflict that cherry-pick to 202012, can you help to review? Thanks!

TestbedV2 doesn't support to designate the branch of sonic-mgmt repo currently, will create pr for different branch later.

**Pull request merged**
