### PR TITLE
[docker-sonic-mgmt] Cleanup and upgrade some packages

### PR DESCRIPTION
**Pull request by wangxin**
#### Why I did it
The Dockerfile of docker-sonic-mgmt became a little bit messy over time. Some packages are also a little bit too old. It would be better to do some cleanup and upgrade some important packages.

#### How I did it
* Updated the dockerfile template for building docker-sonic-mgmt.

#### How to verify it
* Locally built the docker-sonic-mgmt image and used it to run some test scripts.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog

Changes:
* The `build-essential` package contains `gcc` and `make`. It's unnecessary to install them again.
* The `python-is-python2` package is included in the `python` package for Ubuntu 20.04. It's unnecessary to install it again.
* Sort the apt and pip packages by alphabetic order.
* Cleanup `get-pip.py` after installation.
* Cleanup the python-scapy deb package after installation.
* Ensure that the python `pip`, `setuptools` and `wheel` packages are up to date.
* Install pytest-ansible from pip instead of from source code.
* While installing docker-ce-cli, it's unnecessary to install `curl` and `software-properties-common` again.
* Merged some `pip install` steps into one step.
* Upgrade ansible from 2.8.12 to 2.9.27 for env-python3.
* Upgrade pytest to 7.1.3 for env-python3.
* Add `ncclient` package to evn-python3.

### CODE REVIEW

**Review by wsycqyz — APPROVED** [review]

**Comment by aaronpayment** [comment]
Would you be able to verify that Kusto upload scripts are compatible with the new pytest versions.

**Pull request merged**
