### PR TITLE
[Mellanox] updating sensors.conf and psu_sensors.json accordingly

### PR DESCRIPTION
**Pull request by yuazhe**
#### Why I did it
add psu model MTEF-AC-I data to psu_sensors.json
add place holder for model MTEF-AC-G-DELTA
fix 4700/4700a1 inverted psu designation

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
check the `sensors` command output on system with the psu model  MTEF-AC-I

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311

#### Tested branch (Please provide the tested image version)

- [x] 202405
- [ ]

### CODE REVIEW

**Review by liat-grozovik — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@keboliu please review. is it really needed for 202311?

**Comment by bingwang-ms** [comment]
@prgeor Can you help review?

**Review by prgeor — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@yuazhe Do we need to update sonic-mgmt test as well?

**Comment by yuazhe** [comment]
> @yuazhe Do we need to update sonic-mgmt test as well?

@bingwang-ms Yes, as the 4700 psu number designate has been changed, mgmt testing need to make correspond change.

**Pull request merged**
