### PR TITLE
[Mellanox] Updating SDK/FW to 4.6.4082/2012.4082

### PR DESCRIPTION
**Pull request by keboliu**
#### Why I did it

Updating SDK/FW to 4.6.4082/2012.4082

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

updating Makefiles

#### How to verify it

Running sonic-mgmt tests

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@bingwang-ms can you please handle ms-conflic to unblock the PR getting in?

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@Boaz ***@***.***> Can you please share the release for this PR? Thanks!




BRs

Bing



________________________________

**Comment by bingwang-ms** [comment]
@keboliu Please share a release note for this PR. Thanks

**Comment by keboliu** [comment]
> @keboliu Please share a release note for this PR. Thanks

Hi Bing, the new SDK/FW bundle including bug fixes related to some 202311 key features. Have you already got the release notes from Boaz?

**Comment by liat-grozovik** [comment]
- Why I did it
Updating SDK/FW to 4.6.4082/2012.4082

- How I did it
updating Makefiles

- How to verify it
Running sonic-mgmt tests

**Comment by liat-grozovik** [comment]
> @keboliu Please share a release note for this PR. Thanks

Release note for Nvidia ASIC drivers are shared offline.

**Comment by liat-grozovik** [comment]
@keboliu please provide PR against 202405 as of conflicts.

**Comment by bingwang-ms** [comment]
Hi @***@***.***>

Can you please share the release notes for this change? I'm sorry I didn't find it from the link you shared earlier.
I need to double confirm if the FW Assert Causes Health Event issue (After running ISSU, a mismatch in lock/unlock resources causes a firmware assert.) has been fixed in 202311 branch.
Thanks!




BRs

Bing



________________________________

**Comment by bingwang-ms** [comment]
@keboliu Please raise a PR to 202405 to address the conflict.

**Pull request merged**
