### PR TITLE
[Accton] Remove unused swsssdk import from accton device code

### PR DESCRIPTION
**Pull request by liuh-80**
#### Why I did it
Update scripts in sonic-buildimage from py-swsssdk to swsscommon

#### How I did it
Remove unused swsssdk import from accton device code

#### How to verify it
Pass all E2E test case

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog
Remove unused swsssdk import from accton device code

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@jostar-yang Could you help review?

**Comment by liuh-80** [comment]
@jostar-yang, could you help review and give your comments?

**Review by jostar-yang — APPROVED** [review]
It is fine to me.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
