### PR TITLE
Misc sensor updates for DCS-7060DX5-64S

### PR DESCRIPTION
**Pull request by bofish-arista**
#### Why I did it
Follow-up to "Misc platform improvements for DCS-7060DX5-64S" filed originally as PR #13875.

While generating a 202305 backport of the aforementioned PR, some fixes were identified and implemented to the sensors.conf file on 202305.  These same changes are being upstreamed as part of this PR to master and 202311 to bring the branches into alignment.

The 202305 backport is tracked under PR #18701.

#### How I did it

Sensor modifications corresponding to the platform implementation.

#### How to verify it

Fixes have been validated in our in-house testing and running sonic-mgmt testing on DCS-7060DX5-64S. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311

#### Tested branch (Please provide the tested image version)

Tested in-house on builds based on current master and 202311.

#### Description for the changelog

Misc sensor updates for DCS-7060DX5-64S

#### Link to config_db schema for YANG module changes
 
n/a

### CODE REVIEW

**Comment by bofish-arista** [comment]
Please tag this for cherry-picking to 202311.

**Comment by StormLiangMS** [comment]
hi @yxieca this is for 202311 cherry pick, needed by TH4 users.

**Pull request merged**
