### PR TITLE
The build project of s3ip framework

### PR DESCRIPTION
**Pull request by tianshangfei**
Signed-off-by: tianshangfei <tian_shangfei@163.com>

#### Why I did it
The build project of s3ip framework

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by adyeung** [comment]
@FuzailBrcm pls help review

**Comment by tianshangfei** [comment]
@FuzailBrcm pls help review

**Comment by tianshangfei** [comment]
> * Are you building these packages as part of SONiC binary ?
> * How does these package integrate with the full build? Is there any config option to enable S3IP .deb packages to be part of SONiC binary ?

This deb package is only used to generate a demo of how to install and use the s3ip framework in the development environment. Because there is no adaptation to a specific platform and some kernel modules need to be tailored, deb packages will not be included directly in the SONiC binary.


Platform-specific developers, according to the requirements, cut the kernel module of the S3IP sysfs framework, generate the configuration file of the S3ip sysfs framework, and finally embed (or soft-link) the S3IP sysfs framework into the specific platform code.

**Comment by FuzailBrcm** [comment]
> > * Are you building these packages as part of SONiC binary ?
> > * How does these package integrate with the full build? Is there any config option to enable S3IP .deb packages to be part of SONiC binary ?
> 
> This deb package is only used to generate a demo of how to install and use the s3ip framework in the development environment. Because there is no adaptation to a specific platform and some kernel modules need to be tailored, deb packages will not be included directly in the SONiC binary.
> 
> Platform-specific developers, according to the requirements, cut the kernel module of the S3IP sysfs framework, generate the configuration file of the S3ip sysfs framework, and finally embed (or soft-link) the S3IP sysfs framework into the specific platform code.

Please share the commands to build the .deb packages

**Comment by tianshangfei** [comment]
> > > * Are you building these packages as part of SONiC binary ?
> > > * How does these package integrate with the full build? Is there any config option to enable S3IP .deb packages to be part of SONiC binary ?
> > 
> > 
> > This deb package is only used to generate a demo of how to install and use the s3ip framework in the development environment. Because there is no adaptation to a specific platform and some kernel modules need to be tailored, deb packages will not be included directly in the SONiC binary.
> > Platform-specific developers, according to the requirements, cut the kernel module of the S3IP sysfs framework, generate the configuration file of the S3ip sysfs framework, and finally embed (or soft-link) the S3IP sysfs framework into the specific platform code.
> 
> Please share the commands to build the S3ip .deb packages

This command is covered in the "Porting guide" section of the S3ip sysfs HLD pr.
Generate a host package, run the following command
sonic-buildimage/platform/s3ip-sysfs/build.sh

**Pull request merged**
