### PR TITLE
[Mellanox]: Clean up syncd Python development packages

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

Resolves: https://github.com/sonic-net/sonic-buildimage/issues/20419

#### Why I did it
* To clean up `syncd` environment

#### Work item tracking
* N/A

#### How I did it
* Removed python development packages from a `Dockerfile` template

#### How to verify it

1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] master 

#### Description for the changelog

* N/A

#### Link to config_db schema for YANG module changes

* N/A

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@nazariig can you please check if we can cherry-pick for 202405

**Comment by bingwang-ms** [comment]
@nazariig Can you raise a PR to 202405 for the cherry-pick? The automation is not working for this PR.

**Pull request merged**
