### PR TITLE
[Edgecore][sonic-platform-modules-accton]Support kernel 6.1 and bookworm

### PR DESCRIPTION
**Pull request by jostar-yang**
#### Why I did it
The sonic-platform-modules-accton package builds were failing to build against the 6.1 kernel in bookworm branch.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Enable rule.mk to let build sonic-platform-modules-accton
Modify accton driver that use "i2c_driver->remove callback function" to use "void" instead of "init".
Because kernel 6.1 has change to be below.

struct i2c_driver {
	unsigned int class;

	/* Standard driver model interfaces */
	int (*probe)(struct i2c_client *client);
	void (*remove)(struct i2c_client *client);

Old kernel define as below,
 .....
init (*remove)(struct i2c_client *client);
#### How to verify it
Build deb.
BLDENV=bookworm make -f Makefile.work $@
Check deb can build successfully

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by jostar-yang** [comment]
This PR is for fix issue,
https://github.com/sonic-net/sonic-buildimage/issues/16736

**Comment by saiarcot895** [comment]
Thank you for updating the Accton platform module for Bookworm!

Since it looks like there's a dependency on PDDF, I'll get #16954 merged in first and then have the PR checkers be rerun, and verify that the Broadcom build succeeds.

**Comment by saiarcot895** [comment]
@jostar-yang Could you resolve the conflicts? I think cherry-picking the pddf commit introduced the conflicts.

**Comment by jostar-yang** [comment]
> @jostar-yang Could you resolve the conflicts? I think cherry-picking the pddf commit introduced the conflicts.

OK. Done to fix conflicts.

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
