### PR TITLE
[202305][mellanox][ppi]: Enable global port late create for all Mellanox HWSKUs

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**HLD:** https://github.com/sonic-net/SONiC/pull/1084

#### Why I did it
* To improve FAST reboot dataplane downtime

##### Work item tracking
* N/A

#### How I did it
* Updated SAI xml config file

#### How to verify it

* Run sonic-mgmt tests of fastboot

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] 202305 

#### Description for the changelog

* N/A

#### Link to config_db schema for YANG module changes

* N/A

#### Details if related
* Backport from `master`: https://github.com/sonic-net/sonic-buildimage/pull/16945

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by StormLiangMS** [comment]
@bingwang-ms @vaibhavhd could you help to review?

**Comment by dgsudharsan** [comment]
@bingwang-ms @vaibhavhd Can you please help to close the review?

**Comment by nazariig** [comment]
@bingwang-ms @vaibhavhd just a kind reminder

**Comment by bingwang-ms** [comment]
Hi @nazariig, a few comments
1. Do we have the data for how much dataplane down time is decreased with this enhancement?
2. Does this change impact warm-boot?
3. How do you ensure this change doesn't cause regression since the profile for all HWSKU is changed?
4. Please double check no other unexpected change in this PR. The alignment adjust makes it difficult to review.

**Comment by StormLiangMS** [comment]
Hi @saiarcot895 since Vaibhav is on leave, could you help to review?

**Review by StormLiangMS — APPROVED** [review]

**Pull request merged**
