### PR TITLE
[sonic_platform] fix thermal.py for e1031

### PR DESCRIPTION
**Pull request by Xichen96**
Postpone get_temperature so call to Thermal() will not fail early in bootup.

#### Why I did it
When determine-reboot-cause is run early, there is very chance it will fail on call to Chassis(), which calls Thermal(), because it checks hwmon that was not yet initialized. However checking hwmon to get temperature can be postponed to later.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Postpone get_temperature to later

#### How to verify it
Make the change on 202305 and bootup many times to check if there are failures.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)
202305.24

- [ ] 
- [ ]

### CODE REVIEW

**Comment by prgeor** [comment]
@Xichen96 Why is this a new issue in 202305 but not seen in previous release? Also, please attach the process crash backtrace or the failure seen in bootup

**Comment by prgeor** [comment]
@Xichen96 The platform driver has not completed initialization before determine-reboot-cause service could run. To avoid this add the following dependency in https://github.com/sonic-net/sonic-buildimage/blob/master/platform/broadcom/sonic-platform-modules-cel/haliburton/systemd/platform-modules-haliburton.service#L5

image

**Comment by lizhijianrd** [comment]
Close this PR. Use #18526 instead.

**Pull request closed without merging**
