### PR TITLE
[dhcp_relay] Upgrade dhcp_relay container to bookworm

### PR DESCRIPTION
**Pull request by yaqiangz**
#### Why I did it
Upgrade dhcp_relay container to bookworm

##### Work item tracking
- Microsoft ADO **(number only)**: 26699855

#### How I did it
1. Upgrade dhcp_relay container to bookworm
2. Because isc-dhcp-relay_4.4.1 is not supported in bookworm due to dependency lib **libbind-export-dev** missing in bookworm:
2.1 Update isc-dhcp-relay from 4.4.1-2.3+deb11u2 to 4.4.3-P1-4
2.2 Make the patch applicable to the new version of the isc-dhcp-relay. Most of patch conflicts are generated by line number incorrect. And issue fixed by patch13 was fixed in isc-dhcp-relay-4.4.3, hence remove this patch.
3.  Install libjsoncpp-dev in slave container to support dhcp6relay build.

#### How to verify it
Install image and run dhcp_relay related tests in MLNX-2700-T0 and Arista-720DT-M0 and 7260-DUALTOR. All passed.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by kellyyeh — APPROVED** [review]

**Comment by yaqiangz** [comment]
@yxieca Could you please help to merge this PR?

**Pull request merged**
