### PR TITLE
Update sonic-sairedis submodule

### PR DESCRIPTION
**Pull request by saiarcot895**
#### Why I did it

This submodule update needs to be manually done due to build changes done in the sairedis submodule. Specifically, Debian build profiles are now being used instead of dpkg build targets, and dbgsym packages are being used instead of dbg packages. Because of this, there needs to be changes on the sonic-buildimage side for this.

This submodule update brings in the following changes:

```
ce8f642 [vs] Use boost join to concatenate switch types in config (#1266)
d6055a2 [vslib]: Temporaily map DPU switch type to NVDA_MBF2H536C (#1259)
e1cdb4d [CodeQL]: Use dependencies with relevant versions in azp template. (#1262)
c08f9a2 [CI]: Fix collect log error in azp template. (#1260)
eed856c [CodeQL]: Fix syncd compilation in azp template. (#1261)
a3f1f1a Reland 'Make changes to building and packaging sairedis (#1116)' (#1194)
```

##### Work item tracking
- Microsoft ADO **(number only)**: 24405994

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by yxieca** [comment]
@saiarcot895 can you list the commits that are included by sairedis submodule advance.

Please check the build failure.

**Comment by saiarcot895** [comment]
Description has been updated with the list of commits.

The build failure appears to be a test failure in sonic_utilities; I suspect it's a transient failure.

**Review by yxieca — APPROVED** [review]

**Comment by liushilongbuaa** [comment]
@saiarcot895 , https://dev.azure.com/mssonic/build/_build/results?buildId=326876&view=logs&j=993d6e22-aeec-5c03-fa19-35ecba587dd9&t=7be0d2ec-661f-5569-462c-2d9b7ca4ca5d
It seems this PR breaks build.

**Comment by liushilongbuaa** [comment]
It breaks amd64's official build.
ex: broadcom/barefoot/mellanox/...

**Comment by saiarcot895** [comment]
I have a fix in sonic-net/sonic-sairedis#1268, but it's blocked by sonic-net/sonic-sairedis#1269

**Comment by liushilongbuaa** [comment]
Maybe the fix also need PR checker. Maybe revert 15720 first. Then let me enable PR checker for target/docker-syncd-brcm-rpc.gz.
Then you can create PR to update HEAD for sairedis?

**Comment by saiarcot895** [comment]
Ok, that works

**Comment by liushilongbuaa** [comment]
@saiarcot895 , rpc PR checker added. Please Update sairedis again.

**Pull request merged**
