### PR TITLE
[submodule] Advance sonic-py-swsssdk pointer

### PR DESCRIPTION
**Pull request by dprital**
Signed-off-by: dprital <drorp@nvidia.com>

#### Why I did it

Update sonic-py-swsssdk submodule pointer to include the following:
* 7f008a1 Fix UT test_BlockUseSwsssdk() ([#128](https://github.com/sonic-net/sonic-py-swsssdk/pull/128))
* e30a1e1 Throw exception when not use swsssdk in UT. ([#126](https://github.com/sonic-net/sonic-py-swsssdk/pull/126))

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@liuh-80 Could you help check the build failure? Related to swsssdk deprecation.

**Comment by liuh-80** [comment]
The change in swsssdk been tested with this PR: https://github.com/sonic-net/sonic-buildimage/pull/12036/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584

Seems sonic-buildimage update to python3 after that, I will create new PR to fix swsssdk UT issue.

**Comment by liuh-80** [comment]
@dprital , the UT failed with python2 issue fixed with this PR: https://github.com/sonic-net/sonic-py-swsssdk/pull/128

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
