### PR TITLE
[Nokia-7220 IXR]Update NOKIA 7220 H4-32D

### PR DESCRIPTION
**Pull request by fzhou-nokia**
#### Why I did it
Update for NOKIA 7220 H4-32D and NOKIA 7220 H4 to achieve 100% pass in OC for T0/T1 topology
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added files under ../device/nokia/x86_64-nokia_ixr7220_h4_32d-r0 directory.
Added files under ../device/nokia/x86_64-nokia_ixr7220_h4-r0 directory.
#### How to verify it

1. Make sure the sonic-buildimage is successful
2. Run this image on x86_64-nokia_ixr7220_h4_32d-r0 and x86_64-nokia_ixr7220_h4-r0 and verify all dockers are up and test basic commands like:

- show version
- show platform summary
- show platform syseeprom
- show platform fan
- show platform psustatus
- show platform firmware status
- show platform temperature
- sudo show system-health detail
- show interface status

3. Run OC test, for T0/T1 topology and have 100% pass on platform.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Blueve — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@fzhou-nokia Can you raise a PR to 202405 to address the conflict?

**Comment by Pavan-Nokia** [comment]
> @fzhou-nokia Can you raise a PR to 202405 to address the conflict?

Hi @bingwang-ms
below is the pr for 202405 backport. please help merge
https://github.com/sonic-net/sonic-buildimage/pull/20557

**Pull request merged**
