### PR TITLE
[202205][submodule] advance sonic-utilities pointer

### PR DESCRIPTION
**Pull request by dgsudharsan**
Update sonic-utilities submodule pointer to include the following:
* ab21b58 [202205] check for vxlan mapping before removing vlan (#2388) ([#2446](https://github.com/Azure/sonic-utilities/pull/2446))
* e111ad4 [202205][Auto-Techsupport] Fix the coredump_gen_handler Exception when the History table is empty (#2265) ([#2433](https://github.com/Azure/sonic-utilities/pull/2433))
* 6925947 [watermarkstat][202205] Add new warning message for the 'q_shared_multi' counters ([#2406](https://github.com/Azure/sonic-utilities/pull/2406))

Signed-off-by: dgsudharsan <sudharsand@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@dgsudharsan  can you check failures and see if related to the changes in this PR?

**Comment by dgsudharsan** [comment]
@liat-grozovik  The failures are not related to the changes and are generic pipeline failures.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
