### PR TITLE
Install barefoot

### PR DESCRIPTION
**Pull request by donNewtonIntel**
#### Why I did it
This makes the genl-packet kernel module available in barefoot builds
#### How I did it
Added to install list in platform/barefoot/one-(image/aboot).mk
#### How to verify it
Build barefoot image and ensure kernel module is built and loaded into the install image
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by ravi861** [comment]
@akokhan @kperumalbfn Please help review.

**Comment by lguohan** [comment]
why this specific to intel platform?

**Comment by donNewtonIntel** [comment]
> 

It's not really, I talked about it with Kishan from Google and he was thinking it might be better for platform vendors to decide to include or not.  Easy enough to add to all platforms if you think that is better.

**Comment by lguohan** [comment]
pr should be opened from personal repo. close this pr.

**Pull request closed without merging**
