### PR TITLE
Update threshold of PG profile for Arista7060X6-PE 256x200G

### PR DESCRIPTION
**Pull request by Pterosaur**
#### Why I did it
This PR updates the threshold of PG profile for the Arista 7060X6-PE device with 256x200G breakout. This configuration refers : Case CS00012355797 comments 18-July-2024 14:27:06

##### Work item tracking
- Microsoft ADO **(number only)**: 28707303

#### How I did it
1. Change the threshold from -2 to 0
2. Update bcm file from ALPHA_1_4 to ALPHA_1

#### How to verify it
Confirmed by broadcom

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by r12f** [comment]
Hi @Pterosaur , it will be better to also have the bcm file updated too. It looks missing.

**Comment by Pterosaur** [comment]
> Hi @Pterosaur , it will be better to also have the bcm file updated too. It looks missing.

@r12f Done, please check it again.

**Review by lguohan — APPROVED** [review]

**Review by r12f — APPROVED** [review]
lgtm! yes, there are 4 registers changed from what I see before, and they are all in the change.

**Comment by bingwang-ms** [comment]
@Pterosaur Please file another PR to 202405 branch to address cherry-pick conflict.

**Pull request merged**
