### PR TITLE
[202012] [Celestica/Seastone2] Install sonic_platform

### PR DESCRIPTION
**Pull request by bluecmd**
#### Why I did it

This is part of fixing https://github.com/Azure/sonic-buildimage/issues/8212.
This changes fixes installation of `sonic_platform` to be installed for both python2 and python3.
Right now neither is installed.

#### How I did it

Looked at the error messages when booting a clean Seastone2 as well as the packaging files.

#### How to verify it

Verify that `sonic_platform` is installed.

```
(vrf:mgmt)bluecmd@ixp-kg-sw1:~$ python2 -c 'import sonic_platform'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sonic_platform
(vrf:mgmt)bluecmd@ixp-kg-sw1:~$ python3 -c 'import sonic_platform'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sonic_platform'
```

After:

```
(vrf:mgmt)bluecmd@ixp-kg-sw1:~$ python2 -c 'import sonic_platform'
(vrf:mgmt)bluecmd@ixp-kg-sw1:~$ python3 -c 'import sonic_platform'
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106

#### Description for the changelog

cel/seastone2: install `sonic_platform`

#### A picture of a cute animal (not mandatory but encouraged)

image

### CODE REVIEW

**Comment by bluecmd** [comment]
@sujinmkang can you maybe review this?

**Comment by sujinmkang** [comment]
@bluecmd Can you please rebase this PR again?

**Comment by bluecmd** [comment]
@sujinmkang Rebase was done :-)

**Comment by bluecmd** [comment]
@lguohan OK to merge?

**Pull request closed without merging**
