### PR TITLE
Update swsssdk submodule on 202111 branch

### PR DESCRIPTION
**Pull request by liuh-80**
This PR is to cherry-pick #10996 to `202111` branch.

[Submodule] Update src/sonic-py-swsssdk #10996

Signed-off-by: qiluo-msft <qiluo@microsoft.com>

### CODE REVIEW

**Comment by liuh-80** [comment]
This PR depends on another PR: https://github.com/Azure/sonic-buildimage/pull/11262
So, need wait #11262 merge first to pass validation.

**Comment by liuh-80** [comment]
This PR can't merge, if this PR merged, then 202111 branch may build break on following repos:  sonic-sairedis, sonic-swss, sconic-swss-common

Because these repos are build docker image by themself and run vstest on the docker image, their docker image build config does not install c++ version config db cli, however there are some UT depends on sonic-db-cli. so we need wait they confirm the build break issue not caused by this PR, and fix the docker issue on their 202111 branch.

**Review by qiluo-msft — APPROVED** [review]

**Pull request closed without merging**
