### PR TITLE
Update init_cfg.json.j2 to handle global scope for lldp feature

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

Enable control of lldp `has_global_scope` field based on Device runtime metada.

Why I did:
More Details: https://github.com/sonic-net/sonic-host-services/pull/120
Dependent on above PR merged first and submodule update of `sonic-host-services`

### CODE REVIEW

**Comment by abdosi** [comment]
@mlok-nokia @anamehra for viz.

**Comment by rlhui** [comment]
@mlok-nokia  please help review

**Review by judyjoseph — DISMISSED** [review]
LGTM

**Comment by lguohan** [comment]
build failure @abdosi , please check.

**Comment by abdosi** [comment]
waiting on this merge: https://github.com/sonic-net/sonic-buildimage/pull/19039/files

**Review by judyjoseph — APPROVED** [review]

**Review by SuvarnaMeenakshi — APPROVED** [review]

**Pull request merged**
