### PR TITLE
[202012][sonic-platform-daemons] submodule update

### PR DESCRIPTION
**Pull request by vdahiya12**
Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>
The following commits are added in sonic-platform-daemons
git log --oneline 99d2528..202012
aacb772 (HEAD -> 202012, origin/202012) [ycabled] fix naming error for error condition for CLI handling (#302)
f2201ab [ycabled] add some exception catching logic to some vendor specific API's (#301)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by qiluo-msft** [comment]
The build failure may be related https://github.com/sonic-net/sonic-buildimage/pull/12272

**Pull request merged**
