### PR TITLE
[Nokia][sonic-platform] Update Nokia sonic-platform submodule - SFP s…

### PR DESCRIPTION
**Pull request by snider-nokia**
This fixes https://github.com/Nokia-ION/ndk/issues/22
**Note** that this PR **must** be coupled with NDK version >= 22.9.13

#### Why I did it

To provide proper support for CMIS compliant transceiver module CDB operations (including FW related operations).

#### How I did it

Enhanced the transport subsystem so as to provide for up to 2k bytes of data to be passed to/from modules (as contrasted with the prior max of 128 bytes).  

#### How to verify it

Ensure that new FW (firmware) can be programmed to CMIS compliant module(s) using the 'sfputil firmware ...' commands.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

  Tested with branch 202205

#### Description for the changelog

Properly support CDB operations for CMIS transceiver modules
**Note** that this PR **must** be coupled with NDK version >= 22.9.13

### CODE REVIEW

**Comment by snider-nokia** [comment]
@vmittal-msft and/or @prgeor, can you please review?

Merging should be discussed in conjunction with release of NDK version >= 22.9.13 (as the two components **must** be coupled).

**Comment by gechiang** [comment]
@judyjoseph can you help review this?  Will also tag you to review the new ndk 22.9.13 PR...

**Comment by prgeor** [comment]
@snider-nokia could you please share the logs in the PR description for the firmware download steps?

**Review by prgeor — APPROVED** [review]

**Review by rlhui — APPROVED** [review]

**Comment by gechiang** [comment]
@snider-nokia , Before this is picked into 202205 MSFT repo, the required NDK needs to be picked to 202205 MSFT repo first.  Can you please create the needed PR for https://github.com/Azure/sonic-buildimage-msft/pull/112 for 202205 MSFT branch?
Once that is done, I will try to cherry-pick this to 202205 MSFT repo.
Thanks!

**Comment by mlok-nokia** [comment]
> @snider-nokia , Before this is picked into 202205 MSFT repo, the required NDK needs to be picked to 202205 MSFT repo first. Can you please create the needed PR for [Azure/sonic-buildimage-msft#112](https://github.com/Azure/sonic-buildimage-msft/pull/112) for 202205 MSFT branch? Once that is done, I will try to cherry-pick this to 202205 MSFT repo. Thanks!

Related NDK PR has been created: https://github.com/Azure/sonic-buildimage-msft/pull/118

**Comment by gechiang** [comment]
@lguohan , @yxieca , @StormLiangMS:
MSFT ADO: 25264667
Please help approve for the corresponding release.
Thanks!

**Comment by gechiang** [comment]
@snider-nokia , do you intent to backport this to 202211 branch?  If not, I will withdraw request for 202211 branch.
Please help clarify this or resolve the cherry-pick conflict for 202211 branch by raising a separate PR for 202211 for this change.
Thanks!

**Pull request merged**
