### PR TITLE
Import requests libraries for Ragile platform

### PR DESCRIPTION
**Pull request by pettershao-ragilenetworks**
#### Why I did it
The performance of request is better than curl.
#### How I did it
import request python library for Ragile platform.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by pettershao-ragilenetworks** [comment]
@lguohan Can you please review this pr?

**Comment by pettershao-ragilenetworks** [comment]
@xumia , @Gfrom2016 Can you please review this pr?

**Comment by lguohan** [comment]
can you describe how much better the performance?

**Comment by pettershao-ragilenetworks** [comment]
I did not record specific data. But this is the reason, if there is no request, you need to use curl to get data from bmc, and each query needs to start a curl process. pmon is a circular query, which will pull up multiple processes in a loop, which consumes a lot. Using request does not need to pull up the process. @lguohan

**Comment by prgeor** [comment]
@pettershao-ragilenetworks where is this request used. can you point me that?

**Comment by pettershao-ragilenetworks** [comment]
Used for pmon to obtain information from bmc through REST API, such as psu, fan, led, etc.
@prgeor

**Comment by pettershao-ragilenetworks** [comment]
use request: 
img_v2_9862d362-c049-47d9-adf7-66794e1696cg
use curl:
img_v2_7232eeb6-4329-494f-9408-9ec5665f706g

In r6010 products, pmon needs to obtain information from bmc with REST API. Such as psu, fan, led and so on. Without request component, can only be obtained through curl. When the process using REST api obtain information, each query needs to start a curl process, which consumes a lot of resources. When use the request component, can reduce resource consumption.

img_v2_6ceacf09-73fd-4588-ba94-429bd4925c1g

Each process uses curl to get data with REST api.

@prgeor

**Pull request merged**
