### PR TITLE
Update cisco-8000 submodule to v0.111

### PR DESCRIPTION
**Pull request by jhli-cisco**
Update cisco-8000 submodule to v0.108 drop to include BFD functionality.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by kevinskwang — APPROVED** [review]

**Review by kevinskwang — CHANGES_REQUESTED** [review]
Build failed, should not merge it before resolved the issue.

**Comment by kevinskwang** [comment]
Could you update this to latest release?

**Comment by jhli-cisco** [comment]
Hi Kevin,

We’ll have a new release v0.111 very soon, shall we wait for it to update?

Thanks,

Jihong

From: Kevin Wang ***@***.***>
Date: Monday, August 22, 2022 at 2:09 AM
To: sonic-net/sonic-buildimage ***@***.***>
Cc: Jihong Li (jhli) ***@***.***>, Author ***@***.***>
Subject: Re: [sonic-net/sonic-buildimage] Update cisco-8000 submodule to v0.108 (PR #11537)

Could you update this to latest release?

**Comment by kevinskwang** [comment]
Could you authorize the EasyCLA?

**Comment by jhli-cisco** [comment]
> Could you authorize the EasyCLA?

I tried to authorize as corporate contributor, but get "The Corporate CLA option is not enabled for this project. Please contact to your administrator to enable the Corporate CLA option for this project."

**Comment by kevinskwang** [comment]
Could you close thie PR and create a new one?

**Comment by jhli-cisco** [comment]
created https://github.com/sonic-net/sonic-buildimage/pull/11835 per request.

**Pull request closed without merging**
