### PR TITLE
[armhf][Nokia-7215]Add SFP refactor support for Nokia-7215 platform

### PR DESCRIPTION
**Pull request by snider-nokia**
#### Why I did it

Add support for SFP refactor on Nokia-7215 Marvell armhf platform.
    
    Platform: armhf-nokia_ixs7215_52x-r0
    HwSKU: Nokia-7215
    ASIC: marvell
    Port Config: 48x1G + 4x10G (SFP+)

#### How I did it

    Modify sfp.py to support SFP refactor optoe driver and platform.json to facilitate proper OC test completion.

#### How to verify it

    Build armhf target for Nokia-7215 and verify proper Xcvrd and SFP refactor operation.

#### Which release branch to backport (provide reason below if selected)

    - [x] 202205
    - [x] 202211

#### Description for the changelog
     
     [armhf][Nokia-7215]Add SFP refactor support for Nokia-7215 platform

### CODE REVIEW

**Comment by snider-nokia** [comment]
@prgeor, can you please add yourself as reviewer here?

**Comment by prgeor** [comment]
@lguohan please help merge

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@snider-nokia  please open separate PR for 202205 branch.

**Comment by snider-nokia** [comment]
> @snider-nokia please open separate PR for 202205 branch.

Can you just attempt cherry-pick again and provide merge strategy switch **-X=theirs** to take all changes from the specified commit hash?     

So, '**git cherry-pick -X=theirs \<hash\>**'

The changes provided in commit 1117dcbb are the proper ones to apply/favor for the merge strategy.

Thanks.

**Comment by Pavan-Nokia** [comment]
@yxieca @mssonicbld 
New PR for 202205 branch created #14551

**Comment by Pavan-Nokia** [comment]
@yxieca @mssonicbld
New PR for 202211 branch created https://github.com/sonic-net/sonic-buildimage/pull/14789

**Pull request merged**
