### PR TITLE
[Ufispace][PDDF] Add support for S9301-32D platform

### PR DESCRIPTION
**Pull request by linyutsung**
#### Why I did it
Add PDDF support on Ufispace S9301-32D with Broadcom ASIC

#### How I did it
Add PDDF configuration files, scripts and python files

#### How to verify it

Run pddf commands and show command
<pre>
root@sonic:~# pddf_psuutil status
PSU    Status
-----  --------
PSU1   OK
PSU2   NOT OK
root@sonic:~# pddf_thermalutil gettemp
Temp Sensor       Value
----------------  -------
Temp_CPU_PECI     temp1  +41.0 C (high = +95.0 C, crit = +100.0 C)
Temp_CPU_ENV      temp1  +38.0 C (high = +85.0 C, crit = +90.0 C)
Temp_CPU_ENV2     temp1  +31.0 C (high = +70.0 C, crit = +80.0 C)
Temp_MAC_ENV      temp1  +35.0 C (high = +85.0 C, crit = +90.0 C)
Temp_MAC_DIE      temp1  +41.0 C (high = +100.0 C, crit = +105.0 C)
Temp_CAGE         temp1  +28.0 C (high = +85.0 C, crit = +90.0 C)
Temp_PSU_CONNTOR  temp1  +30.0 C (high = +65.0 C, crit = +70.0 C)
root@sonic:~# pddf_ledutil getstatusled SYS_LED
green
root@sonic:~# show interfaces transceiver presence
Port         Presence
-----------  -----------
Ethernet0    Not present
Ethernet8    Not present
Ethernet16   Present
Ethernet24   Present
Ethernet32   Not present
Ethernet40   Not present
Ethernet48   Not present
Ethernet56   Not present
Ethernet64   Present
Ethernet72   Present
Ethernet80   Not present
Ethernet88   Not present
Ethernet96   Not present
Ethernet104  Not present
Ethernet112  Present
Ethernet120  Present
Ethernet128  Not present
Ethernet136  Not present
Ethernet144  Not present
Ethernet152  Not present
Ethernet160  Not present
Ethernet168  Not present
Ethernet176  Not present
Ethernet184  Not present
Ethernet192  Not present
Ethernet200  Not present
Ethernet208  Not present
Ethernet216  Not present
Ethernet224  Not present
Ethernet232  Not present
Ethernet240  Not present
Ethernet248  Not present
Ethernet256  Not present
Ethernet257  Not present
root@sonic:~# show platform fan
  Drawer    LED         FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ----------  -------  -----------  ----------  --------  -----------------
Fantray1  green  Fantray1_1      56%      EXHAUST     Present        OK  20230618 20:52:26
Fantray1  green  Fantray1_2      56%      EXHAUST     Present        OK  20230618 20:52:26
Fantray2  green  Fantray2_1      56%      EXHAUST     Present        OK  20230618 20:52:26
Fantray2  green  Fantray2_2      56%      EXHAUST     Present        OK  20230618 20:52:26
Fantray3  green  Fantray3_1      55%      EXHAUST     Present        OK  20230618 20:52:27
Fantray3  green  Fantray3_2      56%      EXHAUST     Present        OK  20230618 20:52:27
Fantray4  green  Fantray4_1      56%      EXHAUST     Present        OK  20230618 20:52:27
Fantray4  green  Fantray4_2      56%      EXHAUST     Present        OK  20230618 20:52:27
Fantray5  green  Fantray5_1      55%      EXHAUST     Present        OK  20230618 20:52:27
Fantray5  green  Fantray5_2      56%      EXHAUST     Present        OK  20230618 20:52:27
Fantray6  green  Fantray6_1      56%      EXHAUST     Present        OK  20230618 20:52:27
Fantray6  green  Fantray6_2      56%      EXHAUST     Present        OK  20230618 20:52:27
     N/A    N/A   PSU1_FAN1      44%      EXHAUST     Present        OK  20230618 20:52:27
     N/A    N/A   PSU2_FAN1       0%      EXHAUST     Present    Not OK  20230618 20:52:27

</pre>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] master

### CODE REVIEW

**Comment by linyutsung** [comment]
@FuzailBrcm please help review, thanks

**Comment by linyutsung** [comment]
@FuzailBrcm please help review, thanks

**Review by FuzailBrcm — APPROVED** [review]
Look good to me

**Comment by linyutsung** [comment]
@lguohan FuzailBrcm has reviewed and approved, please help merge, thanks

**Comment by linyutsung** [comment]
@yxieca please help merge, thanks.

**Comment by linyutsung** [comment]
@yxiecaFuzailBrcm has reviewed and approved, please help merge, thanks

**Comment by linyutsung** [comment]
@yxieca please help merge, thanks

**Comment by linyutsung** [comment]
@yxieca please help merge, thanks

**Pull request closed without merging**
