### PR TITLE
[ptf] Consider only expected packets for timeout

### PR DESCRIPTION
**Pull request by vkjammala-arista**
#### Why I did it
`dhcp_relay/test_dhcp_relay_stress.py::test_dhcp_relay_stress[offer|ack]` tests are failing on dualtor topologies with signature `Failed: /tmp/dhcp_stress_test_offer.json is missing`, see issue https://github.com/aristanetworks/sonic-qual.msft/issues/325 for more details.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
`count_matched_packets` method is getting stuck in a while loop as long as ptf server port receives any packet (Ex: in dualtor case, we do see continuous ICMP packets on ptf port). Fix is to consider only expected packets w.r.t timeout (similar to `count_matched_packets_all_ports` logic).

#### How to verify it
With this PR changes we should not see dhcp_relay/test_dhcp_relay_stress.py failures on dualtor topologies with symptom `Failed: /tmp/dhcp_stress_test_offer.json is missing`.

#### Which release branch to backport (provide reason below if selected)

- [x] 202405
- [x] 202411

Reason: Issue is seen in 202405 branch.
#### Tested branch (Please provide the tested image version)

- [x] 202405
- [ ]

### CODE REVIEW

**Review by lolyu — APPROVED** [review]

**Review by yaqiangz — APPROVED** [review]
LGTM

**Comment by vkjammala-arista** [comment]
Hi @StormLiangMS, please help merging this PR.

**Comment by yyynini** [comment]
LGTM

**Review by yyynini — APPROVED** [review]

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
