### PR TITLE
Dell S6100 Platform fix

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it
Dell S6100 Platform components needs to be updated.
#### How I did it
Modified platform.json to fix the issue.
#### How to verify it
Run sonic-mgmt component test and check whether it passes.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211
- [x] 202305

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@yxieca @lguohan could you please merge

**Comment by mihirpat1** [comment]
@StormLiangMS @yxieca - Can you please help in cherry-pick this to 202305 and 202205.
ADO - 24867089

**Pull request merged**
