### PR TITLE
Remove DNS configuration from minigraph schema

### PR DESCRIPTION
**Pull request by ganglyu**
#### Why I did it
We should not modify minigraph schema.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Update minigraph.py and remove unit test.

#### How to verify it
Run sonic-config-engine unit test.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by qiluo-msft** [comment]
>     return syslog_servers, dhcp_servers, dhcpv6_servers, ntp_servers, dns_nameservers, tacacs_servers, mgmt_routes, erspan_dst, deployment_id, region, cloudtype, resource_type, downstream_subrole, switch_id, switch_type, max_cores, kube_data, macsec_profile, downstream_redundancy_types, redundancy_type, qos_profile, rack_mgmt_map

Will you remove this also?

---
Refers to: src/sonic-config-engine/minigraph.py:1065 in 0a7993b. [](commit_id = 0a7993b8474d1d894c82181735e2e4381f01fe41, deletion_comment = False)

**Comment by qiluo-msft** [comment]
>     return syslog_servers, dhcp_servers, dhcpv6_servers, ntp_servers, dns_nameservers, tacacs_servers, mgmt_routes, erspan_dst, deployment_id, region, cloudtype, resource_type, downstream_subrole, switch_id, switch_type, max_cores, kube_data, macsec_profile, downstream_redundancy_types, redundancy_type, qos_profile, rack_mgmt_map

Many other occurrences in this file.

---
In reply to: [1624162152](https://github.com/sonic-net/sonic-buildimage/pull/15727#issuecomment-1624162152) [](http://example.com/codeflow?ancestors=1624162152)

---
Refers to: src/sonic-config-engine/minigraph.py:1065 in 0a7993b. [](commit_id = 0a7993b8474d1d894c82181735e2e4381f01fe41, deletion_comment = False)

**Review by qiluo-msft — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@ganglyu could you add ADO in the description?

**Comment by ganglyu** [comment]
> @ganglyu could you add ADO in the description?

updated

**Pull request merged**
