### PR TITLE
Update cisco-8000.ini to 202405.0.11 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: Anand Mehra anamehra@cisco.com

#### Why I did it
Fixed SDK for Cisco 8122 platform

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by anamehra** [comment]
Hi @kevinskwang , for your viz. Thanks

**Comment by kevinskwang** [comment]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
@kevinskwang  @anamehra Do we need it in 202405? Don't see the label for cherry-picking.

**Comment by yejianquan** [comment]
> @kevinskwang @anamehra Do we need it in 202405? Don't see the label for cherry-picking.

This could cause conflict when we cherry-pick https://github.com/sonic-net/sonic-buildimage/pull/21051 to 202405 branch

**Pull request merged**
