### PR TITLE
[Arista] Fix content of platform.json for DCS-7050CX3-32S

### PR DESCRIPTION
**Pull request by andywongarista**
#### Why I did it
Some tests under `platform_tests/api` were failing on the 7050CX3 due to outdated facts in platform.json

#### How I did it
Updated platform.json facts with appropriate values

#### How to verify it
Run tests under `platform_tests/api` to verify no failures

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@andywongarista could you rebase with master once?

**Comment by prgeor** [comment]
@andywongarista could you rebase with master once?

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@yxieca not sure if this is already cherry-picked into 202205 as commented by @andywongarista above

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by liuh-80** [comment]
Cherry pick PR merged: https://github.com/sonic-net/sonic-buildimage/pull/13659

**Pull request merged**
