### PR TITLE
Remove ipmitool compilation

### PR DESCRIPTION
**Pull request by saiarcot895**
#### Why I did it

The latest version of ipmitool in Debian has the enterprise-numbers.txt file. Don't compile this package locally anymore.

This reverts #17878.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by saiarcot895** [comment]
FYI @rajib-dutta1

**Review by prgeor — COMMENTED** [review]
@aravindmani-1 can you review?

**Review by aravindmani-1 — APPROVED** [review]

**Comment by bingwang-ms** [comment]
This PR is required to unblock the build in master and 202405 branch.

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
