### PR TITLE
Update supervisord.conf.j2. This change is to exclude bgpmon for frrc…

### PR DESCRIPTION
**Pull request by prasannam2302**
…fgd.

#### Why I did it
Since bgpmon is part of bgpcfgd, this code change will exclude bgpmon from frrcfgd.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it

Boot up a switch, if frrcfgd is enabled with frr_mgmt_framework_config being "true", then "bgpmon" process should not be
running after this change. bgpmon should be running when bgpcfgd is enable with frr_mgmt_framework_config being "false"
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by venkatmahalingam** [comment]
@gechiang Please review this change.

**Review by venkatmahalingam — APPROVED** [review]

**Review by joyas-joseph — APPROVED** [review]

**Review by puffc — APPROVED** [review]
LGTM

**Comment by gechiang** [comment]
@StormLiangMS can you help review this PR? Thanks!

**Comment by gechiang** [comment]
@prasannam2302  can you address the EasyCLA failure?

**Comment by prasannam2302** [comment]
> @prasannam2302 can you address the EasyCLA failure?

Done

**Pull request merged**
