### PR TITLE
[Micas/Platform]platform support M2-W6920-32QC2X

### PR DESCRIPTION
**Pull request by philo-micas**
#### Why I did it
Add new platform m2-w6920-32qc2x(Tomahawk 3)
ASIC Vendor: Broadcom
Switch ASIC: Tomahawk 3
Port Config: 32×400G + 2×10G

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by philo-micas** [comment]
[report_M2-W6920-32QC2X_0201.zip](https://github.com/sonic-net/sonic-buildimage/files/14159963/report_M2-W6920-32QC2X_0201.zip)
Kernel 6.1.38 adaption
Platform test report from sonic-mgmt.

**Comment by philo-micas** [comment]
> [report_M2-W6920-32QC2X_0201.zip](https://github.com/sonic-net/sonic-buildimage/files/14159963/report_M2-W6920-32QC2X_0201.zip) Kernel 6.1.38 adaption Platform test report from sonic-mgmt.

@lguohan Hi guohan, test report has been submitted, please help to push forward this pr. Thanks.

**Comment by StephenSJCA** [comment]
> > [report_M2-W6920-32QC2X_0201.zip](https://github.com/sonic-net/sonic-buildimage/files/14159963/report_M2-W6920-32QC2X_0201.zip) Kernel 6.1.38 adaption Platform test report from sonic-mgmt.
> 
> @lguohan Hi guohan, test report has been submitted, please help to push forward this pr. Thanks.

@lguohan @prgeor @yxieca **Hi Guohan, Prince, and Ying, please take the time to push forward this PR, it is urgent for us, many thanks!**

**Comment by philo-micas** [comment]
Leave one semgrep error as 'defusedxml' was not installed in sonic.

**Comment by philo-micas** [comment]
Please use new PR link: https://github.com/sonic-net/sonic-buildimage/pull/20626

**Comment by philo-micas** [comment]
Please use new PR link: https://github.com/sonic-net/sonic-buildimage/pull/20626

**Pull request closed without merging**
