### PR TITLE
[Build] Fix the reproducible build variable display error in the slave container

### PR DESCRIPTION
**Pull request by xumia**
#### Why I did it
Enable the reproducible build for PR build for master branch

Fix the reproducible build variable display error in the slave container.
The below config is none, although the config is set and takes effect.
```
"SONIC_VERSION_CONTROL_COMPONENTS": "none"
``` 

#### How I did it
Passing the variable through the slave container command line.
The variable has been passed to the slave container and the other docker container by a config file, it is only used to display the value during the build.

#### How to verify it
See https://dev.azure.com/mssonic/build/_build/results?buildId=247960&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=88f376cf-c35d-5783-0a48-9ad83a873284
```
"SONIC_VERSION_CONTROL_COMPONENTS": "deb,py2,py3,web,git,docker"
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211

### CODE REVIEW

**Comment by xumia** [comment]
> As I understand it fixes #12362

@k-v1 , yes, it will fix the issue. Thanks for opening the issue.

**Review by liushilongbuaa — APPROVED** [review]

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by yxieca** [comment]
@liushilongbuaa do we need this change in 202205 as well? the auto cherry-pick failed.

**Comment by liushilongbuaa** [comment]
> @liushilongbuaa do we need this change in 202205 as well? the auto cherry-pick failed.

It is a logging issue, I will create a PR to fix

**Pull request merged**
