### PR TITLE
Update macsec CAK keys in profile for tests to change to type7 encoded format

### PR DESCRIPTION
**Pull request by judyjoseph**
#### Why I did it
The changes needed in various macsec unit tests and config plugin when we move to accept the type 7 encoded key format for macsec. This goes along with PR : https://github.com/sonic-net/sonic-swss/pull/2892 raised earlier.

##### Work item tracking
- Microsoft ADO **(number only)**: 25046448

#### How I did it
Updated the macsec profiles used in unit test with the type7 encoded CAK keys.

Updated the length check in macsec config plugin to accept not strings of length 66 and 130 bytes depending on whether it is 128 byte cipher suite or 256 byte cipher suite

Additional changes needed to the yang model file. 
1. Increase the CAK key length from 32 bytes and 64 bytes with plain text format --> 66 bytes and 130 bytes with type 7 encoded keys for 128 byte and 256 byte cipher suites.
2. Removing the check to validate the length of CAK and CKN, the key and name need not be same length

#### How to verify it
Validated with CLI commands to make sure macsec profiles are created correctly.
More tests added in PRs : https://github.com/sonic-net/sonic-swss/pull/2892, https://github.com/sonic-net/sonic-mgmt/pull/9812

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Pterosaur — APPROVED** [review]

**Review by Pterosaur — APPROVED** [review]

**Review by Pterosaur — APPROVED** [review]

**Comment by gechiang** [comment]
@arlakshm , can you help review this especially on the yang changes?  Thanks!

**Comment by judyjoseph** [comment]
@arlakshm @qiluo-msft Could you review this change, I have added the dertailed test results in other PRs: https://github.com/sonic-net/sonic-swss/pull/2892, https://github.com/sonic-net/sonic-mgmt/pull/9812 - thanks

**Review by arlakshm — APPROVED** [review]
lgtm

**Review by arlakshm — APPROVED** [review]
lgtm

**Comment by qiluo-msft** [comment]
LGTM.

**Comment by ganglyu** [comment]
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/tests/files/sample_config_db.json#L2321
Would you please check this file?

**Review by ganglyu — APPROVED** [review]

**Comment by gechiang** [comment]
@yxieca , @StormLiangMS , Please help approve cherry pick this for the corresponding branches. Thanks!

**Pull request merged**
