### PR TITLE
[gbsyncd] Graceful shutdown of syncd process in container gbsyncd

### PR DESCRIPTION
**Pull request by jimmyzhai**
#### Why I did it
Fix https://github.com/sonic-net/sonic-buildimage/issues/16608. Need to gracefully shutdown syncd/gbsyncd individually.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Update hook stopplatform1 in gbsyncd.sh.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by lguohan — DISMISSED** [review]

**Comment by gechiang** [comment]
@jimmyzhai , is this fix not needed by 202205? should we backport this for 202205?

**Comment by jimmyzhai** [comment]
> @jimmyzhai , is this fix not needed by 202205? should we backport this for 202205?

Looks 202205 is old and gearbox is not used in production on that.

**Comment by yxieca** [comment]
@jimmyzhai do we still need this change in 202311 or have it been included with your manual cherry-picking PR?

**Comment by jimmyzhai** [comment]
> @jimmyzhai do we still need this change in 202311 or have it been included with your manual cherry-picking PR?

Included in 202311 with manual cherry-picking https://github.com/sonic-net/sonic-buildimage/pull/17563

**Pull request merged**
