### PR TITLE
[centec][arm64] fix tsingma bsp compile error

### PR DESCRIPTION
**Pull request by LuiSzee**
#### Why I did it
fix centec arm64 tsingma bsp compile error caused by linux kernel api change

#### How I did it
fix centec arm64 tsingma bsp compile error caused by linux kernel api change

#### How to verify it
compile centec arm64 image and verify on centec arm64 E530 series device

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [x] 202211

### CODE REVIEW

**Comment by LuiSzee** [comment]
@liushilongbuaa Please help to review this PR, this PR fixs centec tsingma-bsp compile error.

**Comment by liushilongbuaa** [comment]
The change and error message seems not match. @LuiSzee , are you fixing the following error?
```
dh_install: warning: Cannot find (any matches for) "src/ctc_wdt/ctc_wdt.ko" (tried in ., debian/tmp)
dh_install: warning: tsingma-bsp missing files: src/ctc_wdt/ctc_wdt.ko
dh_install: error: missing files, aborting
```

**Review by liushilongbuaa — APPROVED** [review]
I can approve it because change only affect centec-arm64.

**Comment by liushilongbuaa** [comment]
Hi @LuiSzee , if you are sure with the failure, just merge.
Let's wait for the build result.

**Pull request merged**
