### PR TITLE
Update sensor names for msn4600c for the 5.10 kernel

### PR DESCRIPTION
**Pull request by saiarcot895**
Looks like a sensor was removed in the 5.10 kernel for the tps53679
sensor, so the names/indexing has changed.

Related to Azure/sonic-mgmt#4513.

Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

#### Why I did it

With a 4.19 kernel, the sensor information for tps53679 on Mellanox MSN4600C was as follows:

```
tps53679-i2c-15-61
Adapter: i2c-1-mux (chan_id 6)
PMIC-9 PSU 12V Rail (in1):         +11.98 V  (crit min =  +7.50 V, crit max = +17.00 V)
PMIC-9 PSU 12V Rail (in2):         +11.98 V  (crit min =  +7.50 V, crit max = +17.00 V)
PMIC-9 COMEX 1.2V Rail (out):       +1.20 V  (crit min =  +0.80 V, crit max =  +1.90 V)
PMIC-9 Temp 1:                      +36.4 C  (high = +105.0 C, crit = +115.0 C)
PMIC-9 Temp 2:                      +36.4 C  (high = +105.0 C, crit = +115.0 C)
PMIC-9 COMEX 1.2V Rail Pwr (out):    0.00 W
PMIC-9 COMEX 1.2V Rail Curr (out):  +0.06 A  (max = +18.00 A, crit max = +22.00 A)
```

On a 5.10 kernel, the sensor information changed to this:

```
tps53679-i2c-15-61
Adapter: i2c-1-mux (chan_id 6)
PMIC-9 PSU 12V Rail (in1):          11.98 V  (crit min =  +7.50 V, crit max = +17.00 V)
PMIC-9 PSU 12V Rail (in2):           1.20 V  (crit min =  +0.80 V, crit max =  +1.90 V)
PMIC-9 COMEX 1.2V Rail (out):        0.00 V  (crit min =  +0.00 V, crit max =  +1.55 V)
PMIC-9 Temp 1:                      +42.8 C  (high = +105.0 C, crit = +115.0 C)
PMIC-9 Temp 2:                      +42.8 C  (high = +105.0 C, crit = +115.0 C)
PMIC-9 COMEX 1.2V Rail Pwr (out):  182.86 mW (max = 450.00 W)
pout2:                               0.00 W
PMIC-9 COMEX 1.2V Rail Curr (out):   0.00 A  (max = +56.00 A, crit max = +63.50 A)
iout2:                               0.00 A  (max = +18.00 A, crit max = +22.00 A)
```

It looks like `in1` and `in2` from the 4.19 kernel was combined to just `in1` (maybe because the sensor was reporting the same value twice?) and so the sensor names got shifted by one.

#### How I did it

For `tps53679-i2c-*-61` and `tps53679-i2c-*-58`, remove `in2`, and shift the remaining `in*` sensors up by one.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by saiarcot895** [comment]
@alexrallen Could you review this? It appears that the list of sensors has changed slightly between the 4.19 and 5.10 kernel.

**Comment by alexrallen** [comment]
Hrm, I'm not 100% certain this is expected. Let me verify and get back to you.

**Comment by saiarcot895** [comment]
Hi @alexrallen, did you have a chance to verify if the change was needed?

**Comment by saiarcot895** [comment]
Hi @alexrallen, any update here?

**Comment by alexrallen** [comment]
Apologies @saiarcot895 I am no longer actively working on SONiC, I have moved to a new team at NVIDIA. 

@dgsudharsan can help you with or point you to the correct person to help you with this request. I am sorry I could not get to it before leaving. 

Sud, I am not sure that it is correct that we are seeing less sensors on 5.10 you should probably check with Vadim.

**Comment by alexrallen** [comment]
Sud is out of office... perhaps @vivekrnv can help.

**Comment by keboliu** [comment]
let me check internally and get back to this.

**Review by keboliu — CHANGES_REQUESTED** [review]
the updated conf should be like the below:

```
    chip "tps53679-i2c-*-58"
        label in1 "PMIC-8 PSU 12V Rail (in)"
        label in2 "PMIC-8 COMEX 1.8V Rail (out)"
        label in3 "PMIC-8 COMEX 1.05V Rail (out)"
        label temp1 "PMIC-8 Temp 1"
        label temp2 "PMIC-8 Temp 2"
        ignore power1
        label power2 "PMIC-8 COMEX 1.8V Rail Pwr (out)"
        label power3 "PMIC-8 COMEX 1.05V Rail Pwr (out)"
        ignore curr1 
        label curr2 "PMIC-8 COMEX 1.8V Rail Curr (out)"
        label curr3 "PMIC-8 COMEX 1.05V Rail Curr (out)"
    chip "tps53679-i2c-*-61"
        label in1 "PMIC-9 PSU 12V Rail (in)"
        label in2 "PMIC-9 COMEX 1.2V Rail (out)"
        ignore in3
        label temp1 "PMIC-9 Temp 1"
        label temp2 "PMIC-9 Temp 2"
        ignore power1
        label power2 "PMIC-9 COMEX 1.2V Rail Pwr (out)"
        ignore power3 
        ignore curr1 
        label curr2 "PMIC-9 COMEX 1.2V Rail Curr (out)"
        ignore curr3 

```

**Review by keboliu — APPROVED** [review]

**Pull request merged**
