### PR TITLE
[201911][sonic-utilties] Submodule Update

### PR DESCRIPTION
**Pull request by tjchadaga**
#### Why I did it
To pick up - 

**ef2a0cd0**      [201911] [multi_asic] Script to monitor errors on internal links  ([#2971](https://github.com/sonic-net/sonic-utilities/pull/2971))
**1252e31b**     Changes to separate UT data for internal link monitor ([#2976](https://github.com/sonic-net/sonic-utilities/pull/2976))
**3e6654e**   [[201911] [multi-asic] Unit test fix for internal link monitoring ([#2977](https://github.com/sonic-net/sonic-utilities/pull/2977))

##### Work item tracking
- Microsoft ADO **(number only)**: 15439060

#### How I did it
Updated sonic-utilities submodule

#### How to verify it
Ensure the script is available and the build with new unit test cases is successful

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by abdosi** [comment]
@tjchadaga can you please check the build error

**Review by abdosi — COMMENTED** [review]
Approved

**Pull request merged**
