### PR TITLE
[ci]: build nvidia bluefield dpu image

### PR DESCRIPTION
**Pull request by lguohan**
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@liushilongbuaa , can you add a build job for this nvidia bluefield dpu image?

**Comment by liushilongbuaa** [comment]
I will check it.

**Comment by liushilongbuaa** [comment]
I triggerred a build for test:
https://dev.azure.com/mssonic/build/_build/results?buildId=553444

**Review by liushilongbuaa — APPROVED** [review]
LGTM

**Pull request merged**
