### PR TITLE
Remove privileged flag for database and snmp docker

### PR DESCRIPTION
**Pull request by andriydnvd**
Signed-off-by: Andriy Dobush <andriyd@nvidia.com>

#### Why I did it
NOT FOR MERGE !!!!
Reduce docker privilege 
This is part of HLD https://github.com/sonic-net/SONiC/pull/1364

#### How I did it
Remove flag --privileged
#### How to verify it
docker exec -it database bash
root@0048b82b460b:/# ip link add dummy0 type dummy
RTNETLINK answers: Operation not permitted
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by lguohan** [comment]
please identify reviewer for this pr.

**Comment by andriydnvd** [comment]
> please identify reviewer for this pr.

@qiluo-msft

**Comment by qiluo-msft** [comment]
I retriggered another build: https://dev.azure.com/mssonic/build/_build/results?buildId=226231&view=results

**Comment by andriydnvd** [comment]
> I retriggered another build: https://dev.azure.com/mssonic/build/_build/results?buildId=226231&view=results
Current bgp fails looks like infrastructure issue. One of neighbors is down
https://www.testbed-tools.org/scheduler/testplan/63fe6654e64d81d25355e867
Retrigerring

**Comment by andriydnvd** [comment]
azpw run Azure.sonic-buildimage

**Comment by andriydnvd** [comment]
@qiluo-msft   Passed after rebase onto upstream master

**Comment by andriydnvd** [comment]
> I see some changes not related to database docker container. Could you merge latest master or rebase to latest master?

Hi, @qiluo-msft update branch. Pls check

**Review by maipbui — APPROVED** [review]
LGTM. Please change PR title to database and snmp

**Comment by andriydnvd** [comment]
> LGTM. Please change PR title to database and snmp

Done, thanks

**Review by qiluo-msft — APPROVED** [review]

**Comment by Yarden-Z** [comment]
Ready for merger

**Pull request merged**
