### PR TITLE
Add alternate to the bridge interface created on chassis supervisor.

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

Add alternate name `eth1-midplane` to Linux bridge `br1` created on supervisor on some chassis platforms.

Why I did:

See description here: https://github.com/sonic-net/sonic-buildimage/pull/16504

### CODE REVIEW

**Comment by arlakshm** [comment]
@kenneth-arista @ysmanman for viz..

**Comment by kenneth-arista** [comment]
> @kenneth-arista @ysmanman for viz..

Looks fine to me

**Review by arlakshm — APPROVED** [review]

**Comment by abdosi** [comment]
@lguohan can you please help with merge of this

**Comment by abdosi** [comment]
@StormLiangMS  we need this for 202305.

**Comment by StormLiangMS** [comment]
@abdosi could you update ADO in the description?

**Pull request merged**
