### PR TITLE
[Marvell][Nokia-M0] Set custom create switch timeout

### PR DESCRIPTION
**Pull request by pavannaregundi**
#### Why I did it
Migrating Nokia-M0 armhf platform from SONiC 202311 to master and 202405 branch, resulted in syncd create_switch timeout.
It is analyzed to see that SAI SDK code remains the same and time consume by SAI SDK during init when some(snmp mgmt-framework lldp gnmi dhcp_relay radv teamd pmon bgp) of the docker in sonic are disabled is same as running on 202311(with same environment).

Some of the other observations are:
* Switch create time varies from 50sec to 85 sec randomly depending on CPU load.
* Running bullseye based 5.10 sonic kernel yielded same result on latest master.
* Running docker ps -a in 202405 shows all dockers attempting to start, while in 202311 it delays most dockers.
* No single docker seems to have a significant impact.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added changes to support custom create_switch timeout value to orchagent from hwsku.
Orchagent changes are captured in PR https://github.com/sonic-net/sonic-swss/pull/3258

#### How to verify it
Verified by running SONIC PTF run on Nokia-M0.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by pavannaregundi** [comment]
@Blueve @Pavan-Nokia Please check.

**Review by yxieca — APPROVED** [review]

**Comment by Blueve** [comment]
ADO: 29208990

**Pull request merged**
