### PR TITLE
[doc] add pipeline link into README

### PR DESCRIPTION
**Pull request by qiluo-msft**
#### Why I did it
add pipeline link into README

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
image

i do not see any builds. @qiluo-msft

**Comment by qiluo-msft** [comment]
> image
> 
> i do not see any builds. @qiluo-msft

You may click the 'here' link.

**Comment by lguohan** [comment]
@qiluo-msft , that is not correct, why do we need people to have another click?

**Comment by qiluo-msft** [comment]
> @qiluo-msft , that is not correct, why do we need people to have another click?

Resolved.

**Review by xumia — APPROVED** [review]

**Pull request merged**
