### PR TITLE
[Arista] No-op quicksilver qos buffer templates, remove bcm baseline configs

### PR DESCRIPTION
**Pull request by rick-arista**
#### Why I did it
These configs are known to be incorrect and break some testcases, e.g.
the zero-ed out baseline config will cause no multicast traffic egress.
This baseline config was provided to fix a SAI error caused by incorrect
values in the templates, and is unnecessary if the templates result in
no values being added to config db

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)
- [x] 202311
- [x] 202405

#### Description for the changelog
No-op quicksilver qos buffer templates, remove bcm baseline configs

### CODE REVIEW

**Review by r12f — APPROVED** [review]
lgtm! we need to get brcm to get the valid config for these platforms.

**Comment by kperumalbfn** [comment]
Thanks @rick-arista We could update buffer configs for other SKUs after validation.

**Review by kperumalbfn — APPROVED** [review]
LGTM

**Comment by ccroy-arista** [comment]
I believe this will conflict with 202405 branch, which I opened a separate PR for: https://github.com/sonic-net/sonic-buildimage/pull/20231

**Pull request merged**
