### PR TITLE
[dhcp_relay] Revert cli for dhcp per-interface counter

### PR DESCRIPTION
**Pull request by yaqiangz**
#### Why I did it
Functionality for dhcp per-interface counter has been reverted:
dhcpmon: https://github.com/sonic-net/sonic-buildimage/pull/18273
dhcprelay: https://github.com/sonic-net/sonic-buildimage/pull/18288

Cli support hasn't been reverted, but it would not take effect because functionality has been removed.

##### Work item tracking
- Microsoft ADO **(number only)**: 28252981

#### How I did it
Revert related code

#### How to verify it
UT passed

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by yaqiangz** [comment]
@yxieca Could you please help to review this PR?
Change for 202305 has been done by Kelly https://github.com/sonic-net/sonic-buildimage/pull/18253

**Comment by vivekrnv** [comment]
Backport present in 202311 but not in 202405

**Comment by yaqiangz** [comment]
Hi @bingwang-ms could you please help to approve this backport request?

**Pull request merged**
