### PR TITLE
Update cisco-8000.ini to 0.master.0.2 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: anamehra anamehra@cisco.com

* Fixed syncd crash due to segfault in libsai

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by anamehra** [comment]
@abdosi , For your viz. Thanks

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@kevinwangsk for viz.

**Comment by abdosi** [comment]
@anamehra : I assume this should be ok to cherry-pick for 202405 also ?

**Comment by abdosi** [comment]
@lguohan : Please help merge of this.

**Comment by abdosi** [comment]
@bingwang-ms can you please help with cherry-pick pf this.

**Pull request merged**
