### PR TITLE
[build] use real wget for SAI_FLAGS

### PR DESCRIPTION
**Pull request by kv-y**
#### Why I did it

We download libsaibcm.deb every time when we use make to build.
That's because we use build hook but not real wget to get hash for SAI_FLAGS.
As a result we also call curl for libsaibcm.deb inside of function download_packages.

#### How I did it

Add SKIP_BUILD_HOOK=y to use real wget instead of build hook.

#### How to verify it

I redirected all requests to proxy to log them (1st column is timing).

Without fix (curl, curl , wget):

1668034736.348  0 CONNECT sonicstorage.blob.core.windows.net:443
1668034831.997  40064209 GET https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm_7.1.17.4_amd64.deb
1668034832.601  0 CONNECT sonicstorage.blob.core.windows.net:443
1668034833.212  113911 GET https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm-dev_7.1.17.4_amd64.deb
1668034833.831  0 CONNECT sonicstorage.blob.core.windows.net:443
1668034834.030  549 HEAD https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm_7.1.17.4_amd64.deb
1668034834.235  547 HEAD https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm-dev_7.1.17.4_amd64.deb

Fixed version (only wget):

1668034973.199  0 CONNECT sonicstorage.blob.core.windows.net:443
1668034973.339  549 HEAD https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm_7.1.17.4_amd64.deb
1668034973.501  547 HEAD https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/REL_7.0/7.1.17.4/libsaibcm-dev_7.1.17.4_amd64.deb

Signed-off-by: Konstantin Vasin <k.vasin@yadro.com>

### CODE REVIEW

**Comment by kv-y** [comment]
@Kalimuthu-Velappan 
Probably you can also review this PR.
Originally you added this solution with wget in https://github.com/sonic-net/sonic-buildimage/pull/5651
But now it doesn't work as expected cause we are using a build hook instead of real wget.

**Comment by Kalimuthu-Velappan** [comment]
> @Kalimuthu-Velappan Probably you can also review this PR. Originally you added this solution with wget in #5651 But now it doesn't work as expected cause we are using a build hook instead of real wget.

The changes look good.

**Comment by kv-y** [comment]
@lguohan
Could you please review this PR?

**Comment by kv-y** [comment]
@xumia 

Maybe you can help to review and merge this fix?
I afraid that it will be lost.

Without this fix every time you run make you download libsaibcm (40Mb) from sonicstorage.
E.g. you do `make some-pkg-clean` and download libsaibcm.
After that you do `make some-pkg` and libsaibcm is downloaded again.
You do `make list` and wait again.

As a result every time you lose from some seconds to some minutes.

**Review by xumia — APPROVED** [review]

**Pull request merged**
