### PR TITLE
[FRR]: Add support for SRv6 SID Manager

### PR DESCRIPTION
**Pull request by cscarpitta**
#### Why I did it

Bring the below PRs from FRR mainline to SONiC in order to support SRv6 SID Manager in SONiC.

#### New patches that were added

| Patch             | FRR Pull Request |
| ------------- | ----------------- |
| 0064-SRv6-BGP-SID-reachability.patch | https://github.com/FRRouting/frr/pull/14810 |
| 0065-zebra-display-srv6-encapsulation-source-address-when-configured.patch | https://github.com/FRRouting/frr/pull/16151 |
| 0066-lib-fix-srv6-locator-flags-propagated-to-isis.patch | https://github.com/FRRouting/frr/pull/15673 |
| 0067-Add-support-for-SRv6-SID-Manager.patch | https://github.com/FRRouting/frr/pull/15604 |
| 0068-bgpd-Extend-BGP-to-communicate-with-the-SRv6-SID-Manager-to-allocate-release-SRv6-SIDs.patch | https://github.com/FRRouting/frr/pull/15676 |

### CODE REVIEW

**Comment by ahsalam** [comment]
@abdosi @kperumalbfn @lguohan

**Comment by lguohan** [comment]
@abdosi , and @BYGX-wcr

**Review by lguohan — APPROVED** [review]

**Review by BYGX-wcr — APPROVED** [review]

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@r12f : Please let us know when 202411-AI branch is cut off off. we Would need to cherry-pick this one. I have added label for now.


@lguohan : Can you please help merge of this.

**Comment by r12f** [comment]
Hi @abdosi , thanks for the fyi! please expect mid-to-end of this week to get all the branches.

**Review by ahsalam — APPROVED** [review]

**Comment by r12f** [comment]
hi @liushilongbuaa , do you mind to help use this PR for checking the cherry pick automation?

**Pull request merged**
