### PR TITLE
[202305] Upgrade xgs SAI version to 8.4.46.0

### PR DESCRIPTION
**Pull request by Gfrom2016**
#### Why I did it
Upgrade the xgs SAI version to 8.4.46.0 to include the following changes:
- 8.4.42.0: Support _brcm_sai_port_unlos_set when external port_phy_addr is 0xff
- 8.4.45.0: Uplift SONIC-85239 patch-2 to 8.4.
- 8.4.46.0: [CSP CS00012343232][SAI_BRANCH rel_ocp_sai_8_4]Back port MMU related Fixes to 8.4 specific to LTSW/TH4
##### Work item tracking
- Microsoft ADO **(number only)**: 28384445

#### How I did it
Upgrade the SAI version in the sai.mk file.

#### How to verify it
Run the SONiC basic test in the SAI release pipeline, all passed:
https://dev.azure.com/mssonic/internal/_build/results?buildId=570531&view=results

Signed-off-by: zitingguo-ms <zitingguo@microsoft.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@Gfrom2016 , i do not understand this. the CSP listed in the ado is for DNX chip, why are we updating XGS sai lib?

**Comment by StormLiangMS** [comment]
> @Gfrom2016 , i do not understand this. the CSP listed in the ado is for DNX chip, why are we updating XGS sai lib?

hi @lguohan  this is for TH4 which is asked by Arista, they get customer on this branch to use TH4, and need this fix.

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
