### PR TITLE
[swss][202205]: Submodule update

### PR DESCRIPTION
**Pull request by theasianpianist**
Include following commits:

```
9d9f3952 [intfmgr]: Enable `accept_untracked_na` kernel param (#2436)
6b6d25d6  [orchdaemon]: Fixed sairedis record file rotation (#2480)
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by theasianpianist** [comment]
already merged, closing as duplicate

**Comment by theasianpianist** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/12292

**Pull request closed without merging**
