### PR TITLE
  Fix Celestica Silverstone addDecapTunnel failed issue

### PR DESCRIPTION
**Pull request by george-deng88**
#### Why I did it
The current sonic image bringup failed on Silverstone:
Jan  3 14:56:15.957705 sonic NOTICE swss#orchagent: :- addDecapTunnel: Create overlay loopback router interface oid:6000000000520
Jan  3 14:56:15.958451 sonic ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_NOT_SUPPORTED
Jan  3 14:56:15.958623 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID: oid:0x3000000000022
Jan  3 14:56:15.958623 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE: SAI_TUNNEL_TERM_TABLE_ENTRY_TYPE_P2MP
Jan  3 14:56:15.958754 sonic ERR swss#orchagent: :- create: create status: SAI_STATUS_NOT_SUPPORTED
#### How I did it
Enable Tunnel function on Silverstone.
#### How to verify it
The new sonic image can bringup OK on Silverstone.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [x] 202106
- [x] 202111
- [x] 202205
- [x] 202211

### CODE REVIEW

**Comment by george-deng88** [comment]
check failed

**Comment by george-deng88** [comment]
Hi @yxieca ,

This PR no reviewer assigned, please help to review it. Thanks

**Review by prsunny — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@yxieca  @kperumalbfn  @donNewtonIntel @baxia-lan  can anyone of you help to merge this PR? Thanks.

**Comment by zhangyanzhao** [comment]
@yxieca  @kperumalbfn  @donNewtonIntel  @baxia-lan can anyone of you help to merge this PR? Thanks.

**Pull request merged**
