### PR TITLE
Secure boot fix instalation with devices that used ONIE version older than 2021.11

### PR DESCRIPTION
**Pull request by davidpil2002**
#### Why I did it
solution to BUG below/
https://github.com/sonic-net/sonic-buildimage/issues/14316
bug report also in this issue:
backport: secureboot support #14246
#### How I did it
When installing an image secure boot is checking if the UEFI have the secure boot flag enabled or disabled using a tool name `mokutil` this tool its not exist in ONIE version older than 2021.11 so its crasshing the install.
To fix that we add a coded that checking if the tool exist, if not exist it will assume that you ONIE its older an proceed with the installation with grub.
#### How to verify it
Install the image in a device with ONIE version older than 2021.11 and check that the installation and boot succeed (all docker up).
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [X ] 202211
- master

### CODE REVIEW

**Comment by davidpil2002** [comment]
pls @ITJamie can you review this fix
pls @sacnaik you are welcome to review as well also in the the good flow, with new ONIE version to see no degration in your system.

(We are reviewing it also, but still pending for a device with the correct version to test it fully.)

**Comment by davidpil2002** [comment]
rerun, failed in build time, but the commit didn't modify anything than influence the build flow.

**Comment by davidpil2002** [comment]
[29/03/2022 14:40] Noa Or




/azp run Azure.sonic-buildimage

**Comment by davidpil2002** [comment]
Hi @liat-grozovik ,
This PR is a fix about an issue related to Secure Boot that influence device that have ONIE version older than 2021.11.
can you be in the loop as reviewer?
in addition, I'm trying to rerun the PR, and probably the syntax to rerun was change, can you help?

**Comment by davidpil2002** [comment]
/ azp run Azure.sonic-buildimage

**Comment by davidpil2002** [comment]
> Hi David
> 
> I download image from this page [Supported Platforms](https://github.com/sonic-net/SONiC/blob/sonic_image_md_update/supported_devices_platforms.md) today.
> 
> But it install fails and feedback "mokutil: not found", when I try to install SONiC image for Accton AS9716-32D, Install log as below [mokutil_not_found.txt](https://github.com/sonic-net/sonic-buildimage/files/11099574/mokutil_not_found.txt)
> 
> maybe our switch version is too old. is it should still install or without and skip for mokutil ?

this PR contained the fix for your issue.

**Comment by happyttm24** [comment]
Hello, I am also have the same issue. The switch I am using is 100bf-32x. During the process of installing SONiC for 100bf-32x, I encountered an error "mokutil not found" and the installation process did not proceed.

**Comment by luigitalboy** [comment]
Hello @davidpil2002 , do you know when the new sonic-broadcom.bin file containing the PR for mokutil absence will be ready for download in the support platform page?
Thanks!!!

**Comment by davidpil2002** [comment]
this PR is ready.
@qiluo-msft pls can you approve they are pending this fix.
thanks

**Comment by davidpil2002** [comment]
there is some build issue about some unitest of hostcfgd, but my commits in the PR are not related.
sent an email to:
sonicbuildadmin@microsoft.com

**Comment by luigitalboy** [comment]
Thanks @davidpil2002! Do you think we can test the images this monday?

**Comment by davidpil2002** [comment]
> Thanks @davidpil2002! Do you think we can test the images this monday?

This fix its pending approvemt from community.
in general, if you build your image with this fix you should be able to install the image in any ONIE version.

**Comment by luigitalboy** [comment]
Great :-)  which branch should I select from the drop down list?

**Comment by davidpil2002** [comment]
> Great :-) which branch should I select from the drop down list?

the fixed its not merge, so basicly the fix it just in this PR that was created from master.
if you like to check this fix in other branch you can cherry pick the commit to other branch (its just one commit.)

**Review by ITJamie — APPROVED** [review]

**Comment by stephengao-ragilenetworks** [comment]
Same issue on Ragile RA-B6510-48V8C, please someone approves this PR soon.

**Comment by davidpil2002** [comment]
> Same issue on Ragile RA-B6510-48V8C, please someone approves this PR soon.

@qiluo-msft kind reminder to review this PR.

**Comment by liat-grozovik** [comment]
@ITJamie could you please confirm the fix is working for BRCM? we cannot fully test it. If so, I can go a head and merge it.

**Comment by davidpil2002** [comment]
@ITJamie We found other solution, using efivar and doing specific parsing to secureboot. if you can wait, we will upstream this solution as well.
PS: with this solution we will not use `mokutils`

**Pull request closed without merging**
