### PR TITLE
[submodule] Advance sonic-swss and sonic-utilities pointer

### PR DESCRIPTION
**Pull request by stephenxs**
sonic-utilities
7919077f Add FEC correctable and uncorrectable port stats (sonic-net/sonic-utilities#2027)
ecb91367 Add CLI to configure YANG config validation (sonic-net/sonic-utilities#2147)
e9ab5235 Add override testcase to verify removal (sonic-net/sonic-utilities#2288)
c6794b55 Fix version in db_migrator  for `PORT_QOS_MAP|global` (sonic-net/sonic-utilities#2289)
92b889b7 [intfutil] Check whether the FEC mode is supported on the platform before configuring it to CONFIG_DB (sonic-net/sonic-utilities#2223)
dab0d065 Transfer organization from Azure to sonic-net (sonic-net/sonic-utilities#2284)
6de18a1d [watermarkstat] Fix CLI script for unconfigured PG counters (sonic-net/sonic-utilities#2239)
ac2f5530 Improve the way to check port type of RJ45 port (sonic-net/sonic-utilities#2249)
142185c9 Fix the issue that sonic_platform is not installed on vs image (sonic-net/sonic-utilities#2300)
ca14133f [crm] add checking for CRM interval range (sonic-net/sonic-utilities#2293)
be1866fd Fix GCU bug when backend service modifying config (sonic-net/sonic-utilities#2295)
bcf36eb3 Fix issues for sonic_installer upgrade-docker and sonic_installer rollback-docker (sonic-net/sonic-utilities#2278)

sonic-swss
dc8bc1c4 [portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it (sonic-net/sonic-swss#2333)
6565b502 Revert "[portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it (sonic-net/sonic-swss#2333)" (sonic-net/sonic-swss#2396)
dc88d55d Revert hwinfo count change (sonic-net/sonic-swss#2383)
75fc9659 [DualToR] Handle race condition between tunnel_decap and mux orchestrator (sonic-net/sonic-swss#2397)
525a57fa Fix for remote system interface not getting created (sonic-net/sonic-swss#2364)
3161eaae portsorch: initial support for link-training (sonic-net/sonic-swss#2359)
dc477fb0 [swss/cfgmgr] teammgr configure lacp rate (sonic-net/sonic-swss#2121)
2489ad57 Improve pytest speend by grouping 20 tests together. (sonic-net/sonic-swss#2390)
168bd3b3 [EVPN]Modified tunnel creation logic when creating tunnel in VRF-VNI map creation flow (sonic-net/sonic-swss#2404)
1e1438e4 [portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it (sonic-net/sonic-swss#2400)
9f2e27b4 [QoS] Fix issue: the WRED profile can not be set if current min > new max or current max < new min (sonic-net/sonic-swss#2379)
d36c17d6 [asan][aclorch] fix a memory leak in the SaiAttrWrapper::swap() (sonic-net/sonic-swss#2382)

Signed-off-by: Stephen Sun <stephens@nvidia.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by stephenxs** [comment]
azpw azure.sonic-buildimage

**Comment by stephenxs** [comment]
`sonic_platform` isn't installed on vs image but is referenced by sonic-net/sonic-utilities#2249.
Working on a fix.

**Comment by stephenxs** [comment]
> `sonic_platform` isn't installed on vs image but is referenced by [sonic-net/sonic-utilities#2249](https://github.com/sonic-net/sonic-utilities/pull/2249). Working on a fix.

Fixed by sonic-net/sonic-utilities#2300

**Comment by stephenxs** [comment]
```
Aug  9 13:31:46.294905 vlab-01 INFO caclmgrd[64240]: ACL config for namespace '' has not changed for 0.5 seconds. Applying updates ...
Aug  9 13:31:46.306035 vlab-01 NOTICE swss#orchagent: :- addNextHopGroup: Create next hop group fc00::76@PortChannel102,fc00::7a@PortChannel103
Aug  9 13:31:46.334026 vlab-01 INFO kernel: [ 4592.587585] caclmgrd[68366]: segfault at 4d ip 00007f6052666c13 sp 00007f6051c3cb50 error 4 in _swsscommon.so.0.0.0[7f60525b7000+ba000]
Aug  9 13:31:46.334073 vlab-01 INFO kernel: [ 4592.587612] Code: 8d 7c 24 50 31 c0 48 89 0c 24 48 8d 4c 24 48 48 89 4c 24 18 0f 1f 00 49 8b 56 28 48 8b 04 c2 4c 8b 60 18 8d 43 01 48 8b 04 c2 <4c> 8b 68 18 48 8b 04 24 48 89 44 24 50 4d 85 e4 0f 84 f1 01 00 00
Aug  9 13:31:46.371682 vlab-01 WARNING ntpd[67124]: routing socket reports: No buffer space available
Aug  9 13:31:46.376620 vlab-01 NOTICE swss#orchagent: :- addNextHopGroup: Create next hop group fc00::7a@PortChannel103,fc00::7e@PortChannel104
Aug  9 13:31:46.405975 vlab-01 WARNING ntpd[67124]: routing socket reports: No buffer space available
Aug  9 13:31:46.500377 vlab-01 WARNING ntpd[67124]: message repeated 12 times: [ routing socket reports: No buffer space available]
Aug  9 13:31:46.778050 vlab-01 WARNING systemd[1]: caclmgrd.service: Main process exited, code=killed, status=11/SEGV
Aug  9 13:31:46.779042 vlab-01 WARNING systemd[1]: caclmgrd.service: Failed with result 'signal'.
Aug  9 13:31:46.860688 vlab-01 NOTICE syncd#syncd: :- threadFunction: time span 153 ms for 'bulkset:SAI_OBJECT_TYPE_ROUTE_ENTRY:733'
Aug  9 13:31:47.802508 vlab-01 NOTICE swss#orchagent: :- addNextHopGroup: Create next hop group 10.0.0.61@PortChannel103,10.0.0.63@PortChannel104
```

**Review by prgeor — APPROVED** [review]

**Pull request merged**
