### PR TITLE
[Mellanox] Fix SN5400 lane number of service port from 513 to 520

### PR DESCRIPTION
**Pull request by skr31**
#### Why I did it
Fixed a lane numbering bug with service ports on SN5400
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Changed the second service port to be Ethernet520 instead of Ethernet513

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dprital — APPROVED** [review]

**Comment by yxieca** [comment]
@bingwang-ms to track 202405 cherry-picking

**Pull request merged**
