### PR TITLE
[Marvell] Update armhf sai debian

### PR DESCRIPTION
**Pull request by rajkumar38**
#### Why I did it
Fixed syncd syslog errors reported in issue https://github.com/sonic-net/SONiC/issues/1248
Fixes https://github.com/sonic-net/SONiC/issues/1248
#### How I did it
Compile and load the SAI debian in SONiC 202205 image.

#### How to verify it
Verify PTF autorestart testcase passes.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by radha-danda** [comment]
@Blueve, can you check and merge the PR please?

**Comment by Blueve** [comment]
@radha-danda can we backport this PR to 202205 and 202211? Or will you have another PRs to these release branches?

**Review by Blueve — APPROVED** [review]

**Comment by radha-danda** [comment]
> @radha-danda do we have the same fix for master and 202211? Or will you have another PRs to these release branches?

@Blueve, we will raise separate PR for master and cherry-pick the changes to 202211

**Comment by lguohan** [comment]
@yxieca , can you merge?

**Pull request merged**
