### PR TITLE
Fix issue with prod script not found, change the prod signing to work with flags to align to the dev script

### PR DESCRIPTION
**Pull request by DavidZagury**
#### Why I did it
Fix issue with signing tool not running due to being call with the path from the host and not the path it is mounted on inside the docker-slave

#### How I did it
Modified the path on the SECURE_UPGRADE_PROD_SIGNING_TOOL flag to the path where it is mounted inside the slave docker

#### How to verify it
Build SONiC using your own prod script

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [x] 202211

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@davidpil2002 please review this one pls

**Comment by DavidZagury** [comment]
RERUN

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
