### PR TITLE
[202305][SNMP][IPv6]: Revert PRs to support SNMP over IPv6 

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
#### Why I did it
Revert https://github.com/sonic-net/sonic-buildimage/pull/16013 and https://github.com/sonic-net/sonic-buildimage/pull/15487 form 202305 branch
##### Work item tracking
- Microsoft ADO **25243527**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@SuvarnaMeenakshi do you have ADO for this?

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi do you have ADO for this?

Yes, Updated ADO 25243527

**Comment by StormLiangMS** [comment]
@SuvarnaMeenakshi there is a PR test failure, could you help to take a look?

image

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi there is a PR test failure, could you help to take a look?
> 
> image

We need this PR merged in master/202305 and 202205 branches.

https://github.com/sonic-net/sonic-mgmt/pull/10097

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
