### PR TITLE
chassis-packet: resolve the missing static routes

### PR DESCRIPTION
**Pull request by anamehra**
arp_update should resolve the missing arp/ndp static route
    entries. Added code to check for missing entries and try ping to
    resolve the missing entry.

#### Why I did it
Fixes https://github.com/sonic-net/sonic-buildimage/issues/14179
chassis-packet: missing arp entries for static routes causing high orchagent cpu usage

It is observed that some sonic-mgmt test case calls sonic-clear arp, which clears the static arp entries as well. Orchagent or arp_update process does not try to resolve the missing arp entries after clear.

#### How I did it
arp_update should resolve the missing arp/ndp static route
entries. Added code to check for missing entries and try ping if any
found to resolve it.

#### How to verify it
1. After boot or config reload, check ipv4 and ipv4 neigh entries to make sure all static route entries are present
manual validation:
2. Use sonic-clear arp and sonic-clear ndp to clear all neighbor entries
run arp_update
Check for neigh entries. All entries should be present.

Testing on T0 setup route/for test_static_route.py

The test set the STATIC_ROUTE entry in conifg db without ifname:
sonic-db-cli CONFIG_DB hmset 'STATIC_ROUTE|2.2.2.0/24' nexthop 192.168.0.18,192.168.0.25,192.168.0.23

    "STATIC_ROUTE": {
        "2.2.2.0/24": {
            "nexthop": "192.168.0.18,192.168.0.25,192.168.0.23"
        }
    },

Validate that the arp_update gets the proper ARP_UPDATE_VARDS using arp_update_vars.j2 template from config db and does not crash:

{ "switch_type": "", "interface": "", "pc_interface" : "PortChannel101 PortChannel102 PortChannel103 PortChannel104 ", "vlan_sub_interface": "", "vlan" : "Vlan1000", "static_route_nexthops": "192.168.0.18 192.168.0.25 192.168.0.23 ", "static_route_ifnames": "" }

validate route/test_static_route.py testcase pass.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211

### CODE REVIEW

**Comment by anamehra** [comment]
@yejianquan , @abdosi , Created this draft PR while testing a few more times on T0 system. Thanks

**Comment by yejianquan** [comment]
50/50 pass:
image
From the test side it's ok,
@jcaiMR Can you double confirm?

**Comment by jcaiMR** [comment]
> 50/50 pass: image From the test side it's ok, @jcaiMR Can you double confirm?

Looks good to me, verified on physical DUT.

**Review by yejianquan — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
