### PR TITLE
Update cisco-8000.ini to 202405.0.2 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: anamehra anamehra@cisco.com

Cisco platform 202405.0.2 release

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by anamehra** [comment]
Hi @rlhui , @abdosi , raised this PR for new code drop. Thanks

**Review by abdosi — APPROVED** [review]

**Comment by yejianquan** [comment]
For the docker registry issue, fix PR: https://github.com/sonic-net/sonic-buildimage/pull/19445

**Comment by yejianquan** [comment]
> For the docker registry issue, fix PR: #19445

Fix to master merged, pending cherry-pick to 202405
https://github.com/sonic-net/sonic-buildimage/pull/19472

**Comment by abdosi** [comment]
@lguohan : please help with merge of this.

**Pull request merged**
