### PR TITLE
[submodule] [202305] Update sonic-dhcp-relay submodule

### PR DESCRIPTION
**Pull request by vivekrnv**
#### Why I did it

Update the submodule to include the following fixes

```
2b33d76 dhcpv6 per interface counter support 
6a6ce24 fix dhcpv6 relay dual tor source interface selection issue 
c36b8e3 [actions] Support Semgrep by Github Actions (#39)
```

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by jcaiMR — APPROVED** [review]

**Comment by jcaiMR** [comment]
@StormLiangMS  @vivekrnv  In order to get PR test passed, 202305 sonic-mgmt code need syncing with mater branch to have the latest test case gap fix for per-interface counter.

**Comment by StormLiangMS** [comment]
@kellyyeh could you help to review?

**Review by kellyyeh — APPROVED** [review]

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
