### PR TITLE
[Mellanox] Fix component versions caching bug

### PR DESCRIPTION
**Pull request by skr31**
#### Why I did it
The component versions file that is created during compilation was not being updated because it was being cached, even when some of the versions on it should have been updated.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Removed component-versions.dep
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by DavidZagury — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
PR test retriggered.

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Retriggered PR test.

**Comment by dprital** [comment]
@bingwang-ms , No matter how many times this PR is retriggered, the Test of "Test kvmtest-t1-lag by Elastictest" is not running at all. 
Can you please merge it although this checker doesn't run / pass ?

**Comment by bingwang-ms** [comment]
> @bingwang-ms , No matter how many times this PR is retriggered, the Test of "Test kvmtest-t1-lag by Elastictest" is not running at all. Can you please merge it although this checker doesn't run / pass ?

I'm not able to bypass the policy. I just closed and reopened the PR. Hopefully it can fix the issue.

**Comment by liushilongbuaa** [comment]
@bingwang-ms , this PR only change files in platform/mellanox.
PR validation will not run kvmtest because vs image didn't changed.

**Comment by liushilongbuaa** [comment]
PR validation will not pass. Please bypass policy force merge.

**Comment by dprital** [comment]
> PR validation will not pass. Please bypass policy force merge.

@liushilongbuaa , Do we need to do something here ? or the maintainer can handle it ?

**Comment by liushilongbuaa** [comment]
> > PR validation will not pass. Please bypass policy force merge.
> 
> @liushilongbuaa , Do we need to do something here ? or the maintainer can handle it ?

Maintainer can handle it.
The PR Validation failure is false alert.

**Comment by dprital** [comment]
@bingwang-ms , based on the comment above, can you please merge ?

**Comment by dprital** [comment]
@bingwang-ms , Can you please merge and also cherry pick to 202405 ?

**Comment by dprital** [comment]
@bingwang-ms , Can you please merge ?

**Comment by liat-grozovik** [comment]
@skr31 please check failures. we need this to get into 202405

**Comment by DavidZagury** [comment]
> @skr31 please check failures. we need this to get into 202405

@liat-grozovik there are no failure for @skr31 to check.
The only failed checker is **Test kvmtest-t1-lag by Elastictest** which is not running when retriggering the checkers.
And, as @liushilongbuaa said 

> @bingwang-ms , this PR only change files in platform/mellanox. PR validation will not run kvmtest because vs image didn't changed.

So we can't rerun this checker and no matter what we do/did in the last 3 months - this checker will stay failed and it is a false alert.

**Comment by dprital** [comment]
@bingwang-ms , Can you please cherry pick to 202405 ?

**Pull request merged**
