### PR TITLE
[Mellanox] Update SAI build procedure

### PR DESCRIPTION
**Pull request by keboliu**
#### Why I did it
To optimize Mellanox platform SAI build

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

SAI debs are now downloaded as Spectrum-SDK-Drivers-SONiC-Bins release.

#### How to verify it

Configure/build for Mellanox platform, check the image and ensure that correct SAI debs are included.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Yakiv-Huryk — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@keboliu @liat-grozovik  to me, this is more like an enhancement, if so, no for 202305.

**Comment by keboliu** [comment]
@StormLiangMS we are changing our SAI build methodology as mentioned in the description, w/o this change SAI will not build.

**Comment by dgsudharsan** [comment]
@StormLiangMS  This is block us from building 202305 with our latest SAI. Can you please expediate cherry-pick?

**Comment by StormLiangMS** [comment]
enhancement, but only for Mellanox, ok to backport.

**Pull request merged**
