### PR TITLE
[202311] Remove rsyslog plugin regex and config from host and dhcp/bgp/swss containers at build time

### PR DESCRIPTION
**Pull request by zbud-msft**
#### Why I did it

With this change, there will be no need to have any rsyslog plugin configuration files or regexes inside the containers. At buildtime, all configuration files and regexes will be stored in eventd docker. Only when eventd docker is started, will we copy these files to be used in the host.

##### Work item tracking
- Microsoft ADO **(number only)**: 28728116

#### How I did it

Remove all regexes and configuration files from dhcp_relay, bgp, and swss containers, as well as host. Contain all of it inside eventd docker. Modify eventd.sh to copy files from docker to host after starting

#### How to verify it

Nightly test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Why not pull request on master branch first? After merging, we can backport to all relevant release branches.

**Comment by zbud-msft** [comment]
There is a PR on master branch, there is a cherry pick conflict so hence, we have a separate PR for 202311: https://github.com/sonic-net/sonic-buildimage/pull/20041

**Comment by StormLiangMS** [comment]
@yxieca https://github.com/sonic-net/sonic-buildimage/pull/20041, master PR is pending, we should merge after it.

**Comment by zbud-msft** [comment]
Will not use for 202311

**Pull request closed without merging**
