### PR TITLE
Updated PG headroom settings for 40g port speed

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
Update PG headroom settings for 40g port speed

##### Work item tracking
- Microsoft ADO **(24785292)**:

#### How I did it
Updated pg_profile.ini file to add 40g entry

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by gechiang** [comment]
@vmittal-msft please create an MSFT ADO for this (for branch request purpose) and update this PR with the ADO info under PR description.

**Review by arlakshm — APPROVED** [review]

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
@vmittal-msft These PG headroom setting do we have any tests for it or these are strictly tunning numbers?

**Comment by vmittal-msft** [comment]
> @vmittal-msft These PG headroom setting do we have any tests for it or these are strictly tunning numbers?

We don't have any tests. These are HW settings for 40g ports.

**Comment by vmittal-msft** [comment]
> @vmittal-msft please create an MSFT ADO for this (for branch request purpose) and update this PR with the ADO info under PR description.

@gechiang - Updated.

**Review by judyjoseph — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@yxieca @rlhui @lguohan can you please help merge ?

**Comment by StormLiangMS** [comment]
@gechiang could you help to clarify why we need this on 202211?

**Comment by gechiang** [comment]
> @gechiang could you help to clarify why we need this on 202211?

I think the rule for back porting is when we requested for lets' say 202205, we must also ask for all subsequent "released" branches such as 202211, 202305.  Therefore I added the request for "202211".

**Pull request merged**
