### PR TITLE
[Mellanox] Add functionality to handle empty EEPROM files

### PR DESCRIPTION
**Pull request by tshalvi**
#### Why I did it
On Mellanox platforms, it was decided that a good way to simulate an I2C stuck scenario would be to have the files representing the module's EEPROM remain empty. When these files are empty, module initialization will not complete because the read_eeprom() function gets stuck in an infinite loop (```while num_bytes > 0:``` will never evaluate to False as the decrement operation ```num_bytes -= read_length``` has no effect). This happens because 0 bytes are always read from the EEPROM when it is empty. This PR addresses this issue.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
On Mellanox platforms only, I added a validation check to ensure that if an attempt to read from the EEPROM results in 0 bytes read, the _read_eeprom() function exits and returns None.

#### How to verify it
Simulate the empty EEPROM (can be done as described in the script below), update _get_eeprom_path() to redirect to the empty EEPROM location, config reload, and verify that not all ports are down.
```bash
cd /
mkdir -p path_to_empty_files_folder
cd path_to_empty_files_folder

for i in $(seq 1 300); do
    mkdir -p $i
    touch $i/data
done

mkdir -p 0/i2c-0x50
touch 0/i2c-0x50/data
mkdir -p 0/i2c-0x51
touch 0/i2c-0x51/data
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by noaOrMlnx — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prgeor could you please provide your feedback as well? I am OK to merge it.

**Comment by liat-grozovik** [comment]
> @prgeor could you please provide your feedback as well? I am OK to merge it.

@prgeor kindly reminde

**Review by prgeor — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@qiluo-msft Can you please help merge this PR? Thanks

**Comment by tshalvi** [comment]
> @tshalvi is this flow relevant for 202405 only or also 202311?

It is relevant for both 202311 and 202405

**Comment by bingwang-ms** [comment]
@prgeor Can you help review and merge?

**Comment by bingwang-ms** [comment]
@liushilongbuaa Auto-cherrypick is not working for this PR. Can you please check?
@tshalvi Can you raise a PR to 202405 as a workaround?

**Pull request merged**
