### PR TITLE
[submodule] advance sonic-utilities submodule

### PR DESCRIPTION
**Pull request by maipbui**
10f31ea6 (HEAD -> master, upstream/master, upstream/HEAD) Revert "Replace pickle by json (https://github.com/sonic-net/sonic-utilities/pull/2636)" (https://github.com/sonic-net/sonic-utilities/pull/2746)
05fa7513 Fix the `show interface counters` throwing exception on device with no external interfaces (https://github.com/sonic-net/sonic-utilities/pull/2703)
f27dea0c (origin/master) [route_check] remove check-frr_patch mock (https://github.com/sonic-net/sonic-utilities/pull/2732)
2d95529d Revert "Update load minigraph to load backend acl (https://github.com/sonic-net/sonic-utilities/pull/2236)" (https://github.com/sonic-net/sonic-utilities/pull/2735)
c869c970 Update the ref guide to reflect the vlan brief output (https://github.com/sonic-net/sonic-utilities/pull/2731)
76457141 Fix fast-reboot DB migration (https://github.com/sonic-net/sonic-utilities/pull/2734)
f7f783bc Enhance the logic to wait for all buffer tables to be removed in _clear_qos (https://github.com/sonic-net/sonic-utilities/pull/2720)
e6179afa Remove timer from FAST_REBOOT STATE_DB entry and use finalizer (https://github.com/sonic-net/sonic-utilities/pull/2621)
ff688323 [route_check] fix IPv6 address handling (https://github.com/sonic-net/sonic-utilities/pull/2722)
7a604c51 update fast-reboot (https://github.com/sonic-net/sonic-utilities/pull/2728)
9f83ace9 [GCU] Add vlanintf-validator (https://github.com/sonic-net/sonic-utilities/pull/2697)
338d1c05 Check SONiC dependencies before installation. (https://github.com/sonic-net/sonic-utilities/pull/2716)
64d2efd2 Improve show acl commands (https://github.com/sonic-net/sonic-utilities/pull/2667)
2ef5b31e [GCU] Add PFC_WD RDMA validator (https://github.com/sonic-net/sonic-utilities/pull/2619)
c7aa8416 [show][muxcable] increase timeout for displaying HW_STATUS (https://github.com/sonic-net/sonic-utilities/pull/2712)
2fc2b826 YANG validation for ConfigDB Updates: MIRROR_SESSION use case (https://github.com/sonic-net/sonic-utilities/pull/2430)
e16bdaae Fix non-zero status exit on non secure boot system (https://github.com/sonic-net/sonic-utilities/pull/2715)
90d70152 [route_check] implement a check for FRR routes not marked offloaded (https://github.com/sonic-net/sonic-utilities/pull/2531)
c2bc150a [warm/fast-reboot] Backup logs from tmpfs to disk during fast/warm shutdown (https://github.com/sonic-net/sonic-utilities/pull/2714)
a015834d [db_migrator] Add missing attribute 'weight' to route entries in APPL DB (https://github.com/sonic-net/sonic-utilities/pull/2691)
cd519aac [ci] Fix pipeline issue caused by sonic-slave-* change. (https://github.com/sonic-net/sonic-utilities/pull/2709)
2680e6f3 [dhcp_relay] Fix dhcp_relay restart error while add/del vlan (https://github.com/sonic-net/sonic-utilities/pull/2688)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by ZhaohuiS — APPROVED** [review]

**Comment by maipbui** [comment]
@ZhaohuiS @yejianquan I rerun all tests on azure pipelines

**Pull request closed without merging**
