### PR TITLE
[sonic-swss-common] Update sonic-swss-common submodule

### PR DESCRIPTION
**Pull request by liuh-80**
#### Why I did it

Submodule update for sonic-swss-common with following change:
```
2247dbe 2022-08-01 | Fix memory leak issue in ConfigDBConnector. (#655) [Hua Liu]
4af97d6 2022-07-27 | Add new table schemas for DASH (#654) [prabhataravind]
d72e5ea 2022-07-23 | Fix epoll and socket resource leak issue. (#651) [Hua Liu]
dda857b 2022-07-21 | Microsoft mandatory file (#620) [microsoft-github-policy-service[bot]]
4132d14 2022-07-21 | Fix PING database command not backward compatible with python version issue. (#650) [Hua Liu]
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog
Submodule update for sonic-swss-common with following change:
```
2247dbe 2022-08-01 | Fix memory leak issue in ConfigDBConnector. (#655) [Hua Liu]
4af97d6 2022-07-27 | Add new table schemas for DASH (#654) [prabhataravind]
d72e5ea 2022-07-23 | Fix epoll and socket resource leak issue. (#651) [Hua Liu]
dda857b 2022-07-21 | Microsoft mandatory file (#620) [microsoft-github-policy-service[bot]]
4132d14 2022-07-21 | Fix PING database command not backward compatible with python version issue. (#650) [Hua Liu]
```

### CODE REVIEW

**Comment by liuh-80** [comment]
All other replace swsssdk PRs need wait this merge first, because this fix a resource leak issue.

**Comment by liuh-80** [comment]
Will hold this PR because the multiple FS issue still happen.

**Comment by liuh-80** [comment]
The old artifact is wrong format, will rebuild and validate with new image.

**Comment by liuh-80** [comment]
Found another memory leak in swss-common, will update this later.

**Comment by liuh-80** [comment]
Waiting for this PR: https://github.com/Azure/sonic-swss-common/pull/655

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
