### PR TITLE
[submodule] Update sonic-pins submodule

### PR DESCRIPTION
**Pull request by saiarcot895**
#### Why I did it

Update the sonic-pins submodule. This brings in the following commit:

```
56a7762 Use json.hpp from nlohmann-json-dev instead of from swss-common (#22)
```

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by yxieca** [comment]
@xumia @liushilongbuaa can you check why PINS submodule is not handled by automation?

**Comment by liushilongbuaa** [comment]
@yxieca , because sonic-pins used main branch instead of master.
Automation only works for same branch with sonic-buildimage.

**Comment by liushilongbuaa** [comment]
https://github.com/sonic-net/sonic-genl-packet
This repo also used main instead of master.

**Comment by yxieca** [comment]
> https://github.com/sonic-net/sonic-genl-packet This repo also used main instead of master.

Is it possible to add support?

**Comment by liushilongbuaa** [comment]
> > https://github.com/sonic-net/sonic-genl-packet This repo also used main instead of master.
> 
> Is it possible to add support?

sure. If it updates submodule for master branch, check master branch first then main branch.

**Pull request merged**
