### PR TITLE
Fix issue with getting midplane bridge IP address

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### Why I did it
Fix the issue with getting a midplane bridge IP address.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Use the right variable name.

#### How to verify it
On the Smart Switch device ZMQ from the NPU should be able to connect to the orchagent on the DPU,

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by liuh-80 — APPROVED** [review]

**Comment by oleksandrivantsiv** [comment]
@prsunny, @liuh-80 can we merge this PR?

**Comment by liuh-80** [comment]
> @prsunny, @liuh-80 can we merge this PR?

Yes, please, BTW I have another PR which will change ZMQ bind to midplane mgmt interface, which is because the IP address may change by DHCP:

https://github.com/sonic-net/sonic-buildimage/pull/20352

**Comment by prsunny** [comment]
I see the same change in 20352 PR. Should we close this and merge the other one?

**Comment by liuh-80** [comment]
> I see the same change in 20352 PR. Should we close this and merge the other one?

This PR no longer necessary, because #20352 already change code, ZMQ will bind to interface name.

**Pull request closed without merging**
