### PR TITLE
[202205] [Mellanox] Update SDK/FW to 4.5.4318/2010.4316 and SAI to 2205.25.1.2

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
#### Why I did it
Update SDK/FW to 4.5.4318/2010.4316 and SAI to 2205.25.1.2 in order to include listed below fixes.

SDK/FW

- In some cases, when an ACL has two or more rules with a similar key, modifying/removing one of the rules may cause modification/removal of one of the similar-key rules, instead of the requested rule.
- Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes).
- In some case warmboot from 201911 to 202205 might result in dataplane traffic loss
- When upgrade SONiC version using warm boot from version 201911/202012 to newer version, then doing cold boot back to older version and upgrade again to newer one   warm boot might be fail.

</body>

</html>

SAI

- Added support for dynamic ordered ECMP group (SAI_NEXT_GROUP_TYPE_DYNAMIC_ORDERED_ECMP)
- "store and forward" KV was added
- Added Support for IPV6 link local debug counters

#### How I did it
Updated versions in relevant Makefiles

#### How to verify it
Build an image and verify that updated SAI/SDK/FW packages are included.
Run full sonic-mgmt test suits on various Nvidia ASICs and platforms.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]
missing list of fixes and new features. Please add

**Comment by bingwang-ms** [comment]
MSFT ADO: 24865987, 24902417, 24865973

**Comment by bingwang-ms** [comment]
Can you please clarify the items below? Thanks

**SDK/FW:**
Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes).

**SAI:**
Added support for dynamic ordered ECMP group (SAI_NEXT_GROUP_TYPE_DYNAMIC_ORDERED_ECMP)

**Comment by liat-grozovik** [comment]
> Can you please clarify the items below? Thanks
> 
> **SDK/FW:** Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes).
> 
> **SAI:** Added support for dynamic ordered ECMP group (SAI_NEXT_GROUP_TYPE_DYNAMIC_ORDERED_ECMP)

The SAI part is adding support of a SONiC feature called dynamic ordered ECMP. For more details on the feature on SONiC please contact Prince Sunny.

The Fix on the module is a specific module connected to Non Nvidia switches/NICs.

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@prgeor Do you have any concern on this change ?

> Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes).

**Review by prsunny — APPROVED** [review]

**Comment by prgeor** [comment]
> > Can you please clarify the items below? Thanks
> > **SDK/FW:** Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes).
> > **SAI:** Added support for dynamic ordered ECMP group (SAI_NEXT_GROUP_TYPE_DYNAMIC_ORDERED_ECMP)
> 
> The SAI part is adding support of a SONiC feature called dynamic ordered ECMP. For more details on the feature on SONiC please contact Prince Sunny.
> 
> The Fix on the module is a specific module connected to Non Nvidia switches/NICs.

@yxieca @bingwang-ms  does not seems a bug fix ...looks more like feature support

@liat-grozovik we should not change existing link behavior "Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes)."

**Comment by prgeor** [comment]
> @prgeor Do you have any concern on this change ?
> 
> > Using module SPQCELRCDFB when connected to a 3rd party switch, there may either be no link or a very long link up time (~2 minutes).

@bingwang-ms I just realized the above statement in PR description states that the issue is fixed

**Pull request merged**
