### PR TITLE
[service-checker] Fix the service-checker issue which is caused by PR 17836

### PR DESCRIPTION
**Pull request by mlok-nokia**
#### Why I did it
PR https://github.com/sonic-net/sonic-buildimage/pull/17836 added the container checking for database-chassis for Supervisor.  But the related container_feature_dict[] is missing for the database-chassis. This causes the exception failure shows on Supervisor
```
admin@ixre-cpm-chassis13:~$ sudo show system-health sum 
System status summary

  System status LED  red
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: PSU 12 is missing or not available
	     PSU 11 is missing or not available
	     PSU 10 is missing or not available
	     PSU 9 is missing or not available
	     PSU 8 is missing or not available
	     Failed to perform health check for ServiceChecker due to exception - KeyError('database-chassis')

``` 
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added the database-chassis feature entry to container_feature_dict[] to address this issue
 
#### How to verify it
On Supervisor,  execute the "show system-health summary".  No exception error shown
```
admin@ixre-cpm-chassis13:~$ sudo show system-health sum 
System status summary

  System status LED  red
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: PSU 12 is missing or not available
	     PSU 11 is missing or not available
	     PSU 10 is missing or not available
	     PSU 9 is missing or not available
	     PSU 8 is missing or not available
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@judyjoseph @abdosi  OC tested failed on this service checker on MSFT build image .55. Please review this PR. Thanks.

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@mlok-nokia : please create PR for 202305 as their is conflict

**Comment by mlok-nokia** [comment]
@judyjoseph  Are we going to cherry-pick this to 202205 next build?

**Comment by gechiang** [comment]
picked up in 202205-msft repo:
https://github.com/Azure/sonic-buildimage-msft/pull/317

**Comment by gechiang** [comment]
@yxieca , Who can help review/approve this PR for 202311 branch backport?

**Pull request merged**
