### PR TITLE
[ci] Enable sonic-restapi build in PR validation.

### PR DESCRIPTION
**Pull request by liushilongbuaa**
#### Why I did it
Enable sonic-restapi build in two platform to avoid build break on restapi target.
##### Work item tracking
- Microsoft ADO **(number only)**:   26048426

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by xumia — APPROVED** [review]
LGTM

**Comment by liushilongbuaa** [comment]
> @liushilongbuaa cherry pick PR didn't pass PR checker. Please check!!!#19051

Need to wait for PR cherry pick:  https://github.com/sonic-net/sonic-restapi/pull/150

**Pull request merged**
