### PR TITLE
[mux] Integrate `linkmgrd` with swss logger

### PR DESCRIPTION
**Pull request by lolyu**
#### Why I did it
Integrate `linkmgrd` with swss logger.
```
$ swssloglevel -p
...
linkmgrd                      NOTICE
...
```

##### Work item tracking
- Microsoft ADO **(number only)**: 24214621

#### How to verify it
Verified on testbed

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [x] 202205
- [x] master

### CODE REVIEW

**Comment by zjswhhh** [comment]
Hi @lolyu - can you add proper labels to [linkmgrd PR#182](https://github.com/sonic-net/sonic-linkmgrd/pull/182/files) as well. It was only included in 202205.

**Review by zjswhhh — APPROVED** [review]
lgtm.

**Comment by lolyu** [comment]
/azp run

> Hi @lolyu - can you add proper labels to [linkmgrd PR#182](https://github.com/sonic-net/sonic-linkmgrd/pull/182/files) as well. It was only included in 202205.

Good catch, let's enable it for 202205 for now.

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@lolyu can you check the test failures?

**Comment by lolyu** [comment]
Hi @yxieca, the UT passed, please help review again!

**Pull request merged**
