### PR TITLE
Add environs to test PFCWD on DNX

### PR DESCRIPTION
**Pull request by ysmanman**
#### Why I did it

This is required to test DNX specific implementation for PFCWD on VS.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

- Add ASIC_TYPE to force orchagent to run with the given ASIC.
- Add PFC_DLR_INIT_ENABLE to allow test to override PfcDlrInitEnable for VS switch. This is required to test PfcWdAclHandler, instead of PfcWdDlrHandler.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by ysmanman** [comment]
Add @vmittal-msft @arlakshm for visibility.

**Review by arlakshm — APPROVED** [review]

**Review by vmittal-msft — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@prsunny @lguohan Can you please help merge this ?

**Pull request merged**
