### PR TITLE
[202211] Add yang model for scheduler in PORT_QOS_MAP (#16244)

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it

Backport #16244 to 202211

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@ganglyu @dgsudharsan can you please help to approve the PR as of cherry pick conflicts?
@StormLiangMS appreciate if you can merge it

**Review by dgsudharsan — APPROVED** [review]

**Review by ganglyu — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@StormLiangMS can you please help to merge?

**Comment by stephenxs** [comment]
It can cause the following error message when the field is configured
```
2023-08-14.03:38:12.525017|SCHEDULER|port_scheduler|SET|type:STRICT|pir:25000000
2023-08-14.03:38:13.664406|PORT_QOS_MAP|Ethernet124|SET|dscp_to_tc_map:AZURE|pfc_enable:3,4|pfc_to_pg_map:AZURE|pfc_to_queue_map:AZURE|pfcwd_sw_enable:3,4|tc_to_pg_map:AZURE|tc_to_queue_map:AZURE|scheduler:port_scheduler
2023-08-14.03:39:31.630928|PORT_QOS_MAP|Ethernet25|DEL
2023-08-14.03:39:31.897676|QUEUE|Ethernet20|6|DEL
Aug 14 07:03:48.071609 r-panther-13 ERR sonic_yang: Data Loading Failed:All Keys are not parsed in PORT_QOS_MAP#012dict_keys(['Ethernet124'])#012exceptionList:["'scheduler'"]
Aug 14 07:03:48.071835 r-panther-13 ERR ConfigMgmt: Data Loading Failed#012All Keys are not parsed in PORT_QOS_MAP#012dict_keys(['Ethernet124'])#012exceptionList:["'scheduler'"]
```

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by ganglyu** [comment]
> It can cause the following error message when the field is configured
> 
> ```
> 2023-08-14.03:38:12.525017|SCHEDULER|port_scheduler|SET|type:STRICT|pir:25000000
> 2023-08-14.03:38:13.664406|PORT_QOS_MAP|Ethernet124|SET|dscp_to_tc_map:AZURE|pfc_enable:3,4|pfc_to_pg_map:AZURE|pfc_to_queue_map:AZURE|pfcwd_sw_enable:3,4|tc_to_pg_map:AZURE|tc_to_queue_map:AZURE|scheduler:port_scheduler
> 2023-08-14.03:39:31.630928|PORT_QOS_MAP|Ethernet25|DEL
> 2023-08-14.03:39:31.897676|QUEUE|Ethernet20|6|DEL
> Aug 14 07:03:48.071609 r-panther-13 ERR sonic_yang: Data Loading Failed:All Keys are not parsed in PORT_QOS_MAP#012dict_keys(['Ethernet124'])#012exceptionList:["'scheduler'"]
> Aug 14 07:03:48.071835 r-panther-13 ERR ConfigMgmt: Data Loading Failed#012All Keys are not parsed in PORT_QOS_MAP#012dict_keys(['Ethernet124'])#012exceptionList:["'scheduler'"]
> ```

Why do you have scheduler in PORT_QOS_MAP table? If it's from sonic-buildimage repo, can you show me the code?

**Comment by stephenxs** [comment]
> > It can cause the following error message when the field is configured
> > ```
> > 2023-08-14.03:38:12.525017|SCHEDULER|port_scheduler|SET|type:STRICT|pir:25000000
> > 2023-08-14.03:38:13.664406|PORT_QOS_MAP|Ethernet124|SET|dscp_to_tc_map:AZURE|pfc_enable:3,4|pfc_to_pg_map:AZURE|pfc_to_queue_map:AZURE|pfcwd_sw_enable:3,4|tc_to_pg_map:AZURE|tc_to_queue_map:AZURE|scheduler:port_scheduler
> > 2023-08-14.03:39:31.630928|PORT_QOS_MAP|Ethernet25|DEL
> > 2023-08-14.03:39:31.897676|QUEUE|Ethernet20|6|DEL
> > Aug 14 07:03:48.071609 r-panther-13 ERR sonic_yang: Data Loading Failed:All Keys are not parsed in PORT_QOS_MAP#012dict_keys(['Ethernet124'])#012exceptionList:["'scheduler'"]
> > Aug 14 07:03:48.071835 r-panther-13 ERR ConfigMgmt: Data Loading Failed#012All Keys are not parsed in PORT_QOS_MAP#012dict_keys(['Ethernet124'])#012exceptionList:["'scheduler'"]
> > ```
> 
> Why do you have scheduler in PORT_QOS_MAP table? If it's from sonic-buildimage repo, can you show me the code?

This is done in our internal QA test via `redis-cli`.

**Pull request merged**
