### PR TITLE
[Nokia Device] Add Programmability path and dpp_path for Nokia DNX platforms

### PR DESCRIPTION
**Pull request by saksarav-nokia**
#### Why I did it
Added Programmability path and dpp_path for Nokia DNX platforms tow work with latest SAI versions
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added Programmability path and dpp_path for Nokia DNX platforms tow work with latest SAI versions
#### How to verify it
Verified that sonic comes up with SAI 11.X in Nokia platforms

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by saksarav-nokia** [comment]
@arlakshm @judyjoseph could you please review this?

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
compilation error is being fix this PR https://github.com/sonic-net/sonic-buildimage/pull/19882

**Comment by arlakshm** [comment]
@rlhui @lguohan, can you please help merge this PR

**Pull request merged**
