### PR TITLE
[Nokia][sonic-platform] Update Nokia sonic-platform submodule

### PR DESCRIPTION
**Pull request by snider-nokia**
This likely fixes https://github.com/Nokia-ION/ndk/issues/21

#### Why I did it

To fix a failure that results when edge condition results in MDIPC channel being freed with mismatched ownership.

#### How I did it

Properly initialize pid variable for use.

#### How to verify it

Verification involves first causing an edge condition where MDIPC channel ownership becomes ambiguous due to NDK back end failure.  NDK back end must first be killed in order to *potentially* cause this condition under ordinary circumstances.  No python error (or traceback) should occur. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [x] 2022205

#### Description for the changelog

Update Nokia sonic-platform submodule to fix edge condition cleanup path for transceiver module handling subsystem.

### CODE REVIEW

**Comment by snider-nokia** [comment]
@judyjoseph, can you review?

**Review by rlhui — APPROVED** [review]

**Comment by gechiang** [comment]
@yxieca , @StormLiangMS , 
MSFT ADO: 25102947

**Comment by gechiang** [comment]
@snider-nokia Do you intent to address the cherry-pick conflict for this PR for 202211 branch?  If you don't intent to address it, I will remove the request for the 202211 branch.  Please clarify. Thanks!

**Comment by snider-nokia** [comment]
> @snider-nokia Do you intent to address the cherry-pick conflict for this PR for 202211 branch? If you don't intent to address it, I will remove the request for the 202211 branch. Please clarify. Thanks!

We do not plan on requesting merge to 202211 branch, @gechiang.  The box should not have been checked originally (I don't think it was), and if so was accidental.  We are *not* currently working to keep 202211 up to date.  Please remove that request for 202211 merge.  Thanks.

**Comment by gechiang** [comment]
Thanks for replying @snider-nokia .  I will remove the label for 202211 branch.  Ther reason it was marked for 202211 is because whenever we backport a change, we always backport to all subsequent newer releases.  so since this was needed for 202205, we automatically will request the same for all subsequent releases such as 202211, and 202305.  We are ok if no one uses 202211 for chassis and will inform any community member to use 202205 or 202305 or later relases and skip 202211.

**Pull request merged**
