### PR TITLE
[BGP] Fix TCP MD5 authentication problem in VRF

### LINKED ISSUE #19978: [FRR-BGP] BGP session with MD5 authentication in VRF is stuck in Connect state
#### Description

Same as title. We configured mutiple BGP sessions with MD5 authentication across multiple VRF and reloaded the BGP peers. When switches came back online we found all BGP sessions were stuck in Connect state. After deleting all BGP configurations and reconfiguring them via VTYSH, the BGP sessions were successfully established.

#### Steps to reproduce the issue:
1. Configure BGP sessions with MD5 password in multiple VRFs. 
2. Reload switches.
3. Check BGP session status via vtysh

#### Describe the results you received:
[Configs]:
Switch 1:
<pre>
router bgp 65000 vrf Vrf-client-1
 bgp router-id 10.1.0.1
 bgp bestpath as-path multipath-relax
 neighbor 1.1.1.2 remote-as 65030
 neighbor 1.1.1.2 password test1234
 neighbor 1.1.2.2 remote-as 65030
 neighbor 1.1.2.2 password test1234
 neighbor 1.1.3.2 remote-as 65030
 neighbor 1.1.3.2 password test1234
 neighbor 1.1.4.2 remote-as 65030
 neighbor 1.1.4.2 password test1234
 !
 address-family ipv4 unicast
  neighbor 1.1.1.2 soft-reconfiguration inbound
  neighbor 1.1.2.2 soft-reconfiguration inbound
  neighbor 1.1.3.2 soft-reconfiguration inbound
  neighbor 1.1.4.2 soft-reconfiguration inbound
  maximum-paths 64
 exit-address-family
exit
!

router bgp 65000 vrf Vrf-client-2
 bgp router-id 10.1.0.1
 bgp bestpath as-path multipath-relax
 neighbor 1.1.1.2 remote-as 65030
 neighbor 1.1.1.2 password test1234
 neighbor 1.1.2.2 remote-as 65030
 neighbor 1.1.2.2 password test1234
 neighbor 1.1.3.2 remote-as 65030
 neighbor 1.1.3.2 password test1234
 neighbor 1.1.4.2 remote-as 65030
 neighbor 1.1.4.2 password test1234
 !
 address-family ipv4 unicast
  neighbor 1.1.1.2 soft-reconfiguration inbound
  neighbor 1.1.2.2 soft-reconfiguration inbound
  neighbor 1.1.3.2 soft-reconfiguration inbound
  neighbor 1.1.4.2 soft-reconfiguration inbound
  maximum-paths 64
 exit-address-family
exit
!
router bgp 65000 vrf Vrf-client-3
 bgp router-id 10.1.0.1
 bgp bestpath as-path multipath-relax
 neighbor 1.1.1.2 remote-as 65030
 neighbor 1.1.1.2 password test1234
 neighbor 1.1.2.2 remote-as 65030
 neighbor 1.1.2.2 password test1234
 neighbor 1.1.3.2 remote-as 65030
 neighbor 1.1.3.2 password test1234
 neighbor 1.1.4.2 remote-as 65030
 neighbor 1.1.4.2 password test1234
 !
 address-family ipv4 unicast
  neighbor 1.1.1.2 soft-reconfiguration inbound
  neighbor 1.1.2.2 soft-reconfiguration inbound
  neighbor 1.1.3.2 soft-reconfiguration inbound
  neighbor 1.1.4.2 soft-reconfiguration inbound
  maximum-paths 64
 exit-address-family
exit
!

</pre>
Switch 2:
<pre>
router bgp 65030 vrf Vrf-client-1
 bgp router-id 10.1.0.2
 bgp bestpath as-path multipath-relax
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 password test1234
 neighbor 1.1.2.1 remote-as 65000
 neighbor 1.1.2.1 password test1234
 neighbor 1.1.3.1 remote-as 65000
 neighbor 1.1.3.1 password test1234
 neighbor 1.1.4.1 remote-as 65000
 neighbor 1.1.4.1 password test1234
 !
 address-family ipv4 unicast
  neighbor 1.1.1.1 soft-reconfiguration inbound
  neighbor 1.1.2.1 soft-reconfiguration inbound
  neighbor 1.1.3.1 soft-reconfiguration inbound
  neighbor 1.1.4.1 soft-reconfiguration inbound
  maximum-paths 64
 exit-address-family
exit
!

router bgp 65030 vrf Vrf-client-2
 bgp router-id 10.1.0.2
 bgp bestpath as-path multipath-relax
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 password test1234
 neighbor 1.1.2.1 remote-as 65000
 neighbor 1.1.2.1 password test1234
 neighbor 1.1.3.1 remote-as 65000
 neighbor 1.1.3.1 password test1234
 neighbor 1.1.4.1 remote-as 65000
 neighbor 1.1.4.1 password test1234
 !
 address-family ipv4 unicast
  neighbor 1.1.1.1 soft-reconfiguration inbound
  neighbor 1.1.2.1 soft-reconfiguration inbound
  neighbor 1.1.3.1 soft-reconfiguration inbound
  neighbor 1.1.4.1 soft-reconfiguration inbound
  maximum-paths 64
 exit-address-family
exit
!
router bgp 65030 vrf Vrf-client-3
 bgp router-id 10.1.0.2
 bgp bestpath as-path multipath-relax
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 password test1234
 neighbor 1.1.2.1 remote-as 65000
 neighbor 1.1.2.1 password test1234
 neighbor 1.1.3.1 remote-as 65000
 neighbor 1.1.3.1 password test1234
 neighbor 1.1.4.1 remote-as 65000
 neighbor 1.1.4.1 password test1234
 !
 address-family ipv4 unicast
  neighbor 1.1.1.1 soft-reconfiguration inbound
  neighbor 1.1.2.1 soft-reconfiguration inbound
  neighbor 1.1.3.1 soft-reconfiguration inbound
  neighbor 1.1.4.1 soft-reconfiguration inbound
  maximum-paths 64
 exit-address-family
exit
!

</pre>
[Result]:

Switch 1:
<pre>
sonic# show bgp vrf all summary

IPv4 Unicast Summary (VRF Vrf-client-1):
BGP router identifier 10.1.0.1, local AS number 65000 vrf-id 238
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 4, using 2898 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
1.1.1.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.2.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.3.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.4.2         4      65030         0         0        0    0    0    never      Connect        0 N/A

Total number of neighbors 4

IPv4 Unicast Summary (VRF Vrf-client-2):
BGP router identifier 10.1.0.1, local AS number 65000 vrf-id 239
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 4, using 2898 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
1.1.1.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.2.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.3.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.4.2         4      65030         0         0        0    0    0    never      Connect        0 N/A

Total number of neighbors 4

IPv4 Unicast Summary (VRF Vrf-client-3):
BGP router identifier 10.1.0.1, local AS number 65000 vrf-id 240
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 4, using 2898 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
1.1.1.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.2.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.3.2         4      65030         0         0        0    0    0    never      Connect        0 N/A
1.1.4.2         4      65030         0         0        0    0    0    never      Connect        0 N/A

Total number of neighbors 4

</pre>

Switch 2:
<pre>
sonic# show bgp vrf all summary

IPv4 Unicast Summary (VRF Vrf-client-1):
BGP router identifier 10.1.0.2, local AS number 65030 vrf-id 188
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 4, using 2898 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
1.1.1.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.2.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.3.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.4.1         4      65000         0         0        0    0    0    never      Connect        0 N/A

Total number of neighbors 4

IPv4 Unicast Summary (VRF Vrf-client-2):
BGP router identifier 10.1.0.2, local AS number 65030 vrf-id 189
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 4, using 2898 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
1.1.1.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.2.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.3.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.4.1         4      65000         0         0        0    0    0    never      Connect        0 N/A

Total number of neighbors 4

IPv4 Unicast Summary (VRF Vrf-client-3):
BGP router identifier 10.1.0.2, local AS number 65030 vrf-id 191
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 4, using 2898 KiB of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
1.1.1.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.2.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.3.1         4      65000         0         0        0    0    0    never      Connect        0 N/A
1.1.4.1         4      65000         0         0        0    0    0    never      Connect        0 N/A

Total number of neighbors 4

</pre>

#### Describe the results you expected:
BGP sessions should be established successfully.

#### Output of `show version`:

```
admin@sonic:~$ show version

SONiC Software Version: SONiC.master.623703-674a92fb6
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: 674a92fb6
Build date: Tue Aug 20 13:47:49 UTC 2024
Built by: azureuser@68c6be9dc000003

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 01:42:31 up 15:31,  1 user,  load average: 0.08, 0.03, 0.21
Date: Thu 22 Aug 2024 01:42:31

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-macsec                 latest                    1a164c838d2b   347MB
docker-teamd                  latest                    6c8f83240878   344MB
docker-teamd                  master.623703-674a92fb6   6c8f83240878   344MB
docker-sflow                  latest                    78948d770299   346MB
docker-sflow                  master.623703-674a92fb6   78948d770299   346MB
docker-orchagent              latest                    95c797ea9d23   358MB
docker-orchagent              master.623703-674a92fb6   95c797ea9d23   358MB
docker-fpm-frr                latest                    8b55c6f18401   376MB
docker-fpm-frr                master.623703-674a92fb6   8b55c6f18401   376MB
docker-nat                    latest                    ccafa968bf46   347MB
docker-nat                    master.623703-674a92fb6   ccafa968bf46   347MB
docker-syncd-vs               latest                    ada6d08bf055   2.14GB
docker-syncd-vs               master.623703-674a92fb6   ada6d08bf055   2.14GB
docker-gbsyncd-vs             latest                    3d7e69fb4c16   2.14GB
docker-gbsyncd-vs             master.623703-674a92fb6   3d7e69fb4c16   2.14GB
docker-platform-monitor       latest                    e8c7a068a5ac   441MB
docker-platform-monitor       master.623703-674a92fb6   e8c7a068a5ac   441MB
docker-dhcp-relay             latest                    d0f78e61d829   325MB
docker-dash-engine            latest                    7698cab432a2   697MB
docker-dash-engine            master.623703-674a92fb6   7698cab432a2   697MB
docker-eventd                 latest                    0fb35d8e9256   316MB
docker-eventd                 master.623703-674a92fb6   0fb35d8e9256   316MB
docker-sonic-mgmt-framework   latest                    ca9279b301f6   402MB
docker-sonic-mgmt-framework   master.623703-674a92fb6   ca9279b301f6   402MB
docker-snmp                   latest                    238804d1681d   355MB
docker-snmp                   master.623703-674a92fb6   238804d1681d   355MB
docker-router-advertiser      latest                    cba50a11b3a0   316MB
docker-router-advertiser      master.623703-674a92fb6   cba50a11b3a0   316MB
docker-mux                    latest                    ff8abe1373bb   367MB
docker-mux                    master.623703-674a92fb6   ff8abe1373bb   367MB
docker-lldp                   latest                    7cbaa0e95f5c   361MB
docker-lldp                   master.623703-674a92fb6   7cbaa0e95f5c   361MB
docker-sonic-gnmi             latest                    77e66d24d54e   400MB
docker-sonic-gnmi             master.623703-674a92fb6   77e66d24d54e   400MB
docker-database               latest                    f50ecaee5c71   324MB
docker-database               master.623703-674a92fb6   f50ecaee5c71   324MB

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

### PR DESCRIPTION
**Pull request by puffc**
#### Why I did it
Fix #19978 

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Porting bug fix from https://github.com/FRRouting/frr/pull/13084

#### How to verify it
Verify BGP sessions in VRF with MD5 password works as expected.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305
- [x] 202405
#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by puffc** [comment]
@dgsudharsan Can you please help to review this PR?

**Review by dgsudharsan — APPROVED** [review]

**Comment by puffc** [comment]
@lguohan Could you please review and merge this PR?

**Comment by selvatechtalk** [comment]
The reported problem 19978 shows up only after the reboot but not during configurations. So MD5 support is already available in your branch. The mentioned FRR fix is to support MD5. These two are different isn’t?

**Review by kperumalbfn — APPROVED** [review]

**Pull request merged**
