### PR TITLE
[Mellanox] Update SDK/FW/SAI to 4.7.1338/2014.1338/SAIBuild2405.29.0.0

### PR DESCRIPTION
**Pull request by dprital**
#### Why I did it

Update:
* SAI version to SAIBuild2405.29.0.0
* SDK version to 4.7.1338
* FW version to 2014.1338
* SIMX version to 24.7-1154

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Change relevant makefiles

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@bingwang-ms  please handle ms-conflict

**Comment by liat-grozovik** [comment]
@dprital  @moshemos  please check the mellanox failure with prio please.

**Review by bingwang-ms — CHANGES_REQUESTED** [review]
Put a blocker to this PR as there is another PR to update SDK/FW to 4.7.1150/2014.1150

**Comment by moshemos** [comment]
update FW/SDK to newer version

**Pull request closed without merging**
