### PR TITLE
password-hardening: Add support to disable expiration date

### PR DESCRIPTION
**Pull request by davidpil2002**
#### Why I did it
Enhance the feature to support disabling password hardening as Linux support.
-1: expiration will never occur
0: expiration will expired immediately

Opened bug:
https://github.com/sonic-net/sonic-buildimage/issues/17427

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added the -1 value to be supported in hostcfgd and this value will propagate to the relevant Linux files
#### How to verify it
Pls see the details in the bug description that link attached above

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [X] 202205
- [X] 202211
- [X] 202305
- [X] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@davidpil2002 what is the official branch that includes password hardening feature? i dont think 202205 has it. can you confirm?

**Comment by davidpil2002** [comment]
> @davidpil2002 what is the official branch that includes password hardening feature? i dont think 202205 has it. can you confirm?

Hi @liat-grozovik , I see that the feature exists in 202205.

**Comment by liat-grozovik** [comment]
OK. in that case please check that the PR can be cherry picked to the following branches: 202311, 202305 and 202205. If not, please create a PR against each of them and refer to this one for tracking. thanks.

**Review by liat-grozovik — APPROVED** [review]

**Comment by davidpil2002** [comment]
> 202311

checked - this PR can be cherry-pick to 202311, 202305 (no conflict)

**Comment by davidpil2002** [comment]
@liat-grozovik thanks for the merge, 
pls can you merge this one as well:
https://github.com/sonic-net/sonic-host-services/pull/93
is part of the same bug solution

**Comment by dgsudharsan** [comment]
@StormLiangMS Tested on top of 202305 commit https://github.com/sonic-net/sonic-buildimage/commit/690c4c5d367152ab953f947f663002fb87a186bd

**Pull request merged**
