### PR TITLE
Support bulk chunk size in bulk counter polling operation

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it

Added a new field in FLEX_COUNTER_TABLE to represent the bulk chunk size for bulk counter polling.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by ganglyu — APPROVED** [review]

**Review by xincunli-sonic — APPROVED** [review]

**Review by wen587 — APPROVED** [review]
lgtm

**Review by qiluo-msft — APPROVED** [review]

**Comment by kperumalbfn** [comment]
@stephenxs any dependency of this PR with the other sonic-swss and sairedis PRs?

**Comment by stephenxs** [comment]
> @stephenxs any dependency of this PR with the other sonic-swss and sairedis PRs?

No

**Pull request merged**
