### PR TITLE
[BFN] Remove not common entries from pcie yaml configuration

### PR DESCRIPTION
**Pull request by dmytroxIntel**
#### Why I did it
Default pcieutil uses one configuration for all models of platform
#### How I did it
Take the configuration file as base for all models of concrete platform where model-specific devices are not listed in this configuration
#### How to verify it
Run pmon#pcied and verify that there is no error/warning logs on initialization step
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by SavchukRomanLv — APPROVED** [review]

**Review by akokhan — APPROVED** [review]

**Comment by dmytroxIntel** [comment]
@richardyu-ms, @StormLiangMS, please review and merge

**Comment by dmytroxIntel** [comment]
@richardyu-ms, @StormLiangMS, please review and merge

**Comment by dmytroxIntel** [comment]
@richardyu-ms, @StormLiangMS, @lguohan , please review and merge

**Comment by dmytroxIntel** [comment]
@richardyu-ms, @StormLiangMS, @lguohan , please review and merge

**Comment by dmytroxIntel** [comment]
@richardyu-ms, @StormLiangMS, @lguohan , please review and merge

**Comment by dmytroxIntel** [comment]
@richardyu-ms, @StormLiangMS, @lguohan , please review and merge

**Comment by dmytroxIntel** [comment]
@prgeor , please review and merge

**Pull request merged**
