### PR TITLE
[Marvell] Update SAI deb for intel and arm64 arch.

### PR DESCRIPTION
**Pull request by rajkumar38**
#### Why I did it
Add support in SAI debian for, 
- Serdes tuning
- PHY LED config 

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
Compile and load the SAI debian in Marvell SONiC ecosystem. 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by Pavan-Nokia** [comment]
@rajkumar38 can you please trigger the builds. The arm builds were down yesterday

**Review by Pavan-Nokia — APPROVED** [review]

**Comment by Pavan-Nokia** [comment]
@lguohan @yxieca Please help merge

**Comment by yxieca** [comment]
@rajkumar38  is this PR a cherry-pick PR of a master change? Can you share the master branch PR?

**Comment by Pavan-Nokia** [comment]
@yxieca the Marvell SAI version is different for each sonic branch. hence this is not a direct cherry pick.
corresponding SAI update for 2405 and master will follow soon

**Pull request merged**
