### PR TITLE
[Nokia][sonic-platform] Update Nokia sonic-platform submodule - induce NIF port shutdown at ungraceful reboot time

### PR DESCRIPTION
**Pull request by snider-nokia**
These changes provide for the automatic shutdown of NIF ports on LC when an ungraceful reboot scenario occurs.  Reboot and panic notifier hooks are now registered so that callback occurs from the kernel and NIF ports are subsequently shut down.

#### Why I did it

To facilitate the timely movement of traffic away from a crashed LC when its peers recognize that the associated links have gone down.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Linux kernel reboot and panic notifier hooks are used to register a callback routine that, when invoked, stuffs all present transceiver modules into reset.

#### How to verify it

Cause an ungraceful reboot (whether via /usr/sbin/reboot or by causing a kernel panic) and verify that all LC native NIF links are brought down at reboot/panic time (on the way down).  It may be necessary to monitor the LC link peer(s) in order to verify in real-time.

#### Which release branch to backport (provide reason below if selected)

  TBD

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] 202205

#### Description for the changelog

[Nokia][sonic-platform] Update Nokia sonic-platform submodule:  add reboot and panic notifier hooks to induce NIF port shutdown at ungraceful LC reboot time

### CODE REVIEW

**Comment by snider-nokia** [comment]
@judyjoseph, @abdosi, @arlakshm, @deepak-singhal0408,  
Can one (or more) of you guys review please...?

**Review by judyjoseph — APPROVED** [review]
lgtm, verified ports goes down 30+ sec faster

**Comment by judyjoseph** [comment]
@lguohan could you please help merge please.

**Review by judyjoseph — APPROVED** [review]

**Comment by judyjoseph** [comment]
@snider-nokia Had an assosiated question too,  I find multiple hardcoded values while calculating *base and in pci_get_device() -- would like to confirm these are valid in SUP card also and won't cause any other issues.

**Comment by judyjoseph** [comment]
> > @snider-nokia Had an assosiated question too, I find multiple hardcoded values while calculating *base for memory map and in pci_get_device() -- would like to double confirm these are validated in SUP card also and won't cause any other issues.
> 
> Yes, these changes are validated on SUP card, Judy. The particular control device being manipulated on LC is not present on SUP, thus the BAR variable will not be given a value prior to callback registration time. When/if a registered hook is later called back by the kernel there will be no impact except for the "IOCTL BAR is unknown!" message on the console.

Thanks for confirming on validation on SUP. We could follow up in a new PR to fix the "IOCTL BAR is unknown!" error message by checking if it is LC/SUP.

**Comment by gechiang** [comment]
MSFT ADO: 27201281
@StormLiangMS , @yxieca , please approve for 202205, 202305, and 202311 branches for this fix that only impact Nokia Chassis.
Thanks!

**Comment by gechiang** [comment]
@snider-nokia , can you help create a new PR for 202205 branch please.  There is a conflict so it could not be cherry-picked directly to 202205.

**Comment by snider-nokia** [comment]
Ok, new PR for 202205 branch is created here:  https://github.com/sonic-net/sonic-buildimage/pull/18420

**Pull request merged**
