### PR TITLE
Enable iburst option for NTP servers loaded from minigraph

### LINKED ISSUE #19425: NTP configuration no longer has iburst enabled by default
#### Description

On 202305 and older images, NTP servers that were configured in config_db.json had iburst enabled by default. However, with #15058, because iburst was split into a separate configurable option (along with other options being added), and iburst needed to be enabled by default, the iburst option was removed from `ntp.conf`. While there's a way to restore this option when loading a config_db.json file, there's no easy way to do this when loading from minigraph (except for manually adding the option into the generated config_db.json file and either doing a `config reload` or restarting ntp-config and ntp services).

#### Steps to reproduce the issue:
1. Load a 202311, 202405, or master branch image, and load a minigraph.xml file that has an NTP server specified. (The one generated from sonic-mgmt works for this purpose)

#### Describe the results you received:

In `/etc/ntpsec/ntp.conf`, on master branch (only the relevant lines pasted here):

```
server 10.0.0.1
restrict 10.0.0.1 kod limited nomodify noquery

server 10.0.0.2
restrict 10.0.0.2 kod limited nomodify noquery
```

#### Describe the results you expected:

The `server` lines above should have `iburst` at the end.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Relevant section of `config_db.json`:

```
    "NTP_SERVER": {
        "10.0.0.1": {},
        "10.0.0.2": {}
    },
```

### PR DESCRIPTION
**Pull request by saiarcot895**
#### Why I did it

In #15058, the NTP server configuration was modified to add additional options, such as conditionally enabling iburst, specifying the association type, and specifying the NTP version. One side effect of this was that the iburst option which was previously always enabled now requires it to be explicitly enabled in the config_db.

Fixes #19425.

##### Work item tracking
- Microsoft ADO **(number only)**: 28623148

#### How I did it

To restore the old behavior, when loading from minigraph, add `"iburst": "true"` for each NTP server loaded from minigraph.

#### How to verify it

Tested on a KVM setup, verified that the generated `ntp.conf` file had the `iburst` option.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by yxieca — DISMISSED** [review]

**Comment by abdosi** [comment]
@saiarcot895 this should fix : https://github.com/sonic-net/sonic-buildimage/issues/18916.

**Comment by abdosi** [comment]
@anamehra for viz.

**Review by anamehra — APPROVED** [review]

**Comment by saiarcot895** [comment]
On the contrary, this won't truly fix #18916. This PR just hardcodes the `'iburst': 'on'` option for NTP servers loaded from minigraph, restoring the old behavior. For #18916 to be actually fixed, there needs to be new CLI options to enable/disable iburst.

**Comment by saiarcot895** [comment]
@fastiuk FYI

**Pull request merged**
