### PR TITLE
[202211][Mellanox] Update SAI version to SAIBuild2211.25.1.6

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
#### Why I did it
To include latest fixes

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Update SAI version to SAIBuild2211.25.1.6

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by keboliu** [comment]
@volodymyrsamotiy  SAI binary has been uploaded, would you please retrigger the test?

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
