### PR TITLE
[as5835-54x] Add to support PDDF

### PR DESCRIPTION
**Pull request by jostar-yang**
Signed-off-by: Jostar Yang <jostar_yang@accton.com.tw>

#### Why I did it
Add to support PDDF
#### How I did it
Implement code
#### How to verify it
Test pddf cmd and sensors cmd.

root@sonic:~# sensors

lm75-i2c-27-4c
Adapter: i2c-2-mux (chan_id 1)
temp1:        +29.0 C  (high = +84.0 C, hyst = +75.0 C)

psu_pmbus-i2c-12-5b
Adapter: i2c-2-mux (chan_id 2)
in3:          +0.00 V
fan1:         200 RPM
power2:        0.00 W
curr2:        +0.00 A

psu_pmbus-i2c-11-58
Adapter: i2c-2-mux (chan_id 1)
in3:         +11.92 V
fan1:        3000 RPM
power2:       90.00 W
curr2:        +7.34 A

acpitz-virtual-0
Adapter: Virtual device
temp1:         +0.0 C  (crit = +91.0 C)

fan_ctrl-i2c-3-63
Adapter: i2c-1-mux (chan_id 1)
fan1:        11700 RPM
fan2:        9900 RPM
fan3:        11700 RPM
fan4:        9900 RPM
fan5:        11700 RPM
fan6:        9900 RPM
fan7:        11700 RPM
fan8:        9750 RPM
fan9:        11700 RPM
fan10:       9900 RPM

lm75-i2c-28-49
Adapter: i2c-2-mux (chan_id 2)
temp1:        +27.5 C  (high = +83.0 C, hyst = +75.0 C)

lm75-i2c-26-4b
Adapter: i2c-2-mux (chan_id 0)
temp1:        +34.0 C  (high = +85.0 C, hyst = +75.0 C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +40.0 C  (high = +71.0 C, crit = +91.0 C)
Core 2:         +38.0 C  (high = +71.0 C, crit = +91.0 C)
Core 6:         +36.0 C  (high = +71.0 C, crit = +91.0 C)
Core 8:         +39.0 C  (high = +71.0 C, crit = +91.0 C)
Core 12:        +37.0 C  (high = +71.0 C, crit = +91.0 C)

lm75-i2c-29-4a
Adapter: i2c-2-mux (chan_id 3)
temp1:        +28.0 C  (high = +82.0 C, hyst = +75.0 C)

root@sonic:/home/admin# pddf_psuutil seninfo
PSU1 is OK
Output Voltage: 11906.0 mv
Output Current: 7671.0 ma
Output Power: 97000.0 mw
Fan1 Speed: 3000 rpm

PSU2 is Not OK

root@sonic:/home/admin#
root@sonic:/home/admin# pddf_psuutil mfrinfo
PSU1 is OK
Manufacture Id: 3Y POWER
Model: YM-1401A
Serial Number: SA060V061911000339
Fan Direction: Exhaust

PSU2 is Not OK

root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# pddf_psuutil status
PSU    Status
-----  --------
PSU1   OK
PSU2   NOT OK
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# pddf_fanutil status
FAN         Status
----------  --------
Fantray1_1  OK
Fantray1_2  OK
Fantray2_1  OK
Fantray2_2  OK
Fantray3_1  OK
Fantray3_2  OK
Fantray4_1  OK
Fantray4_2  OK
Fantray5_1  OK
Fantray5_2  OK
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

### CODE REVIEW

**Review by FuzailBrcm — DISMISSED** [review]

**Review by FuzailBrcm — APPROVED** [review]

**Review by FuzailBrcm — DISMISSED** [review]
Changes are fine

**Comment by lguohan** [comment]
can you help to resolve the conflict?

**Comment by jostar-yang** [comment]
Close the PR due to there is  esayCLA issue. It can't fix. So create new PR and add new feature to https://github.com/sonic-net/sonic-buildimage/pull/13700.

**Pull request closed without merging**
