### PR TITLE
Add new HwSKUs for Arista-7060dx5-32

### PR DESCRIPTION
**Pull request by bobbymcgonigle**
#### Why I did it
New desired configurations on this Arista SKU

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added the hwsku folders with the necessary files to populate config_db

#### How to verify it
change default sku and generate a new config_db.json

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305
- [x] 202311

#### Tested branch (Please provide the tested image version)
- [x] 202305

### CODE REVIEW

**Review by zhenggen-xu — COMMENTED** [review]
Can you add buffer/qos config files similar to [Arista-7060DX5-32](https://github.com/sonic-net/sonic-buildimage/tree/master/device/arista/x86_64-arista_7060dx5_32/Arista-7060DX5-32) to the new HWKSUs?

**Review by zhenggen-xu — COMMENTED** [review]
Is it possible to use the same th4XXX.bcm file for both HWSKUs?  We should make the bcm file agnostic to HWSKUs, and let SONiC SAI APIs to add/delete ports during the initialization, this will make future HWSKU creation straightforward.

**Comment by bobbymcgonigle** [comment]
> Is it possible to use the same th4XXX.bcm file for both HWSKUs? We should make the bcm file agnostic to HWSKUs, and let SONiC SAI APIs to add/delete ports during the initialization, this will make future HWSKU creation straightforward.

Unfortunatly this is not available in 202305 (where we would like this to go) due to CSP case CS00012347969. This is fixed in SAI 9. 

Until 202305 moves to that SAI version we cannot support the single bcm file.

> Can you add buffer/qos config files similar to [Arista-7060DX5-32](https://github.com/sonic-net/sonic-buildimage/tree/master/device/arista/x86_64-arista_7060dx5_32/Arista-7060DX5-32) to the new HWKSUs?

We are planning to do this in a seperate PR. For now we would like to get these hwsku's merged to unblock testing with these front panel configurations.

**Review by zhenggen-xu — APPROVED** [review]
LGTM.

**Pull request closed without merging**
