### PR TITLE
Add buffers_defaults_t1 for Arista-7260CX3-D108C8

### PR DESCRIPTION
**Pull request by andywongarista**
#### Why I did it
Add symlink so that config-setup passes

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@prsunny , can you take a look at this one?

**Review by prsunny — APPROVED** [review]
lgtm. @neethajohn

**Comment by bingwang-ms** [comment]
@andywongarista Please file a direct PR to 2022405 to address the conflict.

**Comment by bingwang-ms** [comment]
@andywongarista Please file a direct PR to 2022405 to address the conflict.

**Comment by andywongarista** [comment]
> @andywongarista Please file a direct PR to 2022405 to address the conflict.

This PR is already in 202405 (it was already in master when 202405 branched off).

**Pull request merged**
