### PR TITLE
merge common config files from broadcom sonic

### PR DESCRIPTION
**Pull request by geans-pin**
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by adyeung** [comment]
@ZhaohuiS please help review

**Review by anilkpan — APPROVED** [review]

**Pull request merged**
