### PR TITLE
Update fabric monitor data with forceUnisolateSt

### PR DESCRIPTION
**Pull request by jfeng-arista**
#### Why I did it
Update fabric monitoring data in config_db to have forceUnisolateStatus attribute. So users can unisolate the fabric links if needed

Also add the fabric monitoring data for 2 more sku

The updated HLD PR is at https://github.com/sonic-net/SONiC/pull/1656

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by jfeng-arista** [comment]
@vmittal-msft @arlakshm

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@lguohan, can you help approve this PR

**Comment by lguohan** [comment]
where can i find the design doc for this one? in the pr description, it is better to link to the design doc.

**Comment by jfeng-arista** [comment]
> @jfeng-arista , where can i find the design doc for this one? in the pr description, it is better to link to the design doc.

udpated

**Review by vmittal-msft — APPROVED** [review]

**Pull request merged**
