### PR TITLE
[Arista] Add other chassis names to platform_components.json for 720DT-48S

### PR DESCRIPTION
**Pull request by andywongarista**
#### Why I did it
The 720DT-48S platform has variants with different chassis names, and these need to all be included in platform_components.json to ensure that sonic-mgmt platform_tests/fwutil/test_fwutil.py::test_fwutil_show passes

#### How I did it
Updated platform_components.json with the variant names for 720DT-48S.

#### How to verify it
Ran aforementioned testcase and verified that it passes on the different variants.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Comment by andywongarista** [comment]
@Blueve can you help me rerun the checks?

**Comment by Blueve** [comment]
@andywongarista I don't have permission to execute `/azp` as well. As PR owner, you can use: `/azpw run Azure.sonic-buildimage` to rerun ;)

**Comment by andywongarista** [comment]
@Blueve can you review? I think this should be good to merge.

**Review by Blueve — APPROVED** [review]

**Review by yxieca — APPROVED** [review]

**Pull request merged**
