### PR TITLE
Add fix for deserializing XSUB/XPUB subscription message

### PR DESCRIPTION
**Pull request by zbud-msft**
##### Work item tracking
- Microsoft ADO **(number only)**:24851367

#### How I did it

Read subscription message when capture service starts, before reading cached events.

#### How to verify it

UT/Manual testing

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by renukamanavalan — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@zbud-msft have you tested this with 202305?

**Comment by zbud-msft** [comment]
> @zbud-msft have you tested this with 202305?

Tested on earlier version SONiC.202211.387828-29926587b

**Comment by StormLiangMS** [comment]
@zbud-msft pls also test with 202305 image to avoid regression.

**Comment by zbud-msft** [comment]
> @zbud-msft pls also test with 202305 image to avoid regression.

Tested, eventd deserialize error is gone

**Pull request merged**
