### PR TITLE
[devices] add read_eeprom for celestica e1031

### PR DESCRIPTION
**Pull request by Xichen96**
Add a new read_eeprom method for celestica e1031 devices.

#### Why I did it
read_eeprom not implemented will result in xcvrd not able to start.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add method read_eeprom

#### How to verify it
Build image and check xcvrd is fine.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

Implement read_eeprom for celestica e1031

### CODE REVIEW

**Review by lizhijianrd — APPROVED** [review]

**Comment by prgeor** [comment]
@Xichen96 please attach the output of 
1. `sfputil show eeprom-hexdump -p EthernetXX`
2. `sfputil show eeprom -d -p Ethernet0`

**Review by prgeor — APPROVED** [review]

**Comment by Xichen96** [comment]
> @Xichen96 please attach the output of
> 
> 1. `sfputil show eeprom-hexdump -p EthernetXX`
> 2. `sfputil show eeprom -d -p Ethernet0`

@prgeor 
admin@bjw-can-e1031-1:~$ sudo sfputil show eeprom-hexdump -p Ethernet1
SFP EEPROM not detected
admin@bjw-can-e1031-1:~$ sudo sfputil show eeprom -d -p Ethernet0
Ethernet0: SFP EEPROM not detected

**Comment by Xichen96** [comment]
> @Xichen96 please attach the output of
> 
> 1. `sfputil show eeprom-hexdump -p EthernetXX`
> 2. `sfputil show eeprom -d -p Ethernet0`

@prgeor 
Ethernet48: SFP EEPROM detected
        Application Advertisement: N/A
        Connector: CopperPigtail
        Encoding: Unspecified
        Extended Identifier: GBIC/SFP defined by twowire interface ID
        Extended RateSelect Compliance: Unspecified
        Identifier: SFP/SFP+/SFP28
        LengthOM3(UnitsOf10m): 0
        Nominal Bit Rate(100Mbs): 103
        Specification compliance:
                InfinibandComplianceCode: 1X Copper Passive
                SFP+CableTechnology: Passive Cable
        Vendor Date Code(YYYY-MM-DD Lot): 2022-11-11
        Vendor Name: FS
        Vendor OUI: 64-9d-99
        Vendor PN: Q-4SPC02
        Vendor Rev: A
        Vendor SN: C2211157475-1
        MonitorData:
        ThresholdData:


Result of Ethernet48 seems fine

**Comment by lizhijianrd** [comment]
Close this PR and use #18495 instead.

**Pull request closed without merging**
