### PR TITLE
Update sonic-sairedis submodule

### PR DESCRIPTION
**Pull request by tbgowda**
#### Why I did it

Bringing in changes to support SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL

Bringing in the following changes:

Submodule src/sonic-sairedis d5866a3dc..f484cf935:
  > Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL attribute (https://github.com/Azure/sonic-sairedis/pull/975)
  > Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL attribute (https://github.com/Azure/sonic-sairedis/pull/975)
  > [pipeline] Download swss common artifact in a separated directory (https://github.com/Azure/sonic-sairedis/pull/995)
  > Change sonic-buildimage.vs artifact source from CI build to official build. (https://github.com/Azure/sonic-sairedis/pull/992)

#### How I did it

Please refer to 
https://github.com/Azure/sonic-sairedis/pull/975
https://github.com/Azure/sonic-buildimage/pull/9419

#### How to verify it

Please refer to 
https://github.com/Azure/sonic-sairedis/pull/975
https://github.com/Azure/sonic-buildimage/pull/9419

#### Which release branch to backport (provide reason below if selected)

Ideally it is preferred we back port to all branches where fast-reboot is supported. However, 202012 seems like a critical release train.

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

#### Description for the changelog

Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL in case of fast-reboot

### CODE REVIEW

**Comment by yxieca** [comment]
@tbgowda  please list the commits that are included by this submodule head change

**Comment by tbgowda** [comment]
@yxieca , I have updated the description with the commits. Please let me know if anything more needs to be updated.

**Comment by tbgowda** [comment]
I am little confused here, https://github.com/Azure/sonic-sairedis/pull/975 was committed to sonic-sairedis master branch. But we need that commit in 202012 as well. 

Should there be a double commit of https://github.com/Azure/sonic-sairedis/pull/975 to sonic-sairedis 202012 branch and a new PR generated for sonic-buildimage 202012 branch to update the sonic-sairedis submodule?

**Review by yxieca — APPROVED** [review]

**Comment by sachinv-msft** [comment]
@yxieca can we add the request for 202012 branch!

**Comment by prsunny** [comment]
> @yxieca can we add the request for 202012 branch!

@sachinv-msft , submodule-update must be raised separately to corresponding branch

**Pull request closed without merging**
