### PR TITLE
Remove depot_tools repo

### LINKED ISSUE #16087: [202305] Build failure on latest 202305 in target sonic-p4rt_0.0.1_amd64.deb
#### Description

Observed on hash b226ae0699b45808364863a137d27de353cff3ee.

#### Steps to reproduce the issue:
1. git clone -b 202305 git@github.com:azure/sonic-buildimage
2. cd sonic-buildimage
3. make init
4. make configure PLATFORM=mellanox
5. make target/sonic-mellanox.bin

#### Describe the results you received:

```
[ FAIL LOG START ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
Build start time: Wed Aug 9 15:31:30 UTC 2023
[ REASON ] :      target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb does not exist   NON-EXISTENT PREREQUISITES: target/debs/bullseye/libswsscommon-dev_1.0.0_amd64.deb-install
[ FLAGS  FILE    ] : [mellanox amd64 bullseye bullseye]
[ FLAGS  DEPENDS ] : [mellanox amd64 bullseye bullseye]
[ FLAGS  DIFF    ] : []
make[1]: warning: -j12 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/sonic/src/sonic-p4rt'
function cleanup {
# Note: make seems to hang if Bazel is still running
cd /sonic/src/sonic-p4rt/sonic-pins && bazel  shutdown
}
trap cleanup EXIT
pushd ./sonic-pins
bazel  build --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app:p4rt_deb //p4rt_app:p4rt_dbg_deb
bazel  test --fission=yes --features=per_object_debug_info --override_repository=sonic_swss_common=/sonic/src/sonic-swss-common -c opt //p4rt_app/...
cd ./bazel-bin/p4rt_app
mv sonic-p4rt_0.0.1_amd64.deb sonic-p4rt-dbgsym_0.0.1_amd64.deb /sonic/target/debs/bullseye/
popd
/sonic/src/sonic-p4rt/sonic-pins /sonic/src/sonic-p4rt
/usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
/usr/share/depot_tools/vpython3: line 48: /usr/share/depot_tools/.cipd_bin/vpython3: No such file or directory
make[1]: *** [Makefile:34: /sonic/target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb] Error 127
make[1]: Leaving directory '/sonic/src/sonic-p4rt'
[  FAIL LOG END  ] [ target/debs/bullseye/sonic-p4rt_0.0.1_amd64.deb ]
[ 01 ] [ target/docker-config-engine-bullseye.gz ]
[ 02 ] [ target/python-wheels/bullseye/sonic_platform_common-1.0-py3-none-any.whl ]
Makefile.work:602: recipe for target 'target/sonic-mellanox.bin' failed
make[1]: *** [target/sonic-mellanox.bin] Error 2
make[1]: Leaving directory '/builds2/stepanb/202305/sonic-buildimage'
Makefile:39: recipe for target 'target/sonic-mellanox.bin' failed
make: *** [target/sonic-mellanox.bin] Error 2
```

#### Describe the results you expected:

Successful build

#### Output of `show version`:
N/A
#### Output of `show techsupport`:
N/A

### PR DESCRIPTION
**Pull request by saiarcot895**
#### Why I did it

It appears that this was initially added to provide the `git-retry` command (which doesn't appear to be used today). However, this repo is now also providing `bazel` (which is actually used in our build today), and this command (along with `git-retry`) expects some `vpython3` binary to be set up/installed. The sonic-p4rt code runs `bazel`, which means this depot_tools version would get called instead of the regular system-installed version.

Rather than going through the process of setting up/installing vpython3, just get rid of this repo.

Fixes #16087.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Review by liushilongbuaa — APPROVED** [review]
LGTM.
Root cause is code change in depot_tools repo.
Daily build succeeded because we pined repo HEAD: https://github.com/sonic-net/sonic-buildimage/blob/34bad344955541fe560946a545af793172b7451a/files/build/versions/default/versions-git#L1

**Comment by jusherma** [comment]
We're still seeing this issue on 202305. Can you please get this double committed? @qiluo-msft @lguohan

**Comment by StormLiangMS** [comment]
@saiarcot895 do we have an ADO?

**Comment by saiarcot895** [comment]
@StormLiangMS Updated PR description with the ADO number, and ADO for backport to 202305 is 25059425.

**Pull request merged**
