### PR TITLE
Fix content of platform.json for DCS-7050CX3-32S

### PR DESCRIPTION
**Pull request by andywongarista**
#### Why I did it
Some tests under platform_tests/api were failing on the 7050CX3 due to outdated facts in platform.json

#### How I did it
Updated platform.json facts with appropriate values

#### How to verify it
Run tests under platform_tests/api to verify no failures

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@qiluo-msft Cherry-picking #12082

**Review by qiluo-msft — APPROVED** [review]

**Comment by liuh-80** [comment]
@andywongarista , please merge this PR and add 'Included in 202012 Branch' label to original PR https://github.com/sonic-net/sonic-buildimage/pull/12082

**Comment by prgeor** [comment]
@qiluo-msft please merge

**Pull request merged**
