### PR TITLE
202305 platform DCS-7060DX5-64S misc update

### PR DESCRIPTION
**Pull request by vincentpcng**
#### Why I did it
This is to add  the HWSK DCS-7060DX5-64S misc update. This PR is for the commit to the 202305 only at this moment because it will be our initial release branch, later branch and master will be PR separately.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Adding additional profile files  like qos, buffer profiles, etc needed for the HWSKU.

#### How to verify it
we have verified it with sonic mgmt test in house.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@Staphylo , can you provide sign off on this PR?

**Review by Staphylo — APPROVED** [review]
@lguohan yes this looks good and has been tested internally

**Comment by vincentpcng** [comment]
The build keep fail with the following error ...
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
2024-07-16T02:55:14.2727722Z See 'docker run --help'.

Can someone help take a look and share some clues ?

Thanks !

**Pull request closed without merging**
