### PR TITLE
Install ptf afpacket module required by ptf_nn_agent.

### PR DESCRIPTION
**Pull request by ysmanman**
#### Why I did it
ptf_nn_agent failed to start in dnx rpc syncd because module afpacket was not installed.
Please see issue https://github.com/sonic-net/sonic-mgmt/issues/7822

#### How I did it
Add  downloading ptf afpacket module in docker file.

#### How to verify it
Verified that ptf_nn_agent was started successfully in dnx rpc syncd with the change.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ x] 202205
- [ ] 202211

### CODE REVIEW

**Comment by arlakshm** [comment]
I am curious why this change is not required on other platforms. @abdosi @bingwang-ms can you look at this change

**Comment by ysmanman** [comment]
> I am curious why this change is not required on other platforms. @abdosi @bingwang-ms can you look at this change

copp test does not use swap_syncd by default  https://github.com/sonic-net/sonic-mgmt/blob/708ffc3ac7dd6fd08beacd5dac71e287eec6856f/tests/copp/conftest.py#L14. This is probably why the change is not required by other platforms.

**Review by arlakshm — APPROVED** [review]

**Comment by kenneth-arista** [comment]
To add more context. This fix is needed for multi-ASIC copp tests.

**Comment by kenneth-arista** [comment]
Gentle bump. Can we merge this PR?

**Pull request merged**
