### PR TITLE
Generate FEC configuration settings for 400G and 200G speed via minigraph

### PR DESCRIPTION
**Pull request by vdahiya12**
#### Why I did it

This change introduces support for handling new port speeds (200G and 400G) in the SONiC  configuration engine. Specifically, it ensures that when a port's speed is set to 200,000 Mbps (200G) or 400,000 Mbps (400G) and the Forward Error Correction (FEC) setting is not specified, it defaults to "RS" (Reed-Solomon) FEC.

- Added logic to set the FEC to "RS" when the port speed is either 200G or 400G if FEC is not already specified.
Unit Tests (test_cfggen.py):

- Introduced new test case to verify the configuration of 200G ports on Mellanox 4700 devices. These tests ensure that ports configured with 200G speeds correctly default to "RS" FEC, and other port settings such as autoneg  are handled as expected.
Sample configuration files for Mellanox 4700 devices were added to the test suite to validate these changes.

##### Work item tracking
- Microsoft ADO **(number only)**:
- 29240286

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by prgeor** [comment]
@vdahiya12 title seems to suggest this is specific to Mellanox which I think is NOT

**Comment by lguohan** [comment]
@qiluo-msft , can we go this with config db?

**Comment by lguohan** [comment]
no more minigraph change

**Review by dgsudharsan — APPROVED** [review]

**Review by qiluo-msft — CHANGES_REQUESTED** [review]
Talked with @vdahiya12 , we may need to abandon this PR and seek other config_db.json generation method.

**Comment by prgeor** [comment]
@vdahiya12 @lguohan closing as minigraph not used

**Pull request closed without merging**
