### PR TITLE
Fix ecmp hash polarization by enable hash seed/offset config on Broadcom T1

### PR DESCRIPTION
**Pull request by Gfrom2016**
#### Why I did it
To fix ecmp hash polarization issue on 202311 image.
##### Work item tracking
- Microsoft ADO **(number only)**: 28601762

#### How I did it
Braodcom's fix for ecmp hash polarization has been included in 10.1.4.0 in #18044 
Cherry-pick image fix from #17505 
Add sai_hash_seed_config_hash_offset_enable=1 in all config.bcm that Broadcom T1 uses.

| HardwareSku |
|--|
|Force10-S6100-T1|
Force10-S6100-ITPAC-T1
Force10-S6100
Celestica-DX010-C32
Arista-7260CX3-C64
Arista-7060CX-32S-Q32
Arista-7060CX-32S-C32-T1
Arista-7060CX-32S-C32
Arista-7050QX32S-Q32
Arista-7050QX-32S-S4Q31
Arista-7050-QX32
Arista-7050-QX-32S
#### How to verify it
Run ecmp/test_ecmp_sai_values.py on 7260 T1 DUT and passed.
https://dev.azure.com/mssonic/internal/_build/results?buildId=586225&view=results

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @yxieca @kperumalbfn could you help to review?

**Comment by StormLiangMS** [comment]
hi @Gfrom2016 do we have ADO to track this one?

**Comment by Gfrom2016** [comment]
@StormLiangMS ADO: https://msazure.visualstudio.com/One/_workitems/edit/28601762

**Comment by yxieca** [comment]
@Gfrom2016  why are we trying to cherry-pick a change from 202311 to 202405? If the change is needed in both branches but not the master, can you oepn a separate PR for 202405 branch? Thanks!

**Comment by kperumalbfn** [comment]
@Gfrom2016 Why do we need this change in addition to 

https://github.com/sonic-net/sonic-buildimage/pull/18912

Thanks,

**Comment by Gfrom2016** [comment]
> @Gfrom2016 why are we trying to cherry-pick a change from 202311 to 202405? If the change is needed in both branches but not the master, can you oepn a separate PR for 202405 branch? Thanks!

Sure, will do.

**Comment by yxieca** [comment]
@Gfrom2016  is this change still needed?

**Comment by Gfrom2016** [comment]
> @Gfrom2016 is this change still needed?

We don't it anymore, I'll close it.

**Pull request closed without merging**
