### PR TITLE
Python logger enhancement to support setting log level at real time

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
HLD: https://github.com/sonic-net/SONiC/pull/1522
Depends on https://github.com/sonic-net/sonic-buildimage/pull/17171

#### Why I did it

Python logger does not setting log level at real time, this PR is aimed to enhance it.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Use swsscommon.Logger as a internal logger of `sonic_py_common.logger.Logger`

#### How to verify it

unit test
manual test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Working on the checker failure, need reproduce locally.

**Review by prgeor — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@prgeor your approval to this PR got lost. Can you please signoff ?

**Comment by Junchao-Mellanox** [comment]
Will open another one. Closing this one.

**Pull request closed without merging**
