### PR TITLE
[ci] Remove marvell-armhf and vsonic test from PR checker

### PR DESCRIPTION
**Pull request by liushilongbuaa**
#### Why I did it
make marvell-armhf and vsonic test as config to unblock new features.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Review by Pterosaur — APPROVED** [review]

**Comment by saiarcot895** [comment]
@liushilongbuaa  Can I ask what those new features are that break the t0-sonic checker?

**Comment by Pterosaur** [comment]
> @liushilongbuaa Can I ask what those new features are that break the t0-sonic checker?

Type 7 for MACsec. The t0-sonic might be re-enabled once the PR: https://github.com/sonic-net/sonic-mgmt/pull/9812 merged.

**Comment by saiarcot895** [comment]
Is it possible to instead disable just the macsec test case, instead of the whole test suite? I would like the warm reboot test to still run in t0-sonic.

**Comment by Pterosaur** [comment]
> Is it possible to instead disable just the macsec test case, instead of the whole test suite? I would like the warm reboot test to still run in t0-sonic.

I thought there was only macsec test in t0-sonic. That's my mistake.

**Pull request closed without merging**
