### PR TITLE
[Mellanox] Fix issue: watchdogutil command does not work

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

watchdogutil uses platform API watchdog instance to control/query watchdog status. In Nvidia watchdog status, it caches "armed" status in a object member "WatchdogImplBase.armed". This is not working for CLI infrastructure because each CLI will create a new watchdog instance, the status cached in previous instance will totally lose. Consider following commands:

```
admin@sonic:~$ sudo watchdogutil arm -s 100      =====> watchdog instance1, armed=True
Watchdog armed for 100 seconds
admin@sonic:~$ sudo watchdogutil status             ======> watchdog instance2, armed=False
Status: Unarmed
admin@sonic:~$ sudo watchdogutil disarm            =======> watchdog instance3, armed=False
Failed to disarm Watchdog
```

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Use sysfs to query watchdog status

#### How to verify it

Manual test
Unit test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [x] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik , could you please help merge this? Thanks!

**Review by liat-grozovik — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
PR for 202211: https://github.com/sonic-net/sonic-buildimage/pull/16242

**Comment by yxieca** [comment]
@Junchao-Mellanox there is conflict. please help create 202205 PR. Thanks!

**Comment by Junchao-Mellanox** [comment]
PR for 202205: https://github.com/sonic-net/sonic-buildimage/pull/16260

**Pull request merged**
