### PR TITLE
Update Brcm SAI for DNX platforms

### PR DESCRIPTION
**Pull request by judyjoseph**
#### Why I did it
Update the Brcm SAI 7.0 with following fixes 

Offical Brcm SDK fix for memory leak
(CS00012315073 [7.0][J2C+] : PFCWD counter polling causing continuous mem leak on production device)

Official Brcm fix for CPU high
(CS00012317195 High CPU due to SDK calling soc_dnxc_port_resource_get for few stats counters even with bcmCNTR thread)

Offical Brcm SAI fix for getting voq counters working.
CSP CS00012319503: DNX SAI 7.1.60.4 has broken Voq counters support

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Created a new SAI debian package

#### How to verify it

Validated by running the nightly pipeline on a chassis platform.

```
Validated that the voq counters, by sensind traffic from T1 VM --> T3 VM 

                              Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
----------------------------------  -----  --------------  ---------------  -----------  ------------
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ0               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ1              27             1968            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ2               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ3               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ4               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ5               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ6               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet48   VOQ7               0                0            0             0
 
                              Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
----------------------------------  -----  --------------  ---------------  -----------  ------------
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ0               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ1            7099           625680            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ2               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ3               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ4               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ5               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ6               0                0            0             0
svcstr-xxxx-lc1-1|asic0|Ethernet56   VOQ7               0                0            0             0

---------------

The CPU usage has come down in SUP

System 'xxxx-sup-1'
  status                       Running
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  load average                 [7.94] [8.70] [7.54]
  cpu                          2.6%us 45.0%sy 0.0%wa     <<<<-- it is 45%
  memory usage                 8.9 GB [28.6%]
  swap usage                   0 B [0.0%]
  uptime                       21m
  boot time                    Fri, 17 Nov 2023 21:55:55
  data collected               Fri, 17 Nov 2023 22:16:59

-------------

syncd memory usage no increasing.

```

### CODE REVIEW

**Comment by gechiang** [comment]
first PR test build for BRCM failed due to the new SAI was not yet uploaded to the storage account.  reran the failed build job... again...

**Comment by judyjoseph** [comment]
Looks like there is some change in the location where bcm debian is stored. The build is failing with this error 
```
target/debs/bullseye/libsaibcm_dnx_7.1.66.4_amd64.deb does not exist 
```
The image seems not present here - 
```
https://sonicstorage.blob.core.windows.net/public/sai/bcmsai/$(LIBSAIBCM_DNX_BRANCH_NAME)/$(LIBSAIBCM_DNX_VERSION)
```
will check more on this.

**Comment by gechiang** [comment]
@xumia , looks like the new built SAI 7.1.66.4 went into this directory:
public/sai/sai-broadcom/...
Can you help take a look what is going on?  this is automated and why it did not go into the correct storage path?

**Comment by xumia** [comment]
> @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?

Is the result correct?
https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
```
6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
```

**Comment by judyjoseph** [comment]
> > @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?
> 
> Is the result correct? https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
> 
> ```
> 6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
> ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
> ```

It is ok now, I see the images in sai/bcmsai/REL_7.0_202205/7.1.66.4 which is what we are still following for 202205 

> > @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?
> 
> Is the result correct? https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
> 
> ```
> 6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
> ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
> ```

It is fine now, I see saibcm deb images in sai/bcmsai/REL_7.0_202205/7.1.66.4 which is were we expect images for 202205 release.

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
> > > @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?
> > 
> > 
> > Is the result correct? https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
> > ```
> > 6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
> > ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
> > ```
> 
> It is ok now, I see the images in sai/bcmsai/REL_7.0_202205/7.1.66.4 which is what we are still following for 202205
> 
> > > @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?
> > 
> > 
> > Is the result correct? https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
> > ```
> > 6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
> > ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
> > ```
> 
> It is fine now, I see saibcm deb images in sai/bcmsai/REL_7.0_202205/7.1.66.4 which is were we expect images for 202205 release.

@xumia , is this due to some delay by the automation to copy over to the correct Storage path?  how do we check this and avoid this next time?  should we not raise this PR right away and wait for the automation to put the SAI debian to the correct Storage path first?

**Comment by xumia** [comment]
> > > > @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?
> > > 
> > > 
> > > Is the result correct? https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
> > > ```
> > > 6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
> > > ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
> > > ```
> > 
> > 
> > It is ok now, I see the images in sai/bcmsai/REL_7.0_202205/7.1.66.4 which is what we are still following for 202205
> > > > @xumia , looks like the new built SAI 7.1.66.4 went into this directory: public/sai/sai-broadcom/... Can you help take a look what is going on? this is automated and why it did not go into the correct storage path?
> > > 
> > > 
> > > Is the result correct? https://sonicstorage.blob.core.windows.net/public/sai/sai-broadcom/SAI_7.1.0_GA/7.1.66.4/sha256
> > > ```
> > > 6a48ec83b4bc0621fff9472be5473e86f81e2250708f683093166bda076cd1f0  ./xgs/libsaibcm-dev_7.1.66.4_amd64.deb
> > > ea1abc2afdad8016fc04b2d0d2465fad0afc2726befe7a918abe11ff360b0eaf  ./xgs/libsaibcm-modules-5.10.0-12-2-amd64_7.1.66.4_amd64.deb
> > > ```
> > 
> > 
> > It is fine now, I see saibcm deb images in sai/bcmsai/REL_7.0_202205/7.1.66.4 which is were we expect images for 202205 release.
> 
> @xumia , is this due to some delay by the automation to copy over to the correct Storage path? how do we check this and avoid this next time? should we not raise this PR right away and wait for the automation to put the SAI debian to the correct Storage path first?

There are two sai builds, sai/bcmsai is built by another pipeline: https://msazure.visualstudio.com/DefaultCollection/One/_build/results?buildId=82577299&view=logs&j=e648e5ef-a22a-5b6a-b219-628f2b61562b&t=801d0469-f62b-546b-9afe-f059d5e6da0a

**Comment by judyjoseph** [comment]
@gechiang, please wait before we merge this -- I see a failure with fabric links not coming up, Need to debug further

**Comment by judyjoseph** [comment]
> @gechiang, please wait before we merge this -- I see a failure with fabric links not coming up, Need to debug further

Confirmed there is no issue with this SAI change, validated the voq counters to be working fine.

**Comment by gechiang** [comment]
Thanks for the confirmation @judyjoseph !
@lguohan , please help us to merge this PR so we can use it in our next image build.

**Pull request merged**
