### PR TITLE
[Arista] Remove aggregate port config files for multi-asic devices

### PR DESCRIPTION
**Pull request by bktsim-arista**
#### Why I did it
An aggregate port_config.ini file for Arista multi-asic devices was first introduced by mistake. This PR cleans up these unnecessary files.

#### How I did it
Removed all aggregate `port_config.ini` files from multi-asic devices.

#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [X] 202305

#### Description for the changelog
Remove aggregate port_config.ini files from Arista multi-asic devices.

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@arlakshm FYI

**Review by arlakshm — DISMISSED** [review]

**Comment by kenneth-arista** [comment]
@arlakshm can we also cherry-pick this clean up to 202205?

**Review by arlakshm — APPROVED** [review]

**Comment by StormLiangMS** [comment]
ADO: 26327820

**Pull request merged**
