### PR TITLE
Added new test case to check docker-dhcp-relay file generation when secondary subnets are present

### PR DESCRIPTION
**Pull request by shbalaku-microsoft**
##### Work item tracking
- Microsoft ADO **(number only)**: 16784946

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by pushpraj — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@shbalaku-microsoft  is this PR to add test cases or feature code? If this is test case, then it should go to sonic-mgmt repo.

**Review by prsunny — APPROVED** [review]
lgtm

**Comment by prsunny** [comment]
@shbalaku-microsoft , please check the build failure

**Review by prsunny — APPROVED** [review]

**Pull request merged**
