### PR TITLE
[Mellanox] Add support for new platform x86_64-mlnx_msn2700a1-r0

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Add support for new platform x86_64-mlnx_msn2700a1-r0

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

1. new pcie.yaml
2. new sensors.conf
3. new thermal support
4. new platform.json file
5. adjust test code

#### How to verify it

Run sonic-mgmt regression test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Review by keboliu — APPROVED** [review]

**Comment by lguohan** [comment]
@liat-grozovik , @yxieca , do we need backport this one?

**Comment by liat-grozovik** [comment]
> @liat-grozovik , @yxieca , do we need backport this one?

For 202305 as marked yes
We don't plan to qualify it for old active branches

**Comment by yxieca** [comment]
@Junchao-Mellanox can you help create PR for 202311 branch?

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca , it is already in 202311 by this commit: https://github.com/sonic-net/sonic-buildimage/commit/5138afe4e72b6efe1420ca86bb95fda083464765

**Pull request merged**
