### PR TITLE
Sync platform-modules-belgite deb's kernel version 5.10.0-8-2 with master runtime kernel version 5.10.0-12-2

### PR DESCRIPTION
**Pull request by jerseyang**
… PR branch kernel with master kernel version

#### Why I did it
platform-modules-belgite's deb requests linux-image-5.10.0-8-2-amd64-unsigned,  which does not match the runtime kernel version 

[   10.414587] rc.local[517]: + touch /tmp/pending_config_initialization
[   10.506597] rc.local[517]: + touch /tmp/notify_firstboot_to_platform
[   10.598633] rc.local[517]: + [ ! -d /host/reboot-cause/platform ]
[   10.678619] rc.local[517]: + [ -d /host/image-master.0-c92bfe072/platform/x86_64-cel_belgite-r0 ]
[   10.790588] rc.local[517]: + dpkg -i /host/image-master.0-c92bfe072/platform/x86_64-cel_belgite-r0/platform-modules-belgite_0.9_amd64.deb
[   10.955854] rc.local[628]: Selecting previously unselected package platform-modules-belgite.
[   11.070570] rc.local[628]: (Reading database ... 34034 files and directories currently installed.)
[   11.186614] rc.local[628]: Preparing to unpack .../platform-modules-belgite_0.9_amd64.deb ...
[   11.294593] rc.local[628]: Unpacking platform-modules-belgite (0.9) ...
[   11.382605] rc.local[628]: dpkg: dependency problems prevent configuration of platform-modules-belgite:
[   11.502627] rc.local[628]:  platform-modules-belgite depends on linux-image-5.10.0-8-2-amd64-unsigned; however:
[   11.630605] rc.local[628]:   Package linux-image-5.10.0-8-2-amd64-unsigned is not installed.
[   11.746569] rc.local[628]: dpkg: error processing package pla[   11.746693] rc.local[628]:  dependency problems - leaving unconfigured
[   11.914595] rc.local[628]: Errors were encountered while proc[   11.914696] rc.local[628]:  platform-modules-belgite
[   11.915845] rc.local[517]: + sync
[   11.915931] rc.local[517]: + [ -n x86_64-cel_belgite-r0 ]
[   11.916009] rc.local[517]: + [ -n  ]
[   11.916085] rc.local[517]: + mkdir -p /var/platform
[   11.916163] rc.local[517]: + [ -f /etc/default/kdump-tools ]
[   11.916246] rc.local[517]: + sed -i -e s/__PLATFORM__/x86_64-cel_belgite-r0/g /etc/default/kdump-tools
[   11.916324] rc.local[517]: + firsttime_exit
[   11.916403] rc.local[517]: + rm -rf /host/image-master.0-c92bfe072/platform/firsttime
[   11.916479] rc.local[517]: + exit 0

Debian GNU/Linux 11 sonic ttyS0

sonic login: [   27.782290] kdump-tools[552]: Creating symlink /var/lib/kdump/initrd.img.
[   29.263589] kdump-tools[552]: loaded kdump kernel.

sonic login: admin
Password:

Login incorrect
sonic login: admin
Password:
Linux sonic 5.10.0-12-2-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64
You are on
  ____   ___  _   _ _  ____
 / ___| / _ \| \ | (_)/ ___|
 \___ \| | | |  \| | | |
  ___) | |_| | |\  | | |___
 |____/ \___/|_| \_|_|\____|

-- Software for Open Networking in the Cloud --

Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.

Help:    http://azure.github.io/SONiC/

Last login: Wed May 25 02:28:32 UTC 2022 on ttyS0
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ sudo -s
root@sonic:/home/admin# uname -a
Linux sonic 5.10.0-12-2-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
root@sonic:/home/admin#

#### How I did it
update the belgite's deb configuration in deb's control 

#### How to verify it
check the firsttime boot log in belgite platform

/----------------------------------------------------------------------------\
 |*SONiC-OS-master.0-dirty-20220525.090420                                    |                                 |
 | ONIE                                                                       |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 \----------------------------------------------------------------------------/

      Use the ^ and v keys to select which entry is highlighted.
      Press enter to boot the selected OS, `e' to edit the commands
      before booting or `c' for a command-line.
   The highlighted entry will be executed automatically in 0s.
  Booting `SONiC-OS-master.0-dirty-20220525.090420'

Loading SONiC-OS OS kernel ...
Loading SONiC-OS OS initial ramdisk ...
[    0.083627] DMAR: [Firmware Bug]: No firmware reserved region can cover this RMRR [0x000000003e2e0000-0x000000003e2fffff], contact BIOS vendor for fixes
tune2fs 1.46.2 (28-Feb-2021)
Setting reserved blocks percentage to 0% (0 blocks)
Setting reserved blocks count to 0
[    4.798086] rc.local[484]: + sed -e s/build_version: //g;s/'//g
[    4.875793] rc.local[483]: + grep build_version
[    4.949207] rc.local[482]: + cat /etc/sonic/sonic_version.yml
[    5.036895] kdump-tools[463]: Starting kdump-tools:
[    5.107789] kdump-tools[508]: Creating symlink /var/lib/kdump/vmlinuz.
[    5.200168] rc.local[477]: + SONIC_VERSION=master.0-dirty-20220525.090420
[    5.295285] rc.local[477]: + FIRST_BOOT_FILE=/host/image-master.0-dirty-20220525.090420/platform/firsttime
[    5.423265] rc.local[477]: + SONIC_CONFIG_DIR=/host/image-master.0-dirty-20220525.090420/sonic-config
[    5.551299] rc.local[477]: + SONIC_ENV_FILE=/host/image-master.0-dirty-20220525.090420/sonic-config/sonic-environment
[    5.687276] rc.local[477]: + [ -d /host/image-master.0-dirty-20220525.090420/sonic-config -a -f /host/image-master.0-dirty-20220525.090420/sonic-config/sonic-environment ]
[    5.884110] rc.local[477]: + logger SONiC version master.0-dirty-20220525.090420 starting up...
[    6.000841] rc.local[477]: + grub_installation_needed=
[    6.071314] rc.local[477]: + [ ! -e /host/machine.conf ]
[    6.145332] rc.local[477]: + . /host/machine.conf
[    6.207903] rc.local[477]: + onie_arch=x86_64
[    6.267333] rc.local[477]: + onie_bin=
[    6.315303] rc.local[477]: + onie_boot_reason=install
[    6.379657] rc.local[477]: + onie_build_date=2022-02-11T12:38+08:00
[    6.467323] rc.local[477]: + onie_build_machine=cel_belgite
[    6.539274] rc.local[477]: + onie_build_platform=x86_64-cel_belgite-r0
[    6.627720] rc.local[477]: + onie_cli_static_parms=
[    6.699672] rc.local[477]: + onie_cli_static_url=sonic-broadcom-banyan.bin
[    6.787313] rc.local[477]: + onie_config_version=1
[    6.847657] rc.local[477]: + onie_dev=/dev/sda2
[    6.907556] rc.local[477]: + onie_exec_url=sonic-broadcom-banyan.bin
[    6.987480] rc.local[477]: + onie_firmware=auto
[    7.047934] rc.local[477]: + onie_grub_image_name=grubx64.efi
[    7.127621] rc.local[477]: + onie_initrd_tmp=/
[    7.187291] rc.local[477]: + onie_installer=/var/tmp/installer
[    7.271734] rc.local[477]: + onie_kernel_version=4.9.95
[    7.347286] rc.local[477]: + onie_machine=cel_belgite
[    7.419319] rc.local[477]: + onie_machine_rev=0
[    7.479290] rc.local[477]: + onie_partition_type=gpt
[    7.551267] rc.local[477]: + onie_platform=x86_64-cel_belgite-r0
[    7.627275] rc.local[477]: + onie_root_dir=/mnt/onie-boot/onie
[    7.703317] rc.local[477]: + onie_skip_ethmgmt_macs=no
[    7.775326] rc.local[477]: + onie_switch_asic=bcm
[    7.843261] rc.local[477]: + onie_uefi_arch=x64
[    7.903285] rc.local[477]: + onie_uefi_boot_loader=grubx64.efi
[    7.979300] rc.local[477]: + onie_vendor_id=12244
[    8.039324] rc.local[477]: + onie_version=2019.02.01.3.0.0
[    8.111484] rc.local[477]: + program_console_speed
[    8.174009] rc.local[537]: + cat /proc/cmdline
[    8.231825] kdump-tools[619]: libkmod: ERROR ../libkmod/libkmod-module.c:1941 kmod_module_get_holders: could not open '/sys/module/linux_kernel_bde/holders': No such file or directory
[    8.437195] rc.local[538]: + grep -Eo console=ttyS[0-9]+,[0-9]+
[    8.515988] kdump-tools[576]: kdump-tools: Generating /var/lib/kdump/initrd.img-5.10.0-12-2-amd64
[    8.632390] rc.local[553]: + cut -d , -f2
[    8.694997] rc.local[477]: + speed=9600
[    8.751434] rc.local[477]: + [ -z 9600 ]
[    8.811291] rc.local[477]: + CONSOLE_SPEED=9600
[    8.878233] rc.local[560]: +
[    8.924420] rc.local[561]: +
[    8.971768] rc.local[560]: grep agetty
[    9.019715] rc.local[561]: grep
[    9.067284] rc.local[560]:  /lib/systemd/system/serial-getty@.service
[    9.147513] rc.local[561]:  keep-baud
[    9.195273] rc.local[561]: ExecStart=-/sbin/agetty -o '-p -- \\u' --keep-baud 115200,57600,38400,9600 %I $TERM
[    9.324014] rc.local[477]: + [ 0 = 0 ]
[    9.371274] rc.local[477]: + sed -i s|\-\-keep\-baud .* %I| 9600 %I|g /lib/systemd/system/serial-getty@.service
[    9.499417] rc.local[477]: + systemctl daemon-reload
[    9.563283] rc.local[477]: + [ -f /host/image-master.0-dirty-20220525.090420/platform/firsttime ]
[    9.683328] rc.local[477]: + echo First boot detected. Perfor[    9.744807] c3xxx 0000:01:00.0: Failed to send admin msg 0 to accelerator 2
ming first boot tasks...
[    9.831738] c3xxx 0000:01:00.0: Failed to send init message
[    9.931618] rc.local[477]: First boot detected. Performing first boot tasks...
[   10.031432] rc.local[477]: + [ -n  ]
[   10.083354] rc.local[477]: + [ -n x86_64-cel_belgite-r0 ]
[   10.159301] rc.local[477]: + platform=x86_64-cel_belgite-r0
[   10.247353] rc.local[477]: + [ -d /host/old_config ]
[   10.311330] rc.local[477]: + [ -f /host/minigraph.xml ]
[   10.377012] rc.local[477]: + [ -n  ]
[   10.427315] rc.local[477]: + touch /tmp/pending_config_initialization
[   10.507327] rc.local[477]: + touch /tmp/notify_firstboot_to_platform
[   10.599351] rc.local[477]: + [ ! -d /host/reboot-cause/platform ]
[   10.679307] rc.local[477]: + [ -d /host/image-master.0-dirty-20220525.090420/platform/x86_64-cel_belgite-r0 ]
[   10.803337] rc.local[477]: + dpkg -i /host/image-master.0-dirty-20220525.090420/platform/x86_64-cel_belgite-r0/platform-modules-belgite_0.9_amd64.deb
[   10.981144] rc.local[616]: Selecting previously unselected package platform-modules-belgite.
[   11.091288] rc.local[616]: (Reading database ... 34034 files and directories currently installed.)
[   11.207349] rc.local[616]: Preparing to unpack .../platform-modules-belgite_0.9_amd64.deb ...
[   11.327344] rc.local[616]: Unpacking platform-modules-belgite (0.9) ...
[   11.415342] rc.local[616]: Setting up platform-modules-belgite (0.9) ...
[   12.702909] rc.local[2448]: Processing /usr/share/sonic/device/x86_64-cel_belgite-r0/pddf/sonic_platform-1.0-py3-none-any.whl
[   13.337541] rc.local[2448]: Installing collected packages: sonic-platform
[   13.431330] rc.local[2448]: Successfully installed sonic-platform-1.0
[   13.519326] rc.local[2448]: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[   21.075463] rc.local[477]: + sync
[   21.337072] rc.local[477]: + [ -n x86_64-cel_belgite-r0 ]
[   21.411377] rc.local[477]: + [ -n  ]
[   21.459189] rc.local[477]: + mkdir -p /var/platform
[   21.531187] rc.local[477]: + [ -f /etc/default/kdump-tools ]
[   21.607195] rc.local[477]: + sed -i -e s/__PLATFORM__/x86_64-cel_belgite-r0/g /etc/default/kdump-tools
[   21.731303] rc.local[477]: + firsttime_exit
[   21.783271] rc.local[477]: + rm -rf /host/image-master.0-dirty-20220525.090420/platform/firsttime
[   21.895277] rc.local[477]: + exit 0
[   25.639192] kdump-tools[508]: Creating symlink /var/lib/kdump/initrd.img.
[   26.730472] kdump-tools[508]: loaded kdump kernel.

Debian GNU/Linux 11 sonic ttyS0

sonic login: admin
Password:
Linux sonic 5.10.0-12-2-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64
You are on
  ____   ___  _   _ _  ____
 / ___| / _ \| \ | (_)/ ___|
 \___ \| | | |  \| | | |
  ___) | |_| | |\  | | |___
 |____/ \___/|_| \_|_|\____|

-- Software for Open Networking in the Cloud --

Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.

Help:    http://azure.github.io/SONiC/

Last login: Thu May 26 02:00:07 UTC 2022 on ttyS0
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ sudo -s
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# show platform fan
  Drawer    LED         FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ----------  -------  -----------  ----------  --------  -----------------
Fantray1  green  Fantray1_1      40%      EXHAUST     Present        OK  20220526 07:40:18
Fantray2  green  Fantray2_1      40%      EXHAUST     Present        OK  20220526 07:40:18
Fantray3  green  Fantray3_1      40%      EXHAUST     Present        OK  20220526 07:40:18
     N/A  green   PSU1_FAN1      41%      EXHAUST     Present        OK  20220526 07:40:18
     N/A  green   PSU2_FAN1      11%       INTAKE     Present        OK  20220526 07:40:18
root@sonic:/home/admin# show platform psustatus
PSU    Model        Serial       HW Rev      Voltage (V)    Current (A)    Power (W)  Status    LED
-----  -----------  -----------  --------  -------------  -------------  -----------  --------  -----
PSU 1  FSP550-20FM  S1091000897  N/A               12.32           3.70        44.88  OK        green
PSU 2  FSP550-20FM  S1131000295  N/A                0.17           0.00         0.00  NOT OK    off
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# show platform syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 171
TLV Name             Code      Len  Value
-------------------  ------  -----  ----------------------
Product Name         0x21        5  E1070
Part Number          0x22       14  R3059-F9010-01
Serial Number        0x23       22  E1070F2B071602BY200002
Base MAC Address     0x24        6  0C:48:C6:9A:96:66
Manufacture Date     0x25       19  09/22/2021 17:00:01
Device Version       0x26        1  2
Label Revision       0x27        7  Belgite
Platform Name        0x28       21  x86_64-cel_belgite-r0
ONIE Version         0x29        5  2.0.0
MAC Addresses        0x2A        2  57
Manufacturer         0x2B        9  Celestica
Manufacture Country  0x2C        3  THA
Vendor Name          0x2D        9  Celestica
Diag Version         0x2E        5  3.2.0
Service Tag          0x2F        2  LB
Vendor Extension     0xFD        3  0x2F 0xD4 0xFB
CRC-32               0xFE        4  0x42792D74

(checksum valid)
root@sonic:/home/admin#

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111

### CODE REVIEW

**Comment by jerseyang** [comment]
[Blueve](https://github.com/Blueve) Hi Jing Kan,  looks like the Azure pipeline built commit id is 389d7e076, which is not 
as the same as my local committed id bc12e60e8, my local built successfully

Azure Pipeline build logs:
2022-05-27T09:45:37.3253081Z "KERNEL_PROCURE_METHOD"           : "build"
2022-05-27T09:45:37.3253370Z "BUILD_TIMESTAMP"                 : "20220527.094535"
2022-05-27T09:45:37.3253674Z "BUILD_LOG_TIMESTAMP"             : "none"
2022-05-27T09:45:37.5522320Z "SONIC_IMAGE_VERSION"             : "master-10946.103684-389d7e076"
2022-05-27T09:45:37.5523077Z "BLDENV"                          : "stretch"

2022-05-27T09:45:58.9368745Z "KERNEL_PROCURE_METHOD"           : "build"
2022-05-27T09:45:58.9369245Z "BUILD_TIMESTAMP"                 : "20220527.094557"
2022-05-27T09:45:58.9369765Z "BUILD_LOG_TIMESTAMP"             : "none"
2022-05-27T09:45:59.1455716Z "SONIC_IMAGE_VERSION"             : "master-10946.103684-389d7e076"
2022-05-27T09:45:59.1456227Z "BLDENV"                          : "buster"

2022-05-27T11:14:26.5825687Z "KERNEL_PROCURE_METHOD"           : "build"
2022-05-27T11:14:26.5826301Z "BUILD_TIMESTAMP"                 : "20220527.111423"
2022-05-27T11:14:26.5826837Z "BUILD_LOG_TIMESTAMP"             : "none"
2022-05-27T11:14:26.9534713Z "SONIC_IMAGE_VERSION"             : "master-10946.103684-389d7e076"
2022-05-27T11:14:26.9535900Z "BLDENV"                          : "bullseye"
2022-05-27T11:14:26.9536601Z "VS_PREPARE_MEM"                  : "yes"

root@sonic:/home/admin# show version

SONiC Software Version: SONiC.Belgite_Kernel_Mismatch.0-bc12e60e8
Distribution: Debian 11.3
Kernel: 5.10.0-12-2-amd64
Build commit: bc12e60e8
Build date: Thu May 26 17:42:19 UTC 2022
Built by: jersey@cthgd047

Platform: x86_64-cel_belgite-r0
HwSKU: CELESTICA-BELGITE
ASIC: broadcom
ASIC Count: 1
Serial Number: E1070F2B071602BY200002
Model Number: R3059-F9010-01
Hardware Revision:
Uptime: 12:25:51 up 1 day, 44 min,  1 user,  load average: 0.58, 0.73, 0.73
Date: Thu 26 May 2022 12:25:51

root@sonic:/home/admin# show platform fan
  Drawer    LED         FAN    Speed    Direction    Presence    Status          Timestamp
--------  -----  ----------  -------  -----------  ----------  --------  -----------------
Fantray1  green  Fantray1_1      40%      EXHAUST     Present        OK  20220526 12:28:48
Fantray2  green  Fantray2_1      40%      EXHAUST     Present        OK  20220526 12:28:48
Fantray3  green  Fantray3_1      40%      EXHAUST     Present        OK  20220526 12:28:48
     N/A  green   PSU1_FAN1      23%      EXHAUST     Present        OK  20220526 12:28:48
     N/A  green   PSU2_FAN1      21%      EXHAUST     Present        OK  20220526 12:28:48
root@sonic:/home/admin#
root@sonic:/home/admin# uname -a
Linux sonic 5.10.0-12-2-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
root@sonic:/home/admin#

**Comment by jerseyang** [comment]
> lizhuhuams

@[lizhuhuams](https://github.com/lizhuhuams),  we want to the i2c-ismt/i2c-i801 was insmod in order, so we disable their automatic loading during OS booting. just only insmod i2c-i801 one time. Thanks!

**Comment by jerseyang** [comment]
> lizhuhuams

@[lizhuhuams](https://github.com/lizhuhuams),  we want to the i2c-ismt/i2c-i801 was insmod in order, so we disable their automatic loading during OS booting. just only insmod i2c-i801 one time. Thanks!

**Comment by jerseyang** [comment]
@Azure/sonic-platform Hi Team, any comments about this? Thanks!

**Comment by jerseyang** [comment]
@lguohan  Any comments about this? Thanks!

**Comment by jerseyang** [comment]
@Blueve Hi JingKan, can you trigger another pipeline building? Thanks!

**Comment by jerseyang** [comment]
@Blueve Hi JingKan, can you trigger another pipeline building? Thanks!

**Comment by jerseyang** [comment]
@Blueve,  can you help to check this? Thanks!

**Comment by jerseyang** [comment]
@lguohan  @Blueve Hi Guohan and JingKan, can you help to check this PR? Thanks!

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
LGTM

**Comment by jerseyang** [comment]
@Blueve  Hi JingKan,  it look  there are some LFX EasyCLA problems, it cannot pass, I am not sure what is the reason, can you help to check? Thanks!

**Comment by Blueve** [comment]
> @Blueve Hi JingKan, it look there are some LFX EasyCLA problems, it cannot pass, I am not sure what is the reason, can you help to check? Thanks!

The commit was created by https://github.com/nicwu-cel
Can you ask him to sign the CLA doc?

**Comment by jerseyang** [comment]
> > @Blueve Hi JingKan, it look there are some LFX EasyCLA problems, it cannot pass, I am not sure what is the reason, can you help to check? Thanks!
> 
> The commit was created by https://github.com/nicwu-cel Can you ask him to sign the CLA doc?

yeah,  also, I have asked him to sign the CLA doc, but still  the same results. this item is not covered.

**Pull request merged**
