### PR TITLE
[202311][Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

Updated Arista platform drivers
- Add support for new PSU models
- Add support for new FAN models
- Backport lpmode changes
- Fix PSU threshold issue on Quicksilver
- Fix PCIe address of the ASIC for LodogaPrime
- Fix Quicksilver Front Panel leds
- Fix Quicksilver Fan leds

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Cherry-picked the fixes from our main branch

#### How to verify it

Changes validated against sonic-mgmt on 202311

#### Description for the changelog

Update Arista platform library submodules

### CODE REVIEW

**Comment by mihirpat1** [comment]
@prgeor Can you please help in reviewing this (changeset also contains fix for https://github.com/aristanetworks/sonic-qual.msft/issues/229)?

**Comment by prgeor** [comment]
@Staphylo can you raise PR to master as well so that we don't miss this in 202405 and 202411

**Comment by lguohan** [comment]
This PR caused regression, need to limit this fix to only the fix we want.

**Comment by lguohan** [comment]
@Staphylo , can you RCA this one to see why this caused regression on backporting?

**Comment by lguohan** [comment]
@aaronpayment please RCA

**Comment by Staphylo** [comment]
@bingwang-ms we will make a PR against 202405 to update the arista platform modules there.
The regression that happened here is not present in the upstream 202405.

**Pull request merged**
