### PR TITLE
[BFN] Reworked BFN platform thermals plugin

### PR DESCRIPTION
**Pull request by akokhan**
Signed-off-by: Andriy Kokhan <andriyx.kokhan@intel.com>

#### Why I did it
- To reduce an access to I2C bus
- To speed-up thermals polling time
- To fix platform.json info as per wedge100bf_65x requirements

#### How I did it
Added local thermal cache that is updated on read once in >5sec

#### How to verify it
```
show platform temperature
show platform firmware status
```
Run SONiC platform CTs

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111
- [x] 202205

### CODE REVIEW

**Comment by akokhan** [comment]
@lguohan , please approve and merge.

**Comment by akokhan** [comment]
@prgeor , @jleveque , please approve and merge. Thank you.

**Comment by akokhan** [comment]
@prgeor , please review

**Comment by akokhan** [comment]
@jleveque , please review

**Comment by akokhan** [comment]
@lguohan , please approve and merge

**Comment by akokhan** [comment]
@lguohan , could you please take a look? Thanks

**Comment by akokhan** [comment]
@prgeor , could you please take a look? Thank you

**Comment by akokhan** [comment]
@lguohan ,  @prgeor , could you please take a look? Thanks

**Comment by akokhan** [comment]
@prgeor , please review

**Comment by akokhan** [comment]
@lguohan , please review

**Comment by akokhan** [comment]
@prsunny , could you please take a look? Thanks

**Comment by akokhan** [comment]
@lguohan , @prgeor , this PR contains Intel platform specific changes only. Please approve and merge.

**Comment by akokhan** [comment]
@Azure/sonic-platform,  this PR contains Intel platform specific changes only. Please approve and merge.

**Review by richardyu-ms — APPROVED** [review]

**Comment by prgeor** [comment]
@akokhan can you rebase your changes?

**Pull request merged**
