### PR TITLE
[Mellanox] Validate Module Presence Via Sysfs Before Accessing EEPROM in Thermal Control Daemon

### PR DESCRIPTION
**Pull request by tshalvi**
#### Why I did it
Currently, on Mellanox platforms, when trying to read from the EEPROM of an unplugged module from thermalctld, we get the following error:
ERR kernel: [ 2446.261799] sxd_kernel: [error] Failed to get module page valid, err: -5
We need to ensure the EEPROM is not accessed if a module is not connected.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
I updated the logic of get_presence() to rely on the present/hw_present sysfs values and called get_presence() from within the relevant methods in thermalctld.

#### How to verify it
Unplug a module and ensure the following error does not appear:
ERR kernel: [ 2446.261799] sxd_kernel: [error] Failed to get module page valid, err: -5

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by dprital** [comment]
@yxieca , Can you please cherry pick to 202311 ?

**Comment by yxieca** [comment]
@bingwang-ms  to track 202405 cherry-pick

**Comment by bingwang-ms** [comment]
@tshalvi Please raise another PR for 202405 to address conflict.

**Comment by DavidZagury** [comment]
@bingwang-ms  - this is already included in 202405 as it was merged to master before 202405 was created
```
$ git branch --contains c2d06ee
* 202405
  master
```

**Pull request merged**
