### PR TITLE
[Mellanox] route config/set/delete performance improvement

### PR DESCRIPTION
**Pull request by dprital**
#### Why I did it

Increase significantly the rate of routes config/set/delete to HW.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Add required flag in sai.profile and increase orchagent bulk size.

#### How to verify it

Measure rate of route set/del operations at scale.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by stepanblyschak — APPROVED** [review]

**Comment by lguohan** [comment]
can you provide the perf numbers?

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@dprital Can you please confirm the change will not break warm-reboot on the old platforms? And please share the PR for the SAI change so that I can confirm the dependency has been cherry-picked.

**Comment by dprital** [comment]
> @dprital Can you please confirm the change will not break warm-reboot on the old platforms? And please share the PR for the SAI change so that I can confirm the dependency has been cherry-picked.

Hi @bingwang-ms , the change will not break warm-reboot on any platform. 
As for SAI, the one supporting this feature is already on master, 202405 and 202311.

**Comment by dprital** [comment]
@bingwang-ms , This PR was approved for 202405.  What is required to cherry pick it ?

**Comment by bingwang-ms** [comment]
The automation should handle the cherry-pick. But it's not working somehow. @liushilongbuaa Could you please help check?

**Pull request merged**
