### PR TITLE
[202211][Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
- Fix `watchdog` reboot cause for wolverine linecard
 - Fix PSU fan speed of `0%` by adding max RPM to most psu descriptions
 - Add product `DCS-7060DX5-64`
 - Add product `DCS-7060DX5-32`

### CODE REVIEW

**Comment by Staphylo** [comment]
Could we get some attention on our driver changes for `202211` @prgeor @StormLiangMS 
This new PR supersedes our 2 previous attempts at getting changes merged with some new features added:
 - https://github.com/sonic-net/sonic-buildimage/pull/14453
 - https://github.com/sonic-net/sonic-buildimage/pull/14038

**Comment by wenyiz2021** [comment]
@lguohan can you please help on merge this PR? thanks! cc @rlhui @arlakshm

**Comment by lguohan** [comment]
@StormLiangMS  to merge as he is the maintainer for the 202211 branch?

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
