### PR TITLE
[Mellanox] Remove pmon delay for certain platforms

### PR DESCRIPTION
**Pull request by stepanblyschak**
#### Why I did it

For doing fast-reboot with CMIS active modules.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Removed PMON delay for SKUs with support for CMIS active modules

#### How to verify it

Run fast-reboot test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@stepanblyschak is it included in 202405. if not? please add relevant label

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca can you help to handle ms_conflict and re trigger?

**Comment by liat-grozovik** [comment]
@stepanblyschak please check https://github.com/sonic-net/sonic-buildimage/pull/18926 and if this PR need to be updated now with it?cccccbkv

**Comment by bingwang-ms** [comment]
@vaibhavhd @prgeor Is this a must have for 202405? The change is on all Mellanox platform.

**Comment by dprital** [comment]
@bingwang-ms , @vaibhavhd , @prgeor  - Can you please cherry pick to 202405 ?

**Comment by bingwang-ms** [comment]
Discussed offline, we are good to cherry-pick it.

**Comment by chiourung** [comment]
This only works for the Mellanox platform. For other platforms, it would always delay pmon and cause a problem. https://github.com/sonic-net/sonic-platform-daemons/issues/531. 
How about to remove delay for pmon and include https://github.com/sonic-net/sonic-buildimage/pull/18907 to enhance the performance?

**Comment by stepanblyschak** [comment]
@chiourung  The issue is know and a day one xcvrd issue - https://github.com/sonic-net/sonic-buildimage/issues/17943.
Please do not remove pmon delay for nvidia platforms unless reviewed by nvidia.

Even if we remove the delay it does not fix the problem but makes it very unlikelly, need to fix a race condition

**Pull request merged**
