### PR TITLE
Rename the leaf nodes to lower case.

### PR DESCRIPTION
**Pull request by xincunli-sonic**
#### Why I did it
Consolidate the `numvoq`, `coreid`, `coreportid` to be lower case which matches other leaf node convention.

##### Work item tracking
- Microsoft ADO **(number only)**: 27599961

#### How I did it

Rename to lower case.

#### How to verify it
No need to verify.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]
lgtm

**Comment by arlakshm** [comment]
This PR is making the column names in portconfig.ini consistent with port_config.ini files. 
add @saksarav-nokia, @mlok-nokia, @kenneth-arista, @ysmanman viz..

**Review by arlakshm — APPROVED** [review]

**Comment by kenneth-arista** [comment]
@arlakshm Can we get this PR cherry-picked to 202205 ASAP?

**Pull request merged**
