### PR TITLE
Update cisco-8000.ini to 202405.0.15 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: Anand Mehra anamehra@cisco.com

Release for Cisco 8800 Chassis, 8101

Chassis 8800
Test case fix test_thermal_global_state_db for FC in slot 7 XR to SONiC migration process broken in two steps
Apply SONiC config as part of XR to SONiC migration via minigraph.xml Fixed BFD staying up on portchannel member down issue

8101
Fix for MIGSMSFT-771 - Link flap with disabled bad link detection

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Comment by yejianquan** [comment]
https://github.com/Cisco-8000-sonic/platform-cisco-8000/releases/tag/202405.0.15

**Comment by kperumalbfn** [comment]
@anamehra 202411 has 202411.1.0.2, Do we need this in 202411?

**Comment by anamehra** [comment]
> @anamehra 202411 has 202411.1.0.2, Do we need this in 202411?

No @kperumalbfn , not required in 202411.

**Comment by liuh-80** [comment]
Hi @anamehra , currently 202405 branch cisco-8000 HwSKU build break because nvme-cli removed from debian mirror, is there a plan update this submodule?

Warning: Failed to verify the package: http://ftp.us.debian.org/debian/pool/main/n/nvme-cli/nvme-cli_1.7-1_amd64.deb, the version is not specified
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   263    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

**Comment by anamehra** [comment]
> Hi @anamehra , currently 202405 branch cisco-8000 HwSKU build break because nvme-cli removed from debian mirror, is there a plan update this submodule?
> 
> Warning: Failed to verify the package: http://ftp.us.debian.org/debian/pool/main/n/nvme-cli/nvme-cli_1.7-1_amd64.deb, the version is not specified % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed
> 
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 263 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (22) The requested URL returned error: 404

Hi @liuh-80 , I am working on a release to fix this and another build issue. I will do a release early next week. Thanks

**Comment by anamehra** [comment]
> > Hi @anamehra , currently 202405 branch cisco-8000 HwSKU build break because nvme-cli removed from debian mirror, is there a plan update this submodule?
> > Warning: Failed to verify the package: http://ftp.us.debian.org/debian/pool/main/n/nvme-cli/nvme-cli_1.7-1_amd64.deb, the version is not specified % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed
> > 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 263 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (22) The requested URL returned error: 404
> 
> Hi @liuh-80 , I am working on a release to fix this and another build issue. I will do a release early next week. Thanks

HI @liuh-80 , here is PR with fix https://github.com/sonic-net/sonic-buildimage/pull/23773. Thanks

**Pull request merged**
