### PR TITLE
[submodule] Advance sonic-platform-daemons pointer

### PR DESCRIPTION
**Pull request by keboliu**
Signed-off-by: Kebo Liu <kebol@nvidia.com>

#### Why I did it
Advance sonic-platform-daemons submodule to pick up new commits:

> e8c5657 [ycabled] fix exception-handling logic for ycabled [(#306)](https://github.com/sonic-net/sonic-platform-daemons/pull/306)
> 905874d [ycabled] move swsscommon API's from subroutines to call them exactly once per task_worker/thread [(#303)](https://github.com/sonic-net/sonic-platform-daemons/pull/303)
> 510d330 Fix typo in xcvrd [(#313)](https://github.com/sonic-net/sonic-platform-daemons/pull/313)
> 9ae551f [ycabled] add support for detach mode in 'active-active' topology [(#309)](https://github.com/sonic-net/sonic-platform-daemons/pull/309)
> 82fc7a6 Added filtering logic to send filtered fields from DB event [(#307)](https://github.com/sonic-net/sonic-platform-daemons/pull/307)
> 8a2dad9 [ycabled] fix no port/state returned by grpc server [(#308)](https://github.com/sonic-net/sonic-platform-daemons/pull/308)
> 4ea12cf Fix xcvrd to support 400G ZR optic [(#293)](https://github.com/sonic-net/sonic-platform-daemons/pull/293)
> 23b6970 [ycabled] fix naming error for error condition for CLI handling [(#302)](https://github.com/sonic-net/sonic-platform-daemons/pull/302)
> 501abb2 [ycabled] add some exception catching logic to some vendor specific API's [(#301)](https://github.com/sonic-net/sonic-platform-daemons/pull/301)
> 534f839 [ycabled] add support for getting grpc secerts via shared file [(#298)](https://github.com/sonic-net/sonic-platform-daemons/pull/298)
> 3622aac Remove shell=True [(#300)](https://github.com/sonic-net/sonic-platform-daemons/pull/300)
> 143422b add support to execute new ycable API's, add datetime field to mux_info [(#297)](https://github.com/sonic-net/sonic-platform-daemons/pull/297)
> 6522c46 [ycabled] add notification for gRPC connection state transitions to  IDLE/TRANSIENT_FAILURE [(#295)](https://github.com/sonic-net/sonic-platform-daemons/pull/295)
> 4b3b238 Install libyang to azure pipeline [(#292)](https://github.com/sonic-net/sonic-platform-daemons/pull/292)
> 8ff5f37 Use get() to fetch default value from dictionary for port admin_status [(#286)](https://github.com/sonic-net/sonic-platform-daemons/pull/286)
> b03cc74 [Xcvrd] Soak duplicate events and process only updated interested events [(#285)](https://github.com/sonic-net/sonic-platform-daemons/pull/285)
> 3acb171 [ycable] cleanup logic for creating grpc future ready [(#289)](https://github.com/sonic-net/sonic-platform-daemons/pull/289)
> ce3b6db [ycabled] fix insert events from xcvrd;cleanup some mux toggle logic [(#287)](https://github.com/sonic-net/sonic-platform-daemons/pull/287)

#### How I did it
Advance sonic-platform-daemons submodule pointer

#### How to verify it
run regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@keboliu  please handle conflicts. also as there are failures need to debug the failures referring to the changes.

**Comment by keboliu** [comment]
> @keboliu please handle conflicts. also as there are failures need to debug the failures referring to the changes.

commit owner is handling the building failure, after he handled the failure, I will update this PR.

**Comment by keboliu** [comment]
closed since there is already another one opened:  https://github.com/sonic-net/sonic-buildimage/pull/12841
the failure also been fixed.

**Pull request closed without merging**
