### PR TITLE
[BFN] Updated syseeprom platform plugin to use onie-eeprom

### PR DESCRIPTION
**Pull request by dmytroxIntel**
#### Why I did it
OpenBMC eeprom interface doesn't provide all platform information, so `show version` was not showing all parameters.
#### How I did it
Expose Onie TLV system eeprom for sonic parser framework via thrift platform manager service.
#### How to verify it
Run `show version` command, all parameters are visible.
Verify Eeprom contents in redis STATE_DB parsed by syseepromd.
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111

### CODE REVIEW

**Review by akokhan — DISMISSED** [review]

**Comment by dmytroxIntel** [comment]
@prgeor please review

**Comment by dmytroxIntel** [comment]
@lguohan please review

**Comment by akokhan** [comment]
@prgeor , please take a look. Thanks

**Comment by dmytroxIntel** [comment]
@prgeor please take a look. Thanks

**Review by akokhan — APPROVED** [review]

**Comment by dmytroxIntel** [comment]
@lguohan , please review

**Comment by dmytroxIntel** [comment]
@prgeor please take a look, thx

**Comment by dmytroxIntel** [comment]
@lguohan please review, thx

**Comment by dmytroxIntel** [comment]
@lguohan , please take a look, thx

**Comment by dmytroxIntel** [comment]
@qiluo-msft , @prgeor , @richardyu-ms, please approve and merge

**Comment by dmytroxIntel** [comment]
@qiluo-msft , @prgeor , @richardyu-ms, please approve and merge

**Comment by akokhan** [comment]
@prgeor , @richardyu-ms , 
this PR contains Intel platform specific changes
could you please approve and merge? Thanks

**Review by prgeor — APPROVED** [review]

**Pull request merged**
