### PR TITLE
[build] Fix isc-dhcp full version in rules.mk

### PR DESCRIPTION
**Pull request by guillaumelambert**
During the build process, a dsc file is retrieved from the URL: http://deb.debian.org/debian/pool/main/i/isc-dhcp/isc-dhcp_4.4.1-2.3.dsc

Depending on the DNS resolution, the server reached may respond with a HTTP 404 error code, what stops the build process. In all cases, the URL http://deb.debian.org/debian/pool/main/i/isc-dhcp/ no more lists this DSC file but one with a different format.

The suffix "+deb11u1" is now appended to identify the debian version.

- append this suffix to the make file rules of isc-dhcp

Issue  #13281

#### Which release branch to backport (provide reason below if selected)

all using this version of isc-dhcp

#### Description for the changelog

[build]  Fix isc-dhcp full version in rules.mk

#### A picture of a cute animal (not mandatory but encouraged)

                      .".
                         /  |
                        /  /
                       / ,"
           .-------.--- /
          "._ __.-/ o. o\  
             "   (    Y  )
                  )     /
                 /     (
                /       Y
            .-"         |
           /  _     \    \ 
          /    `. ". ) /' )
         Y       )( / /(,/
        ,|      /     )
       ( |     /     /
        " \_  (__   (__        [nabis]
            "-._,)--._,)

### CODE REVIEW

**Comment by guillaumelambert** [comment]
@collivier @odd22 FYI

**Comment by saiarcot895** [comment]
Technically, this is a package update, not just a version numbering fix. It's odd, though, that the dsc file for 4.4.1-2.3 appears to be still partially available, but listing the directory contents doesn't show it.

**Review by saiarcot895 — APPROVED** [review]

**Comment by saiarcot895** [comment]
I see #13276 is also fixing the same thing.

**Comment by guillaumelambert** [comment]
> Technically, this is a package update, not just a version numbering fix. It's odd, though, that the dsc file for 4.4.1-2.3 appears to be still partially available, but listing the directory contents doesn't show it.

Yep I was referring to the variable name in the commit title indeed.
Maybe it would be worth to update this variable name too.
About the weird listing, this is a classical caching issue probably related to debian packages staging process..
I had access to the old dsc file from a different Internet access location where it was not yet removed.
Here are diff and grep results.
As you can see sources checksum are identical but not the debian packages ones.
I suspect this is only a renaming issue indeed.

hope tis helps

`$ diff isc-dhcp*.dsc
8c8
< Version: 4.4.1-2.3+deb11u1
---
> Version: 4.4.1-2.3
27c27
<  dcf53786e6b1650184fde075bbe25a0f3dd7e49c 89040 isc-dhcp_4.4.1-2.3+deb11u1.debian.tar.xz
---
>  aad326e51276efeb3d6d64b23f274eaaa329a737 88136 isc-dhcp_4.4.1-2.3.debian.tar.xz
30c30
<  b693380b77195e6e742848be2a86248506b0c9bbbb461622daa1ad5b36d9ac54 89040 isc-dhcp_4.4.1-2.3+deb11u1.debian.tar.xz
---
>  8396ddc072a5f1d1863f95ba8f95cb4d6f0de3928615038eeaa8897d966dcd35 88136 isc-dhcp_4.4.1-2.3.debian.tar.xz
33c33
<  8c3640097a1b4cc59e927badbd45b3f0 89040 isc-dhcp_4.4.1-2.3+deb11u1.debian.tar.xz
---
>  72af4f677ebb88970bdcae0f73f2d9e8 88136 isc-dhcp_4.4.1-2.3.debian.tar.xz
37c37
< iQKmBAEBCgCQFiEERkRAmAjBceBVMd3uBUy48xNDz0QFAmM8nvlfFIAAAAAALgAo
---
> iQKmBAEBCgCQFiEERkRAmAjBceBVMd3uBUy48xNDz0QFAmCvLJJfFIAAAAAALgAo
40,52c40,52
< ZWJpYW4ub3JnAAoJEAVMuPMTQ89EhycQAJq6XE8fkA8/yPmXmDj7QzBl8bNy5+9g
< FUouv8ofLd896dHwt9HEP0ucP/S0v6sEL8rP29r5jyNHPqQYqtJlafjVrFGZrWTt
< bsiHQvM3r7j5DLvzOq1wmdo82EZBBjdHqL+NJZBBE0mvxnjnlJx6V19GMsPUjoXY
< BHeazobJPCl9Oa3KRQew4lRsKRaSSiAnqGvajOyL2TfnCTHxDCjiOPqm57yzcGO7
< sDI7L5z5oJxnVygaY+z2ANeX9TqFJICyEAXb1VZcs3+6SmmVKrUl5mQuHC5u9Zg+
< +JkySkTx01MIWWU1zF9k5sSAtLI7uER5NhNhDxTApfSGLEj7LWmdaTsNY4ftB1Y8
< 5yv2C5pPYVO0xnJ0udqC4VPPkfFBu6mFuNcxW24U97+33cQYnYuUYsxkfkFIX/KQ
< xVF6rXjNEtu0hlpB7ydHHUU36GgXUCi7kAfsPKAAZP4QlJxpi4dmjf4F73Wb/3AH
< 1n7n7qrLsX30YMpfrTy41kcTcUWXv0p47W90i5wdEIdcTImOsKUbi59fIbgPZBtF
< c8ZLK99Q8+6Hdd9K2b6+yskTVzTwtVLsCKZhWVJqK0IgsGIwzSuwVkrkE60Nq1ht
< 0l40gOfrhqKiMkCly4751iZL5SzfTQoK2F3I5URJw4lFy99xW/Yw1CCsi4mfAQIh
< es30x/Kf13xS
< =ojYu
---
> ZWJpYW4ub3JnAAoJEAVMuPMTQ89EthQP/2LWNpHCbWVuXrL9y245heTPeOmf+t/1
> sxI9iNbg+Szyogllnau2EChexjqhxf42vkcZR/A4O2jFjI9awXJu0i5vFYjn7T7o
> MEa/og7LMJxLW6rm/RcYttJEV4INfR89UF18J6CgMFBfhdEcCei8RvxNEwQWzaCi
> qJFQNFE8yXW8l7fRXcWD3J57NRxnS96mm6V/oPA21O7BPmBGo9YGzVwJ2s0Jd4W8
> YJb8GBFx5xwDd7zp0NVeGM8yI9MAtLpvvTNKBsZzXYIA06iSm7Ww258tI9qh/cMn
> +vmS2oP7W+uFhN7C3r0gO+aqQrM5JyMFtt5ZpAqvfm/TxYgEBGFNEKLH2k7I8LSG
> KM4lmPWYtcBQQ7wTl3vnZp+XTtfdGVh1zs3SR8TVOe2L0GRtZ0lYJKCShk2bC+G0
> 7NjJ8+PWsNe5pTDqaay480XsriUFb9ctiQafuPBIaUD9PjLvjL8owHvArC2fs25b
> SZIXJOpFsG2Ti5lFL2I8SWoMwdqDf02liHgc5UfEBLPbnKUXjtupuXDjnJ+yg/E4
> C7Pere+9y4ObDFXAyuv04B6W84GUSmw02zUqp4LhYILRYETzZUjqrwJjJBdqIx82
> aEvfMrKUwHwfwI0MuVUzdjBdAja21o/IsYTscm28bes7H2Uj3YKmYTGUkmkhCHKi
> LD3ShrW8i03A
> =xYvc

$ grep -A3 Checksum isc-dhcp*.dsc
isc-dhcp_4.4.1-2.3+deb11u1.dsc:Checksums-Sha1:
isc-dhcp_4.4.1-2.3+deb11u1.dsc- 2c52eac4eb3dc9a2ecde623b1a687fa0146a6ce9 1189920 isc-dhcp_4.4.1.orig.tar.gz
isc-dhcp_4.4.1-2.3+deb11u1.dsc- dcf53786e6b1650184fde075bbe25a0f3dd7e49c 89040 isc-dhcp_4.4.1-2.3+deb11u1.debian.tar.xz
isc-dhcp_4.4.1-2.3+deb11u1.dsc:Checksums-Sha256:
isc-dhcp_4.4.1-2.3+deb11u1.dsc- c8e079dd4303ed121811b05c9f62a37669b2c8d91658d47a5ec58ec34e5a8247 1189920 isc-dhcp_4.4.1.orig.tar.gz
isc-dhcp_4.4.1-2.3+deb11u1.dsc- b693380b77195e6e742848be2a86248506b0c9bbbb461622daa1ad5b36d9ac54 89040 isc-dhcp_4.4.1-2.3+deb11u1.debian.tar.xz
isc-dhcp_4.4.1-2.3+deb11u1.dsc-Files:
--
isc-dhcp_4.4.1-2.3.dsc:Checksums-Sha1:
isc-dhcp_4.4.1-2.3.dsc- 2c52eac4eb3dc9a2ecde623b1a687fa0146a6ce9 1189920 isc-dhcp_4.4.1.orig.tar.gz
isc-dhcp_4.4.1-2.3.dsc- aad326e51276efeb3d6d64b23f274eaaa329a737 88136 isc-dhcp_4.4.1-2.3.debian.tar.xz
isc-dhcp_4.4.1-2.3.dsc:Checksums-Sha256:
isc-dhcp_4.4.1-2.3.dsc- c8e079dd4303ed121811b05c9f62a37669b2c8d91658d47a5ec58ec34e5a8247 1189920 isc-dhcp_4.4.1.orig.tar.gz
isc-dhcp_4.4.1-2.3.dsc- 8396ddc072a5f1d1863f95ba8f95cb4d6f0de3928615038eeaa8897d966dcd35 88136 isc-dhcp_4.4.1-2.3.debian.tar.xz
isc-dhcp_4.4.1-2.3.dsc-Files:
 `

**Comment by saiarcot895** [comment]
That's standard practice for the source package (orig.tar.\*) being the same, but the debian package (debian.tar.\*) being different, since the upstream version is the same, but Debian is making specific changes. See [here](https://tracker.debian.org/news/1370213/accepted-isc-dhcp-441-23deb11u1-source-into-stable-security/) for details on the new version.

**Comment by guillaumelambert** [comment]
So this is CVE security updates by Debian security team.
Thanks for the pointer.

**Pull request merged**
