### PR TITLE
[dhcp_server] Fix the issue with "kea-dhcp4.conf" file generation for Smart Switch.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### Why I did it
The configuration generated from the template for the Smart Switch contained incorrect data in the "subnet4:id" field. For regular cases, the subnet ID is deduced from the VLAN name. For the Smart Switch, there is always one subnet, and the ID is set to 0.

```
"subnet4": [
        {
            "id": bridge-midplane,
            "subnet": "169.254.200.0/24",
            "pools": [
                {
                    "pool": "169.254.200.1 - 169.254.200.1",
                    "client-class": "sonic:dpu0"
                },
...
```

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Fix configuration generation for Smart Switch device.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by yaqiangz — APPROVED** [review]
Thanks for fix!

**Review by yaqiangz — CHANGES_REQUESTED** [review]
Hold on...
This change for setting subnet id is for support lease update (From kea-lease file to state_db)
[dhcp_lease.py#L123](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_lease.py#L123)
If this part doesn't corresponding support, lease information will be incorrect for smart swith..
Example:
In state_db, key would be stored like "DHCP_SERVER_IPV4_LEASE|Vlan0|aa:bb:cc:dd:ee:ff"
Could you add correspond support in it?
We can check add flag indicate whether it's smart switch via [is_smart_switch](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-dhcp-utilities/dhcp_utilities/common/utils.py#L168) in [KeaDhcp4LeaseHandler-init](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_lease.py#L91) and construct redis key by the flag in here [dhcp_lease.py#L123](https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-dhcp-utilities/dhcp_utilities/dhcpservd/dhcp_lease.py#L123)

**Comment by oleksandrivantsiv** [comment]
@yaqiangz I update the implementation. Please check.

**Review by yaqiangz — APPROVED** [review]
LGTM

**Comment by yaqiangz** [comment]
@yxieca Could you please help to merge this PR?

**Comment by oleksandrivantsiv** [comment]
@yxieca kindly reminder. Can you please merge the PR?

**Comment by yaqiangz** [comment]
Hi @yxieca could you please help to merge this PR?

**Comment by yaqiangz** [comment]
Hi @bingwang-ms, could you please help to approve the backport request?

**Pull request merged**
