### PR TITLE
Update XGS SAI version to 10.1.37.0 

### PR DESCRIPTION
**Pull request by kperumalbfn**
#### Why I did it
Update max queues in BCM SAI for TH5 in alignment with the flex counter blocks

Update XGS SAI version to 10.1.37.0

##### Work item tracking
- Microsoft ADO **(number only)**: 28967795

#### How I did it
Update Broadcom platform sai.mk with version 10.1.37.0

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311
- [x] 202405

### CODE REVIEW

**Review by Gfrom2016 — APPROVED** [review]
@kperumalbfn Could you list in the description what changes were included in this upgrade?

**Comment by kperumalbfn** [comment]
> @kperumalbfn Could you list in the description what changes were included in this upgrade?

Updated the description.

**Review by lguohan — APPROVED** [review]

**Comment by kperumalbfn** [comment]
Removing 202311 and 202405 labels as the latest SAI update will be part of PRs - https://github.com/sonic-net/sonic-buildimage/pull/19868 and https://github.com/sonic-net/sonic-buildimage/pull/19867

**Pull request merged**
