### PR TITLE
[Micas/Platform]platform support M2-W6510-32C

### PR DESCRIPTION
**Pull request by philo-micas**
#### Why I did it
Add new platform m2-w6510-32c(Trident 3)
ASIC Vendor: Broadcom
Switch ASIC: Trident 3
Port Config: 32×100G QSFP28

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by philo-micas** [comment]
@prgeor Please help review this PR, thanks.

**Review by Praveen-Brcm — APPROVED** [review]

**Pull request merged**
