### PR TITLE
[staticroutebfd] change bfd to singlehop

### PR DESCRIPTION
**Pull request by baorliu**
#### Why I did it
staticroutebfd should use singlehop bfd. Because of a bug (portchannel+singlehop) in the SDK, we were using multi-hop as a temporary workaround. Now the SDK issue is solved, need to switch to singlehop BFD mode.

##### Work item tracking
- Microsoft ADO **(25039238)**:

#### How I did it
change the multihop variable to "false" in staticroutebfd/vars.py 

#### How to verify it
verified it both in UT and testbed. using show bfd sum to confirm the Multihop field is false.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@prsunny can you help merge this

**Comment by StormLiangMS** [comment]
@prsunny  @abdosi  @baorliu  cherry pick conflict, pls resubmit separate PR for 202305.

**Comment by abdosi** [comment]
@baorliu please create PR for 202305 directly.

**Comment by baorliu** [comment]
> cherry pick conflict
a separate PR is created for 202305 branch:
https://github.com/sonic-net/sonic-buildimage/pull/17549

**Pull request merged**
