### PR TITLE
Update AclInterface and Management Interfaces parsing for multi-asic case

### PR DESCRIPTION
**Pull request by abdosi**
What/Why I did:

AclInterface and Management Interfaces are parsed on finding first valid node for it. 
Above logic works for multi-asic scenarios where ACL Interface and Management Interfaces are present in DPG order {Host, Asicx, Asicy} but not when DPG is in {Asicx, Asicy, Host} order.

Fixed the order dependency as part of this PR.

Microsoft ADO: https://msazure.visualstudio.com/One/_workitems/edit/17956325

How I verify:
Added UT by changing the order of DPG in test minigraph.
Verified manually.

### CODE REVIEW

**Comment by abdosi** [comment]
Hi @arlakshm can you please help review this.

**Review by arlakshm — APPROVED** [review]

**Comment by abdosi** [comment]
@lguohan: can you please help review/merge.

**Comment by gechiang** [comment]
@abdosi can you raise a different PR in 202205 for this as it can not be cleanly picked although approved for 202205 branch.
Thanks!

**Comment by rlhui** [comment]
Already in 202305 code base

**Pull request merged**
