### PR TITLE
[202205] [Mellanox] upgrade hw-management package to 7.0020.4305

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Depends on https://github.com/sonic-net/sonic-linux-kernel/pull/330

#### Why I did it

Upgrade hw-management package to 7.0020.4305

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Upgrade hw-management package to 7.0020.4305

#### How to verify it

Manual test
sonic-mgmt regression test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by prgeor** [comment]
@Junchao-Mellanox can you describe what all new changes are being included as part of updating to new package? And why?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox can you describe what all new changes are being included as part of updating to new package? And why?

Hi @prgeor , the changes contains a fix for reboot cause issue found by MSFT. The issue is that after doing Power Loss/Watchdog reboot, sometimes the reboot cause is Unknown.

**Comment by bingwang-ms** [comment]
Microsoft ADO: 24902299

**Comment by bingwang-ms** [comment]
@prgeor  Can you please help review this PR? Thanks

**Review by prgeor — APPROVED** [review]

**Pull request merged**
