### PR TITLE
[Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
- Add chassis platform API reboot
 - Add fwutil hooks for firmware updates
 - Fix PikeZ i2c bus identification issue
 - Fix testing issue

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@lguohan please help merge

**Comment by lguohan** [comment]
Fix PikeZ i2c bus identification issue

@prgeor , @Staphylo , should this issue be backported to 202205?

**Comment by Staphylo** [comment]
This is already taken care of by https://github.com/sonic-net/sonic-buildimage/pull/14039
202211 is still pending here https://github.com/sonic-net/sonic-buildimage/pull/14038

**Pull request merged**
