### PR TITLE
[Mellanox] Fix the issue with ASIC detection on the SN4280 platform

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### Why I did it
Fix the issue with ASIC detection on the SN4280 platform.

The root cause of the issue is in the PCI subsystem race condition. When the Dark Mode is enabled on the system start we do the following actions in parallel:
1.	The dpuctl service starts and powers down the DPUs which causes the DPU PCI devices removal.
2.	At the same time the syncd service starts. It launches mlnx-fw-upgrade.sh script which queries the available ASIC devices from the PCI subsystem using the lspci command. 

There is a small period after the removal of the DPU PCI device when the PCI subsystem in Linux remains inconsistent and lspci command might return an error upon execution. This might cause an error in mlnx-fw-upgrade.sh which interrupts the syncd container start.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add a retry mechanism for the lspci command. Cache lspci output to reduce the number of command executions. 

#### How to verify it
Run regression.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@oleksandrivantsiv seems there is a conflict to take it for 202405. please refer this issue to the new PR on 202405 for tracking

**Pull request merged**
