### PR TITLE
[202311][graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle 

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**DEPENDS ON: [[graceful reboot] Add the pre_reboot_hook script execution, add the watchdog arm before the reboot](https://github.com/sonic-net/sonic-utilities/pull/3204)**

#### Why I did it
Add support for the `graceful reboot` instead of  the `sysfs power cycle` to avoid filesystem corruption 

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Rename the `platform_reboot` script to the `pre_reboot_hook`.
Remove the sysfs power cycle function, from now on the Debian reboot (`/sbin/reboot`) will be executed instead of the sysfs power cycle.

#### How to verify it
1. Start watching logs by using `show log -f` and `journalctl -p debug -f`
2. Execute the `reboot` command from the switch CLI
3. Check in logs that all systemd services terminated 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@prgeor Can you please also review this PR? Thanks!

**Comment by liat-grozovik** [comment]
@yxieca kindly reminder, this is a major fix needed for 202311

**Review by prgeor — APPROVED** [review]

**Comment by vadymhlushko-mlnx** [comment]
@yxieca kind reminder to merge, the same changes were already merged into `master`

**Comment by prgeor** [comment]
@vadymhlushko-mlnx appreciate if you could point to the master PR in the description

**Comment by vadymhlushko-mlnx** [comment]
> @vadymhlushko-mlnx appreciate if you could point to the master PR in the description

[[graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle #18324](https://github.com/sonic-net/sonic-buildimage/pull/18324)

**Pull request merged**
