### PR TITLE
fixed nokia platform m0 asic mismatch

### PR DESCRIPTION
**Pull request by hehuang-nokia**
changed the platform device name under nokia directory; we now need to specify marvell armhf/arm64 to provide more accurate platform identity. otherwise onie discovery won't recognize the asic being installed.

#### Why I did it
when we load images using onie discovery, the process was failing because of marvell ASIC mismatch
#### How I did it
replace the platform asic with marvell-armhf under 7215
#### How to verify it
load a new image using http server and verify that the image can be loaded successfully

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Comment by Blueve** [comment]
@yaqiangz  for awareness. Some of tests were skipped by checking asic_type == 'marvell', now we'd better update these condition to 'marvell' in asic_type

**Comment by Blueve** [comment]
@hehuang-nokia which release branch will be impacted by this issue? Do you want to this fix backport to 202012 and 202205?

**Comment by hehuang-nokia** [comment]
> @hehuang-nokia which release branch will be impacted by this issue? Do you want to this fix backport to 202012 and 202205?

I tested latest 202205 which also has the issue but have not seen the problem in 202012 yet.  tests ongoing. will update and mark 202012 if problem found.

**Comment by hehuang-nokia** [comment]
@yaqiangz @Blueve Hi, regarding the checks that were unsuccessful in this PR, is PR 6401 attempting to fix them?

**Comment by Blueve** [comment]
@hehuang-nokia Current PR issue is not related to PR 6401. We raise PR 6401 was due to we are skipping some sonic-mgmt test cases by checking the asic_type and we need to update them accordingly.

For your PR, the build failure seems like caused by transient network issue. I will rerun these build pipelines

**Comment by Blueve** [comment]
@hehuang-nokia  could you sign CLA per above instruction?

**Comment by hehuang-nokia** [comment]
> @hehuang-nokia could you sign CLA per above instruction?

Thanks for the reminder and instructions. It has been signed.

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
@yxieca Could you help back port this fix to 202205?

**Pull request merged**
