### PR TITLE
Fix 202211 test_events to unblock PR checker

### PR DESCRIPTION
**Pull request by zbud-msft**
##### Work item tracking
- Microsoft ADO **(number only)**: 13366345

#### How I did it

Backport 3 necessary PRs for unblocking PR checker

https://github.com/sonic-net/sonic-buildimage/pull/15805  
https://github.com/sonic-net/sonic-buildimage/pull/14954  
https://github.com/sonic-net/sonic-buildimage/pull/13326 

#### How to verify it

Pipeline

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by StormLiangMS** [comment]
@zbud-msft pls give more info about which PR to backport and ADO info.

**Comment by zbud-msft** [comment]
> @zbud-msft pls give more info about which PR to backport and ADO info.

Added PRs that we are backporting and ADO #

**Review by yejianquan — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
