### PR TITLE
[Wistron] Add sw-to3200k and 6512-32r platform support

### PR DESCRIPTION
**Pull request by WistronNetwork**
#### Why I did it
Add sw-to3200k and 6512-32r support for 202111
#### How I did it
Add code in device and platform folder for 6512-32r
Update sw-to3200k code both in device and platform folder
#### How to verify it
Install on Wistron device and run command to verify, please check attachment for log

Signed-off-by: RogerChang [Roger_Chang@wistron.com](mailto:Roger_Chang@wistron.com)
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111
- [ ] 202205

#### A picture of a cute animal (not mandatory but encouraged)
[202111_sw_3200K_platform_enhance.log](https://github.com/Azure/sonic-buildimage/files/9098675/202111_sw_3200K_platform_enhance.log)

### CODE REVIEW

**Comment by shihjeff** [comment]
@sujinmkang This MR is back port from master of https://github.com/Azure/sonic-buildimage/pull/10956.  We've been trying to reach your team to back port via the labelling system. Since didn't hear back, opened this MR.

**Comment by WistronNetwork** [comment]
Hi @sujinmkang, since we have tight schedule, would you please review this PR? thanks.

**Comment by WistronNetwork** [comment]
@lizhuhuams  please help review, thanks in advance.

**Comment by WistronNetwork** [comment]
@yxieca , @lizhuhuams , please help review, thanks.

**Comment by WistronNetwork** [comment]
close this PR, we will have another new PR for these two platform.

**Pull request closed without merging**
