### PR TITLE
Add Wistron SW-TO3200K and 6512-32R platform support

### PR DESCRIPTION
**Pull request by RogerX87**
Signed-off-by: RogerX87 <RogerX87@gmail.com>

Add sw-to3200k and 6512-32r support for 202111

#### Why I did it
Add sw-to3200k and 6512-32r support for 202111

#### How I did it
Add code in device and platform folder for 6512-32r
Update sw-to3200k code both in device and platform folder

#### How to verify it
Install on Wistron device and run command to verify, please check attachment for log
Signed-off-by: RogerX87 <RogerX87@gmail.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [x] 202111
- [ ] 202205

#### A picture of a cute animal (not mandatory but encouraged)

[3200k_202111.log](https://github.com/sonic-net/sonic-buildimage/files/9400569/3200k_202111.log)

### CODE REVIEW

**Comment by WistronNetwork** [comment]
@yxieca , @sujinmkang , @lizhuhuams would you please review, thanks.

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@RogerX87 why is this PR directly against 202111 branch? Is there a master PR that cannot be cherry-pickec to 202111 branch cleanly?

**Comment by WistronNetwork** [comment]
@yxieca , actually we indeed request for backport 202111 but it didn't worked, and we also do some modification specific to 202111.

**Comment by yxieca** [comment]
> @yxieca , actually we indeed request for backport 202111 but it didn't worked, and we also do some modification specific to 202111.

@WistronNetwork thanks for the clarification, in the future, you could state in the PR comment that this PR is cherry-picking master branch PR #xxxx. so that reviewer won't ask this question again :-)

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@RogerX87 you might need to rebase your PR to the latest master branch head to pick up the build fixes.

**Comment by WistronNetwork** [comment]
@yxieca , thanks for kindly remind, please review again.

**Pull request merged**
