### PR TITLE
[Mellanox] Support SKU Mellanox-SN5600-O128

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it

Align ACS-SN5600 buffer templates to reduce redundant code
Support Mellanox-SN5600-O128

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add relevant files to support the new SKU
Update the SN5600 device files to align with the buffer configuration required.

#### How to verify it
Regression test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by keboliu** [comment]
@yxieca  would you please help to cherry-pick?

**Comment by yxieca** [comment]
> @yxieca would you please help to cherry-pick?

@keboliu this seems to be a new feature code? We only take bug fixes in feature branches

**Comment by keboliu** [comment]
> > @yxieca would you please help to cherry-pick?
> 
> @keboliu this seems to be a new feature code? We only take bug fixes in feature branches

Hi @yxieca  this is not a new feature, we updated some buffer configurations for existing SKU and also added a new SKU.

**Comment by keboliu** [comment]
> > @yxieca would you please help to cherry-pick?
> 
> @keboliu this seems to be a new feature code? We only take bug fixes in feature branches

Hi @yxieca this is not a new feature, we updated some existing buffer profile to fix some issue and also added a new SKU.

**Comment by yxieca** [comment]
> > > @yxieca would you please help to cherry-pick?
> > 
> > 
> > @keboliu this seems to be a new feature code? We only take bug fixes in feature branches
> 
> Hi @yxieca this is not a new feature, we updated some existing buffer profile to fix some issue and also added a new SKU.

Mellanox-SN5600-O128 is a brand new folder, how is it a bug fix?

**Comment by yxieca** [comment]
> > > > @yxieca would you please help to cherry-pick?
> > > 
> > > 
> > > @keboliu this seems to be a new feature code? We only take bug fixes in feature branches
> > 
> > 
> > Hi @yxieca this is not a new feature, we updated some existing buffer profile to fix some issue and also added a new SKU.
> 
> Mellanox-SN5600-O128 is a brand new folder, how is it a bug fix?

Per offline discussion with Liat, this hardware platform already existing in 202305. The new hardware sku doesn't contain code could affect other nvidia platforms. And the new hardware sku has been tested by nvidia on 202311 branch.

**Pull request merged**
