### PR TITLE
[202311][Mellanox]Enable forwarding of packets with link local SIP/DIP on specific platforms

### PR DESCRIPTION
**Pull request by dgsudharsan**
Cherry-pick of https://github.com/sonic-net/sonic-buildimage/pull/18487.

Must be merged after https://github.com/sonic-net/sonic-buildimage/pull/18570

#### Why I did it
Enable forwarding of packets with link local SIP/DIP on specific platforms and SKUs.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Setting SAI key value pair SAI_NOT_DROP_SIP_DIP_LINK_LOCAL=1

#### How to verify it
Manual test to verify that packets with link local SIP/DIP are not dropped

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@yxieca Can you please help to review and merge this cherry-pick?

**Comment by yxieca** [comment]
@dgsudharsan is this PR still in draft?

**Comment by dgsudharsan** [comment]
@yxieca It depends on merge of https://github.com/sonic-net/sonic-buildimage/pull/18570

**Comment by dgsudharsan** [comment]
@yxieca Can you please help to merge this PR?

**Pull request merged**
