### PR TITLE
[Mellanox] Disable SGX for SN5600/SN5400 platforms

### PR DESCRIPTION
**Pull request by vivekrnv**
#### Why I did it

Booting master/202405 images on SN5400 and SN5600 platforms is resulting the log

```
2024-07-23T21:01:07.972045+00:00 sonic kernel: [    0.110657] x86/cpu: SGX disabled by BIOS.
2024-07-23T21:01:07.972045+00:00 sonic kernel: [    0.110657] x86/cpu: SGX disabled by BIOS.
```

Processor on these systems supports the SGX but the BIOS does not. SGX feature is also not important and thus disable using the nosgx kernel boot parameter

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it

Added the parameter, reboot and check for log

### CODE REVIEW

**Comment by vivekrnv** [comment]
@davidpil2002 Please review

**Review by DavidZagury — APPROVED** [review]
Looks good to me

**Review by saiarcot895 — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@saiarcot895 @bingwang-ms We have ms_conflict validation failing here. Can you please help?

**Comment by vivekrnv** [comment]
Cherry-pick is failing because of pending cherry-pick of this. https://github.com/sonic-net/sonic-buildimage/pull/19965

Will remove and re-add the Tag after the dependent PR is merged

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
