### PR TITLE
Revert: "[swss/syncd] remove dependency on interfaces-config.service"

### PR DESCRIPTION
**Pull request by nazariig**
This reverts https://github.com/sonic-net/sonic-buildimage/pull/13084

Resolves https://github.com/sonic-net/sonic-buildimage/issues/15076

#### Why I did it
* To stabilize warm/fast reboot

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
* Reverted changes

#### How to verify it

* Run warm/fast reboot

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [X] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [X] master 
- [ ] 202211 
- [ ] 202205 

#### Link to config_db schema for YANG module changes

* N/A

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
@StormLiangMS can you please assist to merge? The revert was agreed with Ying and Stepan on offline discussion

**Comment by nazariig** [comment]
@qiluo-msft / @yxieca would you please help to merge?

**Comment by yxieca** [comment]
> @qiluo-msft / @yxieca would you please help to merge?

There was an ongoing discussion started by Saikrishna. Please wait for that discussion to close first.

**Comment by liat-grozovik** [comment]
@yxieca could you please update on decision moving forward?

**Comment by nazariig** [comment]
Closing the PR in favour of https://github.com/sonic-net/sonic-buildimage/pull/15080

**Pull request closed without merging**
