### PR TITLE
Tjcw fix vtysh for  -f -

### PR DESCRIPTION
**Pull request by tjcw**
#### Why I did it
I needed vtysh to be able to take input from a pipe, i.e. something like
{
  echo list
  echo list
} | vtysh -f -
#### How I did it
I made changes to the file handling in vtysh so that piped input works; the old code had a dependency on the -f value representing a real file and not a pipe, I removed this dependency
#### How to verify it
Try 
{
  echo list
  echo list
} | docker -i bgp vtysh
to the SONiC shell
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106

### CODE REVIEW

**Comment by tjcw** [comment]
Apologies for forgetting to sign off the commit with '-s'

**Comment by tjcw** [comment]
@lguohan please review this PR

**Comment by tjcw** [comment]
@lguohan what is the next step for this PR ? I think it is ready for review and merge, but if you think it needs further developement please let me know what area I should attend to. Thanks ! Chris Ward, IBM.

**Comment by tjcw** [comment]
@lguohan what is the next step for this PR ? I think it is ready for review and merge, but if you think it needs further developement please let me know what area I should attend to. Thanks ! Chris Ward, IBM.

**Comment by tjcw** [comment]
@lguohan what is the next step for this PR ? IBM would like it integrated into master so that I do not have to maintain a separate branch.

**Comment by lguohan** [comment]
is this upstreamed to frr community?

**Comment by tjcw** [comment]
I am no longer working in this area. I believe the fix would be useful, but I cannot progress it myself. Closing.

**Pull request closed without merging**
