### PR TITLE
Update cisco-8000.ini to 202405.0.8 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: Anand Mehra anamehra@cisco.com

Update cisco-8000.ini to 202405.0.8 release

#### Why I did it

Release Content

* SDK HEALTH event notification causing orchagent crash disabled
* Support for Multiple rconsole sessions to difference LCs from Chassis Supervisor.
* Fixed FC asic init failure on Chassis Supervisor reboot
* Added New CLI to display LC Back Plane port to Sup/RP port mapping. 'show platform npu bp-interface-map -n '
* Fixed Log Analyzer error “counter read timeout”
* Fixed Log Analyzer ERROR avago_sbm_spico_int_read
* Enabled enable_mbist_repair across platforms
* Syncd Rpc docker python version migrated to python3

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by anamehra** [comment]
Hi @abdosi , @yejianquan , for your viz. Thanks

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
Hi @StormLiangMS , could you help to merge this PR?
https://github.com/Cisco-8000-sonic/platform-cisco-8000/releases/tag/202405.0.8

**Comment by anamehra** [comment]
Hi @kevinskwang , @StormLiangMS , for your viz. Thanks

**Comment by kevinskwang** [comment]
@bingwang-ms  could you help to merge and make a formal tag?

**Pull request merged**
