### PR TITLE
Update sonic-frr submodule to FRR 8.2.2

### PR DESCRIPTION
**Pull request by hasan-brcm**
#### Why I did it
The sonic-frr was upgraded to FRR 8.2.2 as part of PR #10691. However, sonic-frr/frr submodule was still referring to previous 7.5 version. Update the sonic-frr/frr submodule to 8.2.2 commit id. Fixes issue #11484. 

#### How I did it
- checkout FRR 8.2.2 commit id 79188bf in sonic-frr/frr
- commit and push

#### How to verify it
- build and load

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

#### Description for the changelog
Update sonic-frr/frr submodule to frr 8.2.2 commit 79188bf 

#### A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Comment by DavidZagury** [comment]
It should also be backported to 202205

**Comment by zhangyanzhao** [comment]
Need merge this issue for 202205.

**Comment by dgsudharsan** [comment]
I went through the list of patches that were removed in the FRR upgrade https://github.com/sonic-net/sonic-buildimage/pull/10691. 

There is one patch of concern.

src/sonic-frr/patch/0009-Link-local-scope-was-not-set-while-binding-socket-for-bgp-ipv6-link-local-neighbors.patch

In FRR
Introduced: https://github.com/sonic-net/sonic-frr/commit/0b6d35324ef3fd2b4d5997103795cad73eb72954

Reverted: https://github.com/sonic-net/sonic-frr/commit/6740a191adb7e330370d568c9192624a22b008cb (https://github.com/FRRouting/frr/pull/8430)

However, this patch was introduced in SONiC but never reverted. Now with upgrading to FRR and without this patch won’t we be facing issues?

**Comment by hasan-brcm** [comment]
> I went through the list of patches that were removed in the FRR upgrade #10691.
> 
> There is one patch of concern.
> 
> src/sonic-frr/patch/0009-Link-local-scope-was-not-set-while-binding-socket-for-bgp-ipv6-link-local-neighbors.patch
> 
> In FRR Introduced: [sonic-net/sonic-frr@0b6d353](https://github.com/sonic-net/sonic-frr/commit/0b6d35324ef3fd2b4d5997103795cad73eb72954)
> 
> Reverted: [sonic-net/sonic-frr@6740a19](https://github.com/sonic-net/sonic-frr/commit/6740a191adb7e330370d568c9192624a22b008cb) ([FRRouting/frr#8430](https://github.com/FRRouting/frr/pull/8430))
> 
> However, this patch was introduced in SONiC but never reverted. Now with upgrading to FRR and without this patch won’t we be facing issues?

Please note that patch file 0009-Link-local-scope.. has been replaced with [0008-Link-local-scope..](https://github.com/sonic-net/sonic-buildimage/pull/10691/files#diff-cd5cfc41e5f3583085d4632c591a487cb2ec39b9b6812d7f475a24c6c63fd5a6):

Regarding the changes in the 0009-Link-local-scope file, one of the changes is already present in the [8.2.2 code](https://github.com/FRRouting/frr/blob/79188bf710e92acf42fb5b9b0a2e9593a5ee9b05/bgpd/bgp_zebra.c#L791):

**Review by dgsudharsan — APPROVED** [review]

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
Thanks for your explanation. However I see the changes in patch 0008-Link-local-scope-was-not-set-while-binding-socket-for-bgp-ipv6-link-local-neighbors.patch are not in upstream FRR since they were reverted. I am not sure if SONiC would allow patches that are not in upstream. @lguohan  @prsunny @abdosi can you please provide feedback here?

**Comment by liat-grozovik** [comment]
@prsunny could you please help to review prev comment? As 202205 should include the new frr version I believe we need to push this with high prio. If fix still need to be done let's close the gap

**Review by dgsudharsan — APPROVED** [review]

**Pull request merged**
