### PR TITLE
[Mellanox] Enable get_tx_fault support in CMIS cable host mgmt mode

### PR DESCRIPTION
**Pull request by yuazhe**
#### Why I did it
Enable get_tx_fault support in CMIS cable host mgmt mode on Mellanox platforms

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Use community get_tx_fault implementation instead of the dummy one

#### How to verify it
API call and run API Test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x]  202311
- [ ]

### CODE REVIEW

**Comment by liushilongbuaa** [comment]
please rebase master branch.

**Comment by yuazhe** [comment]
> please rebase master branch.

done.

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@prgeor FYI

**Pull request merged**
