### PR TITLE
[pddf]: Adding support for I2CFPGA in PDDF

### PR DESCRIPTION
**Pull request by FuzailBrcm**
#### Why I did it
Some of the platform vendors use FPGA in the HW design. This FPGA is connected to the CPU via I2C bus. Adding a common module and a driver to be used for such FPGA in PDDF.

#### How I did it
Added 'pddf_fpgai2c_module' and 'pddf_fpgai2c_driver' kernel modules which takes the platform dependent data from PDDF JSON files and creates an I2C client for the FPGA.

#### How to verify it
Any platform having such an FPGA and brought up using PDDF would use these kernel modules. The detail representation of such a device in PDDF JSON file is covered in the HLD.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by adyeung** [comment]
@jostar-yang pls help review

**Comment by FuzailBrcm** [comment]
@celestica-gl , @qnos 

Please review.

**Review by jostar-yang — APPROVED** [review]
The code is fine to me

**Review by qnos — APPROVED** [review]

**Comment by adyeung** [comment]
@prgeor pls help merge this PR

**Pull request merged**
