### PR TITLE
[202012][submodule] Advance sonic-swss pointer

### PR DESCRIPTION
**Pull request by dprital**
Signed-off-by: dprital <drorp@nvidia.com>

#### Why I did it

Update sonic-swss submodule pointer to include the following:
* 08711a8 [orchdaemon]: Fixed sairedis record file rotation ([#2481](https://github.com/sonic-net/sonic-swss/pull/2481))

#### How I did it

Advance sonic-swss pointer

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@bacrossland I believe your PR is causing some failures. Could you please check if something else is missing in order to have this fix in 202012?

**Comment by bacrossland** [comment]
@liat-grozovik yes, I'll have a look

**Comment by bacrossland** [comment]
@liat-grozovik @dprital this PR should fix the issue with my swss changes not compiling for this branch. GMock is missing in buildimage.

https://github.com/sonic-net/sonic-buildimage/pull/12476

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
