### PR TITLE
Update dhcpv6-relay yang model

### PR DESCRIPTION
**Pull request by kellyyeh**
#### Why I did it
Add interface-id in dhcpv6-relay yang model

#### How I did it
Add interface-id option and corresponding UT. Updated configuration.md

#### How to verify it

kellyyeh@kellyyeh:~/sonic-buildimage/src/sonic-yang-models$ pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/sonic-dhcpv6-relay.yang

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
I don't see rfc6939_support. Please add that as well. You need to add UT, update sample_config_db.json and update configuration guide.  Please check this PR for example https://github.com/sonic-net/sonic-buildimage/pull/13735

**Comment by kellyyeh** [comment]
> rfc6939_support

rfc6939_support is already included. https://github.com/sonic-net/sonic-buildimage/blob/2ba2ff1398032dc39ce516f31390b0ec5fcf6657/src/sonic-yang-models/yang-models/sonic-dhcpv6-relay.yang#L42
Will add UT

**Review by jcaiMR — COMMENTED** [review]
We may also need update test cases for this yang module. 
Test cases under:
sonic-yang-models/tests/yang_model_tests/tests/

**Comment by jcaiMR** [comment]
> We may also need update test cases for this yang module. Test cases under: sonic-yang-models/tests/yang_model_tests/tests/

I see there already comments about this :-)

**Comment by zhangyanzhao** [comment]
@kellyyeh  can you please help to fix the conflict? Thanks.

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@kellyyeh Can you please resolve the conflicts and push again?

**Comment by liat-grozovik** [comment]
@kellyyeh please handle conflicts.
I do believe we need it for 202211 and 202205. can you please check if this can be cleanly cherry picked ?

**Comment by dgsudharsan** [comment]
@kellyyeh I believe the conflict still exists. Can you please check?

**Comment by kellyyeh** [comment]
> @kellyyeh I believe the conflict still exists. Can you please check?

Thanks, should be resolved now

**Comment by kellyyeh** [comment]
> @kellyyeh please handle conflicts. I do believe we need it for 202211 and 202205. can you please check if this can be cleanly cherry picked ?

Seems like it cannot be cherry-picked cleanly, I will create cherry-pick PRs after this is merged

**Comment by dgsudharsan** [comment]
@yxieca @kellyyeh @qiluo-msft Can you please help merge this?

**Pull request merged**
