### PR TITLE
[Nokia][sonic-platform] Update nokia sonic-platform submodule with thermal coherence changes to be paired with NDK >= 22.9.26

### PR DESCRIPTION
**Pull request by snider-nokia**
These changes ensure proper thermal subsystem operation when removing ASIC internal thermal sensor polling from NDK.
     - Please pair this submodule update with NDK >= 22.9.26 : NDK 22.9.26 PR is here:  https://github.com/Azure/sonic-buildimage-msft/pull/316
    -  This PR is 202205 specific.  The associated master PR is here:  https://github.com/sonic-net/sonic-buildimage/pull/18564

Edit:  Now also includes kernel module changes for error level messages to warning level (this change is 202205 specific and not applicable to master) as well as fix for show chassis module with correct linecard description (https://github.com/Nokia-ION/ndk/issues/45).

#### Why I did it
These changes are required in order to ensure thermal subsystem coherence when removing 'bcmcmd show pvt' ASIC thermal sensor polling from NDK.

Please pair this submodule update with NDK >= 22.9.26 : NDK 22.9.26 PR is here:  https://github.com/Azure/sonic-buildimage-msft/pull/316

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Made the necessary modifications to facilitate coherent temp sensor operations.

#### How to verify it
Verify that thermal subsystem operates normally via 'show platform temperature' command.

Please pair this submodule update with NDK >= 22.9.26 : NDK 22.9.26 PR is here:  https://github.com/Azure/sonic-buildimage-msft/pull/316

### CODE REVIEW

**Comment by snider-nokia** [comment]
@judyjoseph, Can you please review and merge?  Thanks.

**Review by judyjoseph — APPROVED** [review]

**Review by gechiang — APPROVED** [review]

**Comment by judyjoseph** [comment]
@snider-nokia could you update the fix for https://github.com/Nokia-ION/ndk/issues/45, also into this platform modules update

**Comment by judyjoseph** [comment]
@snider-nokia could you update the fix for https://github.com/Nokia-ION/ndk/issues/45, also into this platform modules update

**Comment by snider-nokia** [comment]
> @snider-nokia could you update the platform modules update Pr with the fix for [Nokia-ION/ndk#45](https://github.com/Nokia-ION/ndk/issues/45) also, before we merge @rlhui f.y.i

Ok, all set now @judyjoseph.

**Comment by snider-nokia** [comment]
> @snider-nokia , can you also ensure fixes like this are always pushed to public master as well? and its corresponding SDK also in msft repo Master? Thanks!

Yes @gechiang, we are doing so.  Some changes are either master or 202205 specific, so we are handling individually (but keeping a close eye to ensure all changes are made at both branches).  Also, we will discuss NDK at next appropriate meeting since the master and 202205 builds have now diverged there as well.  Will keep you informed as to any/all decisions made in this regard.

**Pull request merged**
