### PR TITLE
Clear FABRIC_PORT_TABLE when swss is got down

### LINKED ISSUE #18554: [Chassis][multi-asic] Stopping swss services on SFMs should remove the related fabric reachability links but it does not
#### Description
When stopping swss services on SFMs,  the related fabric reachability information do not get remove from the database. 

#### Steps to reproduce the issue:
1.Ensure the related swss a syncd are up and running.

```
admin@ixre-cpm-chassis11:~$ docker ps -a
CONTAINER ID   IMAGE                                COMMAND                             CREATED      STATUS    PORTS     NAMES
1c6ac7cd1594   docker-syncd-brcm-dnx:latest     "/usr/local/bin/supeâ¦"   5 days ago   Up 27 hours            syncd15
2a0675724b5a   docker-orchagent:latest              "/usr/bin/docker-iniâ¦"   5 days ago   Up 27 hours             swss14
9f06a06e5907   docker-orchagent:latest               "/usr/bin/docker-iniâ¦"   5 days ago   Up 27 hours             swss15
7b6bde1b5460   docker-syncd-brcm-dnx:latest   "/usr/local/bin/supeâ¦"   5 days ago   Up 27 hours             syncd14
```
2.show fabric reachability information for acic14 and asic15

admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic14 | grep up | wc
     72     288    3960
admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic15 | grep up | wc
     72     288    3960
 
3.Stop swss services

admin@ixre-cpm-chassis11:~$ sudo systemctl stop swss@14
admin@ixre-cpm-chassis11:~$ sudo systemctl stop swss@15

4. Check swss and syncd dockers. Ensure they have exited.

```
admin@ixre-cpm-chassis11:~$ docker ps -a
1c6ac7cd1594   docker-syncd-brcm-dnx:latest     "/usr/local/bin/supeâ¦"   5 days ago   Exited (0) 5 seconds ago     syncd15
2a0675724b5a   docker-orchagent:latest              "/usr/bin/docker-iniâ¦"   5 days ago   Exited (0) 26 seconds ago    swss14
9f06a06e5907   docker-orchagent:latest               "/usr/bin/docker-iniâ¦"   5 days ago   Exited (0) 11 seconds ago    swss15
7b6bde1b5460   docker-syncd-brcm-dnx:latest   "/usr/local/bin/supeâ¦"   5 days ago   Exited (0) 18 seconds ago    syncd14
```

5. Show fabric reachibilty information on each related asics.   These entries should have been removed but they are not.

admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic15 | grep up | wc
     72     288    3960
admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic14 | grep up | wc
     72     288    3960

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

### PR DESCRIPTION
**Pull request by wumiaont**
#### Why I did it
fix #18554

Issue 18554(https://github.com/sonic-net/sonic-buildimage/issues/18554) describes an issue of that when stopping swss services on SFMs, the related fabric reachability information do not get remove from the database.

It's found that corresponding fabric port status information is in STATE_DB with key FABRIC_PORT_TABLE|PORTxxx.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add clean table action for FABRIC_PORT_TABLE in STATE_DB when swss service is down.

#### How to verify it
Made changes and loaded the changes into chassis. Run "show fabric reachability -n asic7" to see the fabric ports. Also checked STATE_DB by using "sonic-db-cli -n asic7 STATE_DB hgetall "FABRIC_PORT_TABLE|PORT112" where port 112 is connected and up.

Issue "sudo systemctl stop swss@7". Check "show fabric reachability -n asic7". It's empty now.
Issue "sudo systemctl start swss@7" or "docker start swss7". Wait for 1 minutes. Run "show fabric reachability -n asic7", all connected port are displayed there. Also checked STATE_DB and all entries with key FABRIC_PORT_TABLE|PORTxxx are correct.
Issue "docker kill swss7". Repeat testing steps in 1). It works as exepcted.
Enter container swss7. Run "kill 35" where 35 is task id for orchagent. Watched container swss7 is stopped and then restarted. Watched the "Cleared FABRIC_PORT_TABLE from STATE_DB for swss7" log showed up after container is stopped.
#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [X] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)
master, 202205

### CODE REVIEW

**Comment by arlakshm** [comment]
@jfeng-arista , @ysmanman, @kenneth-arista  for viz...

**Review by arlakshm — DISMISSED** [review]

**Review by judyjoseph — DISMISSED** [review]

**Comment by judyjoseph** [comment]
@lguohan @rlhui please help to merge

**Comment by wumiaont** [comment]
@rlhui Please help to merge.

**Comment by wumiaont** [comment]
/azpw run Azure.sonic-buildimage (Test kvmtest-t0 by Elastictest)

**Comment by wumiaont** [comment]
@judyjoseph @arlakshm please re-approve and help to merge. Thanks.

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@rlhui please help merge this PR

**Pull request merged**
