### PR TITLE
[System Ready]Handle template value for feature table state field

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### Why I did it
To fix the issue  https://github.com/sonic-net/sonic-buildimage/issues/15935 where system ready state is 'Not ready' while all expected services are ready. This is due to some FEATURE table entries have state value as template and thus in sysmonitor when the value is checked whether its not [disabled](https://github.com/sonic-net/sonic-buildimage/blob/2e1410c7b7975d3bc5fad19d07fa7958f65ad9c4/src/system-health/health_checker/sysmonitor.py#L186) , the feature is assumed to be enabled and to be started by systemd while the rendering would result in disabled resulting in systemd not starting the feature.

Sysmonitor dnsrvs_name will this have this feature and consider the system wrongly down.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Handled dynamic rendering of the feature

#### How to verify it
Run UT. Run install of system and ensure system state is not down when all services are up.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@sg893052  Can you please review this fix?

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by sg893052 — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca could you help to merge it following the approval flow?

**Comment by StormLiangMS** [comment]
enhancement, no cherry pick to 202305 at this stage.

**Pull request merged**
