### PR TITLE
Adding support for FPGAPCIe in PDDF

### PR DESCRIPTION
**Pull request by FuzailBrcm**
#### Why I did it
Some of the platform vendors use FPGA in the HW design. This FPGA is connected to the CPU via PCIe interface. This FPGA also works as an I2C controller having other devices attached to the I2C channels emanating from it. Adding a common module, a driver and a platform specific algorithm module to be used for such FPGA in PDDF.

#### How I did it
Added 'pddf_fpgapci_module', 'pddf_fpgapci_driver' and a sample algorithm module for Xilinx device 7021. Kernel modules which takes the platform dependent data from PDDF JSON files and initialises the PCIe FPGA. The sample algorithm module can be used by the ODMs in case the communication algorithms are same for their device. Else, they need to come up with similar algo module.

#### How to verify it
Any platform having such an FPGA and brought up using PDDF would use these kernel modules. The detail representation of such a device in PDDF JSON file is covered in the HLD.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by adyeung** [comment]
@jostar-yang pls help review

**Comment by FuzailBrcm** [comment]
@celestica-gl , @qnos 

Please review.

**Review by jostar-yang — APPROVED** [review]
The code is fine.

**Review by qnos — APPROVED** [review]

**Comment by adyeung** [comment]
@prgeor pls help merge this PR

**Comment by FuzailBrcm** [comment]
@prgeor pls help merge this PR

**Pull request merged**
