### PR TITLE
Platform DCS-7060DX5-64S misc update

### PR DESCRIPTION
**Pull request by vincentpcng**
#### Why I did it
This is to add the HWSKU DCS-7060DX5-64S misc update. This is a must have for the platform support. This should get into the master branch as soon as possible and back port to the needed releases.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Adding additional media,  port config settings etc needed for the HWSKU.
This is an updated version of an older PR #19109 for 202305 which is closed. This PR should replace the older PR#19109 and should be cast to all active releases. This PR has the latest chip configuration  base on Arista lab setting and the most up to date SI setting for optical transceivers.

#### How to verify it
We have verified it in house using the sonic mgmt test.
In additional, we have verify all the SI value which  match our HW database for optical deployment.
This changes has been verified in Arista lab with 202305 , 202311, 202405 releases.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [X] 202305
- [X] 202311
- [X] 202405
- #### Tested branch (Please provide the tested image version)

- [x] 202305
- [x] 202311
- [x] 202405

### CODE REVIEW

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by vincentpcng** [comment]
This PR look like is already in the 202411, master, 202405, 202311

**Pull request merged**
