### PR TITLE
[Mellanox] Add mlxtrace to techsupport 

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
#### Why I did it
Added the fwtrace config files in order to be able to call the `mlxstrace` utility during the `show techsupport` dump.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added fwtrace config files. Added path to these files to sai.profile for each mlnx device.

#### How to verify it
Execute the `show techsupport` command and check if `mlxstrace` output is in system dump.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by vadymhlushko-mlnx** [comment]
Cherry-pick for `202211`
[[202211][mlxtrace] Add fwtrace config files. Add path to these files to sai.profile for each mlnx device. #15960](https://github.com/sonic-net/sonic-buildimage/pull/15960)

**Comment by vadymhlushko-mlnx** [comment]
@qiluo-msft could you please help to review and merge this PR and cherry-picks?

**Comment by vadymhlushko-mlnx** [comment]
Cherry-pick for `202205`
[[202205][mlxtrace] Add mft-fwtrace-cfg.deb which contains fwtrace_cfg files. Add path to these files to sai.profile for each mlnx device.](https://github.com/sonic-net/sonic-buildimage/pull/15982)

**Review by nazariig — APPROVED** [review]

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
please wait for my approval for this PR and the related ones avaialble for other branches

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
