### PR TITLE
[minigraph] Add rack_mgmt_rack parse support in minigraph.py

### PR DESCRIPTION
**Pull request by yaqiangz**
#### Why I did it
We need to store information of power shelf in config_db for SONiC MX switch. Current minigraph parser cannot parse rack_mgmt_map field.

##### Work item tracking
- Microsoft ADO **(number only)**: 22179645

#### How I did it
Add support for parsing rack_mgmt_map.

#### How to verify it
1. Run `config load_minigraph` cmd to verify.
2. Unit test
```
test_minigraph_rack_mgmt_map (tests.test_minigraph_case.TestCfgGenCaseInsensitive) ... ok
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Blueve — DISMISSED** [review]

**Comment by Blueve** [comment]
+ @ganglyu can you help review the YANG part?

**Comment by ganglyu** [comment]
Please create two PRs, the first PR is for sonic-yang-models, and the second PR is for sonic-config-engine.

**Comment by Blueve** [comment]
This PR requires https://github.com/sonic-net/sonic-buildimage/pull/15109 merge first

**Comment by yaqiangz** [comment]
@yxieca Could you pls help to merge this PR?

**Pull request merged**
