### PR TITLE
[Dell] Update FPGA driver - S52xx, Z9264

### PR DESCRIPTION
**Pull request by ArunSaravananBalachandran**
#### Why I did it

Update FPGA driver `dell_fpga_ocores` for Dell S52xx and Z9264 platforms.
(Independent of FPGA firmware version)

Logs: [Dell_S5224_logs.txt](https://github.com/sonic-net/sonic-buildimage/files/14686534/Dell_S5224_logs.txt)

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [x] 202211
- [x] 202305

#### Description for the changelog

Update FPGA driver for Dell S52xx and Z9264 platforms

### CODE REVIEW

**Review by srideepDell — APPROVED** [review]

**Comment by jeff-yin** [comment]
@lguohan @zhangyanzhao @prgeor -- can someone review/approve/merge this? We have a user who is inquiring about this fix.

**Comment by lguohan** [comment]
can you add some description to indicate which platform is affected? and if such change is backward compatible? for example, if the FPGA on the system is still some older version?

**Comment by ArunSaravananBalachandran** [comment]
> can you add some description to indicate which platform is affected? and if such change is backward compatible? for example, if the FPGA on the system is still some older version?

The platform details have been updated.

**Comment by zhangyanzhao** [comment]
@jeff-yin  @prgeor  @yxieca  can you please help to review this PR? Thanks.

**Review by jeff-yin — APPROVED** [review]

**Comment by jeff-yin** [comment]
I've approved, but a repo owner needs to merge. Thanks!

**Pull request merged**
