### PR TITLE
[Nokia-IXR7250E][Devicedata] Update HW Lane for Inband and Rec ports

### PR DESCRIPTION
**Pull request by saksarav-nokia**
#### Why I did it
HW Lane for Inband and Rec ports were conflicting with front panel ports
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Updated the HW lane for Inband and Rec ports
#### How to verify it
Verified the device in the Nokia chassis 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ x] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by judyjoseph — APPROVED** [review]
LGTM

**Comment by deepak-singhal0408** [comment]
MSFT ADO: 26910111

**Comment by judyjoseph** [comment]
@rlhui to help review and merge

**Comment by StormLiangMS** [comment]
@deepak-singhal0408  could you update ADO in the description?

**Comment by deepak-singhal0408** [comment]
Hi @StormLiangMS , updated..

**Pull request merged**
