### PR TITLE
[202211][Mellanox] Add mlxtrace to techsupport  (#15961)

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
Backport of https://github.com/sonic-net/sonic-buildimage/pull/15961
#### Why I did it
Added the fwtrace config files in order to be able to call `mlxstrace` utility during `show techsupport` dump.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added fwtrace config files. Added path to these files to sai.profile for each mlnx device.

#### How to verify it
Execute the `show techsupport` command and check if `mlxstrace` output is in system dump.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### A picture of a cute animal (not mandatory but encouraged)

### CODE REVIEW

**Review by nazariig — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@StormLiangMS  please help to merge

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
