### PR TITLE
[202211][SNMP][IPv6]: Revert PRs to support SNMP over IPv6

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
#### Why I did it
Reverting PR added to support SNMP over IPv6 as there is an open issue https://github.com/sonic-net/sonic-buildimage/issues/16165 

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Revert https://github.com/sonic-net/sonic-buildimage/pull/16013 and https://github.com/sonic-net/sonic-buildimage/pull/15487 form 202211 branch

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by SuvarnaMeenakshi** [comment]
Requires sonic-mgmt PR  https://github.com/sonic-net/sonic-mgmt/pull/9630 to skip SNMP IPv6 related tests

**Review by qiluo-msft — APPROVED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Comment by keboliu** [comment]
@SuvarnaMeenakshi  would you please check the checker failure?

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi would you please check the checker failure?

The failure is seen test_telemetry and is not related to this revert PR.
Restarted pipeline

**Comment by dgsudharsan** [comment]
@SuvarnaMeenakshi Can you please restart the checkers again. I believe the telemetry failure got fixed.

**Comment by dgsudharsan** [comment]
@SuvarnaMeenakshi The build keeps failing. Can you please investigate?

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi The build keeps failing. Can you please investigate?

Raised this PR in sonic-mgmt to skip based on release https://github.com/sonic-net/sonic-mgmt/pull/9856, will re-run here once sonic-mgmt PR is merged in.

**Comment by dgsudharsan** [comment]
@qiluo-msft @SuvarnaMeenakshi Can we merge this?

**Comment by dgsudharsan** [comment]
@StormLiangMS Can you please help to merge this PR to 202211?

**Pull request merged**
