### PR TITLE
[submodule] update for sonic-utilities

### PR DESCRIPTION
**Pull request by siqbal1986**
#### What I did it
Updated sonic-utilities submodule:
d08f59b9 - 2023-02-06 : Fixed a bug in "show vnet routes all" causing screen overrun. (#2644) (#2654) [siqbal1986]
a996abdb - 2023-02-05 : [202012][show] show logging CLI support for logs stored in tmpfs (#2652) [mihirpat1]
c60f771c - 2023-01-25 : [202012][show_bfd] add local discriminator in show bfd command (#2616) [Baorong Liu]

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
@siqbal1986 PR owner could use another triggering command `/azpw run Azure.sonic-buildimage`.

**Comment by prsunny** [comment]
@siqbal1986 , can you please update to the latest commit?

**Comment by siqbal1986** [comment]
@qiluo-msft could you please merge it or close it if it is obsolete.

**Comment by prsunny** [comment]
@siqbal1986 , Qi's ask is to resolve the conflict for this PR

**Comment by prsunny** [comment]
Closing this in favor of https://github.com/sonic-net/sonic-buildimage/pull/13734

**Pull request closed without merging**
