### PR TITLE
[Broadcom] Upgrade xgs SAI version to 10.1.38.0

### PR DESCRIPTION
**Pull request by Gfrom2016**
#### Why I did it
Upgrade xgs SAI version to 10.1.38.0
- 10.1.38.0: [CSP CS00012359404] Port SONIC-93179 to SAI 10.1 branch
##### Work item tracking
- Microsoft ADO **(number only)**: 29094720

#### How I did it
Upgrade the SAI version in the sai.mk file.

#### How to verify it
https://dev.azure.com/mssonic/internal/_build/results?buildId=620112&view=results

#### Which release branch to backport (provide reason below if selected)

- [x] 202311
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by kperumalbfn** [comment]
@Gfrom2016 Could you check the conflict with LIBSAIBCM_DNX_VERSION

**Comment by Gfrom2016** [comment]
> @Gfrom2016 Could you check the conflict with LIBSAIBCM_DNX_VERSION

Thanks for reminding me. Fixed.

**Comment by Gfrom2016** [comment]
@StormLiangMS Could you help review and merge this? Thanks.

**Comment by Gfrom2016** [comment]
@StormLiangMS could you help review this PR?

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
PR already merged to 202405 https://github.com/sonic-net/sonic-buildimage/pull/19964

**Pull request merged**
