### PR TITLE
[devices] Add DPB support for x86_64-dell_z9100_c2538-r0

### PR DESCRIPTION
**Pull request by msosyak**
#### Why I did it
Added DPB support for x86_64-dell_z9100_c2538-r0 device

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
- Added new SKU folder `Force10-Z9100` based on `Force10-Z9100-C32`
- Added `platform.json` and `hwsku.json`
- Added generic `th-z9100-flex-all.config.bcm`

#### How to verify it
On `x86_64-dell_z9100_c2538-r0` with changes from this PR 
- change default SKU to `Force10-Z9100` 
- do factory reset
- reboot

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

DPB support added for x86_64-dell_z9100_c2538-r0

### CODE REVIEW

**Comment by msosyak** [comment]
@arunlk-dell @prgeor Please review

**Comment by andriy-kokhan** [comment]
@lguohan , @qiluo-msft , @wangxin , looks like we are good to go. Please approve and merge. Thank you in advance!

**Review by prgeor — APPROVED** [review]

**Comment by andriy-kokhan** [comment]
@yxieca , please help to get this PR merged. Thank you.

**Review by jeff-yin — APPROVED** [review]

**Comment by andriy-kokhan** [comment]
@qiluo-msft , please approve and merge.

**Pull request merged**
