### PR TITLE
Updated MMU settings for Arista 400g and 100g HWSKUs

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
Updated MMU settings to enhance performance for RDMA traffic in production.

##### Work item tracking
- Microsoft ADO **(28551006)**:

#### How I did it
Updated device files for buffer pool/profile settings.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by gechiang** [comment]
@vmittal-msft , Please share how these numbers came about... was it due to some performance tests you did or these are contributed by Arista that ran some performance tuning and sharing their results for the community to pick up?
It would be very helpful to mention some support info in the description.

**Comment by vmittal-msft** [comment]
@kenneth-arista @ysmanman please find the HW settings attached.
[Arista MMU settings.txt](https://github.com/sonic-net/sonic-buildimage/files/15425237/Arista.MMU.settings.txt)

**Comment by kenneth-arista** [comment]
@vmittal-msft let's discuss offline the new settings.

**Comment by vmittal-msft** [comment]
[arista_logs.txt](https://github.com/user-attachments/files/15845971/arista_logs.txt)
@kenneth-arista  please have Rahul review/approve.

**Comment by gechiang** [comment]
@vmittal-msft please share MSFT ADO number for this PR

**Comment by vmittal-msft** [comment]
> @vmittal-msft please share MSFT ADO number for this PR



> @vmittal-msft please share MSFT ADO number for this PR

Done

**Comment by kenneth-arista** [comment]
Rahul reviewed the data and it looks good!

**Review by kenneth-arista — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@yxieca @lguohan @rlhui , Can you please help merge this as well ?

**Pull request merged**
