### PR TITLE
[armhf][Nokia-7215] Remove platform reboot

### PR DESCRIPTION
**Pull request by Pavan-Nokia**
#### Why I did it
Remove platform specific reboot file for Nokia-7215 as we do not need this

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Remove platform_reboot from device directory for Nokia-7215 platform

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
@Pavan-Nokia please retry builds

**Comment by Blueve** [comment]
@Pavan-Nokia can you try rebase/merge with master and then retry build?

**Comment by Blueve** [comment]
@yxieca could you help merge this PR?

**Comment by StormLiangMS** [comment]
@Blueve @Pavan-Nokia could you elaborate any bug fix with this PR for 202305?

**Comment by Pavan-Nokia** [comment]
@StormLiangMS This does not fix any bug in particular. This platform_reboot script was not needed and is unused for our platform (Nokia-7215). So a decision was made by MSFT and Nokia to remove it to avoid any confusion.

**Pull request merged**
