### PR TITLE
Fix port index for multi-asic

### PR DESCRIPTION
**Pull request by ysmanman**
#### Why I did it
Port indexes of front panel ports are not contiguous in multi-asic because we didn't distinguish between front panel and internal ports, e.g., recycle ports.   This could cause xcvrd crash seen in https://github.com/aristanetworks/sonic/issues/56

#### How I did it
Fix this by assigning index to front panel port first and then internal ports.

#### How to verify it
Loaded the image with the fix in multi-asic LC and verified that xcvrd was not crashing in pmon.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211

### CODE REVIEW

**Comment by ysmanman** [comment]
Add @arlakshm for visibility.

**Comment by ysmanman** [comment]
Add  @wenyiz2021 who reported issue https://github.com/aristanetworks/sonic/issues/56 .

**Comment by wenyiz2021** [comment]
thanks @ysmanman for changing port_config.ini, can you please also add the change in mingiraph.py, as I mentioned in the issue?
```
(Pdb) interfaces.keys()
[u'Ethernet152', u'Ethernet200', u'Ethernet168', u'Ethernet192', u'Ethernet184', u'Ethernet232', u'Ethernet208', u'Ethernet160', u'Ethernet224', u'Ethernet176', u'Ethernet144', u'Ethernet248', u'Ethernet216', u'Ethernet240']
(Pdb) mg_ports.keys()
[u'Ethernet-Rec1', u'Ethernet152', u'Ethernet200', u'Ethernet168', u'Ethernet192', u'Ethernet184', u'Ethernet232', u'Ethernet208', u'Ethernet160', u'Ethernet-IB1', u'Ethernet176', u'Ethernet224', u'Ethernet144', u'Ethernet216']
(Pdb) len(mg_ports)
14
(Pdb) len(interfaces)
14
(Pdb) intf
```
u'Ethernet248'
(Pdb) intf in mg_ports
False

**Comment by wenyiz2021** [comment]
@ysmanman 
Can you change in this sku instead:  `x86_64-arista_7800r3a_36dm2_lc`

**Comment by ysmanman** [comment]
> 



> @ysmanman Can you change in this sku instead: `x86_64-arista_7800r3a_36dm2_lc/Arista-7800R3A-36DM2-C36`, not current one

@wenyiz2021 Arista-7800R3A-36DM2-C36 is just a symbol link of 36D2-C36.

**Review by wenyiz2021 — APPROVED** [review]

**Comment by wenyiz2021** [comment]
> thanks @ysmanman for changing port_config.ini, can you please also add the change in mingiraph.py, as I mentioned in the issue?
> 
> ```
> (Pdb) interfaces.keys()
> [u'Ethernet152', u'Ethernet200', u'Ethernet168', u'Ethernet192', u'Ethernet184', u'Ethernet232', u'Ethernet208', u'Ethernet160', u'Ethernet224', u'Ethernet176', u'Ethernet144', u'Ethernet248', u'Ethernet216', u'Ethernet240']
> (Pdb) mg_ports.keys()
> [u'Ethernet-Rec1', u'Ethernet152', u'Ethernet200', u'Ethernet168', u'Ethernet192', u'Ethernet184', u'Ethernet232', u'Ethernet208', u'Ethernet160', u'Ethernet-IB1', u'Ethernet176', u'Ethernet224', u'Ethernet144', u'Ethernet216']
> (Pdb) len(mg_ports)
> 14
> (Pdb) len(interfaces)
> 14
> (Pdb) intf
> u'Ethernet248'
> (Pdb) intf in mg_ports
> False
> ```

This issue is not in minigraph.py, it was resolved after re-generating minigraph on the device. The change LGTM

**Comment by wenyiz2021** [comment]
@ysmanman can you please resolve the conflict and merge PR? thanks

**Comment by ysmanman** [comment]
> @ysmanman can you please resolve the conflict and merge PR? thanks Please also add a label `request for 202205 branch`, somehow I could not add it

Hi @wenyiz2021  resolved conflicts just now. I don't think I have permission to add label neither. @rlhui may have the permission.

**Review by arlakshm — APPROVED** [review]

**Comment by wenyiz2021** [comment]
@ysmanman can you please merge this? thanks

**Comment by ysmanman** [comment]
> @ysmanman can you please merge this? thanks

@wenyiz2021 I don't think I have write access to the repo. so I am not able to merge it.

**Pull request merged**
