### PR TITLE
Add yang model for PFC watchdog debug information

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it
When PFC WD is triggered there is no diagnosis information which makes it difficult to understand why PFC WD was triggered. So, we add a field `additional_information` to accommodate the diagnosis information.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
unit test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by zbud-msft — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@stephenxs did you run test with 202305 image with this PR?

**Comment by stephenxs** [comment]
> @stephenxs did you run test with 202305 image with this PR?

@StormLiangMS Yes, I did.

**Comment by zbud-msft** [comment]
Hi @stephenxs 

I am seeing issue in 202305 branch regarding this change, seems like additional_information value is not accounting for floating point values within the key value pairs.

Seems like the yang will need to be updated to support that.

"libyang[0]: Value \"occupancy:0|packets:0|packets_last:0|pfc_rx_packets:0|pfc_rx_packets_last:0|pfc_duration:0|pfc_duration_last:0|timestamp:1709055546.**5448**|timestamp_last:1709055546.**0438**|real_poll_time:501045.**94230652**\" does not satisfy the constraint \"[-a-zA-Z0-9_]+:[-a-zA-Z0-9_]+(\\|{1}[-a-zA-Z0-9_]+:[-a-zA-Z0-9_]+)*\"

Can you please update the yang model to support this and update testcase?

**Comment by stephenxs** [comment]
> Hi @stephenxs
> 
> I am seeing issue in 202305 branch regarding this change, seems like additional_information value is not accounting for floating point values within the key value pairs.
> 
> Seems like the yang will need to be updated to support that.
> 
> "libyang[0]: Value "occupancy:0|packets:0|packets_last:0|pfc_rx_packets:0|pfc_rx_packets_last:0|pfc_duration:0|pfc_duration_last:0|timestamp:1709055546.**5448**|timestamp_last:1709055546.**0438**|real_poll_time:501045.**94230652**" does not satisfy the constraint "[-a-zA-Z0-9_]+:[-a-zA-Z0-9_]+(\|{1}[-a-zA-Z0-9_]+:[-a-zA-Z0-9_]+)*"
> 
> Can you please update the yang model to support this and update testcase?

Hi Zain
Sure.

**Pull request merged**
