### PR TITLE
set cable length of backplane ports to 1m

### PR DESCRIPTION
**Pull request by zhixzhu**
#### Why I did it
backplane ports cable length need to be specified.

#### How I did it
separated handling for the specific port name.

#### How to verify it
Used "sonic-cfggen" to generate buffer config, and verified cable length of backplane ports is 1m, other ports default length.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by zhixzhu** [comment]
@lguohan There is 1 workflow awaiting approval, could you help approve it? 
The failure happened when running script bgp/test_bgp_fact.py, changing the cable length of backplane ports should be have any impact on it, how to rerun this test?

**Comment by alpeshspatel** [comment]
Hi 
@yxieca @rlhui @abhishekd0 

Can you please help this get merged into 202205 as well as master branch.

**Comment by zhixzhu** [comment]
@lguohan @yxieca @rlhui @abhishekd0
All checks have passed, could you help review and merge it into 202205 and master branch?

**Comment by zhixzhu** [comment]
@lguohan @yxieca @rlhui @abhishekd0
All checks have passed, could you help merge it into 202205 and master branch?

**Comment by zhixzhu** [comment]
@yxieca  Could you help approve and merge?

**Comment by abdosi** [comment]
Does cherry-pick of master has conflict ?

**Comment by zhixzhu** [comment]
> Does cherry-pick of master has conflict ?

Yes, the type of argument in src/sonic-config-engine/tests/test_multinpu_cfggen.py run_script is different between master and 202205 branch.

**Review by abdosi — APPROVED** [review]

**Comment by zhixzhu** [comment]
@abdosi Pipeline still failed at:
```
The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1n-0+deb11u4) but 1.1.1n-0+deb11u3 is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update  && apt-get -y install      net-tools               python3-pip             python-setuptools       build-essential         libssl-dev              libffi-dev              python-dev              wget                    cmake                   libqt5core5a            libqt5network5          libboost-atomic1.74.0' returned a non-zero code: 100
```
The failure is not related with this PR's code change, how to proceed with it? Any suggestions?

**Comment by zhixzhu** [comment]
@abdosi I checked the recent PRs to target branch 202205, they all have the same pipeline failure on the "Build marvell_armhf", including open PRs and merged PRs, e.g. https://github.com/sonic-net/sonic-buildimage/pull/13778

Could you help merge my PR in this case?

**Comment by zhixzhu** [comment]
@abdosi Any suggestions on how to proceed?

**Pull request merged**
