### PR TITLE
[Nvidia] Update syncd docker to use python version 3

### PR DESCRIPTION
**Pull request by liorghub**
#### Why I did it
Python 2 is obsolete and no longer supported.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Change several packages installation commands in Nvidia syncd dockerfile to Python3 packages.
Change was done for regular image and for RPC image as well.
 
#### How to verify it
I tested several SDK API scripts manually (while all others are tested by SDK verification) and ran regression tests that run on RPC version.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by volodymyrsamotiy — APPROVED** [review]

**Review by yxieca — APPROVED** [review]

**Comment by liorghub** [comment]
@yxieca can you please cherry pick to 202305 as well?

**Comment by liorghub** [comment]
@yxieca can you please cherry pick to 202305?

**Comment by liorghub** [comment]
@StormLiangMS Can you please cherry pick to 202305?

**Comment by StormLiangMS** [comment]
this seems not a necessary for 202305

**Pull request merged**
