### PR TITLE
[device/wistron] Replace os.system and remove subprocess with shell=True

### PR DESCRIPTION
**Pull request by maipbui**
Signed-off-by: maipbui <maibui@microsoft.com>

#### Why I did it
`subprocess.Popen()` and `subprocess.run()` is used with `shell=True`, which is very dangerous for shell injection.
`os` - not secure against maliciously constructed input and dangerous if used to evaluate dynamic content
#### How I did it
Replace `os` by `subprocess`
Remove `shell=True`, use `shell=False`
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [X] 201911
- [X] 202006
- [X] 202012
- [X] 202106
- [X] 202111
- [X] 202205

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by maipbui** [comment]
@WistronNetwork Could you help review and verify?

**Comment by WistronNetwork** [comment]
@maipbui thanks for suggestion, will verify and get back to you soon.

**Comment by maipbui** [comment]
@WistronNetwork could you update on your verification?

**Comment by WistronNetwork** [comment]
@maipbui  we had verified this and we'll create PR for related modification, thanks for advise.

**Comment by maipbui** [comment]
@WistronNetwork is it good to merge?

**Comment by WistronNetwork** [comment]
@maipbui we have PR for this change, please check https://github.com/sonic-net/sonic-buildimage/pull/12110

**Comment by qiluo-msft** [comment]
Thanks @WistronNetwork!
Close this PR in favor of a larger PR https://github.com/sonic-net/sonic-buildimage/pull/12110

**Pull request closed without merging**
