### PR TITLE
[201911][mellanox]Fix CPLD upgrade script

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### Why I did it
Fixed CPLD upgrade script

#### How I did it
Modified the skip check to be greater than or equal to compared to equal to previously

#### How to verify it
Upgrade image with changes

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by nazariig — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@dgsudharsan did you test the following cases

1. Device already running with latest CPLD and then firmware upgrade skips CPLD upgrade
2. Device has old CPLD and firmware upgrade upgrades to higher version?

**Comment by dgsudharsan** [comment]
> @dgsudharsan did you test the following cases
> 
> 1. Device already running with latest CPLD and then firmware upgrade skips CPLD upgrade
> 2. Device has old CPLD and firmware upgrade upgrades to higher version?

Hi @prgeor . Tested both cases and it works good.

**Comment by prgeor** [comment]
@rlhui please help merge this to 2019

**Pull request merged**
