### PR TITLE
[202205][Arista] Update arista platform submodules

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

 - fix issue where platform debug info would no longer be in the dump
 - fix issue in scd-xcvr where active low bits couldn't be set
 - fix issue in scd-smbus where it perform an oob access

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Description for the changelog

Update arista platform library submodules

### CODE REVIEW

**Comment by prgeor** [comment]
@Staphylo could you specify which all platforms have memory scrubber enabled?

**Comment by Staphylo** [comment]
@prgeor I updated the PR description with the affected products

**Comment by prgeor** [comment]
@Staphylo can we have the "enable DRAM ECC scrubbing on some platforms" is a feature so would like to be only in Master branch

**Comment by Staphylo** [comment]
@prgeor I reverted the DRAM scrubbing change for 202205

**Comment by prgeor** [comment]
> @prgeor I reverted the DRAM scrubbing change for 202205

@Staphylo could you update the PR description accordingly? Now the DRAM scrubbing is removed

**Comment by Staphylo** [comment]
@prgeor I just updated the description

**Pull request merged**
