### PR TITLE
[chassis] Support advertisement of Loopback0 of all LC's across all e-BGP peers in TSA mode

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
In Chassis TSA mode Loopback0 Ip's of each LC's should be advertise through e-BGP peers of each remote LC's

How I did:

- Route-map policy to Advertise own/self Loopback IP to other internal iBGP peers with a community  `internal_community` as define in `constants.yml`
- Route-map policy to match on above `internal_community` when route is received from internal iBGP peers and set a `internal tag` as define in `constants.yml` and also delete the `internal_community` so we don't send to any of e-BGP peers 
- In TSA new  route-map match on above `internal tag` and permit the route (Loopback0 IP's of remote LC's) and set the community to `traffic_shift_community`.
- In TSB delete the above new route-map.

How I verify:
Manual Verification
UT  updated.
sonic-mgmt PR: https://github.com/sonic-net/sonic-mgmt/pull/10239/

### CODE REVIEW

**Comment by gechiang** [comment]
@abdosi , please take a look at the test failure:
```
=================================== FAILURES ===================================
__________________________ test_TSA[vlab-03-default] ___________________________

duthosts = [<MultiAsicSonicHost vlab-03>]
enum_rand_one_per_hwsku_frontend_hostname = 'vlab-03'
ptfhost = <tests.common.devices.ptf.PTFHost object at 0x7fcd6eb17a90>
nbrhosts_to_dut = {'ARISTA01T0': <EosHost VM0112>, 'ARISTA01T2': <EosHost VM0104>, 'ARISTA02T0': <EosHost VM0113>, 'ARISTA03T0': <EosHost VM0114>, ...}
bgpmon_setup_teardown = {'local_addr': '20.0.0.0/31', 'local_intf': 'Ethernet124', 'loopback_ip': '10.1.0.32', 'namespace': None, ...}
traffic_shift_community = '12345:12345'
tbinfo = {'auto_recover': 'False', 'comment': 'Tests virtual switch vm', 'conf-name': 'vms-kvm-t1-lag', 'duts': ['vlab-03'], ...}

    def test_TSA(duthosts, enum_rand_one_per_hwsku_frontend_hostname, ptfhost,
                 nbrhosts_to_dut, bgpmon_setup_teardown, traffic_shift_community, tbinfo):
        """
        Test TSA
        Verify all routes are announced to bgp monitor, and only loopback routes are announced to neighs
        """
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
        try:
            # Issue TSA on DUT
            duthost.shell("TSA")
            # Verify DUT is in maintenance state.
>           pytest_assert(TS_MAINTENANCE == get_traffic_shift_state(duthost),
                          "DUT is not in maintenance state")
E                         Failed: DUT is not in maintenance state

bgpmon_setup_teardown = {'local_addr': '20.0.0.0/31', 'local_intf': 'Ethernet124', 'loopback_ip': '10.1.0.32', 'namespace': None, ...}
duthost    = <MultiAsicSonicHost vlab-03>
duthosts   = [<MultiAsicSonicHost vlab-03>]
enum_rand_one_per_hwsku_frontend_hostname = 'vlab-03'
nbrhosts_to_dut = {'ARISTA01T0': <EosHost VM0112>, 'ARISTA01T2': <EosHost VM0104>, 'ARISTA02T0': <EosHost VM0113>, 'ARISTA03T0': <EosHost VM0114>, ...}
ptfhost    = <tests.common.devices.ptf.PTFHost object at 0x7fcd6eb17a90>
tbinfo     = {'auto_recover': 'False', 'comment': 'Tests virtual switch vm', 'conf-name': 'vms-kvm-t1-lag', 'duts': ['vlab-03'], ...}
traffic_shift_community = '12345:12345'

bgp/test_traffic_shift.py:364: Failed
=============================== warnings summary ===============================
../../../../usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18
  /usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18: DeprecationWarning: The _yaml extension module is now located at yaml._yaml and its location is subject to change.  To use the LibYAML-based parser and emitter, import from `yaml`: `from yaml import CLoader as Loader, CDumper as Dumper`.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /var/src/sonic-mgmt/tests/logs/bgp/test_traffic_shift|||2.xml -
=========================== short test summary info ============================
FAILED bgp/test_traffic_shift.py::test_TSA[vlab-03-default] - Failed: DUT is ...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=================== 1 failed, 1 warning in 127.16s (0:02:07) ===================
```

**Comment by abdosi** [comment]
Blocked on this PR: https://github.com/sonic-net/sonic-mgmt/pull/10273 to merge for PR test case to pass

**Comment by abdosi** [comment]
@arlakshm Sanity is passing now. Can you review the PR.

**Review by arlakshm — APPROVED** [review]

**Comment by abdosi** [comment]
@lguohan can you please help with review/merge of this.

**Comment by gechiang** [comment]
@lguohan , can you help review/approve this PR?

**Comment by gechiang** [comment]
MSFT ADO: 25892510

**Comment by gechiang** [comment]
@StormLiangMS , @yxieca , please help review/Approve for 202305 and 202205. Thanks!

**Comment by StormLiangMS** [comment]
@abdosi  @gechiang could you run test with T1 / T0 device for 202305 image?

**Comment by StormLiangMS** [comment]
@abdosi  @gechiang remind for test result with T1/T0

**Comment by abdosi** [comment]
> @abdosi @gechiang remind for test result with T1/T0

@StormLiangMS Verified on VS testbed for T1/T0 results and it looks fine. Please help with cherry-pick

**Comment by abdosi** [comment]
@gechiang Lets take this into msft repo for 202205.

**Comment by rlhui** [comment]
@abdosi - there's conflict to cherry-pick, please create another PR for msft 202205, thanks

**Comment by abdosi** [comment]
> @abdosi - there's conflict to cherry-pick, please create another PR for msft 202205, thanks

@rlhui PR: https://github.com/Azure/sonic-buildimage-msft/pull/208

**Comment by gechiang** [comment]
@StormLiangMS can we have this approved for 202305?
Thanks!

**Pull request merged**
