### PR TITLE
support for static-route yang model

### PR DESCRIPTION
**Pull request by UmaMaven**
Signed-off-by: Uma Ramanathan [uma.ramanathan@mavenir.com](mailto:uma.ramanathan@mavenir.com)

Why I did it
Support yang model for static route

How I did it
Added a yang file for static route configuration

How to verify it
Add static routes with gateway/interface/blackhole as nexthop with VRF capability

https://github.com/sonic-net/sonic-buildimage/issues/11498

### CODE REVIEW

**Comment by UmaMaven** [comment]
@venkatmahalingam @qiluo-msft @ganglyu @dgsudharsan 
Last PR got "Closed" automatically when I did a sync to latest. I am not sure why this is happening.
Yet again, I had to create a new request here. 
All the comments were addressed as part of last PR
https://github.com/sonic-net/sonic-buildimage/pull/11782

**Review by venkatmahalingam — APPROVED** [review]

**Comment by UmaMaven** [comment]
@venkatmahalingam  
Test kvmtest-t1-lag failed -> Please help. Thanks

**Comment by venkatmahalingam** [comment]
@prsunny Please restart the build.

**Comment by venkatmahalingam** [comment]
Since we have done multiple rounds of review on this YANG, I think, once the build is successful, we can merge the PR.

**Comment by UmaMaven** [comment]
@ganglyu @qiluo-msft @dgsudharsan 
Can you please approve?

**Review by ganglyu — APPROVED** [review]

**Comment by UmaMaven** [comment]
@qiluo-msft @dgsudharsan
Can you please approve as we have done multiple rounds of reviews already?
I would not want to get into the conflict issue again. 
Thanks,
Uma

**Comment by UmaMaven** [comment]
@venkatmahalingam @ganglyu @qiluo-msft @dgsudharsan 
Let me know how we can proceed further to close on this issue?

**Comment by venkatmahalingam** [comment]
> @venkatmahalingam @ganglyu @qiluo-msft @dgsudharsan Let me know how we can proceed further to close on this issue?

@qiluo-msft Please help to merge this PR.

**Pull request merged**
