### PR TITLE
Add mdio IPC client library

### PR DESCRIPTION
**Pull request by jiahua-wang**
Signed-off-by: Jiahua Wang <jiahua.wang@broadcom.com>

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by lguohan** [comment]
why cannot we put this in the sonic-sairedis repo? we can buiild this library into syncd

**Comment by lguohan** [comment]
@jiahua-wang

**Review by lguohan — CHANGES_REQUESTED** [review]
why not move this to sonic-sairedis repo?

**Comment by jiahua-wang** [comment]
We want to build a separate debian package which can be used by gbsyncd docker. We want to dynamically load the library.

**Comment by jiahua-wang** [comment]
Build mdio IPC client library as a debian package and as a .so file has the flexibility. Build the code into syncd process is equivalent to add the debian package as build time dependence and run time dependence of syncd package and add LD flag of -lmdio-ipc-client in the syncd makefile.

**Comment by jiahua-wang** [comment]
Close the PR for now. Will reopen the PR after design document review.

**Comment by jiahua-wang** [comment]
We have created the design doc of "Sonic gbsyncd/PAI mdio access HLD" PR https://github.com/sonic-net/SONiC/pull/1045 , which explains the reason of creating this mdio IPC client library PR and has reference to this PR. We reopen this PR.

**Comment by jiahua-wang** [comment]
This PR is replaced by https://github.com/sonic-net/sonic-sairedis/pull/1134

**Pull request closed without merging**
