### PR TITLE
[202305][Mellanox]Integrate HW-MGMT 7.0030.2300 Changes

### PR DESCRIPTION
**Pull request by dprital**
This PR depend with PR: https://github.com/sonic-net/sonic-linux-kernel/pull/408

#### Why I did it

Intgerate HW-MGMT 7.0030.2300 Changes

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Run make integrate-mlnx-hw-mgmt

#### How to verify it

Build an image and run tests from "sonic-mgmt".

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by vivekrnv — APPROVED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@StormLiangMS  Can you pleas help to merge?

**Comment by dgsudharsan** [comment]
@StormLiangMS  Can you please help to merge this?

**Review by StormLiangMS — APPROVED** [review]
lgtm

**Pull request merged**
