### PR TITLE
Add debug shell packages for Marvell Innovium platforms

### PR DESCRIPTION
**Pull request by rck-innovium**
Signed-off-by: rck-innovium rck@innovium.com

#### Why I did it
Package Marvell/Innovium CLI shell.

#### How I did it
Include shell packages.

#### How to verify it
Platform specific shell commands.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [X] 202111
- [ ] 202205

#### Description for the changelog

Support Innovium Shell packages

#### Link to config_db schema for YANG module changes

Not applicable.

### CODE REVIEW

**Comment by vmittal-msft** [comment]
@rck-innovium Can you please share verification outputs after this change ?

**Comment by rck-innovium** [comment]
> @rck-innovium Can you please share verification outputs after this change ?

Hi Vineet,

Please find the output:

```
root@sonic-dut:~# ivmcmd "ifcs show version"
                Connected to Innovium Shell Server
+----------------------------------------------------+
|      IFCS Version:  :                      0.14.18 |
|----------------------------------------------------|
|      Release Date:  : Fri Jul 29 12:01:31 UTC 2022 |
|        Build Date:  : Fri Jul 29 12:13:45 UTC 2022 |
| Eth Serdes FW Rev:  :              0x10A5_208D_003 |
| SBM Serdes FW Rev:  :                  0x1024_2001 |
+----------------------------------------------------+

root@sonic-dut:~# ivmcmd
```

**Review by vmittal-msft — APPROVED** [review]

**Comment by rlhui** [comment]
please resolve conflicts.

**Comment by rck-innovium** [comment]
> please resolve conflicts.

Resolved, Rita. Now the commit checks are running.

**Comment by lguohan** [comment]
why the build is failing?

**Comment by rck-innovium** [comment]
The build failure was an intermittent issue with some 3rd party packages; that build is no longer present in Azure pipelines and I am not able to recollect the exact issue. This was 3 months ago.

Can you please retrigger the build and I can analyze and give the exact error log:

 /azp run

**Comment by rck-innovium** [comment]
> The build failure was an intermittent issue with some 3rd party packages; that build is no longer present in Azure pipelines and I am not able to recollect the exact issue. This was 3 months ago.
> 
> Can you please retrigger the build and I can analyze and give the exact error log:
> 
>  /azp run

@lguohan

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@rck-innovium please check the build failure

**Comment by prgeor** [comment]
@lguohan please help merge

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@liat-grozovik @lguohan please help merge

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
