### PR TITLE
[Mellanox] Support read/write more than 1 page in a single platform API call

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it

Support read/write more than 1 page in a single platform API call.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it

Manual and mock test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by stephenxs** [comment]
> @stephenxs what else is pending ? seems still draft

@prgeor internal test.

**Comment by liat-grozovik** [comment]
@prgeor can you approve from code POV? once tests will be passing internally we will move from draft and i will merge. this is expected in 1-2d

**Comment by stephenxs** [comment]
> @stephenxs what else is pending ? seems still draft

@prgeor ready for review.

**Review by Chenjunchao — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@stephenxs Please raise a new PR for 202311 branch to address conflict.

**Comment by stephenxs** [comment]
> @stephenxs Please raise a new PR for 202311 branch to address conflict.

@bingwang-ms @prgeor cherry-pick conflict is caused by https://github.com/sonic-net/sonic-buildimage/pull/18414 not being cherry-picked. Would you please cherry-pick 18414 first or it won't be cherry-picked?

**Pull request merged**
