### PR TITLE
[Arista] Remove arista.log from rsyslog default logrotate 

### PR DESCRIPTION
**Pull request by bratashX**
**_It's cherry-pick from master branch:_**  https://github.com/Azure/sonic-buildimage/pull/9731

**Why I did it**
In parallel of this change Arista added a custom logrotate configuration as part of its driver library.
Having 2 logrotate configuration for the same log file triggers an issue.

Fixes https://github.com/aristanetworks/sonic/issues/38

**How I did it**
Arista merged a few changes in sonic-buildimage which added a logrotate configuration https://github.com/aristanetworks/sonic/commit/e43c7977f7473be67a7e8be7846c9dd71357feae
It is therefore the right path to remove the arista.log line from the logrotate.d/rsyslog configuration.

**How to verify it**
Logrotate works without any error message, arista log rotation happens and arista daemons still append logs once file was truncated.

### CODE REVIEW

**Comment by bratashX** [comment]
@akokhan @lguohan @prgeor @Staphylo please review and merge

**Review by Staphylo — APPROVED** [review]

**Comment by bratashX** [comment]
@prsunny @lguohan @akokhan please review and merge

**Comment by bratashX** [comment]
@prsunny @lguohan @akokhan please take a look

**Comment by bratashX** [comment]
@Staphylo could you please sign EasyCLA?

**Pull request closed without merging**
