### PR TITLE
[202305 branch] Upgrade dnx SAI version to 9.2.x

### PR DESCRIPTION
**Pull request by wenyiz2021**
202305 image does not come up on chassis with SAI 7.1.111.1.
SAI 9.2.0.0 on 202305 image is verified to come up on Arista chassis. Initial testing is also done, no new failures compare to 202205 image, SAI 7.1.111.1.

#### Why I did it
Bring up 202305 image on chassis.

##### Work item tracking
- Microsoft ADO **(number only)**: 18189434

#### How to verify it
Brought up SAI 9.2.0.0 on Arista chassis.
Ran pipeline on acl, bgp, arp, acms, cacl, copp, decap, fib, iface_namingmode.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
HI @lguohan , @StormLiangMS 
Please help approve/merge this PR as this is needed for T2 Chassis bring up on 202305 branch.
Thanks!

**Comment by wenyiz2021** [comment]
hi @StormLiangMS this is MSFT ADO: 18189434

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
