### PR TITLE
[device/arista/7800r3ak]: Convert symlink to directory and update name in platform.json

### PR DESCRIPTION
**Pull request by liamkearney-msft**
* Convert symlink to copy of 7800r3a_36d2_lc -> 7800r3ak_36d2_lc
* Symlink 7800r3ak_36d2_lc -> 7800r3ak_36dm2_lc
* Update name in platform.json for 7800r3ak

#### Why I did it
get_name platform test failing due to incorrect platform.json for 7800r3ak linecards

##### Work item tracking
https://github.com/aristanetworks/sonic/issues/113

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405
#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

Convert symlink to directory and update name in platform.json for 7800r3ak

### CODE REVIEW

**Comment by liamkearney-msft** [comment]
@patrickmacarthur could you please help review this? thanks

**Comment by patrickmacarthur** [comment]
I'm not entirely happy with creating a full copy of the entire directory tree because we need to change one file. At the very least could we symlink the files within the 7800R3AK directory to the equivalent files in the 7800R3A directory?

**Comment by arlakshm** [comment]
@patrickmacarthur @kenneth-arista, please create the PR with the proposed fix?

**Pull request closed without merging**
