### PR TITLE
Added libpci and pciutils to the pmon docker

### PR DESCRIPTION
**Pull request by assrinivasan**
#### Why I did it

This is part of a corresponding change to the pcie daemon that enables it to verify PCI peripherals on a platform against a preconfigured YAML file, and enables the pcied daemon to call the system commands needed for PCI peripheral verification

#### How I did it
Adding aforementioned libraries to the Dockerfile.j2 file

#### How to verify it
run 'which setpci' from the pmon docker - would show the path of the binary

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106
- [x] 202111
- [x] 202205

#### Description for the changelog

Modified pmon's Dockerfile.j2 to include pciutils and libpci libraries.

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Comment by assrinivasan** [comment]
@prgeor @yxieca Please review my requests for 202012, 202205 and 202211 branches. TIA

**Comment by prgeor** [comment]
@qiluo-msft if you can cherry pick to 202012
@StormLiangMS if you can cherry pick to 202211

**Comment by assrinivasan** [comment]
PR to cherry-pick to 202012 branch: https://github.com/sonic-net/sonic-buildimage/pull/14056

**Comment by StormLiangMS** [comment]
@assrinivasan pls create PR for 202211, cherry-pick failed.

**Pull request merged**
