### PR TITLE
[Mellanox] CMIS management feature enablement 

### PR DESCRIPTION
**Pull request by dbarashinvd**
Depends on https://github.com/sonic-net/sonic-buildimage/pull/18571

#### Why I did it
CMIS management feature enablement 

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add new variable with value 1 for CMIS management feature enablement under specific HWSKU folder. Not the default one

#### How to verify it
Install image on switch with same HWSKU and check "show interfaces status" (Type column)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [X] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@dbarashinvd please add also recent added SKU to this PR done by @DavidZagury.

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
see comment below

**Comment by dbarashinvd** [comment]
> see comment below

working on it. cant get the new SKU folder for update after fetch and rebase. will sort it out and update

**Comment by dbarashinvd** [comment]
> @dbarashinvd please add also recent added SKU to this PR done by @DavidZagury.

done

**Comment by prgeor** [comment]
@liat-grozovik @dbarashinvd please see if this can be moved out of draft and unblocked?

**Comment by prgeor** [comment]
@moshemos @liat-grozovik @keboliu What is pending for this to be enabled?

**Comment by liat-grozovik** [comment]
New asic and platform driver update. Should be in few days on another pr

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by liat-grozovik — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@liat-grozovik can you please merge?

**Comment by noaOrMlnx** [comment]
@yxieca can you please cherry-pick to 202311?

**Pull request merged**
