### PR TITLE
Advance sonic-swss submodule

### PR DESCRIPTION
**Pull request by judyjoseph**
#### Why I did it
Advance sonic-swss submodule

```
13bda3c [Everflow/ERSPAN] Set correct destination port and mac address when the nexthop is updated for ERSPAN mirror destination (#2392)
0ccb315 Revert "[VS Test] Skip failing subport tests (#2370)" (#2421)
ac8a83f [UT] [Portsyncd] Added Unit Tests for portsyncd (#2297)
83a186a Change the log messages in addKernelNeigh/Route from ERROR to INFO (#2437)
9c23389 [BFD]Clean up state_db BFD entries on swss restart (#2434)
d41aebf EntityBulker SIGSEGV when create_entry attr_count 0 (#2224)
f52a7b1 Fix the Fec Mode Setting of gbsyncd (#2430)
8cc0a45 [neighsyncd] Enabling ipv4 link local entries for non-dualtor (#2427)
5624e87 Revert "[ci][asan] add DVS tests run with ASAN (#2363)" (#2433)
a26b26a Dynamic port configuration - add port buffer cfg to the port ref counter (#2194)
486939a tlm_teamd: Filter portchannel subinterface events from STATE_DB LAG_TABLE (#2408)
a4b8992 [counters] Improve performance by polling only configured ports buffer queue/pg counters (#2360)
4aaeec9 added support for Xsight platform (#2426)
ca9edca [ci][asan] add DVS tests run with ASAN (#2363)
dec4570 Handle dual ToR neighbor miss scenario (#2151)
9eb4422 Upstream new development on p4orch (#2237)
e9be2c0 [lgtm] Fix dependency (#2419)
c0168f3 [muxorch] Returning true if nbr in skip_neighbor_ in isNeighborActive() (#2415)
cfcf3d8 [macsec]: Set MTU for MACsec (#2398)
8346034 Delete Invalid if condition in intfsorch.cpp (#2411)
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by judyjoseph** [comment]
sonic-swss updated via a different PR

**Pull request closed without merging**
