### PR TITLE
[staticroutebfd] fix an error in error logging

### PR DESCRIPTION
**Pull request by baorliu**
#### Why I did it
Fix an error in the log_err call.
this error can be triggered by an invalid static route key. usually the code cannot go here with normal config file. but hit this issue with an invalid key by manual testing with redis-cli directly. the file is scanned by Python lint to prevent such errors.

##### Work item tracking
- Microsoft ADO **()**:26250268

#### How I did it
fix the format error.

#### How to verify it
1, ran pylint to check the design, make sure no such error in the design file.
2, wrote a separate python program to verify the log call.
In the current logging related testing, usually use patch/mock for logging. for this specific error, could not trigger it if we call mock function instead the real function in the design. so need to do lint checking for code change.

 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@abdosi to review. @baorliu , is it possible to add a unit test?

**Comment by baorliu** [comment]
> @abdosi to review. @baorliu , is it possible to add a unit test?

Yes. I will check if I can use mocked function to test this logging issue.

**Review by prsunny — APPROVED** [review]

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
LGTM. @StormLiangMS  can you help with merge of this.

**Comment by anamehra** [comment]
required in 202305/202311

**Comment by lguohan** [comment]
@abdosi , MS ADO?

**Comment by abdosi** [comment]
> @abdosi , MS ADO?

updated.

**Pull request merged**
