### PR TITLE
[submodule] Update sonic-sairedis to include SAI v1.15.1

### PR DESCRIPTION
**Pull request by kcudnik**
For fixing RPC build issue

#### Why I did it

Address https://github.com/sonic-net/sonic-buildimage/issues/20322

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Update SAI submodule on sonic-sairedis which contains fix

#### How to verify it
local build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by kcudnik** [comment]
@lguohan  please restart test, i believe this is not related to my change, and i dont have privileges to restart

**Comment by Gfrom2016** [comment]
@kcudnik @lguohan Could you help merge this PR, it's a blocker for Broadcom build.
@StormLiangMS FYI

**Comment by kcudnik** [comment]
@lguohan @rlhui  please merge I don't have permissions on this repo

**Comment by kcudnik** [comment]
this PR is obsolete, sairedis pointer moved alrady

**Pull request closed without merging**
