### PR TITLE
[healthd] Added change to handle Feature Table exception

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Fix: https://github.com/sonic-net/sonic-buildimage/issues/18818

How  I did:

Handle any exception in API `get_service_from_feature_table()` gracefully .

How I verify:
Manual Verification.

### CODE REVIEW

**Comment by abdosi** [comment]
@bingwang-ms : Can you help review this.

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@dgsudharsan Can you help review this change?

**Review by dgsudharsan — APPROVED** [review]

**Comment by abdosi** [comment]
@bingwang-ms : please help with merge of this and cherry-pick to 202405.

**Comment by abdosi** [comment]
@rlhui / @lguohan : can you help with sign off of this PR.

**Comment by rlhui** [comment]
[like]  Rita Hui reacted to your message:
________________________________

**Comment by StormLiangMS** [comment]
enhancement, no cherry pick for 202305

**Pull request merged**
