### PR TITLE
[Mellanox] update buffers and align QoS to add support for DSCP remapping (for Dual-Tor on t1) for Mellanox-SN4700-O8C48

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
#### Why I did it
- update buffers and align QoS to add support for DSCP remapping (for Dual-Tor on t1) for Mellanox-SN4700-O8C48
- use latest pg_profile_lookup.ini file

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
run related QoS/DSCP remapping test

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@ayurkiv-nvda Please confirm if this PR can be cherry-picked to 202311. Thanks

**Comment by ayurkiv-nvda** [comment]
> @ayurkiv-nvda Please confirm if this PR can be cherry-picked to 202311. Thanks



> @ayurkiv-nvda Please confirm if this PR can be cherry-picked to 202311. Thanks

Hello Bing
PR passed internal review, If there wouldn't be PR check failures, I beleive we can merge and cherri-pick to 202311

**Comment by bingwang-ms** [comment]
PR test was failing. I just retrigger the test.

**Comment by ayurkiv-nvda** [comment]
All PR's checks are passed, I think we can merge it

**Comment by bingwang-ms** [comment]
@yxieca Can you please help merge this PR?

**Pull request merged**
