### PR TITLE
[201911] Improve sudo cat command for RO user. (#14428)

### PR DESCRIPTION
**Pull request by liuh-80**
Improve sudo cat command for RO user.
Manually cherry-pick for https://github.com/sonic-net/sonic-buildimage/pull/14428

#### Why I did it
RO user can use sudo command show none syslog files.

#### How I did it
Improve sudo cat command for RO user.

#### How to verify it
Pass all UT.
Manually check fixed code work correctly.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106
- [x] 202111
- [x] 202205
- [x] 202211

#### Description for the changelog
Improve sudo cat command for RO user.

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by liuh-80** [comment]
This PR need a force merge, currently 201911 branch build break because jessie package deprecated on debian repo:

W: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/jessie/main/source/Sources  404  Not Found

W: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/jessie/contrib/source/Sources  404  Not Found

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@liushilongbuaa / @xumia can you please help look into build failure

**Comment by xumia** [comment]
> @liushilongbuaa / @xumia can you please help look into build failure

Jessie has removed from the mirror, see http://deb.debian.org/debian/dists/;
Suggest to use snapshot, for instance: https://packages.trafficmanager.net/snapshot/debian/20221110T000213Z/dists/jessie/

@liushilongbuaa, could you please change all the references for 201911?

**Comment by liuh-80** [comment]
> > @liushilongbuaa / @xumia can you please help look into build failure
> 
> Jessie was not supported, and been removed from the mirror, see http://deb.debian.org/debian/dists/; Suggest to use snapshot, for instance: https://packages.trafficmanager.net/snapshot/debian/20221110T000213Z/dists/jessie/
> 
> @liushilongbuaa, could you please change all the references for 201911?

@xumia @liushilongbuaa ,201811 also break.

**Comment by liuh-80** [comment]
@abdosi , could you please help merge this PR? I don't have permission.

**Pull request merged**
