### PR TITLE
Upgrading hsflowd version from 2.0.45 to 2.0.51-26 to address for [sf…

### PR DESCRIPTION
**Pull request by Gokulnath-Raja**
#### Why I did it
Below error log is seen sometimes when services startup.
ERR sflow#hsflowd: device Loopback0 Get SIOCGIFFLAGS failed : No such device 

#### How I did it
latest changes to hsflowd will avoid this race (e.g. the release tagged as v2.0.51-26). The new start up sequence waits first for the redis connections to come up, then waits for the redis to indicate SYSTEM_READY|SYSTEM_STATE Status=Up, and only then does it read the interfaces from Linux.

#### How to verify it
Post upgrade to latest version of hsflowd, manually verifying the sflow functionalities such as counter/flow samples.
UT is inprogres.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja Please ensure all the existing sonic-mgmt Sflow tests pass with this upgrade.

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja Please also sync to latest master to resolve the conflicts.

**Comment by Gokulnath-Raja** [comment]
> @Gokulnath-Raja Please ensure all the existing sonic-mgmt Sflow tests pass with this upgrade.

Validated sFlow functionality attached sample logs 
[hsflow_update.txt](https://github.com/sonic-net/sonic-buildimage/files/11733733/hsflow_update.txt)

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja Thanks. Did we qualify with sonic-mgmt sflow test suite? It would cover different test scenarios and not basic sanity test.

**Comment by dgsudharsan** [comment]
> > @Gokulnath-Raja Thanks. Did we qualify with sonic-mgmt sflow test suite? It would cover different test scenarios and not basic sanity test.
> 
> Could not find any sonic-mgmt sflow test suite... We have done following testing,

Hi @Gokulnath-Raja  We do have sonic-mgmt test in sflow https://github.com/sonic-net/sonic-mgmt/blob/master/tests/sflow/test_sflow.py 
I feel its important to run it before doing an upgrade. Can you please make sure we run this test with the new hsflow version?

**Comment by dgsudharsan** [comment]
Hi @Gokulnath-Raja  Any update here?

**Comment by Gokulnath-Raja** [comment]
> Hi @Gokulnath-Raja Any update here?

We are working on building test topology and test server to run the mgmt test_sflow, will keep you updated.

**Comment by mohanapriya-meganathan** [comment]
> > Hi @Gokulnath-Raja Any update here?
> 
> We are working on building test topology and test server to run the mgmt test_sflow, will keep you updated.

@dgsudharsan , We ran the script and found one failure. When we are deleting the agent-id, hsflowd is referring for the eth0 interface and expecting samples in that interface. (This is with the updated hsflowd , When you start hsflowd with no explicit agent-id configured,  it will run an "election" to decide which IP address to adopt.). We are debugging further.

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja  Please compile with flag ENABLE_SFLOW_DROPMON=y  and make sure compilation passes. Recent sflow upgrade to 2.0.45-1 broke the build and I have notified the PR owners about it.

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja Please check this PR https://github.com/sonic-net/sonic-buildimage/pull/15948. Once its merged, you can resync your PR and verify if it compiles fine.

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja  Can you please resync your changes to latest master as https://github.com/sonic-net/sonic-buildimage/pull/15948 is merged?

**Comment by dgsudharsan** [comment]
@Gokulnath-Raja  Can you please update the status of sonic-mgmt sflow tests?

**Comment by Gokulnath-Raja** [comment]
> We ran the script and found one failure. When we are deleting the agent-id, hsflowd is referring for the eth0 interface and expecting samples in that interface. (This is with the updated hsflowd , When you start hsflowd with no explicit agent-id configured, it will run an "election" to decide which IP address to adopt.).

@dgsudharsan we found the RCA and fixed the same... Running tests now will update the PR

**Comment by Gokulnath-Raja** [comment]
> > We ran the script and found one failure. When we are deleting the agent-id, hsflowd is referring for the eth0 interface and expecting samples in that interface. (This is with the updated hsflowd , When you start hsflowd with no explicit agent-id configured, it will run an "election" to decide which IP address to adopt.).
> 
> @dgsudharsan we found the RCA and fixed the same... Running tests now will update the PR

@dgsudharsan we have raise PR for sonic-mgmt test for sflow https://github.com/sonic-net/sonic-mgmt/pull/9766 kindly approve the same

**Review by prsunny — APPROVED** [review]

**Pull request merged**
