### PR TITLE
[Mellanox][202311] Adding SKU Mellanox-SN4700-O32 and Mellanox-SN4700-V64

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
**Additional changes for 202311**

On master branch, pg_profile_lookup.ini was pointed to pg_profile_lookup.ini from SN4280 as a symlink
But SN4280 wasn't merged to 202311
Need to use files instead of links

#### Why I did it
A new SKUs for MSN4700 Platform: **Mellanox-SN4700-O32** and **Mellanox-SN4700-V64**

Requirements for Mellanox-SN4700-O32:
- 8 x 400Gbps uplink to T2 switch (O13 to O20)
- 24 x 400Gbps downlinks to T0 switch (O1-O12, O21-O32)
- Breakout mode No breakout mode. All ports working in 400Gb mode. .
- FEC mode: RS
- Type of transceiver: 400Gb Optical.
- warm boot should be supported “No for T1 role”
- VxLAN source port range set N/A
- Static Policy Based Hashing supported N/A
- Cable length “T0-T1 40m default, 300m max; T1-T2 2000m”
- Tradition buffer model is must “Yes”
- Shared headroom should be supported “Yes”
- Over-subscription ratio: “2”.

Requirements for **Mellanox-SN4700-V64**

- 16 x 200Gbps uplink to T1 switch (V-25&V26 to V-39&40)
- 48 x 200Gbps downlinks to servers (Left panel downlink ports: V-1&2 to V-23&24; Right panel downlink ports: V-41&42 to V-63&64)
- Breakout mode split from 400Gbps ports (2x200)
- FEC mode: RS
- Type of transceiver: 200Gb AOC between T0 and T1; 200Gb DAC between T0 and host.
- warm boot should be supported “Yes for T0 role”
- VxLAN source port range set N/A
- Static Policy Based Hashing supported N/A
- Cable length “T0-T1 40m default, 300m max, T0-Server 5m”
- Tradition buffer model is must “Yes”
- Shared headroom should be supported “Yes”
- Over-subscription ratio: “2”.

Additional Details:

QoS configs for Mellanox-SN4700-V64 updated in order to fulfill Dual-ToR buffer (+DSCP remapping) requirements
Support for independent module added for both SKUs, so Auto-negotiation changed to NO

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
run full regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by ayurkiv-nvda** [comment]
PR passed internal review

**Comment by bingwang-ms** [comment]
@ayurkiv-nvda Please confirm if this PR is ready?

**Comment by bingwang-ms** [comment]
Discussed in email. PR is ready for review. 
@volodymyrsamotiy Could you please help sign-off this PR?

**Comment by bingwang-ms** [comment]
The PR should be merged first, and then PR https://github.com/sonic-net/sonic-buildimage/pull/20000/files should be cherry-picked to 202311.

**Pull request merged**
