### PR TITLE
[Quanta] Update files for Bullseye and kernel 5.10 with enhancements

### PR DESCRIPTION
**Pull request by roberthong-qct**
#### Why I did it
Enhance Quanta files and re-enable the building of Quanta platform modules

#### How I did it
Modify Quanta device and platform files for current master branch and pass PDE tests as many as possible

#### How to verify it
1. Manually update sonic-platform-pde to https://github.com/sonic-net/sonic-platform-pdk-pde/commit/3dcda836ebbdf21b7ed8fc5101cfafd09101477f and modify platfom/test json files in it

2. Build with "INCLUDE_PDE = y" in rules/config for pde-test

3. Verify the show platform { } commands
[show_IX7.log](https://github.com/sonic-net/sonic-buildimage/files/9355744/show_IX7.log)
[show_IX7_BDE.log](https://github.com/sonic-net/sonic-buildimage/files/9355739/show_IX7_BDE.log)
[show_IX8.log](https://github.com/sonic-net/sonic-buildimage/files/9355740/show_IX8.log)
[show_IX8A_BDE.log](https://github.com/sonic-net/sonic-buildimage/files/9355741/show_IX8A_BDE.log)
[show_IX8C.log](https://github.com/sonic-net/sonic-buildimage/files/9355742/show_IX8C.log)
[show_IX9.log](https://github.com/sonic-net/sonic-buildimage/files/9355743/show_IX9.log)

4. Verify with pde-test -v
[pde-test_IX7.log](https://github.com/sonic-net/sonic-buildimage/files/9355750/pde-test_IX7.log)
[pde-test_IX7_BDE.log](https://github.com/sonic-net/sonic-buildimage/files/9355745/pde-test_IX7_BDE.log)
[pde-test_IX8.log](https://github.com/sonic-net/sonic-buildimage/files/9355746/pde-test_IX8.log)
[pde-test_IX8A_BDE.log](https://github.com/sonic-net/sonic-buildimage/files/9355747/pde-test_IX8A_BDE.log)
[pde-test_IX8C.log](https://github.com/sonic-net/sonic-buildimage/files/9355748/pde-test_IX8C.log)
[pde-test_IX9.log](https://github.com/sonic-net/sonic-buildimage/files/9355749/pde-test_IX9.log)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog
Update files of existing Quanta device/platform

#### A picture of a cute animal (not mandatory but encouraged)
乁( ◔ ౪◔)「

### CODE REVIEW

**Comment by roberthong-qct** [comment]
@geans-pin @saiarcot895 please help to review this PR, thank you.

**Comment by saiarcot895** [comment]
@roberthong-qct there's an issue that the build is running into. I've opened #11763 to try to fix it.

**Comment by roberthong-qct** [comment]
@saiarcot895 Should I run the build after the issue is fixed (https://github.com/sonic-net/sonic-buildimage/pull/11763 is merged) or it can be neglected in the PR since  "Build broadcom" can be passed in the previous run (https://dev.azure.com/mssonic/build/_build/results?buildId=135912&view=results) ?

**Comment by saiarcot895** [comment]
Run the build after the issue is fixed. Only the latest status is considered for determining if something is successful or not.

**Comment by roberthong-qct** [comment]
@saiarcot895 The checks can pass now, thank you.
@geans-pin Can you help to review this PR, especially pde-test logs?

**Comment by geans-pin** [comment]
> @saiarcot895 The checks can pass now, thank you. @geans-pin Can you help to review this PR, especially pde-test logs?

Approved

**Comment by geans-pin** [comment]
> > @saiarcot895 The checks can pass now, thank you. @geans-pin Can you help to review this PR, especially pde-test logs?
> 
>

@saiarcot895 Can you help to review and merge the Quanta SONIC BSP code ? The PDE testing UT is provided

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
