### PR TITLE
Start fabric mgr daemon in swss container.

### PR DESCRIPTION
**Pull request by jfeng-arista**
#### Why I did it
The fabricmgr daemon started in vs environment for testing from sonic-net/sonic-buildimage#16791, we now start the daemon in product code.  
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Start fabric mgr daemon in swss container . 
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by jfeng-arista** [comment]
the failure seems not related to the change 

/Azpw run Azure.sonic-buildimage

**Comment by jfeng-arista** [comment]
2023-12-13T21:09:29.8376752Z Test plan id: 657a0283cfacd86e78e3e907, status: EXECUTING, progress: 91.67%, elapsed: 5169 seconds
2023-12-13T21:09:29.8377841Z Operation failed with exception: Exception('Test plan id: 657a0283cfacd86e78e3e907, status: FAILED, result: FAILED, Elapsed 5229 seconds. Check https://elastictest.org/scheduler/testplan/657a0283cfacd86e78e3e907 for test plan status')
2023-12-13T21:09:29.8580108Z ##[error]Bash exited with code '3'.
2023-12-13T21:09:29.8610465Z ##[section]Finishing: Run test

failed as abvoe, not sure if this could related to my change as it is in t0.

I will retirgger the pipline tomorrow

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@lguohan, can you help merge this PR

**Pull request merged**
