### PR TITLE
[VOQ Chassis] Reduce the i-BGP Keep alive and Hold timer value

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

Reduce the i-BGP Keep alive and Hold timer value for i-BGP session in VOQ Chassis

Why I did:

In case on upgraceful reboot of LC's faster BGP convergance.

How I verify:
Manual Verification
UT updated.

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Review by judyjoseph — APPROVED** [review]

**Comment by abdosi** [comment]
@rlhui : Can you please help with merge of this.

**Comment by abdosi** [comment]
@gechiang : please help in taking MSFT repo.

**Comment by rlhui** [comment]
@BYGX-wcr

**Comment by BYGX-wcr** [comment]
> @BYGX-wcr

Got this

**Comment by abdosi** [comment]
@bingwang-ms @yejianquan : please help with cherry-pick.

**Pull request merged**
