### PR TITLE
[Micas/Platform]platform M2-W6510 uses Linux kernel drivers

### PR DESCRIPTION
**Pull request by philo-micas**
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
We try to use Linux kernel drivers to replace our drivers, except for some drivers that we have implemented ourselves.
For this purpose, we have submitted the following PR to the sonic-linux-kernel repository:
https://github.com/sonic-net/sonic-linux-kernel/pull/411
https://github.com/sonic-net/sonic-linux-kernel/pull/413
https://github.com/sonic-net/sonic-linux-kernel/pull/417

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by vmittal-msft** [comment]
@saiarcot895  Can you please help review these changes ?

**Comment by philo-micas** [comment]
[report_M2-W6510-48V8C_0723.zip](https://github.com/user-attachments/files/16344575/report_M2-W6510-48V8C_0723.zip)
@lguohan Hi guohan, test report has been submitted, please help to push forward this pr. Thanks.

**Comment by philo-micas** [comment]
cc @prgeor Hi Price and guohan, help review this PR, the modification is simple, include remove native kernel drivers from platform, and add GPL comments, since other products pr depend on this common pr, need help push it, appreciate and thanks!

**Comment by philo-micas** [comment]
@prgeor Help review and push the Micas platform optimization pr forward, thanks! It is about removing all native drivers from platform code, and add some license comments for other self implemented drivers, wish it could not take your too much time, thanks!

**Comment by gechiang** [comment]
@saiarcot895 please help review these PRs. Thanks!

**Comment by StephenSJCA** [comment]
@gechiang @saiarcot895 Any other questions on it? Everything checked OK and this PR ONLY adjust our platform's codes, why has there been no movement after two weeks? 
We don't want to repeatedly bring up this matter in issue triage meetings... It has a very serious impact on our contribution progress, please take time working on it ASAP, many thanks.

cc PM @zhangyanzhao

**Comment by zhangyanzhao** [comment]
@prgeor  can you please help to review this PR and see if you are ok to merge. Thanks.

**Comment by qiluo-msft** [comment]
Could you move license related changes into a standalone PR and let this PR focus on platform code changes? Need completed different set of reviewers on each one.

**Comment by philo-micas** [comment]
> Could you move license related changes into a standalone PR and let this PR focus on platform code changes? Need completed different set of reviewers on each one.

Of course, thanks.

**Comment by philo-micas** [comment]
@qiluo-msft Done. The separate PR for the license is https://github.com/sonic-net/sonic-buildimage/pull/20312. Please help review it and continue to push this PR forward. Many thanks!

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
