### PR TITLE
[Bookworm] Fix timezone propagation to containers

### PR DESCRIPTION
**Pull request by vivekrnv**
#### Why I did it

Fix https://github.com/sonic-net/sonic-buildimage/issues/20925

Not cherry-pickable to 202405, will raise a separate PR

#### How I did it

Mount /etc/localtime on containers and remove /etc/timezone dependency

#### How to verify it

```
root@sonic:/home/admin# zdump /etc/localtime
/etc/localtime  Fri Dec  6 23:24:03 2024 IST

root@sonic:/home/admin# docker exec swss zdump /etc/localtime
/etc/localtime  Fri Dec  6 23:24:12 2024 IST
```

Verify swss.rec/sairedis.rec and syslog are following same time

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by vivekrnv** [comment]
@nmoray FYI

**Comment by liat-grozovik** [comment]
thanks @vivekrnv for the fix.

**Comment by liat-grozovik** [comment]
@saiarcot895 would you like to review or suggest someone else? if not, i would take Sud approval as good enough and merge

**Review by saiarcot895 — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
