### PR TITLE
Support SymCrypt OpenSSL for armhf

### PR DESCRIPTION
**Pull request by xumia**
#### Why I did it
Support SymCrypt OpenSSL for armhf

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@xumia , is this still needed?

**Comment by xumia** [comment]
> @xumia , is this still needed?

Closed.

**Pull request closed without merging**
