### PR TITLE
[202311][Mellanox] Update SDK/FW to 4.6.4122/2012.4120

### PR DESCRIPTION
**Pull request by DavidZagury**
#### Why I did it
Update SDK/FW to 4.6.4122/2012.4120

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@DavidZagury Can you check the build failure? Seems some file is missing.
```
curl: (22) The requested URL returned error: 404 
Try 5: /usr/bin/curl --retry-connrefused --retry 5 failed to get: -L
[  FAIL LOG END  ] [ target/files/bullseye/fw-SPC2-rel-29_2012_4120-EVB.mfa ]
make: *** [slave.mk:661: target/files/bullseye/fw-SPC2-rel-29_2012_4120-EVB.mfa] Error 1
[ finished ] [ target/files/bullseye/fw-SPC-rel-13_2012_4120-EVB.mfa ] 
[ FAIL LOG START ] [ target/files/bullseye/fw-SPC-rel-13_2012_4120-EVB.mfa ]
Build start time: Mon Oct 7 19:42:23 UTC 2024
```

**Comment by DavidZagury** [comment]
> @DavidZagury Can you check the build failure? Seems some file is missing.
> 
> ```
> curl: (22) The requested URL returned error: 404 
> Try 5: /usr/bin/curl --retry-connrefused --retry 5 failed to get: -L
> [  FAIL LOG END  ] [ target/files/bullseye/fw-SPC2-rel-29_2012_4120-EVB.mfa ]
> make: *** [slave.mk:661: target/files/bullseye/fw-SPC2-rel-29_2012_4120-EVB.mfa] Error 1
> [ finished ] [ target/files/bullseye/fw-SPC-rel-13_2012_4120-EVB.mfa ] 
> [ FAIL LOG START ] [ target/files/bullseye/fw-SPC-rel-13_2012_4120-EVB.mfa ]
> Build start time: Mon Oct 7 19:42:23 UTC 2024
> ```
Thank you @bingwang-ms, fixed

**Comment by DavidZagury** [comment]
> @DavidZagury Can you check the build failure? Seems some file is missing.
> 
> ```
> curl: (22) The requested URL returned error: 404 
> Try 5: /usr/bin/curl --retry-connrefused --retry 5 failed to get: -L
> [  FAIL LOG END  ] [ target/files/bullseye/fw-SPC2-rel-29_2012_4120-EVB.mfa ]
> make: *** [slave.mk:661: target/files/bullseye/fw-SPC2-rel-29_2012_4120-EVB.mfa] Error 1
> [ finished ] [ target/files/bullseye/fw-SPC-rel-13_2012_4120-EVB.mfa ] 
> [ FAIL LOG START ] [ target/files/bullseye/fw-SPC-rel-13_2012_4120-EVB.mfa ]
> Build start time: Mon Oct 7 19:42:23 UTC 2024
> ```
@bingwang-ms 
Looking in to it

**Comment by DavidZagury** [comment]
@bingwang-ms fixed

**Comment by bingwang-ms** [comment]
MSFT ADO: 29661544
The PR is to address the #1 issue on SN4700.

**Pull request merged**
