### PR TITLE
[Mellanox] enable the SDK api recording by default

### PR DESCRIPTION
**Pull request by yuazhe**
#### Why I did it
SDK sniffer will record the RPC calls from the SDK user API library to the sx_sdk task into a .pcap file. This .pcap file can be replayed afterward to get the exact same state on SDK and FW to reproduce and investigate issues. 

SDK added cyclic mode of API sniffer, and previously, users could use config platform mlnx sniffer enable/disable to control the feature, now they must manually change the content of saiprofile. The old CLI entry point will be removed. 

Depending on SAI 2405.28.0.45

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
added relevant SAI keys in sai-common.profile
removed deprecated CLI in sonic-utilities https://github.com/sonic-net/sonic-utilities/pull/3491

#### How to verify it

check the pcap file under /var/log/sdk_dbg

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] 202405
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yuazhe once this is enabled, what are the CLI commands that should not be used?
please have a PR that introduce the CLI removal as well.

**Comment by yuazhe** [comment]
> @yuazhe once this is enabled, what are the CLI commands that should not be used? please have a PR that introduce the CLI removal as well.

@liat-grozovik  at this time there is no new CLI available, user need to manually edit the SAI profile to control this feature. Regarding the CLI removal, the pr had been stated in the description https://github.com/sonic-net/sonic-utilities/pull/3491

**Comment by bingwang-ms** [comment]
Hi @yuazhe, I do have concern in enabling api recording by default. Particularly on some weak CPU platform (like SN2700). The sx_sdk is already consuming lot of memory and CPU.

**Comment by yuazhe** [comment]
> Hi @yuazhe, I do have concern in enabling api recording by default. Particularly on some weak CPU platform (like SN2700). The sx_sdk is already consuming lot of memory and CPU.

Hi, @bingwang-ms Regarding the performance concern, we had run regression testing on all platforms including SN2700 and no degradation had been found. Besides, for every API, we expect less than 2% execution time increase when api recording enabled.

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Hi @yuazhe, since this is an enhancement, I tend to leave it for next release (202411).

**Comment by yuazhe** [comment]
> Hi @yuazhe, since this is an enhancement, I tend to leave it for next release (202411).

Hi, @bingwang-ms I would like to emphasis the advantage of this feature, as it can record sdk calling in the real time and if you still decide to put it to 2411, please also be aware that https://github.com/sonic-net/sonic-utilities/pull/3491 is depend on this pr.

**Pull request merged**
