### PR TITLE
[Mellanox] Enable CMIS host mgmt. feature to Mellanox-SN4700-O8C48, Mellanox-SN4700-O8V48 SKUs

### PR DESCRIPTION
**Pull request by noaOrMlnx**
#### Why I did it
To enable CMIS host mgmt feature
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
N/A
#### How to verify it
Load the system with the relevant SKU, verify CMIS host management is enabled, and per supported module check SW control is on.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — CHANGES_REQUESTED** [review]
please also update the SAI profile

**Comment by keboliu** [comment]
and also please update the media_settings and optics_si_settings file.

**Comment by noaOrMlnx** [comment]
@keboliu 
Feature in sai.profile is already enabled. 
Regarding the media_settings.json update request, disucssed internally and found a solution. will apply soon

**Review by keboliu — APPROVED** [review]

**Comment by noaOrMlnx** [comment]
Azure-Pipelines-Wrapper / ms_conflict

**Review by prgeor — APPROVED** [review]

**Comment by noaOrMlnx** [comment]
@yxieca can you please cherry-pick to 202311?

**Pull request merged**
