### PR TITLE
Added change to add 'peerType' as element in NEIGH_STATE_TABLE.

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Added change to add 'peerType' as element in NEIGH_STATE_TABLE.
'peerType' can be i-BGP vs e-BGP determined based on local and remote AS number.

Why I did:
This is useful to filter neighbors in SONiC as internal vs external in chassis use-case (example: telemetry) 

Verification:

- Manual Verification

```
127.0.0.1:6379[6]> hgetall "NEIGH_STATE_TABLE|10.0.0.5"
1) "state"
2) "Established"
3) "peerType"
4) "e-BGP"
127.0.0.1:6379[6]> hgetall  "NEIGH_STATE_TABLE|2603:10e2:400::4"
1) "state"
2) "Established"
3) "peerType"
4) "i-BGP"

```

- Also sonic-mgmt test case `test_bgp_fact.py` is enhanced: https://github.com/sonic-net/sonic-mgmt/pull/8462

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by abdosi** [comment]
@StormLiangMS can you please help review/merge this.

**Review by StormLiangMS — APPROVED** [review]
Approved with one question, for chassis, i-bgp between linecards? e-bgp for everything else?

@abdosi

**Comment by abdosi** [comment]
> Approved with one question, for chassis, i-bgp between linecards? e-bgp for everything else?
> 
> @abdosi



> Approved with one question, for chassis, i-bgp between linecards? e-bgp for everything else?
> 
> @abdosi

yes i-BGP between all ASIC's across all LC's

**Comment by prsunny** [comment]
Should we add a test for this?

**Comment by abdosi** [comment]
> Should we add a test for this?

sonic-mgmt test has been updated for this: https://github.com/sonic-net/sonic-mgmt/pull/8462

**Comment by abdosi** [comment]
@yxieca  this is need to be cherry-picked.

**Pull request merged**
