### PR TITLE
PFCWD fix for multi port multi priority scenario for HWSKU Dell Z9332

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
PFCWD recovery mechanism had issues for multi port multi priority scenario if PFCWD triggers simultaneously.

#### How I did it
PFCWD recovery mechanism is changed from SONIC based recovery to SAI/SDK using SAI attribute SAI_QUEUE_ATTR_PFC_DLR_INIT.

Order of changes -
1. swss - https://github.com/sonic-net/sonic-swss/pull/2316
2. SAI change for new method - https://github.com/sonic-net/sonic-buildimage/pull/11693
3. swss submodule update - https://github.com/sonic-net/sonic-buildimage/pull/11690

#### How to verify it
Verified the fix on actual HW using ixia as tester.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [x] 202012
- [x] 202106
- [x] 202111
- [x] 202205

#### Description for the changelog

PFCWD fix for multi port multi priority scenario for HWSKU Dell Z9332

### CODE REVIEW

**Review by gechiang — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by liuh-80** [comment]
Discussion in today's 202012 branch release meeting, add reject tag.

**Comment by liuh-80** [comment]
Fix the rejected tag issue.

**Pull request merged**
