### PR TITLE
[Marvell-arm64] Add platform support for rd98DX35xx

### PR DESCRIPTION
**Pull request by pavannaregundi**
#### Why I did it
Add following two variants of rd98DX35xx board to marvell-arm64 build.

Board with CPU integrated into the 98DX35xx switching chip:
    
     Platform: arm64-marvell_rd98DX35xx-r0
     HwSKU: rd98DX35xx
     ASIC: marvell
     Port Config: 32x1G + 16x2.5G + 6x25G
    
Board with external CN9131 CPU connected over PCI to 98DX35xx switching chip:
    
     Platform: arm64-marvell_rd98DX35xx_cn9131-r0
     HwSKU: rd98DX35xx_cn9131
     ASIC: marvell
     Port Config: 32x1G + 16x2.5G + 6x25G

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added new HWSKU in device/marvell.
Added submodule platform/marvell-arm64/sonic-platform-marvell and makefile platform/marvell-arm64/platform-marvell.mk to compile debs for new platform.
Added change for platform.conf and sonic_fit.

#### How to verify it
Verified ONIE and SONiC installs and checked to see "show interface status" shows ports UP.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by pavannaregundi** [comment]
@lguohan Can you please review this.

**Comment by pavannaregundi** [comment]
@yxieca Please see if you can review this.

**Comment by saiarcot895** [comment]
@prgeor would you be able to review this?

**Review by lguohan — APPROVED** [review]

**Comment by lguohan** [comment]
lgtm,  @prgeor , do you want to review, or you are fine?

**Pull request merged**
