### PR TITLE
Change TTL value range

### PR DESCRIPTION
**Pull request by xincunli-sonic**
#### Why I did it

The industry standard of TTL is actually 0..255

##### Work item tracking
- Microsoft ADO **(number only)**: 29679446

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by bingwang-ms — DISMISSED** [review]

**Comment by xincunli-sonic** [comment]
@StormLiangMS can you help take a look this conflict?

**Review by bingwang-ms — APPROVED** [review]

**Comment by xincunli-sonic** [comment]
@qiluo-msft can you help merge?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
