### PR TITLE
YANG Configuration.md fix table of contents links

### PR DESCRIPTION
**Pull request by bradh352**
#### Why I did it
Due to excess whitespace, the table of contents does not render as links in github, leading to navigation issues.

This might cause some minor "pain" for other merge requests due to the formatting differences in the ToC, but it should really only take a second to correct.  Better to fix it once and make everyone's life easier than just living with it.

#### How I did it

Updated whitespace and a couple other very minor correctness changes for MarkDown.  There are still other changes I'd like to do but much lower priority and possibly not worth the disturbance.

#### How to verify it

View the corrected table of contents here:
https://github.com/bradh352/sonic-buildimage/blob/configuration.md/src/sonic-yang-models/doc/Configuration.md

Compared to original unrendered ToC here:
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md

#### Which release branch to backport (provide reason below if selected)

Not needed

#### Tested branch (Please provide the tested image version)

master as of 20241206

#### Description for the changelog
YANG Configuration.md fix table of contents links
#### A picture of a cute animal (not mandatory but encouraged)
Signed-off-by: Brad House (@bradh352)

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by bradh352** [comment]
rebased to force rebuild to see if general sonic CI tests are working yet

**Comment by bradh352** [comment]
@qiluo-msft please merge since you approved it

**Comment by bradh352** [comment]
@qiluo-msft i think maybe azpw needs to be run.  Will it auto-merge if that succeeds since you approved?  I think the build failed to actually kick off.

**Comment by bradh352** [comment]
rebased to try to force rebuild since last build hung

**Pull request merged**
