### PR TITLE
[Build] fix make clean

### PR DESCRIPTION
**Pull request by kv-y**
#### Why I did it

`make clean` is broken after #12000:
```
bash: -c: line 1: syntax error near unexpected token `;'
bash: -c: line 1: `make -f slave.mk PLATFORM= PLATFORM_ARCH=amd64 MULTIARCH_QEMU_ENVIRON=n 
...
MIRROR_URLS= MIRROR_SECURITY_URLS=  Q=@ clean; ; '
make[1]: *** [Makefile.work:531: clean] Error 2
```
#### How I did it
Remove a conditional for `clean` command.

Signed-off-by: Konstantin Vasin <k.vasin@yadro.com>

### CODE REVIEW

**Comment by kv-y** [comment]
@Kalimuthu-Velappan 

You added this conditional: ifeq ($(filter clean,$(MAKECMDGOALS)),)  in #12000.
If it's not for some special purpose then I think we can just remove it to fix `make clean` command.

**Comment by Kalimuthu-Velappan** [comment]
> @Kalimuthu-Velappan
> 
> You added this conditional: ifeq ($(filter clean,$(MAKECMDGOALS)),) in #12000. If it's not for some special purpose then I think we can just remove it to fix `make clean` command.
> 
> Another possible solution is:
> 
>     1. Use filter or filter-out not only for clean but for other targets like distclean and list too.
> 
>     2. Fix double semicolon error.

You can go ahead and commit the current fix. I will address this in a separate PR.

**Review by xumia — APPROVED** [review]

**Comment by lguohan** [comment]
@kv-y , i resolve the conflict, can you check if the pr still good?

**Comment by kv-y** [comment]
> You can go ahead and commit the current fix. I will address this in a separate PR.

@Kalimuthu-Velappan 
Are you still going to address this bug in a separate PR?
I mean this code `filter clean,$(MAKECMDGOALS)` was added as part of you PR for vcache.
PR for vcache was merged in #12000 and #12005.

If you don't need a special handling for `clean` command for vcache framework and it's just for refactoring then we can merge this PR.

**Pull request merged**
