### PR TITLE
Platform DCS-7060DX5-32 MMU rollback to avoid dependancy on Broadcom

### PR DESCRIPTION
**Pull request by vincentpcng**
driver patch

#### Why I did it
This commit is to avoid Broadcom driver dependency on the MMU config

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
We upload  the basic version of the Broadcom configure with limited configuration.

#### How to verify it
We verified the change internally in Arista

#### Which release branch to backport (provide reason below if selected)
master and 202405

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)
202405 and master

- [x] master
- [x] 202405

### CODE REVIEW

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @bingwang-ms this is only impact 7060dx5, could you help to cherry pick?

**Comment by byu343** [comment]
We need this change to be backported to 202411. Thanks

**Comment by StormLiangMS** [comment]
hi @kperumalbfn could you help to cherry pick to 202411, this is for TH4.

**Comment by StormLiangMS** [comment]
Hi @kperumalbfn  could you help to pick for 202411? It was a mistake that I thought it is not needed.

**Comment by kperumalbfn** [comment]
@StormLiangMS Do we need this SKU to be added in GCU https://github.com/sonic-net/sonic-utilities generic_config_updater/gcu_field_operation_validators.conf.json?

**Pull request merged**
