### PR TITLE
[chassis] Added support of isolating given LC in Chassis with TSA mode

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Added support when TSA is done on Line Card make sure it's completely
isolated from all e-BGP peer devices from this LC or remote LC

Why I did:
Currently when TSA is executed on LC routes are withdrawn from it's connected e-BGP peers only. e-BGP peers on remote LC can/will (via i-BGP) still have route pointing/attracting traffic towards this isolated LC.

How I did:
1. When TSA is applied on LC all the routes that are advertised via i-BGP are set with community tag of `no-export` so that when remote LC received these routes it does not send over to it's connected e-BGP peers.

2. Also once we receive the route with `no-export ` over iBGP match on it and and set the `local preference` of that route to lower value (80) so that we remove that route from the forwarding database.  Belowe scenario explains why we do this:

- LC1 advertise R1 to LC3
- LC2 advertise R1 to LC3
- On LC3 we have multi-path/ECMP over both  LC1 and LC2
- On LC3 R1 received from LC1 is consider best route over R1 over received from LC2 and is send to LC3 e-BGP peers
- Now we do TSA on LC2
- LC3 will receive R1 from LC2 with community `no-export` and from LC1 same as earlier (no change)
- LC3 will still get traffic for R1 since it is still advertised to e-BGP peers (since R1 from LC1 is best route)
- LC3 will forward to both LC1 and LC2 (ecmp) and this causes issue as LC2 is in TSA mode and should not receive traffic

To fix above scenario we change the preference to lower value of R1 received from LC2 so that it is removed from Multi-path/ECMP group.

How I verfiy:
1. UT has been added to make sure Template generation is correct
2. Manual Verification of the functionality
4. sonic-mgmt test case will be updated accordingly.

Please note this PR is on top of this :https://github.com/sonic-net/sonic-buildimage/pull/16714 which needs to be merged first.

### CODE REVIEW

**Comment by gechiang** [comment]
@abdosi , test failed here:
```
=================================== FAILURES ===================================
__________________________ test_TSA[vlab-03-default] ___________________________

duthosts = [<MultiAsicSonicHost vlab-03>]
enum_rand_one_per_hwsku_frontend_hostname = 'vlab-03'
ptfhost = <tests.common.devices.ptf.PTFHost object at 0x7fde0d3bf640>
nbrhosts_to_dut = {'ARISTA01T0': <EosHost VM0112>, 'ARISTA01T2': <EosHost VM0104>, 'ARISTA02T0': <EosHost VM0113>, 'ARISTA03T0': <EosHost VM0114>, ...}
bgpmon_setup_teardown = {'local_addr': '20.0.0.0/31', 'local_intf': 'Ethernet64', 'loopback_ip': '10.1.0.32', 'namespace': None, ...}
traffic_shift_community = '12345:12345'
tbinfo = {'auto_recover': 'False', 'comment': 'Tests virtual switch vm', 'conf-name': 'vms-kvm-t1-lag', 'duts': ['vlab-03'], ...}

    def test_TSA(duthosts, enum_rand_one_per_hwsku_frontend_hostname, ptfhost,
                 nbrhosts_to_dut, bgpmon_setup_teardown, traffic_shift_community, tbinfo):
        """
        Test TSA
        Verify all routes are announced to bgp monitor, and only loopback routes are announced to neighs
        """
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
        try:
            # Issue TSA on DUT
            duthost.shell("TSA")
            # Verify DUT is in maintenance state.
>           pytest_assert(TS_MAINTENANCE == get_traffic_shift_state(duthost),
                          "DUT is not in maintenance state")
E                         Failed: DUT is not in maintenance state

bgpmon_setup_teardown = {'local_addr': '20.0.0.0/31', 'local_intf': 'Ethernet64', 'loopback_ip': '10.1.0.32', 'namespace': None, ...}
duthost    = <MultiAsicSonicHost vlab-03>
duthosts   = [<MultiAsicSonicHost vlab-03>]
enum_rand_one_per_hwsku_frontend_hostname = 'vlab-03'
nbrhosts_to_dut = {'ARISTA01T0': <EosHost VM0112>, 'ARISTA01T2': <EosHost VM0104>, 'ARISTA02T0': <EosHost VM0113>, 'ARISTA03T0': <EosHost VM0114>, ...}
ptfhost    = <tests.common.devices.ptf.PTFHost object at 0x7fde0d3bf640>
tbinfo     = {'auto_recover': 'False', 'comment': 'Tests virtual switch vm', 'conf-name': 'vms-kvm-t1-lag', 'duts': ['vlab-03'], ...}
traffic_shift_community = '12345:12345'

bgp/test_traffic_shift.py:364: Failed
=============================== warnings summary ===============================
../../../../usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18
  /usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18: DeprecationWarning: The _yaml extension module is now located at yaml._yaml and its location is subject to change.  To use the LibYAML-based parser and emitter, import from `yaml`: `from yaml import CLoader as Loader, CDumper as Dumper`.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /var/src/sonic-mgmt/tests/logs/bgp/test_traffic_shift|||2.xml -
=========================== short test summary info ============================
FAILED bgp/test_traffic_shift.py::test_TSA[vlab-03-default] - Failed: DUT is ...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=================== 1 failed, 1 warning in 143.10s (0:02:23) ===================
```

**Comment by gechiang** [comment]
@abdosi , Can you check/address the PR test failures?

**Review by deepak-singhal0408 — APPROVED** [review]
LGTM

**Comment by abdosi** [comment]
@StormLiangMS please help with cherry-pick in 202305. Has been tested with T0/T1

**Pull request merged**
