### PR TITLE
[202405][TSA] Reliable TSA: Conflict resolution for merging into 2024.05 branch

### PR DESCRIPTION
**Pull request by fountzou**
#### Why I did it
Conflict resolution of [PR#19217](https://github.com/sonic-net/sonic-buildimage/pull/19217) so that it can be cherry-picked into 2024.05
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Cherry-pick commits d702bcec5947d87f4becefbc593d4d174865d49a, 0975f250bbb43ce43000c251138608a23d6e1e0a

#### How to verify it
Ran reliable_tsa tests from https://github.com/sonic-net/sonic-mgmt/pull/13290 on a T2 chassis.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by abdosi** [comment]
can we patch this: https://github.com/sonic-net/sonic-buildimage/pull/19527  also as part of this PR.

**Comment by fountzou** [comment]
> can we patch this: #19527 also as part of this PR.

Done ae2d38ddc224de858fed275e970cd24ead712d4d. Thank you

**Comment by fountzou** [comment]
Hi @abdosi, could you please restart the pipeline? Thank you.

**Comment by fountzou** [comment]
@abdosi, @tjchadaga: Could you please assist on reviewing this one?

**Review by abdosi — APPROVED** [review]

**Pull request merged**
