### PR TITLE
[Mellanox] Add bfb image installation script to the switch image

### PR DESCRIPTION
**Pull request by gpunathilell**
#### Why I did it
In order to install the bfb image from the switch to all the dpus we need a script to execute the bfb_install script on all the detected rshim device parallely. The `sonic-bfb-installer` can be used to install bfb images on the DPUs from the switch using the rshim drivers
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added new makefile and script files for installation of bfb image
#### How to verify it
`sonic-bfb-installer.sh -b <bfb_image_path> -r all`
`sonic-bfb-installer.sh -b <bfb_image_path> -r rshim1,rshim0`

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by lguohan** [comment]
@dgsudharsan , can we get sign off?

**Comment by dgsudharsan** [comment]
@oleksandrivantsiv Can you please signoff?

**Review by oleksandrivantsiv — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
