### PR TITLE
[202211][Mellanox] Update HW-MGMT package to new version V.7.0030.1011(#16239)

### PR DESCRIPTION
**Pull request by keboliu**
#### Why I did it
backport https://github.com/sonic-net/sonic-buildimage/pull/16239

1. Update Mellanox HW-MGMT package to newer version V.7.0030.1011
2. Replace the SONiC PMON Thermal control algorithm with the one inside the HW-MGMT package on all Nvidia platforms
3. Support Spectrum-4 systems

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
1. Update the HW-MGMT package version number and submodule pointer
2. Remove the thermal control algorithm implementation from Mellanox platform API
3. Revise the patch to HW-MGMT package which will disable HW-MGMT from running on SIMX
5. Update the downstream kernel patch list 
#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [] 
- []

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@StormLiangMS can you please help to merge? pls confirm the dependency is included as well

**Comment by keboliu** [comment]
@StormLiangMS  would you please help to merge this PR?

**Comment by StormLiangMS** [comment]
enhancement, but only take effect on Mellanox platform.

**Comment by keboliu** [comment]
> enhancement, but only take effect on Mellanox platform.

Hi Storm, this new HW-MGMT is to support Mellanox SPC4 platforms, w/o it SPC4 won't work in this branch.

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
