### PR TITLE
Added flag in sonic_version.yml to see if image is secured or non-secured

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Added flag in sonic_version.yml to see if **compiled image is secured or non-secured**. This is done using build/compile time environmental variable `SECURE_UPGRADE_MODE`  as define in HLD: https://github.com/sonic-net/SONiC/blob/master/doc/secure_boot/hld_secure_boot.md

This flag does not provide the runtime status of whether the image has booted securely or not. It's possible that compile time signed image (secured image) can boot on non secure platform.

Why I did:
Flag can be used for manual check or by the test case.

ADO: 24319390

How I verify:
Manual Verification

```
---
build_version: 'master-16191.346262-cdc5e72a3'
debian_version: '11.7'
kernel_version: '5.10.0-18-2-amd64'
asic_type: broadcom
asic_subtype: 'broadcom'
commit_id: 'cdc5e72a3'
branch: 'master-16191'
release: 'none'
build_date: Fri Aug 25 03:15:45 UTC 2023
build_number: 346262
built_by: AzDevOps@vmss-soni001UR5
libswsscommon: 1.0.0
sonic_utilities: 1.2
sonic_os_version: 11
secure_boot_image: 'no'
```

This changes are used by this PR: https://github.com/sonic-net/sonic-mgmt/pull/9747

### CODE REVIEW

**Comment by abdosi** [comment]
@sacnaik please review

**Comment by abdosi** [comment]
@xumia can you please review.

**Review by xumia — APPROVED** [review]
LGTM

**Comment by abdosi** [comment]
@lguohan: Can you please help merge this PR.

**Comment by lguohan** [comment]
can you clairfy this secure_boot_image flag, what does it indicating, is it indicating the image has secure boot enabled, but when we install it on a non-secure boot enabled platform, will the image install ok? but boot without secure boot enabled?

**Comment by StormLiangMS** [comment]
@abdosi  could you provide test result with 202305 image?

**Comment by abdosi** [comment]
> @abdosi could you provide test result with 202305 image?

@StormLiangMS this change is generic and already this test https://github.com/sonic-net/sonic-mgmt/pull/9747 which is part of 202305 sonic-mgmt indirectly invoke this new variable define in sonic_version.yml

**Pull request merged**
