### PR TITLE
Add dependency to libyang in rules/swss-common.mk 

### PR DESCRIPTION
**Pull request by liuh-80**
Build swss-common with libyang

#### Why I did it
sonic-swss-common lib add dependency to libyang recently, so need update make file before update sonic-swss-common submodule.

#### How I did it
Add dependency to libyang in rules/swss-common.mk 

#### How to verify it
Pass all E2E test case.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog
Add new Redis database PROFILE_DB

### CODE REVIEW

**Comment by liuh-80** [comment]
This PR need wait for all azure pipelines PRs merge first, then must merge before update sonic-swss-common submodule.

**Comment by liuh-80** [comment]
The base branch restricts merging to authorized users.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
