### PR TITLE
[Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

 - Refactor PSU detection logic for more future proofing
 - Add support for new PSU models for Quicksilver
 - Leave low power mode asserted for all xcvrs
 - Use the newer `sonic_storage` APIs for storage

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Description for the changelog

Update Arista platform library submodules

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@lguohan please see if this can be merged.

**Comment by Staphylo** [comment]
This PR has been stuck for a while due to the `ms_conflict` which I cannot do anything about.
I tried rebasing hoping the `ms_conflict` and `ms_checker` errors would go away but they remain.
I believe this requires an action from someone at Microsoft. @prgeor @StormLiangMS @yxieca

**Pull request merged**
