### PR TITLE
[Nvidia] [202205] Update syncd docker to use python version 3

### PR DESCRIPTION
**Pull request by liorghub**
#### Why I did it
Python 2 is obsolete and no longer supported.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Change several packages installation commands in Nvidia syncd dockerfile to Python3 packages.
Change was done for regular image and for RPC image as well.
 
#### How to verify it
I tested several SDK API scripts manually (while all others are tested by SDK verification) and ran regression tests that run on RPC version.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by dprital** [comment]
@yxieca , Can you please approve and merge ?

**Comment by yxieca** [comment]
> @yxieca , Can you please approve and merge ?

@dprital can you elaborate why do we need to make this change when 202205 qualification is at the tail end? Are these commands broken in pyhon2? I fully support commands become python3 compliant or python3 only in the newer branches.

**Comment by liorghub** [comment]
@yxieca The initial plan was to remove python2 from Nvidia syncd container, but then I saw that Python2 exists in RPC container therefore I handled RPC container as well.
If you think it is not the right approach, may I create a different PR that contains only the changes in Nvidia syncd container?

**Comment by dprital** [comment]
@yxieca , Python2 is deprecated from NVIDIA (Mellanox) syncd so it was removed. This is the reason for this PR.

**Comment by yxieca** [comment]
> @yxieca , Python2 is deprecated from NVIDIA (Mellanox) syncd so it was removed. This is the reason for this PR.

@liorghub @dprital I fully support removing python2 code. However, I don't think we should do it in 202205 at this point when qualification activity is done or almost done. This change can go to newer branches.

**Comment by dprital** [comment]
> > @yxieca , Python2 is deprecated from NVIDIA (Mellanox) syncd so it was removed. This is the reason for this PR.
> 
> @liorghub @dprital I fully support removing python2 code. However, I don't think we should do it in 202205 at this point when qualification activity is done or almost done. This change can go to newer branches.

@yxieca , OK. This is the PR for Master (and request to cherry pick to 202305 and 202311. Can you please Approve and merge ?

https://github.com/sonic-net/sonic-buildimage/pull/17735

**Pull request closed without merging**
