### PR TITLE
Add Structured Events w/ YANG Models

### PR DESCRIPTION
**Pull request by zbud-msft**
#### Why I did it

Add events for dhcp-relay, bgp, syncd, kernel along with YANG models/UT

#### How I did it

Add regex for each process, add events_publish code for needed events

#### How to verify it

Run Unit tests

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Review by renukamanavalan — APPROVED** [review]

**Comment by ganglyu** [comment]
This PR has too many changes, maybe we can use one PR for yang models, and other PR for container and dhcpmon.

**Review by ganglyu — APPROVED** [review]

**Review by kellyyeh — APPROVED** [review]

**Pull request merged**
