### PR TITLE
[doc]: YANG UM: CRLF->LF

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

#### Why I did it
* To align YANG doc format with Linux line ending

#### How I did it
* Converted: `CRLF`->`LF`

#### How to verify it
* N/A

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Description for the changelog

* N/A

#### Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.
* N/A

#### Link to config_db schema for YANG module changes

* N/A

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Comment by nazariig** [comment]
@qiluo-msft can you please help to merge?

**Comment by nazariig** [comment]
@qiluo-msft just a kind reminder

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
