### PR TITLE
Updated bcmsai from version 7.1.66.7 to 7.1.80.4

### PR DESCRIPTION
**Pull request by vmittal-msft**
#### Why I did it
Updated SAI to include all latest fixes for sonic T2 chassis

##### Work item tracking
- Microsoft ADO **(28551006)**:

#### How I did it
Syncd up with BRCM master branch.

SAI version - 7.1.80.4
[SAI_BRANCH rel_ocp_sai_7_1] [CSP CS00012340907] Backport JIRA Backport SONIC-89800 to rel_ocp_sai_7_1
Issue Summary: Seeing traffic drops on all priorities when PFC asserted on two priorities.
Root Cause: 400G alpha settings incorrect
Fix Description: EGQ alpha tuning

SAI version - 7.1.79.4
[SAI_BRANCH rel_ocp_sai_7_1] [CSP CS00012340180] Backport JIRA SONIC-87935 to rel_ocp_sai_7_1
Issue Summary: Update the ACL impelementation to enable the ACL switch bind to support PFCWD on MACSEC devices --- DNX
Root Cause: RFE
Fix Description: RF (Info : Released before as part of 7.1.66.6)
Updated SDK with latest fixes for IPS Queue delete interrupt not clearing

SAI version - 7.1.78.4 (Info : Released before as part of 7.1.66.7)
Update git submodules
Update sdk-src/hsdk_6.5.24_SAI_7.1.0_GA from branch 'hsdk_6.5.24_SAI_7.1.0_GA'
to 6d522a50666f59ecf5c0b062206696058d067204
[SAI_BRANCH rel_ocp_sai_7_1] Backport JIRA SDK-279322 to rel_ocp_sai_7_1
Issue Summary: EPNI_EtppEbdErrInt,ESB_ECC_Ecc_1bErrInt,ESB_ECC_Ecc_2bErrInt reported when inject packet with random packet size
Root Cause: RFE
Fix Description: EGQ stuck and EPNI/ESB interrupts may occur due to a wrong ETPP latency configuration. Such behavior may happen when a different stream of packets hit different databases in ETPP Termination databases (e.g. one flow runs with ESEM access and one flow without ESEM access in parallel). The issue is now fixed.
Update git submodules
Update sdk-src/hsdk_6.5.24_SAI_7.1.0_GA from branch 'hsdk_6.5.24_SAI_7.1.0_GA'
to 183ee14b9930a0956e400b645d35137de0935d6f
[SAI_BRANCH rel_ocp_sai_7_1] Backport JIRA SDK-272527 to rel_ocp_sai_7_1

Issue Summary: JR2 PVTMON temp readings has rare outlier values
Root Cause: SW fix for PVT
Fix Description: SW actions to reduce the outlier value by reading 5 times, and check if value difference > 5 oC, then reject the reading, and reading again.

SAI version - 7.1.76.4
[CSP CS00012334537]backport SONIC-74283 to SAI7.1. Removed the restriction on FADT max on VSQ config

SAI version - 7.1.75.4
[CSP CS00012330453]backport SONIC-85159_to_SAI7.1
add pp drop to Egress queue counter's drop reason, then egress queue counter increases for DNX ERPP Trap drop packet

SAI version - 7.1.74.4 (Info : Released before as part of 7.1.66.6)
[CSP CS00012332612] backport_SONIC-85922 to SAI7.1
revert EGQ2SCH internal flow control on JR2
[CSP CS00012316306] backport SONIC-80654 to SAI 7.1
fix SAI qos_prof allocaiton issue
[CSP CS00012316306]SAI - backport SONIC-64658 to SAI7.1
After this fix below SAI debugcommands work

SAI version - 7.1.73.4
[CSP CS00012322843] SAI_API_ROUTE:brcm_sai_xgs_route_create:115 iptnl info get failed with error -7

SAI version - 7.1.72.4 (Info : Released before as part of 7.1.66.6)
BACKPORT SONIC-81858 PFCWD on IPv6
Issue Summary: PFCWD didn't drop IPv6 traffic in storm condition
Root Cause: EPMF is not created correctly
Fix Description: Add support for the ipv6 traffic

SAI version - 7.1.71.4
SID: MMU cosq control configuration with Dynamic Type Check

SAI version - 7.1.70.4
Backport SONIC-79944 to rel_ocp_sai_7_1
Issue Summary: Enable learning only if the port/lag is a bridge-port with ADMIN UP
Root Cause: Learmimg was enabled in all cases
Fix Description: Learning encabled only if the port/lag is a bridge-port with ADMIN UP

SAI version - 7.1.69.4
ECMP LB traffic polarization, configure hash_offset along with hash_seed attr

SAI version - 7.1.68.4
Update git submodules
Update sdk-src/hsdk_6.5.24_SAI_7.1.0_GA from branch 'hsdk_6.5.24_SAI_7.1.0_GA' to 00c41616710e8254f89b0bdd8af869b046ea0899
[CSP CS00012316299][SAI_BRANCH rel_ocp_sai_7_1] L3 entry delete failed when SER error is present

SAI version - 7.1.67.4
[CSP CS00012302165] Backport JIRA SONIC-77116 to rel_ocp_sai_7_1
Issue Summary: DNX ECMP hash fields clear before set
Root Cause: Original hash field selection was not being cleared when user updated the selection.
Fix Description: Field selection is cleared and only newly supplied selection is used.

#### How to verify it
Verified on sonic T2 chassis for basis tests.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
@vmittal-msft  can you check if the SAI debian is at the SONiC Storage location correctly?  PR build is failing.

**Comment by gechiang** [comment]
Managed to find the new brcmsai debians and uploaded them to 7.1.80.4 folder. Have restarted the failed build to see if it will pass now...

**Review by xumia — APPROVED** [review]
LGTM

**Comment by vmittal-msft** [comment]
@kenneth-arista @saksarav-nokia for info,

**Pull request merged**
