### PR TITLE
[dhcp_relay] Optimize j2 file in dhcp_relay container

### PR DESCRIPTION
**Pull request by yaqiangz**
#### Why I did it
Comma after dhcprelayd would cause error when dhcpv6relay doesn't exist.

##### Work item tracking
- Microsoft ADO **(number only)**: 26164305

#### How I did it
Add comma via dhcp6relay

#### How to verify it
UT passed and build image success

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by yaqiangz** [comment]
@kellyyeh Could you help to review this PR?

**Review by kellyyeh — APPROVED** [review]

**Comment by yaqiangz** [comment]
@yxieca Could you help to merge this PR?

**Comment by yaqiangz** [comment]
@yxieca Could you help to backport this PR?

**Comment by yaqiangz** [comment]
@yxieca Could you help to backport this PR?

**Pull request merged**
