### PR TITLE
Add a new config option to make gbsyncd optional

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

In an effort to allow people to build a slim version of SONiC to fit on devices to small storage, there is a need to disable some unneeded features.
The `docker-gbsyncd` are only applicable to devices with external gearboxes and might not apply to devices that need a small image.
It is therefore desirable to have a knob to not include these gbsyncd containers.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Add a new config `INCLUDE_GBSYNCD` which is enabled by default to retain the previous behavior.
Setting it to `n` will not include the `platform/components/docker-gbsyncd-*.mk`.

#### How to verify it

Set `INCLUDE_GBSYNCD = n` and witness that `docker-gbsyncd` images are not present in the final image.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Description for the changelog
Add a new config option to make gbsyncd optional

### CODE REVIEW

**Comment by Staphylo** [comment]
@StormLiangMS @lipxu

**Comment by lipxu** [comment]
Hi, @Staphylo , Thanks for your PR.
Does this mean 7050qx does not require the "docker-gbsyncd-broncos" and "docker-gbsyncd-credo" images? 
If so, how much storage size could be saved by disabling them, thanks a lot.

**Comment by Staphylo** [comment]
@lipxu this is correct, only a few products need gearboxes. The 7050QX-32S and 7060CX-32S do not need this.
The `phy-credo` package contributes `1M` to the `fs.squashfs` (`6.3M` uncompressed)
The `docker-gbsyncd-broncos` contributes to `13M` the `dockerfs.tar.gz` (`53M` uncompressed)
The `docker-gbsyncd-credo` contributes to `4.5M` the `dockerfs.tar.gz` (`17M` uncompressed)
At this point any savings we can get on `dockerfs.tar.gz` is good to have especially for `docker_inram`.

With the various savings in place I can also install the 202305 slim image in flash entirely and it takes 50% of the 4GB.
There is still some extra savings that can be done in the fs.squashfs that could potentially bring this percentage down.

**Review by lipxu — APPROVED** [review]
picked the diff and enabled INCLUDE_GBSYNCD, the test result seems OK to me, thanks a lot.

**Review by StormLiangMS — APPROVED** [review]
lgtm

**Comment by StormLiangMS** [comment]
ADO:25423859

**Pull request merged**
