### PR TITLE
[202205] [submodule] Advance sonic-dhcp-relay pointer

### PR DESCRIPTION
**Pull request by vivekrnv**
#### Why I did it

**Update dhcprelay submodule:**

```
047afb7 Fix multiple vlan issue 
2fbe729 disable cfg dynamic change 
13d0805 Use github code scanning instead of LGTM 
1e846f6 Fix packet range check for relay-reply packets 
4d19e13 Add unittest infrastructure 
7f4fdab fix packet range check issue 
257ecdf Add client packet UDP header length check 
```

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Comment by yxieca** [comment]
@vivekrnv can you remove your platform daemon commit? The submodule has already been advanced to the point you wanted to.

**Comment by vivekrnv** [comment]
> @vivekrnv can you remove your platform daemon commit? The submodule has already been advanced to the point you wanted to.

Updated

**Comment by dgsudharsan** [comment]
@yxieca @jcaiMR Can we merge this?

**Review by yxieca — APPROVED** [review]

**Pull request merged**
