### PR TITLE
sonic-buildimage: rename qsp 128x400g to o128s2, fix lane map typo

### PR DESCRIPTION
**Pull request by ccroy-arista**
#### Why I did it
Renamed hwsku directory for qsp-128x400g in an effort to use consistent hwsku naming convention going forward.
Added fix for lane mapping typo found recently.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Renamed hwsku directory from `Arista-7060X6-64PE-128x400G` to `Arista-7060X6-64PE-O128S2`.
Changed lanes to correct mapping for Ethernet356.

#### How to verify it
Confirm that the "hwsku" entry in config_db.json: matches: "Arista-7060X6-64PE-O128S2"

#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [ ] 202311
- [x] 202405

#### Tested branch (Please provide the tested image version)
202405

#### Description for the changelog
Renaming a hwsku folder for qsp platform from 128x400G to O128S2. Fixing lane map typo for interface Ethernet356.

### CODE REVIEW

**Review by r12f — APPROVED** [review]

**Comment by r12f** [comment]
hi Chris - just in case, do you mind to mention this PR in the issue tracker? Storm will help check and get it merged.

**Comment by ccroy-arista** [comment]
@r12f FYI I expanded the scope of this PR a bit to include a commit to fix a small typo in the bcm config file.

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @bingwang-ms could you help to cherry pick for 202405? This is for TH5.

**Pull request merged**
