### PR TITLE
Update cisco-8000.ini to 202405.0.9 release

### PR DESCRIPTION
**Pull request by anamehra**
Signed-off-by: Anand Mehra [anamehra@cisco.com](mailto:anamehra@cisco.com)

#### Why I did it

**Release Content**
Chassis: Added services.conf for startup_tsa_tsb.service
Fixed incorrect acpi log level (MIGSMSFT-723)
Fixed rconsole unresponsive issue (MIGSMSFT-759)
Add sensor offset and scaling factor to fan control sensor block
Fix for platform_tests.api.test_thermal.TestThermalApi failure (MIGSMSFT-674)
Fix for TestPfcwdFunc.test_pfcwd_no_traffic - syslog error (MIGSMSFT-672)
Fixed “[8101] Fail to create switch as SAI_COMMON_API_BULK_CREATE failed with 100G uplink” (MIGSMSFT-680)
Disabled sensord which is replaced by sensormond. Added sensormond test configurations
Increase ACL Table limit from 16 to 32
Various SAI loganalyzer error fixes

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by anamehra** [comment]
Hi @yejianquan , for you viz. Thanks

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
Release note:  https://github.com/Cisco-8000-sonic/platform-cisco-8000/releases/tag/202405.0.9

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
Hi @bingwang-ms ,could you help to cherry-pick to 202405? Thanks!

**Pull request merged**
