### PR TITLE
[202311][FRR]Adding fix for memory leak seen with BGP community

### PR DESCRIPTION
**Pull request by dgsudharsan**
Porting PR https://github.com/sonic-net/sonic-buildimage/pull/18272 to 202311.

#### Why I did it
Porting fix for https://github.com/FRRouting/frr/issues/15459

Adding patch for PR https://github.com/FRRouting/frr/pull/15466

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Ported the fix https://github.com/FRRouting/frr/pull/15466 to 8.5.1

#### How to verify it
Running the test_stress_route and ensure no memory leak

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@StormLiangMS please help to review. Tests will be completed very soon and we will to merge once done

**Comment by StormLiangMS** [comment]
hi @lipxu  @jimmyzhai  could you help to take review this PR?

**Comment by StormLiangMS** [comment]
> @StormLiangMS please help to review. Tests will be completed very soon and we will to merge once done

Have you verified with 202311 image? PR test has no gating for this one.

**Review by lipxu — APPROVED** [review]
LGTM

**Comment by dgsudharsan** [comment]
> > @StormLiangMS please help to review. Tests will be completed very soon and we will to merge once done
> 
> Have you verified with 202311 image? PR test has no gating for this one. @liat-grozovik

Hi @StormLiangMS . There is no test to verify. 202305 and 202311 have identical FRR. @lipxu verified the fixes in 202305. In my opinion the testing in 202305 is sufficient.

I would also recommend adding a test to sonic-mgmt to cover this scenario.

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
oops, 202311 should be Ying to decide to take or not, my bad. @yxieca

**Pull request merged**
