### PR TITLE
Align the ref pointer to latest code drop on 202205

### PR DESCRIPTION
**Pull request by kevinskwang**
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Pterosaur — APPROVED** [review]

**Review by lguohan — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@kevinskwang  ADO ?

**Comment by kevinskwang** [comment]
> @kevinskwang ADO ?

25228008

**Comment by lguohan** [comment]
@StormLiangMS , and @kevinskwang , during test we do find some minor issue on 202305 branch, if there is no hurry, we do not need to do backport.

**Comment by StormLiangMS** [comment]
sure.

**Pull request merged**
