### PR TITLE
Add gearbox taps to vs gearbox_config.json

### PR DESCRIPTION
**Pull request by byu343**
#### Why I did it
For the change to support gearbox taps by gearbox_config.json (https://github.com/Azure/sonic-swss/pull/2158), I need to add tests to sonic-swss/tests/test_gearbox.py to satisfy the test coverage of the change. The existing code in test_gearbox.py has already used brcm_gearbox_vs and here is to add some gearbox tap value to its gearbox_config.json, for the added tests in sonic-swss/tests/test_gearbox.py.

#### How to verify it
This change itself will not affect existing code.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

### CODE REVIEW

**Comment by prgeor** [comment]
@jimmyzhai can you review?

**Review by prgeor — APPROVED** [review]

**Review by jimmyzhai — APPROVED** [review]

**Comment by byu343** [comment]
@prgeor The checks have been passed. Can you please help to merge this change?

**Pull request merged**
