### PR TITLE
[Marvell] Updating hwsku configs to EZB1.08 version

### PR DESCRIPTION
**Pull request by Keshavg-marvell**
Updating hwsku file to EZB1.08 for AC5X RD board

#### Why I did it
To update hwsku file to EZB1.08 version for AC5X RD board 
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

hwsku ezb configs are needed for 202405 branch also. 

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Comment by Keshavg-marvell** [comment]
@yxieca Can you please backport this port to 202405? it is pending from long time.

**Comment by yxieca** [comment]
@Keshavg-marvell , please update which platforms/hardwareskus are affected/added by this change. @bingwang-ms  will help assess the requirement of backporting.

**Comment by Keshavg-marvell** [comment]
@yxieca   thanks for looking into it. This change is for Marvell AC5X platform's RD board hwskus.

**Comment by Keshavg-marvell** [comment]
@bingwang-ms  Can you please backport this fix to 202405?

**Pull request merged**
