### PR TITLE
[Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it
- Convert `hw-dump` into `generate-dump` plugins
- Enable DRAM scrubber on some products
- Fix xcvr driver active low register bit logic
- Improve cooling algorithm (now considers xcvrs and modules)
- Add linecard graceful shutdown (disabled by default)

The scrubber was enabled for the following products:
- `DCS-7050QX-32S`
- `DCS-7050CX3-32S`
- `DCS-7060CX-32S`

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Description for the changelog
Update Arista platform library

### CODE REVIEW

**Comment by Staphylo** [comment]
@prgeor @yxieca

**Comment by prgeor** [comment]
@Staphylo can you be specific which products `Enable DRAM scrubber on some products`
Will be helpful for future reference

**Comment by Staphylo** [comment]
@prgeor I just updated the comment

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@lguohan please help merge

**Pull request merged**
