### PR TITLE
[Mellanox] Support running hw-management service on MSN4700 emulation platform

### PR DESCRIPTION
**Pull request by stephenxs**
#### Why I did it

Support running hw-management service on MSN4700 emulation platform.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
- Use physical EEPROM instead of the fake one
- Do not skip PSUd, PCId, thermal control daemon
- Adjust PCIe and thermal configuration files
- Adjust platform.json for different chassis names and thermals
- Remove a patch to hw-management in order to enable it

#### How to verify it
Run Nvidia simulation on SN4700 (ASIC and Platform)

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by stephenxs** [comment]
The failure is not relevant to the PR. Merged the latest master back and then retry

**Pull request merged**
