### PR TITLE
Vnet monitor table cleanup

### PR DESCRIPTION
**Pull request by siqbal1986**
Missed Cast to master.
#### Why I did it
The changes in PR https://github.com/sonic-net/sonic-buildimage/pull/11999 should have been present in the master and were missed.
This PR remedies that.
##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by siqbal1986** [comment]
@prsunny can you please merge this? I dont have the rights.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
