### PR TITLE
[Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
#### Why I did it

 - Add support for new psus
 - Add support for new fan modules
 - Report fan information from all fabric cards
 - Fix psud warning due to invalid pmbus threshold reported
 - Disable lpmode for chassis

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Updated our platform driver submodules

#### How to verify it

Changes validated against sonic-mgmt 202405 and master

#### Description for the changelog

Update Arista platform library submodules

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@arlakshm @wenyiz2021 for viz

**Comment by arlakshm** [comment]
Hi @Staphylo, @kenneth-arista,
do we need the change to disable lpmode for chassis in the platform driver? I thought the change is done in xcvr to fix the lpmode issue on the chassis?

**Comment by kenneth-arista** [comment]
> Hi @Staphylo, @kenneth-arista, do we need the change to disable lpmode for chassis in the platform driver? I thought the change is done in xcvr to fix the lpmode issue on the chassis?

The change to disable lpmode for chassis in the platform library is a temporary work around while the fix to xcvrd is being worked on.

**Comment by prgeor** [comment]
> > Hi @Staphylo, @kenneth-arista, do we need the change to disable lpmode for chassis in the platform driver? I thought the change is done in xcvr to fix the lpmode issue on the chassis?
> 
> The change to disable lpmode for chassis in the platform library is a temporary work around while the fix to xcvrd is being worked on.

@Staphylo @kenneth-arista can we avoid hacking here? Looks like you don't want to own the change on Xcvrd code

**Review by wenyiz2021 — APPROVED** [review]

**Comment by patrickmacarthur** [comment]
I have opened PR #20929 to supersede this PR; it includes a revert for the "Disable lpmode on chassis" commit that was included in this PR

**Comment by rlhui** [comment]
> I have opened PR #20929 to supersede this PR; it includes a revert for the "Disable lpmode on chassis" commit that was included in this PR

please close this one then, thanks.

**Comment by patrickmacarthur** [comment]
> > I have opened PR #20929 to supersede this PR; it includes a revert for the "Disable lpmode on chassis" commit that was included in this PR
> 
> please close this one then, thanks.

This is Samuel's review so I don't have permissions to close it.

**Comment by rlhui** [comment]
> > > I have opened PR #20929 to supersede this PR; it includes a revert for the "Disable lpmode on chassis" commit that was included in this PR
> > 
> > 
> > please close this one then, thanks.
> 
> This is Samuel's PR so I don't have permissions to close it.

@Staphylo would you be closing this PR? thanks.

**Comment by Staphylo** [comment]
Closing as discussed

**Pull request closed without merging**
