### PR TITLE
[Mellanox] Use sdk sysfs instead of ethtool

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Currently, implementation:

- Reading EEPROM: via ethtool
- Writing EEPROM: via mlxreg tool.

The problem is that spawning new process of ethtool/mlxreg is very slow. To optimize the performance, this PR will use SDK provided sys fs for EEPROM reading/writing.

#### How I did it

Replace the logic of `sfp.read_eeprom` and `sfp.write_eeprom` by SDK sys fs.

#### How to verify it

Manual test
Unit test cases (new test case added)
sonic-mgmt regression

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox  now that PR https://github.com/sonic-net/sonic-buildimage/pull/12542 is merged, should this PR be ready for review?

**Review by keboliu — APPROVED** [review]

**Comment by prgeor** [comment]
@Junchao-Mellanox do you mind testing your changes with https://github.com/sonic-net/sonic-utilities/pull/2379 ?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox do you mind testing your changes with [sonic-net/sonic-utilities#2379](https://github.com/sonic-net/sonic-utilities/pull/2379) ?

Sure

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor , I ran some tests based on https://github.com/sonic-net/sonic-utilities/pull/2379. I did not find issue on the current bug, but I found https://github.com/sonic-net/sonic-utilities/pull/2379 itself contains some issues:
1. This line is a confusing, https://github.com/sonic-net/sonic-utilities/blob/569edf3b75840b1db844c5a4797679babc412c4e/sfputil/main.py#L738. Better change name `eeprom_hexdump_sff8636` to something else because it is not only for sff8636.  

```python
        if id[0] == 0x3:
            output = eeprom_hexdump_sff8472(port, physical_port, page)
        else:
            output = eeprom_hexdump_sff8636(port, physical_port, page)

```

2. A2H is not a mandatory for sff8472, but the command line output nothing if A2H is not available:

```python
        page_dump = platform_chassis.get_sfp(physical_port).read_eeprom(SFF8472_A0_SIZE, PAGE_SIZE)
        if page_dump is None:
            click.echo("Error: Failed to read EEPROM for A2h!")
            sys.exit(ERROR_NOT_IMPLEMENTED)
```

**Review by prgeor — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
No clean cherry-pick, will create PR to 202205

**Pull request merged**
