### PR TITLE
[202205] [Mellanox] Revert LPM implementation to the old way

### PR DESCRIPTION
**Pull request by keboliu**
#### Why I did it
backport https://github.com/sonic-net/sonic-buildimage/pull/17096  because of no clean cherry-pick

The current low power mode setting implementation requests the user to set the port to admin down first before toggling LP mode, this is not backward compatible, now revert it to the old way so that the user can toggle the LP mode regardless of the port admin status.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Reverts commit f74c69e876bdc80c38ae6bd06b414e357d1a63fa.

#### How to verify it

run all sfputil and SFP platform API related tests on all the Mellanox platforms.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by Junchao-Mellanox — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prgeor please help to review.
BTW the sonic-mgmt test will be updated to align to this req.

**Review by liat-grozovik — APPROVED** [review]

**Comment by lguohan** [comment]
@prgeor  to check

**Comment by keboliu** [comment]
Hi @yxieca @prgeor this PR intends to backport https://github.com/sonic-net/sonic-buildimage/pull/17096 to the 202205 branch,  the original PR has been merged.  The change to 202205 is not exactly the same because of the codebase difference on both branches.  This change has also been verified on the 202205 branch, would you please help to review and merge?

**Comment by yxieca** [comment]
@prgeor please help check.

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
> @prgeor please help check.

@yxieca please help merge

**Pull request merged**
