### PR TITLE
[202205] Add linux perf tool to sonic image

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Add linux perf tool to sonic image

#### How I did it

Use apt install in build_debian.sh

#### How to verify it

Run build

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Hi @qiluo-msft , could you please suggest a reviewer from MSFT side?

**Review by keboliu — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Is it only required in a debug image? Seem like occupying several MB disk space.

**Comment by Junchao-Mellanox** [comment]
> Is it only required in a debug image? Seem like occupying several MB disk space.

Hi, we want to put it into regular image so that we can use this tool to debug issues in production environment. I suppose a few MB disk space is fine.

**Comment by yxieca** [comment]
> > Is it only required in a debug image? Seem like occupying several MB disk space.
> 
> Hi, we want to put it into regular image so that we can use this tool to debug issues in production environment. I suppose a few MB disk space is fine.

Why is this change not done against master branch and requesting for back porting? Does master branch have this change already?

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox it should be in master as well. Do we have it? If not let's tart with master and then cherry pick. If cannot be cherry picked we will use this one

**Comment by Junchao-Mellanox** [comment]
sure.

**Comment by Junchao-Mellanox** [comment]
Created PR for master https://github.com/sonic-net/sonic-buildimage/pull/11817

**Pull request merged**
