### PR TITLE
[Mellanox] Add more unit test coverage for platform API

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Why I did it

Increase UT coverage for Nvidia platform API code

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

Focus on low coverage file:
 - component.py
 - watchdog.py
 - pcie.py

#### How to verify it

Run the unit test, the coverage has been changed from 70% to 90%

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by liat-grozovik** [comment]
This is great initiative.
@prgeor could you please help to review and merge?

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik , could you please help merge this?

**Review by liat-grozovik — APPROVED** [review]

**Comment by StormLiangMS** [comment]
ADO: 24833061

**Pull request merged**
