### PR TITLE
[Marvell] Update mrvl-prestera SDK driver

### PR DESCRIPTION
**Pull request by pavannaregundi**
#### Why I did it
Update mrvl-prestera SDK driver with below fixes,

* [mvSai] Add netdev notifier call - Change adds netdev notifier call to sai module to handle cleanup in case of unregister event in netdev.
* [ethDriver] Populate TX_DSA Tag(isTagged and VID) from egress packet - Change fixes the update of SAI_ROUTER_INTERFACE_STAT_OUT_OCTETS.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
Verified by running following test, 
1) config reload
2) syncd process kill
3) Check SAI_ROUTER_INTERFACE_STAT_OUT_OCTETS counter updates.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202405

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by pavannaregundi** [comment]
@lguohan Can you please review this?

**Review by saiarcot895 — APPROVED** [review]

**Comment by pavannaregundi** [comment]
@lguohan @prgeor Can you please merge this request.

**Comment by pavannaregundi** [comment]
@yxieca @saiarcot895 This needs to be backported to 202405.

**Comment by bingwang-ms** [comment]
@Blueve FYI.

**Pull request merged**
