### PR TITLE
[Arista] Update platform library submodules

### PR DESCRIPTION
**Pull request by Staphylo**
##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

 - Ignore intermittent IO errors during `get_change_event` in the Platform API
 - Fix tunings for some ports on CatalinaDD
 - Fix kernel module build for 6.1 kernel in preparation of bookworm upgrade

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [x] 202205
- [x] 202211
- [x] 202305
- [x] master

#### Description for the changelog

Update Arista platform library submodules

### CODE REVIEW

**Comment by Staphylo** [comment]
@prgeor @StormLiangMS this addresses the xcvrd crash issue.
A backport to 202205, 202211 and 202305 could be attempted but IIRC backporting submodule updates doesn't work on release branches.
If that doesn't do it, I'll create individual PRs for the other branches.

**Comment by StormLiangMS** [comment]
@prgeor  could you help to review? this is the fix for 7050qx xcvrd issue.

**Comment by Staphylo** [comment]
@prgeor could we get some attention on this PR ?

**Comment by prgeor** [comment]
@Staphylo for `Ignore intermittent IO errors during get_change_event in the Platform API` please raise separate PR for 202012, 202205, 202305

**Pull request merged**
