### PR TITLE
Update sonic-mux-linkmgr yang model

### PR DESCRIPTION
**Pull request by vivekverma-arista**
#### Why I did it
A new flag was introduced in https://github.com/sonic-net/sonic-linkmgrd/pull/250 to disable mux oscillations but yang model wasn't updated. We are seeing multiple tests failing due to this, some of them are -
1.  `generic_config_updater/test_dynamic_acl.py`
2. `passw_hardening/test_passw_hardening.py`
3. `dualtor_mgmt/test_toggle_mux.py`

##### Work item tracking
- [#153](https://github.com/aristanetworks/sonic-qual.msft/issues/153)
#### How to verify it
Ran the failing tests with the image.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202311

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by lolyu — COMMENTED** [review]
Could you please check the PR test failures?

**Comment by vivekverma-arista** [comment]
> Details

```##[error]We stopped hearing from agent sonic-ubu000AQ9. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error.```

Looks like infra thing. @lolyu can you fire the run again.

**Review by lolyu — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
@bingwang-ms  for 202405 cherry pick.

**Comment by bingwang-ms** [comment]
> @bingwang-ms for 202405 cherry pick.

Done.

**Pull request merged**
