### PR TITLE
DellEMC: System health config changes

### PR DESCRIPTION
**Pull request by aravindmani-1**
#### Why I did it
System health config is missing in few Dell platforms.

#### How I did it
Added system health monitoring config and its related API's
#### How to verify it
show system-health summary/detail commands.

#### Which release branch to backport (provide reason below if selected)
- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211
- [x] 202305

#### Description for the changelog
UT:
[S5248F_UT.txt](https://github.com/sonic-net/sonic-buildimage/files/12001180/S5248F_UT.txt)

### CODE REVIEW

**Comment by aravindmani-1** [comment]
@prgeor Could you please help to review and merge this PR?.

**Comment by aravindmani-1** [comment]
@prgeor @yxieca could you please help to merge this PR?.

**Review by prgeor — APPROVED** [review]

**Pull request merged**
