### PR TITLE
[202305][graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
**DEPENDS ON: [[202305][graceful reboot] Add the pre_reboot_hook script execution, add the watchdog arm before the reboot](https://github.com/sonic-net/sonic-utilities/pull/3191)**

#### Why I did it
Add support for the `graceful reboot` instead of  the `sysfs power cycle` to avoid filesystem corruption 

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Rename the `platform_reboot` script to the `pre_reboot_hook`.
Remove the sysfs power cycle function, from now on the Debian reboot (`/sbin/reboot`) will be executed instead of the sysfs power cycle.

#### How to verify it
1. Start watching logs by using `show log -f` and `journalctl -p debug -f`
2. Execute the `reboot` command from the switch CLI
3. Check in logs that all systemd services terminated 

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@prgeor Can you please also review this one?

**Comment by liat-grozovik** [comment]
@yxieca @prgeor  kindly reminder, this is a major fix needed for 202305

**Comment by vadymhlushko-mlnx** [comment]
@yxieca, @prgeor kind reminder to merge, the same changes were already merged into `master`

**Review by prgeor — APPROVED** [review]
@vadymhlushko-mlnx appreciate if you could point to the master PR in the description

**Comment by vadymhlushko-mlnx** [comment]
> @vadymhlushko-mlnx appreciate if you could point to the master PR in the description

[[graceful reboot] Rename the platform_reboot to the pre_reboot_hook, remove the sysfs power cycle #18324](https://github.com/sonic-net/sonic-buildimage/pull/18324)

**Comment by vadymhlushko-mlnx** [comment]
@prgeor could you please help to merge

**Comment by prgeor** [comment]
> @prgeor could you please help to merge

@liat-grozovik can you merge.

**Comment by vadymhlushko-mlnx** [comment]
@liat-grozovik could you please merge

**Comment by prgeor** [comment]
@StormLiangMS @yxieca can you merge

**Comment by vadymhlushko-mlnx** [comment]
@StormLiangMS @yxieca can you please merge

**Comment by StormLiangMS** [comment]
hi @bingwang-ms  could you help to comment on this? Is this needed for 202305?

**Pull request merged**
