### PR TITLE
[Mellanox] Fix SN2700-A1 sensors.conf and update psu_sensors.json accordingly

### PR DESCRIPTION
**Pull request by yuazhe**
#### Why I did it
previously 2700a1 sensors.conf is missing bus section for psu, so add it and update the psu_sensors.json with the info.

fix psu_sensors_conf_updater to treat PSR psu as same as PSF one.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it

use `sensors` command and verify the output

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [x] 202305
- [x] 202311
- [x] 202405  

#### Tested branch (Please provide the tested image version)

- [x]  202405
- [ ]

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yuazhe please create a PR against 202311 and correlate it to this one for tracking

**Comment by yuazhe** [comment]
> @yuazhe please create a PR against 202311 and correlate it to this one for tracking
The conflict is caused by https://github.com/sonic-net/sonic-buildimage/pull/18528 doesn't been cherry-pick to 202311 yet.

**Comment by bingwang-ms** [comment]
Discussed offline. The change LGTM.

**Comment by bingwang-ms** [comment]
Re-adding tags to trigger auto cherry-pick

**Pull request merged**
