### PR TITLE
[Micas/Platform]platform support M2-W6520-24DC8QC

### PR DESCRIPTION
**Pull request by philo-micas**
#### Why I did it
Add new platform m2-w6520(Trident 4)
ASIC Vendor: Broadcom
Switch ASIC: Trident 4
Port Config: 24x200G+8x400G

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
show platform fan
show platform ssdhealth
show platform psustatus
show platform summary
show platform syseeprom
show platform temperature
show interface status

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by philo-micas** [comment]
[report_M2-W6520-24DC8QC_0223.zip](https://github.com/sonic-net/sonic-buildimage/files/14400327/report_M2-W6520-24DC8QC_0223.zip)
Platform test report from sonic-mgmt.

**Comment by StephenSJCA** [comment]
> [report_M2-W6520-24DC8QC_0223.zip](https://github.com/sonic-net/sonic-buildimage/files/14400327/report_M2-W6520-24DC8QC_0223.zip) Platform test report from sonic-mgmt.

@lguohan @prgeor @yxieca  **Hi Guohan, Prince, and Ying, please take the time to push forward this PR, it is urgent for us, many thanks!**

**Comment by philo-micas** [comment]
Leave one semgrep error as 'defusedxml' was not installed in sonic.

**Comment by philo-micas** [comment]
Please use new PR link https://github.com/sonic-net/sonic-buildimage/pull/20553

**Pull request closed without merging**
