### PR TITLE
[Marvell] Update armhf driver version

### PR DESCRIPTION
**Pull request by pavannaregundi**
Changes in MRVL_PRESTERA_DRIVER_1.4:
- Memory leak fixed by adding missing releasing pci device.
- Fixes for 5.10 kernel porting.

Change-Id: I1d7ee4ec02ec17a29ddb8473725ab68ca399748b

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How to verify it
Tested by building master sonic-marvell-armhf.bin and loaded on switch to check the 'show interface status' for port up.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [x] 202205
- [x] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by pavannaregundi** [comment]
@Pavan-Nokia please review

**Review by Pavan-Nokia — APPROVED** [review]

**Comment by pavannaregundi** [comment]
@lguohan Can you please review this PR. This is similar to https://github.com/sonic-net/sonic-buildimage/pull/15310.

**Comment by johnchiucc** [comment]
@lguohan Could you please review this PR?

**Comment by Blueve** [comment]
@yxieca could you help merge this PR?

**Comment by Blueve** [comment]
MS Internal ADO: 24294745

**Pull request merged**
