### PR TITLE
[202205][utilities][swss] advance submodule head

### PR DESCRIPTION
**Pull request by yxieca**
utilities:
* 5892f6d 2022-08-29 | [VRF]Adding CLI checks to ensure Vrf is valid in interface bind and static route commands (#2333) (HEAD -> 202205) [Sudharsan Dhamal Gopalarathnam]
* 87ec859 2022-08-30 | Subinterface vrf bind issue fix (#2211) [Preetham]
* edc0169 2022-08-16 | [decode-syseeprom] Fix setting use_db based on support_eeprom_db (#2270) [byu343]
* 1542e7a 2022-08-15 | Fix vrf UT failed issue (#2309) [Hua Liu]

swss:
* 39f5cdf 2022-08-31 | [BFD]Clean up state_db BFD entries on swss restart (#2434) (HEAD -> 202205) [Sudharsan Dhamal Gopalarathnam]
* f4a6945 2022-08-30 | Fix the Fec Mode Setting of gbsyncd (#2430) [abdosi]
* 36e8092 2022-08-30 | [neighsyncd] Enabling ipv4 link local entries for non-dualtor (#2427) [Nikola Dancejic]
* a2bac7c 2022-08-26 | tlm_teamd: Filter portchannel subinterface events from STATE_DB LAG_TABLE (#2408) [Preetham]
* 8bb21be 2022-08-10 | PFCWD recovery changes using DLR_INIT (#2316) [vmittal-msft]
* 3e888b7 2022-08-29 | Dynamic port configuration - add port buffer cfg to the port ref counter (#2194) [Dror Prital]

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@yxieca Can you please include latest commits in sonic-utilities in your PR? There are few merges after this.

**Comment by liat-grozovik** [comment]
@yxieca please check swss submodule PR just merged to 202205. i suggest you will update this PR before merging.

**Comment by yxieca** [comment]
Submodule has been advanced by other PRs.

**Pull request closed without merging**
