### PR TITLE
Revert iBGP GTSM feature for VOQ Chassis

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

Revert the GTSM feature for VOQ iBGP session done as part of https://github.com/sonic-net/sonic-buildimage/pull/16777.

Why I did:
On VOQ chassis BGP packets go over Recycle Port and then for Ingress Pipeline Routing making ttl as 254 and failing single hop check.

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
@lguohan , can you help review/approve this PR? This is needed by Chassis community to resolve issue for DNX based chassis.

**Comment by gechiang** [comment]
@abdosi , please include MSFT ADO number for this so 202205 and 202305 can be approved once master is merged.

**Comment by abdosi** [comment]
@lguohan can you please help with approval/merge of this

**Comment by gechiang** [comment]
@abdosi , I have created the MSFT ADO: 25892897
@StormLiangMS , @yxieca , Please help review/approve for 202205 and 202305.

**Comment by abdosi** [comment]
> @abdosi PR conflicts with 202305 branch

@StormLiangMS PR: https://github.com/sonic-net/sonic-buildimage/pull/17237

**Comment by mlok-nokia** [comment]
We need this PR in 202205 branch to fix the issue.

**Comment by gechiang** [comment]
@yxieca , please help review/approve this for 202205.
Thanks!

**Pull request merged**
