### PR TITLE
[submodule] Advance sonic-utilities submodule pointer

### LINKED ISSUE #12170: [Sub-If|VRF] Unbind sub-interface from VRF is failed
#### Description

Sun-Interface is left in inconsistent state if it was unbinded from VRF

#### Steps to reproduce the issue:
1. Create any VRF `config vrf add Vrf_11`
2. Create any sub-interface `config subinterface add Eth0.11 11`
3. Bind sub-interface to VRF `config interface vrf bind Eth0.11 Vrf_11`
4. Check bind was successful
`show vrf`
`ip link show vrf Vrf_11`
5. Unbind `config interface vrf unbind Eth0.11`
6. Check again
`show vrf`
`ip link show vrf Vrf_11`

#### Describe the results you received:

After unbinding Linux interface is still has master Vrf_11. SONIC output looks OK

```
root@qa-eth-vt01-3-2700a0:/home/admin# ip link show vrf Vrf_11
77: Eth0.11@Ethernet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue master Vrf_11 state UP mode DEFAULT group default qlen 1000
    link/ether 24:8a:07:80:d1:40 brd ff:ff:ff:ff:ff:ff
root@qa-eth-vt01-3-2700a0:/home/admin# show vrf
VRF     Interfaces
------  ------------
Vrf_11
root@qa-eth-vt01-3-2700a0:/home/admin#
```

#### Describe the results you expected:

Linux interface unbinded too

#### Output of `show version`:

```
SONiC Software Version: SONiC.202205_rc.11-a0e7525cf_Internal
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: a0e7525cf
Build date: Wed Sep 14 14:08:46 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic-ci02-241

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1649X04248
Model Number: MSN2700-CS2F
Hardware Revision: Not Specified
Uptime: 11:24:02 up 14 min,  2 users,  load average: 0.94, 0.90, 0.76
Date: Mon 19 Sep 2022 11:24:02

```
#### Output of `show techsupport`:

[sonic_dump_qa-eth-vt01-3-2700a0_20220919_112341.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9631881/sonic_dump_qa-eth-vt01-3-2700a0_20220919_112341.tar.gz)

### PR DESCRIPTION
**Pull request by keboliu**
Signed-off-by: Kebo Liu <kebol@nvidia.com>

#### Why I did it
update the sonic-utilities submodule pointer to pick up following commits:

> b34a540 [generate_dump] Fix for deletion flow for all secret files from show-techsupport dump [(#2571)](https://github.com/sonic-net/sonic-utilities/pull/2571)
> fd4d9c0 [sonic_installer] use /etc/resolv.conf from the host when migrating packages [(#2573)](https://github.com/sonic-net/sonic-utilities/pull/2573)
> a09461d [Mellanox] Change severity to NOTICE in Mellanox buffer migrator when unable to fetch DEVICE_METADATA due to empty CONFIG_DB during initialization [(#2569)](https://github.com/sonic-net/sonic-utilities/pull/2569)
> ba45b81 Fix issue: unconfigured PGs are displayed in watermarkstat [(#2556)](https://github.com/sonic-net/sonic-utilities/pull/2556)
> d00780e [Command Ref] Add doc for syslog rate limit [(#2508)](https://github.com/sonic-net/sonic-utilities/pull/2508)
> 258ffa0 [generate_dump] Optimize the execution time of 'show techsupport' CLI by parallel function execution [(#2512)](https://github.com/sonic-net/sonic-utilities/pull/2512)
> 739e4d7 [timer.unit.j2] use wanted-by in timer unit [(#2546)](https://github.com/sonic-net/sonic-utilities/pull/2546)
> 748540c Fixes #12170: Delete subinterface and recreate the subinterface  in [(#2513)](https://github.com/sonic-net/sonic-utilities/pull/2513)
> caf92aa [db_migrator] Fix migration of Loopback data: handle all Loopback interfaces [(#2560)](https://github.com/sonic-net/sonic-utilities/pull/2560)
> 572c8cf Optimize the execution time of the 'show techsupport' script to 5-10%, [(#2504)](https://github.com/sonic-net/sonic-utilities/pull/2504)
> ce1c444 [muxcable][show] update `show mux tunnel-route` to separate ASIC and kernel into two columns [(#2553)](https://github.com/sonic-net/sonic-utilities/pull/2553)

#### How I did it

Advance the submodule pointer

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by keboliu** [comment]
it seems there is some real issue introduced by some new commits,  working on it.

**Pull request merged**
