### PR TITLE
Revert "Move eventd enabled check from build time to runtime"

### PR DESCRIPTION
**Pull request by zbud-msft**
Reverts sonic-net/sonic-buildimage#20248 and fixes https://github.com/sonic-net/sonic-buildimage/issues/20544

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by volodymyrsamotiy** [comment]
@bingwang-ms , could you please also revert it in 202405?

**Comment by bingwang-ms** [comment]
The change is reverted from 202405 by PR https://github.com/sonic-net/sonic-buildimage/pull/20946

**Comment by Junchao-Mellanox** [comment]
Hi @bingwang-ms @zbud-msft , should we also fix the issue in 202411?

**Comment by rlhui** [comment]
@bingwang-ms , should this revert be needed in 202405 branch too?

**Comment by bingwang-ms** [comment]
@zbud-msft Can you also file a PR for 202411 to revert?

**Comment by dprital** [comment]
> @zbud-msft Can you also file a PR for 202411 to revert?

Hi @zbud-msft , Do we have same PR for 202411 ? Or this can be cherry picked with no issues to 202411 ?

**Comment by zbud-msft** [comment]
@bingwang-ms The revert is already in 202411

**Pull request merged**
